### ISSUE TITLE
How to Save the form

### ISSUE THREAD

**Issue by padminibee** [kevinchappell/formBuilder#1]
Hi,
Thank you for the code to build forms online...
i am unable to write the code for saving the template..can u help me to do...

**Comment by kevinchappell** [comment]
At the moment form data is stored as XML in a hidden textarea so saving the data should be the same as saving a normal textarea. I am working on a new demo now that will include save functionality for a php backend.

**Comment by thewizster** [comment]
Extracting the XML directly using toXML()
http://jsfiddle.net/thewizster/kcevbmqx/

Is there a way yet to render this back to HTML?

**Comment by kevinchappell** [comment]
@thewizster version 1.4 (just released) addresses this. Check the [demo](http://kevinchappell.github.io/formBuilder/) for usage.

**Comment by thewizster** [comment]
@kevinchappell I've been testing the new render feature. Working well so far. I'm testing under bootstrap 3. I'll let you know if I run into any issues. Great work!

**Comment by ashvushinde** [comment]
I have a XML data and I saved it to database.
And I get it back from database but how to convert it to HTML form. In short how do i render it ?

###### XML data returned from the database:

```javascript
<form-template>
	<fields>
		<field name="select-1447927575220" label="Select" style="multiple" description="" required="false" type="select" >
			<option value="option-1">Option 1</option>
			<option value="option-2">Option 2</option>
		</field>
		<field name="autocomplete-1447927571725" label="Autocomplete" description="" required="false" type="autocomplete" />
		<field name="radio-group-1447927576634" label="Radio Group" style="multiple" description="" required="false" type="radio-group" >
			<option value="option-1">Option 1</option>
			<option value="option-2">Option 2</option>
		</field>
		<field name="date-input-1447927572946" label="Date Field" description="" required="true" type="date" />
		<field name="checkbox-group-1447927574129" label="Checkbox Group" style="multiple" description="" required="false" type="checkbox-group" >
			<option value="option-1">Option 1</option>
			<option value="option-2">Option 2</option>
		</field>
	</fields>
</form-template>
```

How do i render it to new HTML page?

**Comment by kevinchappell** [comment]
Can you log the `$(template).val()`? If its direct from the DB the XML may be escaped. 

Here is a minimal usage example. http://jsfiddle.net/kevinchappell/yzr2p5y4/

**Comment by ashvushinde** [comment]
I logged $(template).val()?
It shows the same which is already given.
But now the issue is how to append the XML to textarea.
Because the demo you given on jsfiddle, isslustrates the XML part is child of textarea.
Alternatively I assigned the value of XML to textarea.
Still nothing happens?
How to append the XML as a child of textarea ?

**Comment by ashvushinde** [comment]
@kevinchappell : 

I did a Silly thing actually.
      %form
        %textarea#template_form{:cols => "30", :name => "form-template", :rows => "10"}
          = session[:form_template]

Solved my problem.
Thanks.

**Comment by kevinchappell** [comment]
Sorry im not sure as I have 0 rails experience but from what i see online assigning should have worked.
```%textarea.hidden#form-builder-template{:cols => "30", :name => "form-builder-template", :rows => "10"}= session[:form_template]```

**Comment by ashvushinde** [comment]
Yeah that's right..!!
The same you suggested solved my problem..!!

**Comment by kevinchappell** [comment]
@ashvushinde great!. best of luck.

**Comment by JosephMendez** [comment]
how to save data once the form is rendered and fill in with values.?

**Comment by Varungpurohit** [comment]
Hi, 
Thank u for the code.
I have one doubt regrading ,,,,,can we get rendered or build html directly when we saved the form or is it possible to convert xml or json or js directly without any plugins
