### ISSUE TITLE
I like to add a new custom panel and send the option values from the data base 

### ISSUE THREAD

**Issue by chanakya009** [kevinchappell/formBuilder#1004]
### Environment Details:

 - formBuilder Version: 3.2.5

Hi kevin,

Thanks for such a awesome API

i actually want to add a new custom panel on left with custom fields and i want to send the option values form data base , so that user will select the values from there its self 

please help out on customizing  for my requirement

**Comment by naisargparmar** [comment]
It is possible?

**Comment by kevinchappell** [comment]
yes. there is a new option called `onAddOption` that should facilitate https://formbuilder.online/docs/formBuilder/options/onAddOption/
