### ISSUE TITLE
[demo website] button is empty (Adblock Plus)

### ISSUE THREAD

**Issue by Cyrille37** [kevinchappell/formBuilder#1005]
### Description:

On the [demo website](https://formbuilder.online/), the button control is displayed as an empty line, as in this screen shot :

![image](https://user-images.githubusercontent.com/368965/68302128-ae2ada00-00a1-11ea-9759-1a7009d457d8.png)

### Environment Details:

 - formBuilder Version: 3.2.5 (formbuilder.online on 2019-11-06)
 - Browser: Firefox 70.0 (64 bits)
 - OS: Linux Ubuntu 18.04 LTS

**Comment by Cyrille37** [comment]
I found that it's caused by "Adblock Plus", when desactivated the button control is well displayed.

**Comment by kevinchappell** [comment]
thanks for reporting this. looks like it is the `fb-` prefix for the `fb-button` class. prefix should probably be updated to `formbuilder` for all controls
