### ISSUE TITLE
Invalid control type with replaced or custom fields (in combination with paging)

### ISSUE THREAD

**Issue by sxndy1** [kevinchappell/formBuilder#1006]
### Description:
```
Javascirpt-Error:
Uncaught Error: Invalid control type. (Type: radio-group-4783, Subtype: undefined). Please ensure you have registered it, and imported it correctly.
```

FormBuilder-Options:
```
replaceFields: [
{
   label: "Kontrollkästchen-Gruppe",
   type: "checkbox-group",
   values: [
      // vordefinierte Optionen mit Beschreibung
      {
      label: "Beschriftung",
      value: "Wert bei Auswertung (z.B.: Ja/Nein)"
      },
      {
      label: "Beschriftung",
      value: "Wert bei Auswertung (z.B.: Ja/Nein)"
      }
   ]
}
```

Hi guys,

I'm using FormBuilder in multible tabs (like the "paging" functionality described in the docs). So I'm running multiple, tabbed instances of formBuilder on a site. 

Since I want my checkbox-group has predefined fields, I set in the options, that my checkbox has default fields inserted when created. I did it via the "replaceFields" in the formBuilder options.

Because of this I get the error "invalid control type". This happens always then, when I'm **not** on the last created tab. On the last tab I always can insert a checkbox-group.

Any ideas?

### Environment Details:

 - formBuilder Version: 3.2.5
 - Browser: all

### Steps to Reproduce
FormBuilder used with paging functionality (like in the docs). Insert 2 or more pages. On the last page inserting a checkbox-group is working, on all the others not!

### Screenshot - *(optional)*
![image](https://user-images.githubusercontent.com/47420177/69403262-68ede580-0cfa-11ea-8385-8b07441a297f.png)

**Comment by sxndy1** [comment]
Same happening with formbuilder options:
`fields: [
            {
                label: 'Sprungmarke',
                type: 'button'
            }
        ]`

So, always when customizing or adding custom fields in formbuilder, it isn't working anymore with multiple formbuilder instances like paging elements, where on every page/tab is a different formbuilder instance.

**Comment by IrvanFza** [comment]
Hi @sxndy1, wondering if you already solved this issue or have a workaround for it. I also face the same problem. I get `Invalid control type.` error only on the first tab, others work perfectly.

**Comment by Dhurba123a** [comment]
Hi, Please Make use the below code..which should work
      {
        type: "checkbox-group",
        required: true,
        label: "Checkbox Group",
        className: "form-check-input col-lg-4",
        toggle: false,
        inline: false,
        access: false,
        other: false,
        values: [{
          label: "Option 1",
          value: "option-1",
          selected: true
        }]
      },

**Comment by lucasnetau** [comment]
Custom fields was recently fixed to work with multiple instances of formBuilder
https://github.com/kevinchappell/formBuilder/pull/1454

This may be fixed

**Comment by lucasnetau** [comment]
Tested and confirmed this is fixed by https://github.com/kevinchappell/formBuilder/pull/1454
