### ISSUE TITLE
Checkbox bug  , 'no correct chose'

### ISSUE THREAD

**Issue by Danisimogg** [kevinchappell/formBuilder#1007]
### Description:
Hi everyone,I found an Bug, this means that the userData action does not work for you correctly when you select in your example (https://codepen.io/kevinchappell/pen/QGjqbV) the flag that you select in the group of flags, as a result of active ( true) will be first anyway

### Environment Details:

 - formBuilder Version: 
 - Browser: Google chrome
 - OS: Windows 10

### Screenshot - *(optional)*
![BUG](https://user-images.githubusercontent.com/40449766/69965441-55762200-1525-11ea-9e92-b8d287252398.png)

**Comment by W1-PopelierE** [comment]
![image](https://user-images.githubusercontent.com/17490821/71674423-6a8bde00-2d7b-11ea-8db8-da9d4b991778.png)

The first 3 values are the default form settings (checked, unchecked, checked).
After those values there is "userData" with the selected option values.

I don't know if this is supposed to be like this but it could be useful to keep the default checked fields.

**Comment by kevinchappell** [comment]
@W1-PopelierE Thanks for expanding on this issue it looks like a bug for sure. I'll take a closer look at it today.

**Comment by kevinchappell** [comment]
i was not able to reproduce the issue. Can you verify this is still a problem with the current version?

**Comment by Danisimogg** [comment]
You need to choose NO DEFAULT value
