### ISSUE TITLE
Hidden fields does not get i field-label when loaded from formData

### ISSUE THREAD

**Issue by nahojd** [kevinchappell/formBuilder#1008]
When a hidden input field is loaded into the form build from formData, it does not get a field-label set at all. This is because the `appendNewField` function only reads the field-label from values.label -- but hidden fields does not have a label -- and only fallbacks to get the default type description when a field is new, which is not the case then loading from formData.

In `form-builder.js`, line 850:

```javascript
 const appendNewField = function(values, isNew = true) {
    const type = values.type || 'text'
    const label = values.label || (isNew ? i18n.get(type) || mi18n.get('label') : '')
    //The rest of the function is omitted
}
```

I have fixed this, and also added the name of the hidden field to the label, because that is very useful if you have multiple hidden fields:

```javascript
const appendNewField = function(values, isNew = true) {
    const type = values.type || 'text'
    let label = values.label || (isNew ? mi18n.get(type) || mi18n.get('label') : '')
    if (!label && type === 'hidden')
      label = mi18n.get(type) + ': ' + values.name

```

I also fixed a bug where `i18n.get` was called when it ought to be `mi18n.get` (I assume, since i18n does not have a get function).

The fix is available at https://github.com/nahojd/formBuilder/commit/cb44bda0551ca3d9ee6d8fa7f10a56721c5eeb7d

### Environment Details:

 - formBuilder Version: 3.2.5
 - Browser: All
 - OS: All

**Comment by kevinchappell** [comment]
I like this. i made one small change because on most systems the condition will not match as there is the predefined "Hidden Input" label.

**Comment by nahojd** [comment]
Great!
