### ISSUE TITLE
how to align / add the two button in the same row. 

### ISSUE THREAD

**Issue by KathirvelGContus** [kevinchappell/formBuilder#1009]
### Description:
Right now when we drag the field, it will be listed one by one. **For eg:** I have a form which has two text field like username & Password followed by that we have a login and cancel button.  Here the drag and drop all the fields are listed one by one. I want to move the "Login" &  "Cancel" button in the same row ie) Horizontally i need to add these buttons. How i can achieve this? 

### Environment Details:

 - formBuilder Version: 
 - Browser: 
 - OS:

**Comment by AdamDocherty** [comment]
Bump ;)

**Comment by rinmehmeti** [comment]
I have the same question. I would like to make a horizontal form instead of putting controls one after the other vertically. @AdamDocherty If you have the answer, can you explain it, please?

**Comment by Jojoshua** [comment]
See https://formbuilder.online/docs/formBuilder/demos/bootstrap-grid/  ...also this PR will enhance that experience https://github.com/kevinchappell/formBuilder/pull/1243

**Comment by Jojoshua** [comment]
If you are using bootstrap there is a built-in solution now. If not, feel free to reopen.
