### ISSUE TITLE
How should I add custom HTML and CSS to individual fields(input)?

### ISSUE THREAD

**Issue by sibanandamohapatra** [kevinchappell/formBuilder#1010]
Like I create a form by using formBuilder when I render that form for each field I want to show Some text before each field.  therefor I want to add HTML to individual fields.  Like before input text add span attribute <apan>Q1</span>

**Comment by kevinchappell** [comment]
this should be doable with templates and/or custom labels. https://formbuilder.online/docs/formBuilder/options/templates/
