### ISSUE TITLE
Formbuilder proposal

### ISSUE THREAD

**Issue by gtbu** [kevinchappell/formBuilder#1016]
Frombuilder wit drag and drop is a great idea. Tts just that users want to have fields in a grid and not with full width of a page. I have seen some grids with drag and drop (https://kbjr.github.io/DragDrop/index.html and https://github.com/haltu/muuri) and shift and variable width.

Evtl. You can make the width of the fileds drawable and make it possible to put several fileds into a line , and to put fields into other fields like textarea.

**Comment by kevinchappell** [comment]
unfortunately formBuilder would require too much of a rewrite to add inline fields/columns. There is another frontend form editor called Formeo you could try. https://draggable.github.io/formeo/
