### ISSUE TITLE
How to customize this plugin?

### ISSUE THREAD

**Issue by KamilGromov1122** [kevinchappell/formBuilder#1017]
Hi.

I am going to customize this plugin as following:
For Dropdown List, I would like to add import txt file for auto-create bulk options such as US codes.

How can I do this?
Please help me.

Thanks.

**Comment by kevinchappell** [comment]
custom controls or templates may get you where you need https://formbuilder.online/docs/formBuilder/controls/ but it sounds like you just need the file upload control
