### ISSUE TITLE
form builder and form render not working with internet explorer 11

### ISSUE THREAD

**Issue by harshalyelpale** [kevinchappell/formBuilder#1022]
### Description: 
App Env. : Angular 8 with .Net Core 3.0
form builder and form render not working with internet explorer 11, even edge browser also.
Tried with polyfill.js also, below is script added at the top of other JS files

`<script src="https://polyfill.io/v3/polyfill.min.js?features=Object.assign,Object.entries,Promise,Array.prototype.includes,Array.prototype.find,String.prototype.startsWith,Object.values,String.prototype.includes"></script>`

![formBuilderPolyfillUse](https://user-images.githubusercontent.com/29271510/71709906-aed0ba00-2e1f-11ea-810b-d07fe3275d4c.png)

### Environment Details:

 - formBuilder Version: 
 - Browser: IE 11 & Edge
 - OS: Windows 7, Windows 10

**Comment by W1-PopelierE** [comment]
This is the error:

`{description: "Unspecified error.", 
message: "Unspecified error.", number: -2147467259, stack: "Error: Unspecified error. at t.orderFields (https://formbuilder.online/assets/js/form-builder.min.js:19:102944) at t.appendControls (https://formbuilder.online/assets/js/form-builder.min.js:19:103526) at t.init (https://formbuilder.online/assets/js/form-builder.min.js:19:101748) at e (https://formbuilder.online/assets/js/form-builder.min.js:19:101543) at A (https://formbuilder.online/assets/js/form-builder.min.js:19:104228) at Anonymous function (https://formbuilder.online/assets/js/form-builder.min.js:19:126310) at each (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js:2:2875) at n.prototype.each (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js:2:838) at Anonymous function (https://formbuilder.online/assets/js/form-builder.min.js:19:126290)"}`


When running the project in a node project it works in Edge (https://formbuilder.online/docs/contributing/).

**Comment by kevinchappell** [comment]
can you share your configuration in a codepen?
@W1-PopelierE can you test #1027 in IE11?

**Comment by W1-PopelierE** [comment]
> can you share your configuration in a codepen?
> @W1-PopelierE can you test #1027 in IE11?

Will test this when I get home from work.

**Comment by W1-PopelierE** [comment]
@kevinchappell in IE11 i get these errors:
![image](https://user-images.githubusercontent.com/17490821/73245023-8c765600-41ab-11ea-8290-34f196ca94e8.png)

Polyfills (cdn provided by @harshalyelpale ) also couldn't solve it.

**Comment by harshalyelpale** [comment]
formBuilder is working perfectly on Microsoft Edge (Chromium-based Edge) Version 79.0.309.71 now. As @W1-PopelierE said Internet Explorer 11 is no longer supported on Windows 7, we should not rely on IE 11.

**Comment by kevinchappell** [comment]
Thanks for testing @W1-PopelierE

**Comment by kevinchappell** [comment]
Resolved by #1033
