### ISSUE TITLE
ionic cordova build failed

### ISSUE THREAD

**Issue by manojrock** [kevinchappell/formBuilder#1023]
### Description:
 FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Projects\insiightPhase2\platforms\android\app\build.gradle' line: 95

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not resolve all files for configuration 'classpath'.
   > Could not resolve com.android.tools.build:gradle:+.
     Required by:
         unspecified:unspecified:unspecified
      > Could not resolve com.android.tools.build:gradle:+.
         > Failed to list versions for com.android.tools.build:gradle.
            > Unable to load Maven meta-data from https://jcenter.bintray.com/com/android/tools/build/gradle/maven-metadata.xml.
               > Could not HEAD 'https://jcenter.bintray.com/com/android/tools/build/gradle/maven-metadata.xml'.
                  > Connect to 10.1.56.237:8080 [/10.1.56.237] failed: Connection timed out: connect
      > Could not resolve com.android.tools.build:gradle:+.
         > Failed to list versions for com.android.tools.build:gradle.
            > Unable to load Maven meta-data from https://repo1.maven.org/maven2/com/android/tools/build/gradle/maven-metadata.xml.
               > Could not HEAD 'https://repo1.maven.org/maven2/com/android/tools/build/gradle/maven-metadata.xml'.
                  > Connect to 10.1.56.237:8080 [/10.1.56.237] failed: Connection timed out: connect

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org
### Environment Details:
Ionic:

   Ionic CLI          : 5.4.13 (C:\Users\59409\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : android 7.1.4
   Cordova Plugins   : no whitelisted plugins (16 plugins total)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (D:\android_sdk\sdk1)
   NodeJS            : v11.6.0 (C:\Program Files\nodejs\node.exe)
   npm               : 4.6.1
   OS                : Windows 10
 - formBuilder Version: 
 - Browser: 
 - OS:

**Comment by W1-PopelierE** [comment]
Have you tried Googling these 2 seperately?
Could not resolve all files for configuration 'classpath'.
Could not resolve com.android.tools.build:gradle:+.
Because I am not seeing anything related to formBuilder. (Correct me if I am wrong)

**Comment by manojrock** [comment]
@W1-PopelierE sorry i have posted issues in wrong group ... Thanks for your replying

**Comment by manojrock** [comment]
posted issues in wrong group
