### ISSUE TITLE
Feature request custom edit input types

### ISSUE THREAD

**Issue by W1-PopelierE** [kevinchappell/formBuilder#1024]
Hey, do you think it is possible to create some options for the formbuilder to add custom attributes?
In my example I would like to add some translations in the edit section. So the user can create a form for multiple languages. Now the logic behind that is already working for me except the custom input attributes.

Talking about the image below that edit form.

![image](https://user-images.githubusercontent.com/17490821/71725324-bdc16780-2e33-11ea-8223-60ec3f19534e.png)

**Comment by W1-PopelierE** [comment]
Something like this in the code

![image](https://user-images.githubusercontent.com/17490821/71726454-70df9000-2e37-11ea-8b0f-a54db74e40af.png)

**Comment by W1-PopelierE** [comment]
Possible via https://formbuilder.online/docs/formBuilder/options/typeUserAttrs/

**Comment by W1-PopelierE** [comment]
`
[
  {
    "type": "checkbox-group",
    "label": "Checkbox Group",
    "name": "checkbox-group-1578309799043",
    "values": [
      {
        "label": "Option 1",
        "value": "option-1",
        "selected": true
      }
    ]
  }
]`

Is it possible to add some sort of hidden attribute to the values?
example:
` "values": [
      {
        "label": "Option 1",
        "value": "option-1",
        "selected": true,
        "id": 3,
        "dutch": "Optie 1"
      }
    ]`

**Comment by kevinchappell** [comment]
hidden attributes can now be added using the `onAddOption` callback
