### ISSUE TITLE
Removal of element doesn't really remove element

### ISSUE THREAD

**Issue by idmeneo** [kevinchappell/formBuilder#1028]
### Description:
Hi,
When you click on the delete button on an element, it disapears from the DOM (the field is put on "display:none") but is'nt actually removed from the form.
And when you save the data, the field is still in the form. It can easally seen on the demo site under the getData() method.

### Environment Details:

 - formBuilder Version: LAST
 - Browser: Chrome
 - OS: Windows

### Expected Behavior
Field is supposed to be removed from the form

### Actual Behavior
Field is just hidden and not removed

### Steps to Reproduce
Click a delete button on a field and save data : the field is still here.

### screenshot
![formbuilder](https://user-images.githubusercontent.com/3907879/73269425-1a1e6980-41dd-11ea-8aea-6db6f252fee1.png)

**Comment by idmeneo** [comment]
Ok found a way to make it work : if you add "fieldRemoveWarn: true, " to the options, the field is actually deleted.

**Comment by W1-PopelierE** [comment]
Are you sure this isn't still a bug?
Seems like a bug to me. If you remove a component, it should not be in the form data.

**Comment by idmeneo** [comment]
> Are you sure this isn't still a bug?
> Seems like a bug to me. If you remove a component, it should not be in the form data.

Yes it is of course. I'll reopen it.

**Comment by W1-PopelierE** [comment]
@kevinchappell Looks like a critical bug in the latest release.

**Comment by kevinchappell** [comment]
Thanks for opening and re-opening this issue. A new version should be released in a few minutes
