### ISSUE TITLE
Select Field Bug

### ISSUE THREAD

**Issue by relosmot** [kevinchappell/formBuilder#1030]
### Description:
Single select fields displaying as select multiple.

### Environment Details:

 - formBuilder Version: 3.2.6+
 - Browser: Chrome
 - OS: MacOS

### Expected Behavior
When a select field is not set to multiple, it should display as a single select.

### Actual Behavior
The select field is always displaying as a multiple select.

### Steps to Reproduce
Go to https://formbuilder.online/ and add a select field. It will be a multiple select even when it's not supposed to be.

**Comment by KrenZfer** [comment]
hey,
I got the same problem too, i think it's multiple attribute that inlcuded even its value is false and then rendered by browser as multiple select as well, i hope this will be fixed soon,

**Comment by relosmot** [comment]
@kevinchappell - any plans on fixing this one?

**Comment by uzegonemad** [comment]
I'm using this as a workaround.

```js
function fixFormBuilderRendering() {
    // fix rendering of selects that are NOT multiple
    jQuery('.formbuilder-select select[multiple=false]').removeAttr('multiple');
}

const options = {
    //...options,

    onAddField: function() {
        fixFormBuilderRendering();
    },
    onCloseFieldEdit: function() {
        fixFormBuilderRendering();
    }
};
```

**Comment by futureweb** [comment]
@kevinchappell - unfortunately I'm still getting muktiple="false" on rendered HTML:

```
var renderedForm = $("<div>");
            formRenderOpts = {
              dataType: "json",
              formData: formData
            };
            renderedForm.formRender({formData});
            formHTML = renderedForm.html();
            console.log(renderedForm.html());
```
Output:

`<div class="formbuilder-select form-group field-select-1583430112019"><label for="select-1583430112019" class="formbuilder-select-label">Auswahl</label><select class="form-control" name="select-1583430112019" multiple="false" id="select-1583430112019"><option value="AWoption-1" id="select-1583430112019-0">AW Option 1</option><option value="AWoption-2" id="select-1583430112019-1">AW Option 2</option><option value="AWoption-3" id="select-1583430112019-2">AW Option 3</option><option value="AWoption-4" id="select-1583430112019-3">AW Option 4</option><option value="AWoption-5" id="select-1583430112019-4">AW Option 5</option></select></div>`

**Comment by huzoorbux** [comment]
Dear @kevinchappell  I'm still getting multiple="false" after render :(

**Comment by mcrozes** [comment]
+1. As a workaround, I've been able to completely disable the attribute with
`disabledAttrs: [.. 'multiple']`

**Comment by myowinthein** [comment]
Still happening in version `3.4.2`. 

`multiple: false` is including and should be removed.

![Screenshot from 2020-06-19 14-43-50](https://user-images.githubusercontent.com/20858430/85112279-670de580-b23b-11ea-81c5-976be6ad1b5a.png)
