### ISSUE TITLE
Drag & Drop not working correctly on IE

### ISSUE THREAD

**Issue by atnegrete** [kevinchappell/formBuilder#1036]
### Description:
Try the drag and drop feature for all the form builder items. Most of the items will be removed from the right side once they are dragged over to the drop zone box. See screenshot for the DEV tools red errors.

If I add in a startsWith to String.prorotype it breaks other libraries I depend on that also use startsWith, is it possible to change it?

### Environment Details:

 - formBuilder Version: 3.4.0
 - Browser: IE 11
 - OS: Windows 10

### Expected Behavior
Drag & drop works as expected.

### Actual Behavior
Dragged items are also being cleared from the Fields List on the right (drag source).

### Steps to Reproduce
Run in IE 11

### Screenshot - *(optional)*
http://jira.tmctrans.com:8080/secure/attachment/36537/2019-12-23%2011_49_44-Create%20Issue%20-%20Jira.png

**Comment by lucasnetau** [comment]
IE is not longer supported by this project
