### ISSUE TITLE
Field ID increment bug (onAddField/onclone/data.lastID)

### ISSUE THREAD

**Issue by relosmot** [kevinchappell/formBuilder#1044]
### Description:
Wrong field opened when editing a cloned field.

### Environment Details:

 - formBuilder Version: Latest (3.4.1)
 - Browser: Chrome
 - OS: MacOS

### Expected Behavior
Cloned field should be editable.

### Actual Behavior
The edit panel for the field that was cloned is opened instead of the target field.

### Steps to Reproduce
1. Go to https://formbuilder.online/.
2. Add a text field.
3. Clone the text field.
4. Click to edit the newly cloned field.
5. The previous field edit panel will open instead of the target field.

**Comment by kevinchappell** [comment]
Thanks for filing this and the detailed steps to reproduce. A PR will be opened shortly.

**Comment by relosmot** [comment]
> Thanks for filing this and the detailed steps to reproduce. A PR will be opened shortly.

You're welcome!
Thank you for the prompt reply & fix.

Also, thanks for building this great piece of software!
