### ISSUE TITLE
typeUserAttrs only when specific SubType is selected?

### ISSUE THREAD

**Issue by futureweb** [kevinchappell/formBuilder#1046]
Hey there,
is is possible to add a special typeUserAttrs only when "E-Mail" SubType in Textfield is selected?
I need a DropDown when E-Mail SubType is selected with "Empty Value", "Set as Sender".
thx, bye from Austria
Andreas

**Comment by futureweb** [comment]
solved as own subtype ...

```
subtypes: {
            text: ["email_als_Absender"]
         }
```

**Comment by parrainc** [comment]
Any updates about this? 
I'm needing the same thing, but looks like that's no possible yet :(

Have you figured out how to do it?

**Comment by parrainc** [comment]
I've managed to implement this, so far it's working as I needed. 
@futureweb I think this could work for your use case as long as you set the subtype to the text field before rendering. (not sure if the library would support something like what you mentioned though which would be adding the field dynamically based on the subtype).

I can create a pull request, probably the way I implemented it is useful in some way to get this merged.

**Comment by futureweb** [comment]
@parrainc - for our use case it would unfortunately have to happen dynamically after rendering.
Our customers can choose in the text field whether it is normal "text", "password", "e-mail" or a few other types. And depending on the selected type, you should be able to select a few more attributes. For example, in the case of "E-Mail", the attribute "must be empty" (for anti-spam checks) ...
But I guess your PW can help others ... ;-)

**Comment by parrainc** [comment]
I hope so, and also would like to see that feature you need implemented soon. There might be some users who benefits from it.
cheers!

**Comment by lucasnetau** [comment]
Was implemented in PR https://github.com/kevinchappell/formBuilder/pull/1168
