### ISSUE TITLE
Add Feature: Phone Number, Address

### ISSUE THREAD

**Issue by dwaynedsouza** [kevinchappell/formBuilder#1047]
Hi,
This form builder is awesome and easy to use. Could we have the following components as this will be a great benefit for my use

1. Phone Number
![image](https://user-images.githubusercontent.com/25810089/76000070-27f89600-5ed1-11ea-8217-ff6c6d1897d4.png)

2. Address field.

![image](https://user-images.githubusercontent.com/25810089/76000132-3fd01a00-5ed1-11ea-91de-9e67ffeceba0.png)

**Comment by kevinchappell** [comment]
Address can be accomplished with input groups, phone number will require a custom field. Please see documentation for examples.

**Comment by scottrpaterson** [comment]
+1

Yes, it can be accomplished using custom fields, but it would be very nice if this were built into the core feature set.
