### ISSUE TITLE
Drop down is not rendering when JSON data is provided in Form Render:

### ISSUE THREAD

**Issue by ammaran2000** [kevinchappell/formBuilder#1048]
### Description:
Hello, I am rendering the form with JSON data. Dropdown list is not rendering properly and is expended as a list like I can select the multiple values. On my investigation, I found out that this element ""multiple":false" is creating the problem and when I remove this then its working fine. Can you please guide me how to remove this glitch or what is way around other than using xml data instead of JSON data?
Rendering from the XML data is working file.

### Environment Details:
Windows 10 Enterprise
Simple HTML Page

 - formBuilder Version: 3.3.5
 - Browser: Version 76.0.3809.87 (Official Build) (64-bit)
 - OS: Windows 10 Enterprise (64 bit)

### Expected Behavior
Drop down should be rendered as

**Comment by buttle** [comment]
Hi,

I can confirm this (though I haven't tested it with XML like @ammaran2000 says).

**Comment by Jojoshua** [comment]
Try with the latest version. Feel free to reopen if still an issue
