### ISSUE TITLE
Reference Error with strict mode in builder and render

### ISSUE THREAD

**Issue by bjnhuggins** [kevinchappell/formBuilder#105]
Hi,

I have had to rename some function names in the builder and render. I run automated tests using selenium web driver. When running it in htmlunit it throws the following error on a few lines. Renaming the functions to be different to the variable names seems to do the trick. I am currently using version 1.9.10 but will need to update soon. Could you please rename the functions to fix this so I do not have to do so for each update.

ReferenceError: Assignment to undefined "formBuilderHelpers" in strict mode (http://localhost:8000/javascript/formbuilder/form-builder.js#10)

Changes made:

form-builder.js
ln 10
var formBuilderHelpers = function formBuilderHelpersFn(opts, formBuilder) {
ln 721
var formBuilderEvents = function formBuilderEventsFn(opts, _helpers) {

from-render.js
ln 56
var FormRender = function FormRenderFn(options, element) {

**Comment by kevinchappell** [comment]
I knew it threw errors under strict mode for redefinition because of jshint global setting but don't quite understand "Assignment to Undefined" because in each case it's being defined. I'll change the name but it looks like these need to be refactored as submodules.
