### ISSUE TITLE
formBuilder does not wok on Safari on iPad

### ISSUE THREAD

**Issue by davidh07** [kevinchappell/formBuilder#1053]
### Description:
Hi Trying to use formBuilder directly from your website landing page using Safari on iPad latest version.  It does not show up.  Is it supported?
### Environment Details:
iPad Safari latest version
 - formBuilder Version: your website.  formbuilder.online
 - Browser: Safari
 - OS: iPad

**Comment by kevinchappell** [comment]
finally got to test this on ipad but was not able to reproduce the problem. do you see a specific error?
