### ISSUE TITLE
Add a custom field based on "select" type

### ISSUE THREAD

**Issue by jbousque** [kevinchappell/formBuilder#1055]
### Description:

Basically I would like to add a new field, based on the "select" type (ie, benefiting from the config params available to the user, like possibility to define list of options), but with a custom way of displaying it, and best, some additional and specific config params.
But I fail to find an easy way to do this.

Tried so far:

1-
added a new field in "fields" FB options based on type "select", then added to "templates" my custom markup, also associated to type "select".
OK: new field with my custom display, and config params from "select" type.
NOK: original "select" type/field is not available anymore to users, as it's been replaced.

	const fields = [{
			label: 'Select Custom',
			attrs: {type: 'select'},
			icon: '🌟'}];

	let templates = {'select': function(fieldData) {
			return {
				field: '<span id="'+fieldData.name+'">',
				onRender: function() {
					// my markup rendering code
				}
			};}};

Note: I may decide to "sacrifice" the "select" original field but if there's another way I'd prefer being able to keep it :)

2-
Tried to register a new subtype :

  a- either in "subtypes" FB options, and fields/templates as above for custom markup but referencing this subtype
      OK: new field is available, select not replaced
      NOK: config params for new field are the basic ones, no way to define options
  (based on what you said in another issue, I understand it's normal that this does not work)

  b- either by registering new subtype, from a dummy class extending controlClass, I pass the second optional param with keys as types and values as control classes, and I use this to register a new subtype based on the controlClass of the "select". Then I do as in a-, referencing this subtype "selectCustom" to add a field with a specific template.
OK and NOK are the same as for a-.

   controlClass.register('selectCustom', allControls.select, 'select');

### Environment Details:

 - formBuilder Version: 3.4.0
 - Browser: brave/FF
 - OS: linux

**Comment by jbousque** [comment]
In fact approach 1- is NOK, because when I render the form based on saved formData, a standard select is displayed instead of my custom markup ... Which makes sense but I don't see any option to adapt this on formRender side.

**Comment by Nopraz** [comment]
I want to do nearly the same thing as you, I want to be able to generate a list of text inputs with the same interface as the select types controls.

What i did for now is i defined a new custom plugin control and extended the select control class :

``` 
// configure the class for runtime loading
if (!window.fbControls) window.fbControls = new Array();
window.fbControls.push(function(controlClass, allControlClasses) {
    const controlSelect = allControlClasses.select

  /**
   * Classe du plugin de groupe de champs
   */
  class controlInputGroup extends controlSelect {

    static get definition(){
        return {
            i18n: 'Groupe de champs',
            name: "inputGroup",
            type: 'select',
            attrs: {
              type: 'select'
            },
            icon: '🌟'
          }
    }

    /**
     * build a text DOM element, supporting other jquery text form-control's
     * @return DOM Element to be injected into the form.
     */
    build() {
        //TODO Créer les champs input selon les options indiqué dans les paramètres du contrôle

        return this.markup('div', null, {id: this.config.name});
    }

    onRender() {
        console.error($('#' + this.config.name));
        $('#' + this.config.name).html('<h1>Test</h1>');
    }
  }

  // register this control for the following types & text subtypes
  controlSelect.register('inputGroup', controlInputGroup);
  return controlInputGroup;
});
```

I want to be able to add options with the "Add new option" in the form builder interface to add new inputs in a div

**Comment by asavchyn5** [comment]
Trying to do the same thing. 1+ 
Too bad that you cant pass an option/values attribute to the custom field and have the functionality of editing the options in the edit mode show up.

**Comment by NoobLTv** [comment]
@Nopraz I am curious did you fix the options field?

**Comment by lucasnetau** [comment]
You can achieve this by extending the select control in the plugins. If you only want to have the options then don't call to super.build or super.onRender

```javascript
window.fbControls.push(function(controlClass, allControlClasses) {
    "use strict";

    const controlSelect = allControlClasses.select;

    class myCustomWithOptions extends controlSelect {
...
        configure() {
            //Set type back to radio-group so that we render correctly, or any other type supported by controlSelect
            this.config.type = 'radio-group';
            //any other config...
            return super.build();
        }

        onRender() {
            super.onRender(); //Call super.onRender if we define our own render in the child class

```

one thing to note is for control

**Comment by lucasnetau** [comment]
An example of this is now available https://github.com/lucasnetau/formBuilder-plugins/blob/main/plugins/customSelect.js
