### ISSUE TITLE
Quotes in "description" breaking JSON formData

### ISSUE THREAD

**Issue by futureweb** [kevinchappell/formBuilder#1056]
Hey there,
adding a Link to a Description will break JSON formData Loading ... see Pen: https://codepen.io/futureweb/pen/mdJQXLr

>   var options = { 
>     formData: '[{"type":"text","required":false,"label":"Textfeld","description":"<a href=\\"/test\\"/>Test</a>","className":"form-control","name":"text-1585227893014","subtype":"text"}]'
>   };

The Quotes are escaped - but still throwing JS Error when trying to Load this formData ... ?

> SyntaxError: "JSON.parse: expected ',' or '}' after property value in object at line 1 column 77 of the JSON data"

Any Ideas on that?

thx, bye from Austria
Andreas

**Comment by futureweb** [comment]
Also Backslash bringing troubles :-(
A simple \ in Field name is exported as \\ - and when trying to load this SJON - also Error: https://codepen.io/futureweb/pen/GRJwQbE

**Comment by futureweb** [comment]
Any idea on this? As this one really brings troubles while using this great Tool ... :-/

**Comment by Jojoshua** [comment]
You need to stringify and parse json appropriately.
