### ISSUE TITLE
Fields and templates are nested under InputSets then type attribute is not working

### ISSUE THREAD

**Issue by naisargparmar** [kevinchappell/formBuilder#1062]
### Environment Details:

 - formBuilder Version: 3.4.2
 - Browser: Chrome
 - OS: Mac Mojave

### Expected Behavior
In the below code, I am expecting the type='txt_country_code'. But it show type='text'
formBuilder = $(this.fb.current).formBuilder({
inputSets: [
.......{
..............label: 'Mobile',
..............icon: "#",
..............fields: [
.....................{
............................label: 'Country code',
............................icon: "#",
............................className: 'form-control',
............................attrs: {
...................................type: 'txt_country_code'
............................}
.....................}
...................],
..............templates: {
............................txt_country_code: (fieldData) => {
............................return {
...................................field: '<input id="' + fieldData.name + '" class="form-control">',
...................................onRender: function() {}
................................}
........................}
..............}
.......}
.......]
.......})

### Actual Behavior
Above code it show the type='text

### Screenshot - *(op
<img width="1154" alt="Screenshot 2020-04-14 at 8 19 36 PM" src="https://user-images.githubusercontent.com/35989770/79224275-651b5500-7e8d-11ea-895d-aa1ac04a3637.png">
tional)*

**Comment by lucasnetau** [comment]
templates cannot be nested, they need to be defined at the root level of config.

```javascript
templates: {
    txt_country_code ...
}
inputSets: [
{
   label: 'Mobile',
   icon: "#",
   fields: [ ...
   ]
...
```
