### ISSUE TITLE
Custom Validation

### ISSUE THREAD

**Issue by nirav1211** [kevinchappell/formBuilder#1082]
Description: Can we add any custom validation to any field eg: textarea, text field ?

**Comment by rendezz** [comment]
you can add the pattern typeUserAttr quite easily described here

[](https://formbuilder.online/docs/formBuilder/options/typeUserEvents/)

Specifically
`  typeUserAttrs: {
    text: {
      pattern: {
        label: 'Pattern',
        description: 'Enter a RegExp passwords must match'
      }
    }
  },`

**Comment by nirav1211** [comment]
Thankyou @rendezz
