### ISSUE TITLE
FormRender React

### ISSUE THREAD

**Issue by AlexCharlton93** [kevinchappell/formBuilder#1086]
Hi, I've been trying to get FormRender to work in my React Application. Sorry if there is already documentation for this - I've looked through and couldn't find anything.

I understand for non-react apps the following guide works, providing the JS file is referenced
https://formbuilder.online/docs/formRender/demos/basic/

But how do I use formRender in React?

I've tried installing and requiring formRender package but guessing it doesn't exist?
i.e. require('formRender');

Thanks in advance,
Alex

**Comment by NatalieWLSS** [comment]
I have used it in react by adding this:
`require('formBuilder/dist/form-render.min.js');`

here's a sample way of calling it
`$(fb.current).toggle();
$(fbRender.current).toggle();
$(userForm.current).formRender({
	dataType: 'json',
	formData: $(fb.current).formBuilder('getData', 'json')
});`

fb = Form Builder
fbRender = Form Render
useForm = Form element inside my Form Render

**Comment by jahids** [comment]
> I have used it in react by adding this: `require('formBuilder/dist/form-render.min.js');`
> 
> here's a sample way of calling it `$(fb.current).toggle();` `$(fbRender.current).toggle();` `$(userForm.current).formRender({` ` dataType: 'json',` ` formData: $(fb.current).formBuilder('getData', 'json')` `});`
> 
> fb = Form Builder fbRender = Form Render useForm = Form element inside my Form Render


brother where do I use require?plz help me

**Comment by NatalieWLSS** [comment]
> > I have used it in react by adding this: `require('formBuilder/dist/form-render.min.js');`
> > here's a sample way of calling it `$(fb.current).toggle();` `$(fbRender.current).toggle();` `$(userForm.current).formRender({` ` dataType: 'json',` ` formData: $(fb.current).formBuilder('getData', 'json')` `});`
> > fb = Form Builder fbRender = Form Render useForm = Form element inside my Form Render
> 
> brother where do I use require? give me any GitHub or code link plz... plz help me

You can add it after your importing components.  Kevin Chappel has a sample of it in CodeSandbox:
https://codesandbox.io/s/725zk1mx1?file=/src/index.js
