### ISSUE TITLE
Can't add custom element in multiple form builder!

### ISSUE THREAD

**Issue by myowinthein** [kevinchappell/formBuilder#1090]
### Description:
I'm using form builder on Laravel blade and created a custom element below.
```javascript
{
   className: "form-control",
   label: "Relationship",
   type: "select",
   values: @json($relationships),
   icon: '<i class="fas fa-link"></i>'
}
```

That custom element is used by multiple form builder within the same page. I'm using multi-page builder as described in [here](https://formbuilder.online/docs/formBuilder/demos/tabs/).

![Screenshot from 2020-06-23 11-30-57](https://user-images.githubusercontent.com/20858430/85362670-118c4e00-b545-11ea-8156-f0ca3b4bbda2.png)

### Environment Details:

 - formBuilder Version: 3.4.2
 - Browser: Chrome 83.0.4103.106
 - OS: Ubuntu 20.04

### Expected Behavior
Custom element should be added in every form builder instance.

### Actual Behavior
It's only work in last initiated form builder (in my screenshot above, it's Page 7). When I add in other pages, it show below error.

![Screenshot from 2020-06-23 11-26-50](https://user-images.githubusercontent.com/20858430/85362838-8495c480-b545-11ea-909b-5b65c86b56b9.png)

That custom element is imported as `type + random number`. So, it can't find in template and showing above error. Is this the default behavior ? How can I fix that ?

**Comment by lucasnetau** [comment]
The custom.js class is re-initialised with each formBuilder. This is causing the controlCustom.customRegister property to be overwritten.

https://github.com/kevinchappell/formBuilder/blob/24cc643dcabb7e810aa4321a1d0aff939729d067/src/js/control/custom.js#L16
