### ISSUE TITLE
Change default Screen message

### ISSUE THREAD

**Issue by dwaynedsouza** [kevinchappell/formBuilder#1091]
Is there a way to change the default screen message of the builder. I would like to add a few instructions for the user.

![image](https://user-images.githubusercontent.com/25810089/85762168-77154180-b6e1-11ea-85ae-0e5ef8778173.png)

**Comment by JasonVonKrueger** [comment]
Did you ever figure this out?  I have the controls on the left and need to make the text dynamic to match which side they're on.  I can't find where this verbiage is set.

**Comment by JasonVonKrueger** [comment]
Never mind.  It was as simple as adding an option...

`		i18n: {
			override: {
				'en-US': {
					getStarted: 'Drag and drop a field here!',
				}
			}
		},`
