### ISSUE TITLE
Install Dependencies Error

### ISSUE THREAD

**Issue by shgohh** [kevinchappell/formBuilder#1092]
### Description:
Install Dependencies error (npm install)

### Environment Details:

 - formBuilder Version: 3.4.2
 - Browser: Firefox 78.0.1
 - OS: Windows 10

### Expected Behavior
Build successfully

### Actual Behavior
D:\Lab\GitHub\formBuilder>npm install

> node-sass@4.13.1 install D:\Lab\GitHub\formBuilder\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.1/win32-x64-83_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.13.1/win32-x64-83_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> core-js@3.6.4 postinstall D:\Lab\GitHub\formBuilder\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> node-sass@4.13.1 postinstall D:\Lab\GitHub\formBuilder\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe D:\Lab\GitHub\formBuilder\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'D:\\Lab\\GitHub\\formBuilder\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.5.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\Lab\GitHub\formBuilder\node_modules\node-gyp\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\Lab\GitHub\formBuilder\node_modules\node-gyp\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\Lab\GitHub\formBuilder\node_modules\node-gyp\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\Lab\GitHub\formBuilder\node_modules\node-gyp\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\Lab\GitHub\formBuilder\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\Lab\GitHub\formBuilder\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:176:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\Lab\GitHub\formBuilder\node_modules\node-gyp\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\Lab\GitHub\formBuilder\node_modules\node-gyp\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\Lab\GitHub\formBuilder\node_modules\node-gyp\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\Lab\GitHub\formBuilder\node_modules\node-gyp\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\Lab\GitHub\formBuilder\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\Lab\GitHub\formBuilder\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:176:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Program Files\Python37\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Program Files\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:308:12)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Lab\\GitHub\\formBuilder\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\Lab\GitHub\formBuilder\node_modules\node-sass
gyp ERR! node -v v14.5.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN rollback Rolling back ansi-regex@2.1.1 failed (this is probably harmless): EPERM: operation not permitted, lstat 'D:\Lab\GitHub\formBuilder\node_modules\has-ansi\node_modules'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

`

### Steps to Reproduce
npm install

**Comment by kevinchappell** [comment]
this looks like it was a temporary node-sass issue. additionally all dependencies have been update.
