### ISSUE TITLE
I want to create some custom selects that will bind with SQL data

### ISSUE THREAD

**Issue by Fenix-ops** [kevinchappell/formBuilder#1093]
### Description:
I want to create some custom selects that will bind with SQL data. I would like to lock those values down so our users can add the select but not manipulate the options for the select. Is there a way to do this currently?
### Environment Details:

 - formBuilder Version: 
 - Browser: 
 - OS:

**Comment by rayenmhamdi** [comment]
hi, @Fenix-ops it will be awesome to have this feature. I'll wait for it too.
and not only select widgets any kind of widgets: bind their values with an API that came from ajax request, in the end, we can have widgets with dynamic values.
I hope the Jquery builder team can provide an answer

**Comment by lucasnetau** [comment]
Please take a look at https://github.com/lucasnetau/formBuilder-plugins/blob/main/plugins/customSelect.js for an example of how to inject your options into a select in the build() stage
