### ISSUE TITLE
I want to create checkbox-group , with type typeUserAttrs in custom control

### ISSUE THREAD

**Issue by kashif-ali-khan** [kevinchappell/formBuilder#1099]
### Description:
I am creating custom control,
so i want to add checkbox-group control using typeUserAttrs.

i am not sure how it will be done.

I am able to add only single checkbox

### Environment Details:

 - formBuilder Version:  3.4.1
 - Browser:  any
 - OS:  any

**Comment by kashif-ali-khan** [comment]
> ### Description:
> I am creating custom control,
> so i want to add checkbox-group control using typeUserAttrs.
> 
> i am not sure how it will be done.
> 
> I am able to add only single checkbox
> 
> ### Environment Details:
> * formBuilder Version:  3.4.1
> * Browser:  any
> * OS:  any
> 
> ### Expected Behavior
> ### Actual Behavior
> ### Steps to Reproduce
> ### Screenshot - _(optional)_

@kevinchappell , any idea how can achieve this

**Comment by kevinchappell** [comment]
can you provide an example use case? i think it may be possible but not sure of the use case
