### ISSUE TITLE
formBuilder based on xml, problem

### ISSUE THREAD

**Issue by GarryOne** [kevinchappell/formBuilder#110]
If I initialize formBuilder based on following xml, it doesn't work properly
```
<form-template>
	<fields>
		<field label="Checkbox Group" name="checkbox-group-1458766047820" type="checkbox-group">
			<option value="option-1">some text</option>
			<option value="option-2">another text</option>
			<option value="fsadfdas">some another text</option>
		</field>
	</fields>
</form-template>
```

It will produce the following result.
http://i.imgur.com/UrJcfFy.png
No matter what

The problem persist on radio buttons too.

The problem appeared in the latest versions. 
In the Version: 1.7.5, it's working well.

**Comment by kevinchappell** [comment]
That's quite bad. The difference between those versions is the way form data is saved. I look into this tonight.

**Comment by agerson** [comment]
How do you initialize formBuilder based on xml?

**Comment by agersoncgps** [comment]
Sorry, just to be clearer, I know how to get the XML of a form I previously built, but I cant find the option for passing that back into $(template).formBuilder(options); to generate the form again.

**Comment by kevinchappell** [comment]
@agersoncgps @agerson 
http://codepen.io/kevinchappell/pen/MygvQg
http://codepen.io/kevinchappell/pen/Vedrqr

Working on some documentation for this now.

**Comment by GarryOne** [comment]
```
<textarea id="form-builder-template" ><?php echo $model->dataXML; ?></textarea>
<script>
$('#form-builder-template').formBuilder();
</script>
I use this code 
```fore editing an form.

**Comment by GarryOne** [comment]
http://codepen.io/GarryOne/pen/dMWrzj
