### ISSUE TITLE
How to add Options in custom control

### ISSUE THREAD

**Issue by kashif-ali-khan** [kevinchappell/formBuilder#1101]
![options-control](https://user-images.githubusercontent.com/7630477/87642836-add1fb00-c767-11ea-8fbe-c9249607e436.png)
### Description:
I want to achieve this using custom control ?
I don't know how to proceed
### Environment Details:

 - formBuilder Version: 
 - Browser: 
 - OS:

**Comment by kashif-ali-khan** [comment]
Any one has , any idea about this ?

**Comment by KrenZfer** [comment]
Hi, kashif,
What is your purpose to take options as custom control?

**Comment by kashif-ali-khan** [comment]
> Hi, kashif,
> What is your purpose to take options as custom control?

The reason is,  i am planning to make make few custom control, and each custom control will have it's own set of configurations.

those configuration i am able to achieve with   "typeUserAttrs", 
but when i need to captured some multiple configuration option, i am not able to do so.

![custom control](https://user-images.githubusercontent.com/7630477/87847119-071a6580-c8f3-11ea-9387-0b1726ff9656.png)

**Comment by kevinchappell** [comment]
should be doable now with `onAddOption`
