### ISSUE TITLE
Error when fetch the xml 

### ISSUE THREAD

**Issue by wudoz** [kevinchappell/formBuilder#111]
I used v1.9.14 version, and try to put some elements into the textarea in the form builder design web page.
then I try to get the xml after click "Save" button the patrial code as below.
var xmlString = $('.frmb').toXML();

I found there bug some error in form-builder.js
![image](https://cloud.githubusercontent.com/assets/829351/14007519/72b06f6e-f1b2-11e5-914d-36319a928f75.png)

**Comment by kevinchappell** [comment]
I was not able to replicate this issue, could you try the latest version? Also, are you able to get formData at all? If so can you post and I will see if there is something in the xml throwing messing up`toXML()`

**Comment by wudoz** [comment]
@kevinchappell ,I already update the latest version but still got the same issue. could you give me a demo with the latest version on your demo site?

**Comment by kevinchappell** [comment]
All demos use latest version. If you go to Demos from main menu you should be able to find one you can text your code on. Http://formBuilder.online

**Comment by wudoz** [comment]
I put the following code in "formbuilder->basic" and still can't get XML data.
```
$(".fb-save").click(function (e) {
    e.preventDefault();
    var xmlString = $('.frmb').toXML();
    alert(xmlString);
});
```

**Comment by kevinchappell** [comment]
Are you trying to export the xml?

**Comment by kevinchappell** [comment]
Oh, I see the problem. `toXML` needs to be refactored because its not a standalone plugin anymore. Now if you want to get just the XML you could to something like this: http://codepen.io/kevinchappell/pen/bpRowv?editors=0010

Future versions will have a `getData()` method but for now formData has a copy in jquery `data()`.

**Comment by wudoz** [comment]
@kevinchappell , refer to your sample code I solved my problem, thank you.
