### ISSUE TITLE
How to move the default field area to the right side

### ISSUE THREAD

**Issue by an-amin** [kevinchappell/formBuilder#1117]
### I want the fields area (.stage-wrap to) be right and the controls (.cb-wrap) area to be left side
Is there is any settings option to do that?

### Environment Details:

 - formBuilder Version: Version: 3.6.0
 - Browser: Firefox
 - OS: Ubuntu 18.04

### Current 
![form-builder-current](https://user-images.githubusercontent.com/11975039/91318317-e9d39380-e7dc-11ea-8604-06a57c6bfeaf.jpg)

### Expectation 
![form-builder-wish](https://user-images.githubusercontent.com/11975039/91318363-f48e2880-e7dc-11ea-815d-382bc4d246e4.jpg)

**Comment by Fenix-ops** [comment]
hi this will help you https://formbuilder.online/docs/formBuilder/options/controlPosition/

**Comment by kevinchappell** [comment]
thank you!
