### ISSUE TITLE
Umlauts break XML

### ISSUE THREAD

**Issue by ivuorinen** [kevinchappell/formBuilder#112]
Following XML breaks because of `&auml;`, I imagine all other umlauts act same way.

```xml
<form-template>
	<fields>
		<field class="btn" label="L&auml;het&auml;" name="button-1458140997967" type="submit" subtype="submit"/>
	</fields>
</form-template>
```

Edit: jQuery.parseXML returns the error.

**Comment by kevinchappell** [comment]
Umlauts should no longer break and will render correctly however I noticed `type="submit"` is no longer a valid type. it should be `type="button" subtype="sumit"` unfortunately this button may need to be recreated
