### ISSUE TITLE
enhancement: select to be made extendable

### ISSUE THREAD

**Issue by nmase88** [kevinchappell/formBuilder#1121]
### Description:
I have been looking into adding a plugin for select2 as the standard select is... not great. However, it doesn't appear to be possible as you cannot add a subtype for select like you can for text area and if you try to add it as a new type the configuration does not have options attribute only value attribute.

### Environment Details:

 - formBuilder Version: 3.6.0
 - Browser: chrome
 - OS: windows

**Comment by mariusmow** [comment]
I manage to get select2 working, I used jquery to apply select2 to all dropdowns with an id starting with "select-"

	$('#fb-render').formRender(fbRenderOptions)
	
	//apply select2 to all select dropdowns
	$('select[id^="select-"]').select2();

**Comment by nmase88** [comment]
So you've just applied it after rendering the form instead of doing it as a plugin. That makes sense, not sure why I didn't think of that... thank you!

**Comment by nmase88** [comment]
> I manage to get select2 working, I used jquery to apply select2 to all dropdowns with an id starting with "select-"
> 
> ```
> $('#fb-render').formRender(fbRenderOptions)
> 
> //apply select2 to all select dropdowns
> $('select[id^="select-"]').select2();
> ```
