### ISSUE TITLE
Select Options radio issue

### ISSUE THREAD

**Issue by suffian-farooq** [kevinchappell/formBuilder#1124]
### Description:
Select -> Options -> radio switch issue here is an example image. https://prnt.sc/uhlkjd

### Environment Details:

 - formBuilder Version: v3.6.1
 - Browser: chrome
 - OS: windows

### Expected Behavior
at a time only one radio option selected

### Steps to Reproduce
switch radio option in a select element

### Screenshot - *(optional)*
 https://prnt.sc/uhlkjd

**Comment by instagibb** [comment]
The radio buttons are missing the name attribute. This was broken sometime between 3.5.2 and 3.6.0 and seems to be related to the `onAddOption` changes. Rolling back to 3.5.2 resolves this.
