### ISSUE TITLE
Button variables not processed from XML

### ISSUE THREAD

**Issue by ivuorinen** [kevinchappell/formBuilder#113]
When opening Button modification panel in the stage, button type dropdown is set as "button" even when XML states ``subtype="submit"``.

Might be related: ``.fld-className`` is missing set CSS classes, defaults to ``btn btn-default`` when XML states ``class="btn btn-success"``.

**Comment by kevinchappell** [comment]
This issue was due to the way subtypes are handled. Unfortunately the buttons may need to be recreated to work with the new schema
