### ISSUE TITLE
Bug | onAddField callback regression

### ISSUE THREAD

**Issue by happymachines** [kevinchappell/formBuilder#1131]
# Description:
The `onAddField` option does not behave according to the spec defined in the documentation.

### Environment Details:

 - formBuilder Version: `3.6.1` and any version > `3.4.3`
 - Browser: N/A (Tested on Firefox/Chrome/Safari)
 - OS: N/A

### Expected Behavior

The `onAddField` callback should behave according to the spec defined in the documentation

> Callback for when fields are added to the stage. Good as a catch-all action for anything that needs to happen before a field is added to the stage. Possible to modify the field's configuration before it's appended by returning a fieldData object

This callback should run _before_ the field is added to the stage allowing fieldData to be modified as expected.

### Actual Behavior

The changes implemented here:
- Issue: https://github.com/kevinchappell/formBuilder/issues/1096
- PR for the issue: https://github.com/kevinchappell/formBuilder/pull/1097

Moved the callback execution after the field is appended to the form builder. The result of this is any changes made to the `fieldData` object in the callback are not applied to the rendered field.

### Steps to Reproduce

- Add a callback handler to the `onAddField` option
- Attempt to modify the `fieldData` object
```
onAddField: function(fieldId, fieldData) {
    fieldData.label = 'This should be updated';
    return fieldData;
}
```
- The changed data is not applied to the added field

**Comment by zeonglobal** [comment]
Please make this solution available in the master branch. I am having this issue too.

**Comment by gruelas16** [comment]
> Please make this solution available in the master branch. I am having this issue too.

Me too, hoping it will get merge soon

**Comment by happymachines** [comment]
This was incl
