### ISSUE TITLE
Render URL / Link on simple field

### ISSUE THREAD

**Issue by AliakseiAzarchankau** [kevinchappell/formBuilder#1134]
Hi all, 

When using the Form Builder, if I add a simple **Paragraph** field or **Text** field, and I make the value of those fields a hard coded link/url like [http://www.google.ca](http://www.google.ca), when the form is rendered it displays it as a simple string that's not clickable.

Is this an issue, or is there a way I can configure a field to be able to display a clickable link? Apologies if this is not an issue / has been resolved already, I tried to do some searching and could not find any results. If anyone could advice or point me in the right direction for how to display a link/URL, it would be greatly appreciated.

Thank you!

**Comment by tanzeel917** [comment]
How you render your form Can you please help me out?
Basically when I click on the save button not action is performed.

**Comment by lucasnetau** [comment]
Auto detection/markup of URLs is not part of the controls. You can insert a link via adding HTML content into the paragraph fieldd

eg 

```html
<a href="https://google.com">Google</a>
```

**Comment by lucasnetau** [comment]
There are various ways to make the links which could be done via a custom template for paragraph

https://stackoverflow.com/questions/1500260/detect-urls-in-text-with-javascript
