### ISSUE TITLE
Checkbox Attributes not working when untick the options from edit 

### ISSUE THREAD

**Issue by testtechno** [kevinchappell/formBuilder#1137]
### Description:
I have created one checkbox group and click on edit icon. And i have unchecked the Toggle, Inline and Enable other checkbox. And saved that form in database in JSON format.. but when i am showing that JSON from then above unchecked marked as checked. That the issue. I want to show checkbox instead of switch and not want to show other check box fields. But its not working. 
### Environment Details:

 - formBuilder Version: 3.6.1
 - Browser: Chrome
 - OS: WIndow

### Screenshot - *(optional)*

![image](https://user-images.githubusercontent.com/47387674/98434297-790df900-20f4-11eb-9437-ca61a36e8fab.png)

![image](https://user-images.githubusercontent.com/47387674/98434318-93e06d80-20f4-11eb-8c7f-90e20277282f.png)

**Comment by lucasnetau** [comment]
Please try with a more recent version. If this is still occurring please reopen this issue and attach a reproducible test script
