### ISSUE TITLE
Pre defined fields

### ISSUE THREAD

**Issue by DevGarg262** [kevinchappell/formBuilder#1142]
### Description:
Can we add pre defined fields like First Name , Last Name , DOB , email id etc in the drag and drop fileds. So that we don't need to edit in the label.
### Environment Details:

 - formBuilder Version: 
 - Browser: 
 - OS:

**Comment by kevinchappell** [comment]
yes, there are a few ways to do this:
https://formbuilder.online/docs/formBuilder/options/fields/
https://formbuilder.online/docs/formBuilder/options/inputSets/
https://formbuilder.online/docs/formBuilder/options/templates/

**Comment by simon1982** [comment]
Hi @kevinchappell, first I would like to say great work very cool project! 

My question is how can I add custom dom elements? 

Well in the form builder mode in options, based on the "star rating" I have created this : 

var fields = [{
                label: 'Step Start',
                attrs: {
                    type: 'tabStart'
                },
                icon: '🌟'

            }, {
                label: 'Step Stop',
                attrs: {
                    type: 'tabStop'
                },
                icon: '🌟'
            }];
            var templates = {
                tabStart: function(fieldData) {
                    return {
                        field: '<div class="tab">',
                        onRender: function() {
                            $(document.getElementById(fieldData.name));
                        }
                    };
                },
                tabStop: function(fieldData) {
                    return {
                        field: '</div>',
                        onRender: function() {
                            $(document.getElementById(fieldData.name));
                        }
                    };
                }
            };

I would like to have as an output "<div class="tab">" and the second (tabStop) out put would be "</div>".

Now on the form Render site the out put need to be with no warp around this divs, so clean <div class="tab"> and then latter some where in the form a closing of div. 

You may ask, what I want to make with that. Well I want to have the possibility to create a easy multi step forms :) 

Based on this https://www.w3schools.com/howto/howto_js_form_steps.asp. 

It would be super easy to make them, as the user that is drag and drop elements would just drag where the page should start and where should stop :)
