### ISSUE TITLE
Does not remove options on editor

### ISSUE THREAD

**Issue by FreitasJonas** [kevinchappell/formBuilder#1143]
### Description:
Is impossible to remove options from CheckBox Group, Radio Group, Select...

### Environment Details:

 - formBuilder Version: 3.6.0
 - Browser: Google Chrome
 - OS: Windows 10

### Expected Behavior
Remove options in the editor by clicking the Close button

### Actual Behavior
Does not remove

### Steps to Reproduce
Add a radio group on editor, add some options and try to remove clicking on the button 'close'

### Screenshot - *(optional)*
![image](https://user-images.githubusercontent.com/31151320/101350905-8f7faf80-386e-11eb-9fdf-9572fceed2ff.png)

This button doesn't work.

**Comment by kevinchappell** [comment]
@FreitasJonas This is actually a styling error. If you check the console after clicking the remove button on the second option you'll see a message saying that a radio group requires at least 2 options. I'm not sure why the style for this stopped working but have updated it to hide the second option remove again in #1144 .

**Comment by FreitasJonas** [comment]
@kevinchappell Thanks for your attention.

Unfortunately the problem persist.

See:

![image](https://user-images.githubusercontent.com/31151320/101399981-fe7cf880-38ae-11eb-9bf4-306f556a3572.png)

When I keep clicking

![image](https://user-images.githubusercontent.com/31151320/101400029-0e94d800-38af-11eb-9475-86d11c13e3a5.png)

**Comment by kevinchappell** [comment]
i have never seen that second screenshot. Can you create a codepen that replicates the problem? https://codepen.io/kevinchappell/pen/vLjOLL

currently i am unable to reproduce the issue:
![1143](https://user-images.githubusercontent.com/1457540/101402541-bba82a00-3888-11eb-9ef6-5f11e455d909.gif)

**Comment by FreitasJonas** [comment]
I managed to resolve this error when I analyzed the page's css, I realized that a style file was interfering with the style of the formbuilder causing the position of the close button to be changed.

thanks for your attention and sorry for the mistake, it was not a problem in formBuilder.
