### ISSUE TITLE
Renderer - No userdata for prechecked checkbox

### ISSUE THREAD

**Issue by Maexwillsmart** [kevinchappell/formBuilder#1147]
Create a checkboxgroup with predefined checked:
![Checkbox Create](https://user-images.githubusercontent.com/75825439/101867030-8f3b2900-3b7a-11eb-98ce-7a296032ded3.JPG)

After renderer, no userdata will be tracked vor uncheck, checkbox will always be true:
![Deselect1](https://user-images.githubusercontent.com/75825439/101867072-a843da00-3b7a-11eb-904c-a62886fea6c0.JPG)

Checked without predefined - everything worked:
![Disabled](https://user-images.githubusercontent.com/75825439/101867120-b72a8c80-3b7a-11eb-95eb-8105d6ce3e8d.JPG)

Is there a possibility to disable the definition on creation ?

**Comment by lucasnetau** [comment]
There have been quite a few fixes with checkboxes in recent versions. Please test with the recent release and reopen if this is still occurring, I have not been able to reproduce locally.
