### ISSUE TITLE
Mulitple Inputs in control plugin value 

### ISSUE THREAD

**Issue by Wujek280** [kevinchappell/formBuilder#1148]
### Description:

I want to build custom control (matrix) which involves use of multiple `input` elements across one control.

I want to render/fill these using JSON serialized data into value attribute of hidden input.

However changing any control updates field value to last changed `input` element - i want to cutom serialize data of all inputs in control to render/rerender matrix.

Any idea how to achieve/workaround it?

### Environment Details:

 - formBuilder Version: 3.6.1
 - Browser: Chromium / Chrome 
 - OS: macOS

### Expected Behavior
Value of Input with **name** attribute or one declared input's value should be saved as "value" in formBuilder configuration 

### Actual Behavior
Last changed input in given control is saved as "value" in field configuration

### Steps to Reproduce

Have custom control 
 -> add multiple `input` elements in one control
 -> change any input element
 -> observe that value in JSON data is set to last changed `input` 

Reproduced in 
https://codepen.io/Wujek280/pen/mdrOKmQ?editors=0010

**Comment by Wujek280** [comment]
Found out that `input.change` event is handled by `li.form-field` and can be stopped. 
Happlily coding custom plugin field.

**Comment by iftkharhussain** [comment]
Hi, @Wujek280 can you please guide me a little, I didn't get you?

Thanks
