### ISSUE TITLE
Formeo vs FormBuilder

### ISSUE THREAD

**Issue by yoshie902a** [kevinchappell/formBuilder#1149]
It seems Formeo and Form Builder are very similar.  

My use case is that I need the users to dynamically be able to add columns and be able to integrate with Bootstrap. 

 Is there a way to do this with Form Builder?   I would love to use form builder if it has columns, and I would love to use Formeo, if I could integrate it with bootstrap.  What's the best solution here?  Are both libraries equally supported by the community? It seems formbuilder may have a larger following.

**Comment by KrenZfer** [comment]
Hi,

I think its clearly stated at [Formeo Docs](https://formeo.readthedocs.io/en/latest/)

_"Formeo is the much hyped version 2.0 of the popular jQuery form building plug-in aptly titled "jQuery formBuilder". More than just a re-branding, Formeo is a 100% rewrite with focus on configuration extensibility."_

**Comment by yoshie902a** [comment]
Firstly, thanks. Yes, I read that too, but much of the documentation for formeo is missing, unlike the original.  So many questions still are unanswered about it.

**Comment by KrenZfer** [comment]
Yeah, i think the documentations are not done yet, but the column and row features are really good, and i hope it will done soon enough and ready for production,

**Comment by Jojoshua** [comment]
> 

FormBuilder does have columns. Try the latest version and try the new settings:
enableColumnInsertMenu: true,
enableEnhancedBootstrapGrid: true,

**Comment by bdkoder** [comment]
> > 
> 
> FormBuilder does have columns. Try the latest version and try the new settings: enableColumnInsertMenu: true, enableEnhancedBootstrapGrid: true,

Thank you. It's working well with column - https://codepen.io/bdkoder/pen/eYrGXKG
