### ISSUE TITLE
table element is missing

### ISSUE THREAD

**Issue by amitchandrakar** [kevinchappell/formBuilder#1150]
### Description: 
I have imeplemented formBuider in one of my project, now i needed to draw/implement a table using formBuider but unfortunately, it is missing here.

### Environment Details:

 - formBuilder Version: all
 - Browser: all
 - OS: all

### Expected Behavior: 
should have table feature

**Comment by Jojoshua** [comment]
You can easily add whatever table control you like using custom plugin https://formbuilder.online/docs/formBuilder/control-plugins/
