### ISSUE TITLE
Adding more than one space in the label text replaces all spaces except last with nbsp; 

### ISSUE THREAD

**Issue by NK-Hertz** [kevinchappell/formBuilder#1151]
### Description:
Adding more than one space in the label text replaces all spaces except last with nbsp;  

 - formBuilder Version: 3.6.1
 - Browser: all

### Expected Behavior
Adding more than one space in the label text should replace each space with empty string(' ').

### Actual Behavior
Adding more than one space in the label text replaces all spaces except last with nbsp; 
e.g. basdnbsp;nbsp; 23

### Steps to Reproduce
- Create a text area element
- Edit label to something with two or more consecutive spaces anywhere in it
- Print formbuilder data - To save the form you are building, you will probably have something like
$('#fb-create-btn').on('click', function (e) {
        e.preventDefault();
        let formBuilderData = formBuilder.actions.getData('json', true);
        //console.log(formBuilderData);
        $('#fb-form').submit();
    });

Printing the form builder data will show you the structure for said form element
{
    "type": "textarea",
    "required": false,
    "label": "basdnbsp; nbsp; 2312",
    ...
  }

### Screenshot - *(optional)*
![image](https://user-images.githubusercontent.com/3494741/102514987-d737df80-4095-11eb-9002-e39aaa811d17.png)

**Comment by lucasnetau** [comment]
That is to be expected. The HTML specification collapses multiple contiguous spaces into one. The browsers are automatically formatting the content correctly by replacing spaces with the html entity &nbsp; to ensure they are not lost
