### ISSUE TITLE
[Feature Request] - auto-generate options names

### ISSUE THREAD

**Issue by patik123** [kevinchappell/formBuilder#1153]
**[Feature Request]**

For users will be automatic generating auto-names of options in style option-1, option-2, option-3, option-4, option-5  and so on for every append option value.

Same for select and checkbox.

![image](https://user-images.githubusercontent.com/69119220/103776323-8e899b80-502f-11eb-8bb0-11a77c270bab.png)

**Comment by Jojoshua** [comment]
This is should help 

https://formbuilder.online/docs/formBuilder/options/onAddOption/
