### ISSUE TITLE
Can't understand the profit from npm installation. Need example please

### ISSUE THREAD

**Issue by maxkrok** [kevinchappell/formBuilder#1154]
I'm new to npm...
Please give some example how to use all the staff I'v got in node_modules. I dowloaded JS scriprs for formbuilder and render and I use them ok. But what for all these tricks with npm are needed? How to use nmp in a normal way with FB?
Please give some step by step example...

Also there is no "dist" directory at all anywhere from this description

> If you've followed the above steps you're ready to start making changes. All changes to the plugin should be made in the /src directory. The build process will transpile, lint and concatenate the contents of /src into the files found in /dist. Any changes made in the /dist will be lost once the build process is run.

And this "dist" is here in the demo project. What is the link with the npm?
> 
    <script src="dist/form-builder.min.js"></script>
    <script src="dist/form-render.min.js"></script>
    <script src="demo/assets/js/demo.min.js"></script>

And there is nowhere the demo.min.js file as well...
What all this means?

This 

> $ git clone https://github.com/kevinchappell/formBuilder.git form-builder
$ cd form-builder
$ npm i
$ npm start

gives only `index.html` and `assets` directory with `vendor.js` and 'langs' in nmp's created demo directory. No demo.min.js !!! What I'm doing wrong?

npm start gives the output:

> /var/www/html/fb/form-builder$ npm start

> formBuilder@3.6.2 prestart /var/www/html/fb/form-builder
> npm-run-all -p build:vendor copy:lang

> formBuilder@3.6.2 copy:lang /var/www/html/fb/form-builder
> babel-node tools/copy-language-files

> formBuilder@3.6.2 build:vendor /var/www/html/fb/form-builder
> babel-node tools/build-vendor

> formBuilder@3.6.2 start /var/www/html/fb/form-builder
> npm run start:devServer

> formBuilder@3.6.2 start:devServer /var/www/html/fb/form-builder
> webpack-dev-server --mode development --config tools/webpack.config

And all... 
The demo works, and F12 Inspector show demo.min.js
> <script src="demo/assets/js/demo.min.js"></script>
but there is no demo.min.js file in the filesystem NOWHERE!!!
please help!

**OK! All I need is how to move this demo project on some other web-site, not a WEBPACK development? Where to get all this demo.min.js etc unavailable staff?**

PS. And from where vendor.js comes?

**Comment by maxkrok** [comment]
There is no "dist" direvtory at all anywhere
which is here in the deo project
`    <script src="dist/form-builder.min.js"></script>
    <script src="dist/form-render.min.js"></script>
    <script src="demo/assets/js/demo.min.js"></script>
`
and there is nowhere the demo.min.js file...
what all this means?

**Comment by kevinchappell** [comment]
@maxkrok these questions seem more npm related than formBuilder. You can download formBuilder without npm from [Releases](https://github.com/kevinchappell/formBuilder/releases) or from the [website](https://formbuilder.online/).

vendor.js is a file generated for the demo that has jquery and jquery touch. If you're looking for how configure formBuilder I recommend checking the [documentation](https://formbuilder.online/docs/).
