### ISSUE TITLE
radio-group not align with bootstrap css

### ISSUE THREAD

**Issue by srleesw** [kevinchappell/formBuilder#1155]
### Description:
hi,  apply col-md-6 for radio-group pair with text field, for second pair of radio-group with text field, the radio-group was out of alignment, any idea how to solve this? 
the problem only occur for radio-group & check-group, the rest was ok,

### Environment Details:

 - formBuilder Version: 
 - Browser: 
 - OS: 

### Screenshot - *(optional)*
![image](https://user-images.githubusercontent.com/69565414/104419731-d8383000-55b3-11eb-829c-d3100ff2db16.png)

**Comment by lucasnetau** [comment]
hi @srleesw , not much to go on here. Can you please provide steps or code to reproduce and also the generated output of formRender

**Comment by lucasnetau** [comment]
Cannot replicate locally. Based on the image I suspect there is an additional style being assigned to the container that is pulling the Radio Group right.

<img width="890" alt="image" src="https://github.com/kevinchappell/formBuilder/assets/9331242/973ea526-9081-4a3b-9129-e99c6e1db3dc">
