### ISSUE TITLE
Using your demo site, I am unable to edit the LABEL field when using an iPad

### ISSUE THREAD

**Issue by smogHead** [kevinchappell/formBuilder#1157]
### Description:
When using FormBuilder on an iPad the label field is not editable.
### Environment Details:

 - formBuilder Version: Live demo
 - Browser: Chrome & Safari
 - OS: ios

### Expected Behavior
To be able to edit the Label field
### Actual Behavior
Not able to edit the values

**Comment by lucasnetau** [comment]
Confirmed on the demo https://formbuilder.online/ cannot replicate locally

**Comment by lucasnetau** [comment]
@kevinchappell  Appears to be jquery-ui-touch-punch causing this issue on formbuilder-online

**Comment by lucasnetau** [comment]
This has been rectified by remove the jquery-ui-touch-punch plugin from the demo site. It was required prior to around iOS 13 but does not appear to be required anymore
