### ISSUE TITLE
Issues while Upgrading TinyMCE version to 5

### ISSUE THREAD

**Issue by Tirthesh** [kevinchappell/formBuilder#1159]
Issues while Upgrading TinyMCE version to 5:

### Expected Behavior
TinyMCE editor should show for existing elements on page load

### Actual Behavior
TinyMCE editor not showing for existing elements on page load

### Steps to Reproduce
Please see attached example, can also send a sample implementation.

### Screenshot - *(optional)*
![image](https://user-images.githubusercontent.com/128023/107366002-9a232300-6b03-11eb-8aab-69cbf172c0bf.png)

@kevinchappell

**Comment by Tirthesh** [comment]
Thanks for the same.
Will try at my end and revert.

Regards.

**Comment by Tirthesh** [comment]
Hi @SVDion,

I checked the implementation, but we are not including any separate instance for TinyMCE, we are just including Form-Builder.min.js which loads TinyMCE.

Thus, with the above given solution, can I have a working sample plz ?

**Comment by Tirthesh** [comment]
Hi @SVDion ,

Any clue ?

**Comment by SVDion** [comment]
@Tirthesh, if you want to make the changes I was suggesting, you need to download the source code for formBuilder and recompile to create a new version of the formbuilder.min.js.

**Comment by Tirthesh** [comment]
Hi @SVDion ,
I tried to compile at my end with form builder 3.6.*, the build did not work for me after implementing the above changes.

Also tried to compile with a different version (3.2.3).

Both the above options did not work for me. Request you if can forward me the updated formbuilder.min.js.

Thanks & regards.

**Comment by TheTrueSpin** [comment]
@SVDion @Tirthesh 

Do either of you happen to have a compiled version of form-builder.js and form-render.js with the above changes that you wouldn't mind sharing?

**Comment by lucasnetau** [comment]
This WIP PR allows loading version 4, 5 and 6 of TinyMCE

https://github.com/kevinchappell/formBuilder/pull/1400
