### ISSUE TITLE
I am trying to Imitate your Test Submit Button.

### ISSUE THREAD

**Issue by macklemore725** [kevinchappell/formBuilder#1160]
### Description:
I am new programing and trying  use your formbuilder. 
I was wondering how you check all the required fields using Test Submit Button. I can't seem to Imitate it or understand your demo code ? 
I just need some help/guidance. 
Thanks.
Not much of an Issue, just need some help to implement something you did on your demo.
### Environment Details:

 - formBuilder Version:  Version: 3.6.1
 - Browser: Google Chrome 
 - OS: 

### Expected Behavior
none
### Actual Behavior
none
### Steps to Reproduce
none
### Screenshot - *(optional)*
none

**Comment by Jojoshua** [comment]
Do you still need help with this issue?
