### ISSUE TITLE
[i18n][override] - "Other" label

### ISSUE THREAD

**Issue by Wujek280** [kevinchappell/formBuilder#1163]
### Description:

I have trouble customising language in UI.
Changes (as override) in i18n setting does not appear in rendered form.

### Steps to Reproduce

- Add Checkbox / Radio and allow custom user option listing
- See that label for custom option is "Other"
- Override lang setting in settings
```
const builderOptions = {
        i18n: {
            override: {
                'en-US': {
                    other: 'Text I want to see',
...
 
```
- Observe, that label for "Other" remain the same as before overriding in option

### Expected Behavior
Should result in different (specified) label text for "Other" option in checkbox/radio 

### Actual Behavior
Other label is rendered as "Other" despite change in lang settings

### Environment Details:
 - formBuilder Version: 3.6.1
 - Browser: Chrome/Chromium
 - OS: macOS

### Possible Resolution 

What I have found is that there is

https://github.com/kevinchappell/formBuilder/blob/902206505760b8af8417f479a4ddcdc641c46b10/src/js/control/select.js#L129

with hard-coded "Other" string instead of referece to i18n.

If that's the case I would be more than happy to hear guidance on how to fix this and submit pull request.

**Comment by lucasnetau** [comment]
You can access mi18n within the control plugin.

Replacing 'Other' with control.mi18n('other') should fix your issue

**Comment by lucasnetau** [comment]
Please try PR #1385, FormRender will correctly use the value from override or the language file
