### ISSUE TITLE
Error with userData - no way to identify choosen value

### ISSUE THREAD

**Issue by scottrpaterson** [kevinchappell/formBuilder#1167]
In the below example, when rendered, all three options have the same value of 20. If the user selects "Option 1 and Option 3", the userData will be exactly the same when they select any other combination.

There is no way to tell if Option 1, Option 2, or Option 3 are chosen when they have the same values.

Example:
```
const originalFormData = [
  {
    type: "checkbox-group",
    label: "Checkbox Group",
    className: "checkbox-group",
    name: "checkbox-group-1478704652409",
    values: [
      {
        label: "Option 1",
        value: "20",
        selected: true
      },
      {
        label: "Option 2",
        value: "20"
      },
      {
        label: "Option 3",
        value: "20",
        selected: true
      }
    ]
  },
];
```

No matter what options are chosen, the userData will be exactly the same:

```
[{"type":"checkbox-group","label":"Checkbox Group","className":"checkbox-group","name":"checkbox-group-1478704652409","values":[{"label":"Option 1","value":"20","selected":true},{"label":"Option 2","value":"20"},{"label":"Option 3","value":"20","selected":true}],"userData":["20","20"]}]
```

---
To fix this problem, I recommend that userData is put in a key, value pair format like so: "userData":["Option 1": "20","Option 2": "20"]

**Comment by Wujek280** [comment]
Not sure, but id/value should be unique for given option. 
Imo it's a bad design to have values not unique in checkbox/select/radio elements

**Comment by Jojoshua** [comment]
Yes, this may technically be valid but it really doesn't make practical sense.
