### ISSUE TITLE
Radio Button & Other Option not working

### ISSUE THREAD

**Issue by toepfer** [kevinchappell/formBuilder#1172]
### Description:
When we use the Radio Button list and the "Other" option together we run into a validation error, because it is possible to mark two elements in the radio button list. Validation fails.
We would like to see this solved meanwhile we don't allow to use the "Other" Option.
Checkboxes are working fine. 

### Environment Details:

 - formBuilder Version: 3.6.0
 - Browser: Edge, Chrome
 - OS: Windows

### Actual Behavior
When we use the Radio Button list and the "Other" option together we run into a validation error, because it ist possible to to mark two elements in the radio button list. It seems to be two lists. When the "Other" radio button gets selected and aome text is asses to the text field, the name of the <input type=radio name=blabla...   this gets automatically added to the name: []
### Screenshot - *(optional)*
![image](https://user-images.githubusercontent.com/1536789/112498246-a0552200-8d86-11eb-849a-547055c28f5d.png)
![image](https://user-images.githubusercontent.com/1536789/112498602-fa55e780-8d86-11eb-9e11-ba3401a5a2d6.png)
![image](https://user-images.githubusercontent.com/1536789/112499176-849e4b80-8d87-11eb-9471-22301b9bbcb4.png)

**Comment by toepfer** [comment]
Does as well not work in version 3.6.2 on your website:
![image](https://user-images.githubusercontent.com/1536789/112499642-f70f2b80-8d87-11eb-8689-4381777521cb.png)

**Comment by stg-andrei** [comment]
Confirmed for  * Version: 3.7.1 too
