### ISSUE TITLE
Add custom attributes

### ISSUE THREAD

**Issue by omerosmanoglu** [kevinchappell/formBuilder#1174]
How can I add custom attributes like onclick or data-sql to the wizard?

### Environment Details:

 - formBuilder Version:  3.6.2 
 - Browser:  Chrome 86
 - OS:  Windows

![image](https://user-images.githubusercontent.com/57272860/113782212-88907d00-973a-11eb-9e51-252995ab2330.png)

**Comment by chandler3224** [comment]
For existing field types you can utilise ```typeUserAttrs``` with
```
 'typeUserAttrs': {
        'text': {
             'onclick': { 'label' : 'onClick', 'value' : '' }
        }
}
```
or for custom controls you can use ```defaultAttrs```. 
```
static get definition() {
      return {
        i18n: {
          default: 'Custom Control'
        },
        defaultAttrs:{
            'onclick': {'label': 'onClick', 'value' : '', 'type': 'textarea'}
        }
      };
    }
```
