### ISSUE TITLE
Checkbox group should have minimum 1 option

### ISSUE THREAD

**Issue by ian-weatherhogg-refractiv** [kevinchappell/formBuilder#1176]
selects and radios have a minimum of 2, which makes sense.
but checkboxgroups have no minimum - when rendered a checkboxgroup with no options is empty.
(ref minOptionMessage)

**Comment by lucasnetau** [comment]
I cannot replicate this locally, this issue may have been fixed in a later release. Can you please provide a reproducible script showing the issue if it still occurs?

**Comment by lucasnetau** [comment]
CSS is used to disable the remove buttons for option fields in formBuilder. If rendering a handwritten form with no options then checkboxes will be empty. However you cannot get here if formBuilder is used.
