### ISSUE TITLE
actions.save(): save action, button below form in my local form, or CP examples doesn't work

### ISSUE THREAD

**Issue by j2l** [kevinchappell/formBuilder#1178]
Maybe it's just me, I tried on 2 browsers and after restarting OS.

### Description:
Clicking on the blue Save button doesn't produce any result.
Reading https://github.com/kevinchappell/formBuilder/issues/1058 I thought it was fixed but I don't see any saving action.
Also external save https://codepen.io/kevinchappell/pen/xyOdzp throw in console: 
`external save clicked (pen.js:66:13), result: undefined`

### Environment Details:
 - formBuilder Version: 3.6.1
 - Browser: FF, Chromium
 - OS: Ubuntu 20.04

### Expected Behavior
Save in browser, or as file, or leave a message in the console (for the blue save button)

### Actual Behavior
Nothing happens

### Steps to Reproduce
Click any save button in codepen example above

**Comment by kevinchappell** [comment]
@j2l thanks for reporting this. this should be fixed in the next release
