### ISSUE TITLE
[BUG][FOUND] Mutliple textarea with same ID cannot retrieve userData value

### ISSUE THREAD

**Issue by Wujek280** [kevinchappell/formBuilder#1182]
### Set Up
- Having two forms on one page **BEFORE** and **AFTER** for "form migration" purpose on one page

### Expected behavoiur
- Both Textarea's control will reflect JSON value for `userData[0]` value respectively for formBuilder instance

### Actual behaviour
- Only the first Textarea **BEFORE** has value updated 

### Screenshots And Data setup

These objects are definition for both textareas

![image](https://user-images.githubusercontent.com/19411906/115871155-76078a80-a440-11eb-868d-7cac6f8d6df6.png)

![image](https://user-images.githubusercontent.com/19411906/115871398-cb439c00-a440-11eb-8d07-e025737bd220.png)

You can see, that textareas are `textarea-1619179998327` and have migrated `userData` attribute
but only one (first / BEFORE) textarea has been fullfiled on front-end

### Possible solution

What I've found it might be setting textarea value as `$("#id").val()` without form encapsulation/context so only first textarea is affected?

https://github.com/kevinchappell/formBuilder/blob/902206505760b8af8417f479a4ddcdc641c46b10/src/js/control/textarea.js#L36

**Comment by Wujek280** [comment]
Setting this line to the one below fixes this issue but don't know if there is any impact on textarea subtypes then
```javascript 
this.field.value = this.config.userData[0]

**Comment by Jojoshua** [comment]
ID should be unique, it sounds like you did something out of the ordinary to achieve this. Feel free to reopen if you think this is valid.
