### ISSUE TITLE
Form render is not working

### ISSUE THREAD

**Issue by tanzeel917** [kevinchappell/formBuilder#1196]
Hi  
I have added form builder using 3 to 4 lines of code
one line is cdn or script source and the other is a div and a jquery 2 line of code that's it.
Now the form builder is generated and adding form elements but when I click on the Save button nothing is happining.
I just want to render that form to get the HTML of that form Can you  please help me 

 - formBuilder Version:  no idea
 - Browser: chrome
 - OS: windows 10

**Comment by sheeraz100** [comment]
Same is happening for me, Save does nothing.

formBuilder Version: v3.7.3
Browser: Chrome
OS: windows 10

**Comment by Jojoshua** [comment]
Can you post a fiddle to reproduce?
