### ISSUE TITLE
Every other call to setData appends data to existing stage contents, instead of overwriting existing data, and causes stage to blank.

### ISSUE THREAD

**Issue by shaunhurley** [kevinchappell/formBuilder#1197]
### Description:

Hopefully I'm not going mad!  While an initial call to actions.setData() works exactly as expected, a second call to actions.setData appends the new data to the existing stage data, and causes the stage to blank (although the data appears to be in place and retreivable via getData())

Further calls to setData alternate between working as expected, and displaying the problem behavior i.e. every odd call works, and every even call appends data/blanks the stage.

Since the calls to setData are being invoked from a manual button press, I can't see how there is any background async behavior possibly causing the issue.

Issuing an actions.clearFields() prior to the actions.setData() does not appear to impact the problem.

### Environment Details:

 - formBuilder Version: current
 - Browser: Chrome, Edge, Safari
 - OS: Windows, Mac, iOS

### Expected Behavior

Calling setData with a field definition set should overwrite the current data on the stage every time.

### Actual Behavior

Calling setData with a field definition set only overwrites the current data on the stage every other time.

### Steps to Reproduce

I forked Kevin's original Actions -> SetData codepen to demonstrate what I am seeing @ https://codepen.io/shaunhurley/pen/RwpjWbp

**Comment by kevinchappell** [comment]
thanks for opening this issue. I should have a fix out shortly.

**Comment by shaunhurley** [comment]
Thanks for looking at that, most appreciated, I'm a big fan of your work :)

Presumably that fix will be rolled out in the next release?  Any idea of your schedule on that?

**Comment by kevinchappell** [comment]
@shaunhurley 
Just published: 
![image](https://user-images.githubusercontent.com/1457540/120824906-b9f4b180-c50d-11eb-899f-3af944174c61.png)

**Comment by shaunhurley** [comment]
Perfect, thanks!
