### ISSUE TITLE
[BUG][FOUND]Checkbox &/OR Radiobox "OTHER" field value is  = NULL

### ISSUE THREAD

**Issue by stg-andrei** [kevinchappell/formBuilder#1205]
### Description:
When you create the form and let the users add "Other option" for checkboxes or radios, when the form is submitted that vlaue is equal to null even though it is populated with data.

### Environment Details:

 - formBuilder Version: 3.7.1
 - Browser: Chrome
 - OS: MAC OS

### Expected Behavior
Get existent value in field 

### Actual Behavior
Value is set to Null

### Screenshot - *(optional)*
![image](https://user-images.githubusercontent.com/44063410/121686076-649a4080-cac9-11eb-98f6-e2f0b192fa65.png)

```
  +request: Symfony\Component\HttpFoundation\InputBag {#44 ▼
    #parameters: array:7 [▼
      "_token" => "Fzdc9cke1MeWh7m7CURq4GoImZe2rWCZ5cCxTXY6"
      "form_id" => "1"
      "text-1622822063765" => "Nostrum beatae volup"
      "text-1622822065256" => "Nostrum ratione aut"
      "text-1622822066625" => "Magnam id esse dolor"
      "radio-group-1623342287264" => null
      "checkbox-group-1623412496784" => array:3 [▼
        0 => "option-1"
        1 => "option-solid"
        2 => null
      ]
    ]
  }
```

**Comment by lucasnetau** [comment]
Cannot replicate with current version. This may have been resolved in a later release. If you still encounter the issue please reopen this issue
