### ISSUE TITLE
[Bug] Fileuploads (input type="file") always multiple

### ISSUE THREAD

**Issue by Mauerbluemchen** [kevinchappell/formBuilder#1209]
### Description: checkbox "Allow users to upload multiple files" does not work any more

if checked, it creates the attribute multiple="true"
if unchecked, it creates the attribute multiple="false"

in html similar to the attributes required, disabled and so on, the value is not used at all

just being there, results in always TRUE
'multiple' == 'multiple="multiple"' == 'multiple="true"' == 'multiple="false"'

<input type="file" class="form-control" name="file-1571296005358" **multiple="false"** id="file-1571296005358">
^-- this is a an input field, that allows multiple uploads

### Environment Details:

 - formBuilder Version: 3.6.1
 - Browser: Firefox
 - OS: Windows

### Expected Behavior

no 'multiple' attribute at all in case of the checkbox  "Allow users to upload multiple files" being unchecked

### Actual Behavior

see description

### Steps to Reproduce

see description

**Comment by lucasnetau** [comment]
That does violate the HTML spec https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes#boolean_attributes

**Comment by lucasnetau** [comment]
@Mauerbluemchen , can you please test the patch in #1216 ?

**Comment by Mauerbluemchen** [comment]
@lucasnetau tests were successful and also the code change looks fine
thank you for looking into this!
