### ISSUE TITLE
Class field doing some funky stuff when you try to add a space character

### ISSUE THREAD

**Issue by sheibeck** [kevinchappell/formBuilder#121]
On the Demo, if you try to type the space character into the class field it jumbles whatever is in that field. It looks like it's trying to automatically do something, but it ends up garbling what you've already typed in the field.

I'm not sure if this is just a problem with the Demo site only or not.

I'm using chrome

Steps to reproduce:
1. Open the demo site with a fresh canvas
2. Drop a single text field onto the form
2. Open the properties of the text field and begin typing after the default class name form-control.
3. As you start typing, pressing the space key you'll notice it will start to adjust the words in the field.

**Comment by kevinchappell** [comment]
It's reversing the order of user created classes but should be functioning correctly, just looks a bit funky.

**Comment by sheibeck** [comment]
If you pause at all while typing it takes what you've already typed and moves it out from under your cursor. So, if you get half a class out and stop for a second it moves what you just started typing. And it reverses the words every time you hit space. So, if you type "hello world" and then hit space after "world" it reverses the two words. Then if you hit space again, it reverses them again. Just makes it very difficult to use.

**Comment by kevinchappell** [comment]
@sheibeck yeah its pretty wonky. we are on code freeze but this is a simple fix. I'll post it in a minute.

**Comment by kevinchappell** [comment]
@sheibeck Try [the demo](http://formbuilder.online/) now. Should be resolved.

**Comment by sheibeck** [comment]
You're fast! That works great. Thanks Kevin.
