### ISSUE TITLE
dont get the userData from Custom Plugin

### ISSUE THREAD

**Issue by OkaminoTsuki** [kevinchappell/formBuilder#1214]
### Description:
I used the Star Rating example and i didnt get the userData.
### Environment Details:

 - formBuilder Version: 3.7.3
 - Browser: Chrome
 - OS: Windows 10

### Expected Behavior
I expected get the User Data
### Actual Behavior
Dont Get It
### Steps to Reproduce
Do the example of Custom Plugin Star Rating
### Screenshot - *(optional)*
![image](https://user-images.githubusercontent.com/55732527/129342964-bc149c06-62eb-44b2-a459-15e05cc0ad69.png)

**Comment by Jojoshua** [comment]
There are likely multiple options to return the data. Which method from the plugin are you expecting formBuilder to use?
