### ISSUE TITLE
dataForm not working properly

### ISSUE THREAD

**Issue by mrjk990** [kevinchappell/formBuilder#1215]
### Description:
dataForm not working properly
when add dataForm with json data its show wrong data !!
example : https://codepen.io/mrjk990/pen/VwbROdL
as you can see , "select" has 4 items , but only showing 3 in another names and data
what i miss ?
### Environment Details:

 - formBuilder Version:  latest
 - Browser: chrome
 - OS: windows 7

**Comment by Jojoshua** [comment]
Example link doesnt work

**Comment by kevinchappell** [comment]
@mrjk990 the select input uses `options` to define the field's options but you have `items` in your formData
