### ISSUE TITLE
removeField NOT working AT ALL

### ISSUE THREAD

**Issue by Ale-Digitale** [kevinchappell/formBuilder#1217]
Hi,

why **removeField** doesn't work at all ? Are you aware of this ?

please try it here... click on the REMOVE FIELD red button... nothing happens:

https://formbuilder.online/docs/formBuilder/actions/removeField/

**Comment by Jojoshua** [comment]
Can you post a fiddle to reproduce?

**Comment by lucasnetau** [comment]
Hi @Ale-Digitale thank you for your report.

Calling removeField without passing a fieldID was broken in https://github.com/kevinchappell/formBuilder/commit/e0c0f2ea8f204da6e11d8de938e27ca6687d5588

The const field variable is declared prior to the fallback to select the last form field and therefore can not be updated.
