### ISSUE TITLE
CHECKBOX: if required = true, then checkbox items remains unselected

### ISSUE THREAD

**Issue by mvirdhruv** [kevinchappell/formBuilder#1218]
### Description:
For the checkbox-group, if **required = true**, then checkbox items remains unselected even if userData provided.

You can check here, https://codepen.io/mvir/pen/wvdVmQd

### Environment Details:

 - formBuilder Version: 3.7.3
 - Browser: Google Chrome
 - OS: Windows 10

### Expected Behavior
![formRender-userData1](https://user-images.githubusercontent.com/7158386/130206862-f20eeeca-b960-475c-af16-f5a241d4647d.png)

### Actual Behavior
![formRender-userData2](https://user-images.githubusercontent.com/7158386/130207076-8fa16237-8281-445a-8e4c-0b221d6d3b35.png)

### Steps to Reproduce
https://codepen.io/mvir/pen/wvdVmQd

**Comment by jayden626** [comment]
I have also had this issue.

**Comment by lucasnetau** [comment]
Try this simple patch, when you have a checkbox-group with required the current codepath skips onRender and instead calls groupRequired, this patch calls both

```
diff --git a/src/js/control/select.js b/src/js/control/select.js
index c37969d..e7694be 100644
--- a/src/js/control/select.js
+++ b/src/js/control/select.js
@@ -33,7 +33,12 @@ export default class controlSelect extends control {
     }
 
     if (type === 'checkbox-group' && data.required) {
-      this.onRender = this.groupRequired
+      const self = this
+      const defaultOnRender = this.onRender
+      this.onRender = function() {
+        self.groupRequired()
+        defaultOnRender()
+      }
     }
 
     delete data.title
```

**Comment by FrancineBlerter** [comment]
@lucasnetau Thank you! I also needed to bind `defaultOnRender` to `this`:
```javascript
if (type === 'checkbox-group' && data.required) {
    const self = this
    const defaultOnRender = this.onRender.bind(this)
    this.onRender = function () {
      self.groupRequired()
      defaultOnRender()
    }
}

**Comment by lucasnetau** [comment]
@FrancineBlerter, I've created a PR with your modified patch. I'm hoping @kevinchappell will have a chance to review this PR along with a few others currently open.

**Comment by Lukimer** [comment]
@FrancineBlerter, thanks for fixing patch, and could you teach me or help to make a formRender.min.js. as I dont know how to use  patch and compile to formRender.min.js. as I try to direct use the src, javascript will occurs.... please help, thanks God..

Best Regards,
Kim

**Comment by mvirdhruv** [comment]
@kevinchappell Thank you!
