### ISSUE TITLE
Builder - Select - unable to uncheck "selected" if checked once

### ISSUE THREAD

**Issue by futureweb** [kevinchappell/formBuilder#1220]
### Description:
Once you have clicked "selected" Option in a SELECT FIELD, you can no longer remove this. Several "selected" are possible.

### Environment Details:

 - formBuilder Version: 3.7.3
 - Browser: Firefox
 - OS: Windows 10

### Expected Behavior
uncheck "selected" on another click on it ...

### Actual Behavior
unable to disable "selected" once it's set

### Steps to Reproduce
1) https://formbuilder.online/
2) add SELECT Field
3) add a few Options
4) click on the "selected" Icon in front of the Row
5) try to unselect it ...

### Screenshot - *(optional)*
![grafik](https://user-images.githubusercontent.com/1698881/130795598-adfe4489-8af2-4546-a4fe-b3204aff300a.png)

**Comment by jayden626** [comment]
A small workaround is to click 'Allow Multiple Selections', uncheck the boxes, then toggle multiple off

**Comment by webserviceXXL** [comment]
This is still unfixed. However, the solution by @FrancineBlerter works great in general.

Unfortunately, I can't find a solution to work with the actions from the lib. Without the fix you can simply get the current configuration by `formBuilder.actions.getData('json')`. With the mutation, actions is undefined. Any idea how to solve this?

Example from the documentation: https://formbuilder.online/docs/formBuilder/actions/getData/

**Comment by webserviceXXL** [comment]
Short update for all who have the same problem. For the `actions` to continue to work, the corresponding calls must be relocated within the promise.

You'll find a working example at: https://codepen.io/webserviceXXL/pen/wvpGmJL
