### ISSUE TITLE
how to solve error fb.actions.setLang is not a function

### ISSUE THREAD

**Issue by MBagherii** [kevinchappell/formBuilder#1226]
### Description:
I want to use setLang Api Method but it does not work. what can I do?
### Environment Details:

 - formBuilder Version: 
 - Browser: Chrome
 - OS: 

### Expected Behavior
Change language of plugin
### Screenshot - *(optional)
![Screenshot (4)](https://user-images.githubusercontent.com/28698947/135259255-6dade7c2-c1d3-46ec-a5c2-c1506d2c56b7.png)
*

**Comment by Jojoshua** [comment]
Could you post a fiddle to reproduce

**Comment by lucasnetau** [comment]
This can only occur when the formbuilder instance is not initialised completely. If you are initialising multiple forms or are calling actions.setLang right after initialisation then you need to use the promise interface to ensure initialisation is complete.

Please reopen with a reproduction if this still occurs.
