### ISSUE TITLE
Disable edit attributes for all fields

### ISSUE THREAD

**Issue by forerser** [kevinchappell/formBuilder#1227]
### Description:

is it possible to disable double click to edit the attributes of a field? I use a drop down list to render a form, and I want the user to be unable open this panel.
### Screenshot

![Screenshot_2021-09-30 formBuilder Options - linebreak hr](https://user-images.githubusercontent.com/29029407/135505319-7916feb7-b44e-45d4-a263-d6e73a1c7e07.png)

**Comment by djstini** [comment]
I need this feature too.

**Comment by Jojoshua** [comment]
This is already available, https://formbuilder.online/docs/formBuilder/options/disabledFieldButtons/
