### ISSUE TITLE
Missing translation for snippet for "Other"

### ISSUE THREAD

**Issue by PSchmitz90** [kevinchappell/formBuilder#1228]
### Description:
We translated the snippet "Other":
```js
  i18n:
  {
    override: {
      'en-US': {
        other: "Sonstige"
      }
    }
  }
```

But in the formBuilder and formRender it still outputs 'Other' instead of 'Sonstige'. 

### Environment Details:

 - formBuilder Version: current, v3.7.3
 - Browser: all
 - OS: all

### Expected Behavior
Printing 'Sonstige' instead of 'Other'

### Actual Behavior
Printing 'Other' instead of translation

**Comment by Jojoshua** [comment]
I think this should be moved to https://github.com/kevinchappell/formBuilder-languages

**Comment by lucasnetau** [comment]
Please try PR #1385, FormRender will correctly use the value from override or the language file
