### ISSUE TITLE
[Feature] Export CSV

### ISSUE THREAD

**Issue by jokamax** [kevinchappell/formBuilder#1232]
### Description:
Is there a way to export from form.builder to an csv file ?
Flat export : title field / value field ?

Or is it a feature you will develop in the future ?

(Sorry if this is not the good place to ask)

Jonathan

**Comment by Jojoshua** [comment]
I don't think CSV would be an appropriate format for the data. You can call userData to get all the data as an object and convert into a custom format you would like https://formbuilder.online/docs/formRender/actions/userData/
