### ISSUE TITLE
Unexpected Behaviour When Hover on Element (tobe removed)

### ISSUE THREAD

**Issue by fgroupindonesia** [kevinchappell/formBuilder#1234]
### Description:
I encountered this when i finished designing the form. And then i changed my mind to delete several elements. Luckily, strange behavior shown as below. Please check the video for more details.

### Environment Details:
 - formBuilder Version: 3.7.3
 - Browser: chrome & brave
 - OS: windows 7, 8, and 10.

### Expected Behavior
The Remove item button should be normal.

### Actual Behavior
Strange behavior, the button's shown & hidden with a scrambled effect.

### Steps to Reproduce
- Open your UI page for designing a form.
- Drag some elements
- Hover into a single element
- Hover into the remove button
- Strange behavior appeared

### Screenshot - *(optional)*
Here is the [screenshot : show](https://ibb.co/Ws2MC68)
Or you may also check [the video: utube.](https://youtu.be/D9xtqdQ8OhM)

**Comment by lucasnetau** [comment]
Unable to replicate with current version. Does this still occur for you?

**Comment by lucasnetau** [comment]
The video shows a very old version of the UI. Closing as this cannot be replicated with the current or recent releases
