### ISSUE TITLE
How can i customize edit panel for custom elements?

### ISSUE THREAD

**Issue by MBagherii** [kevinchappell/formBuilder#1236]
### Description:
I want to create a custom control with its custom edit panel? How can i change and custimze edit panel of each control???
Is it possible or not?? if yes which js files should be changed??
### Environment Details:

 - formBuilder Version: 
 - Browser: 
 - OS:

**Comment by Obaidraj** [comment]
![issue1234](https://user-images.githubusercontent.com/38789569/151934915-e0d84350-c280-44b7-9444-9c58dc7f97b9.PNG)

**Comment by lucasnetau** [comment]
https://formbuilder.online/docs/formBuilder/options/typeUserAttrs/
