### ISSUE TITLE
How to check if field is required

### ISSUE THREAD

**Issue by silicahd** [kevinchappell/formBuilder#1239]
Maybe I am missing something but is there a way to check if the field were filled? I see that you can set a required field but cant seem to check if they were filled. Any ideas?

**Comment by Allenci** [comment]
Handle by your own js and sure backend validation, I remember you can get "required" key in the formdata json

**Comment by Jojoshua** [comment]
To do this you would call userdata from formRender and then iterate the fields and check each field's userData array 
https://formbuilder.online/docs/formRender/actions/userData/
