### ISSUE TITLE
[Announcement] - Embed media (Image, Video, Audio) plugin

### ISSUE THREAD

**Issue by lucasnetau** [kevinchappell/formBuilder#1246]
## Plugin Announcement
If you would like to embed Images, Video, or Audio into your forms please take at look my newly release plugin. Released under the MIT License.

https://github.com/lucasnetau/formBuilder-plugin-media

Usage should hopefully be straight forward, please ask if you run into any issues.

## Features
* Renders HTML5 elements - Figure, Video, Audio
* Supports embedding via:
  * URL
  * DataURI
  * File Upload

**Comment by Jojoshua** [comment]
Good stuff! Will add to a pinned issue

**Comment by vijay-torani** [comment]
it working i am getting image but problem is after saving the image how i will display image ? i try to store image url into src of file object that is getting from userdata but still image not showing ?
