### ISSUE TITLE
How to use FormBuilder in ReactJS

### ISSUE THREAD

**Issue by Obaidraj** [kevinchappell/formBuilder#1250]
I am not able to use it in react this is showing me the error formbuilder is not a function.Jquery and other CDN are add already.
![issue1234](https://user-images.githubusercontent.com/38789569/151924443-ca04c081-c3dc-4c01-9acd-b1a5ed5bc1c5.PNG)

**Comment by a4ajay36** [comment]
https://formbuilder.online/docs/formBuilder/demos/react/
check this out

**Comment by Obaidraj** [comment]
how to create two input field in a single row here

**Comment by a4ajay36** [comment]
For that please check
https://github.com/oneplugin/formBuilder
 This guy added bootstrap grid system but this feature still not merged yet

**Comment by Obaidraj** [comment]
How to use this thing

**Comment by a4ajay36** [comment]
Install this repo as a package

**Comment by Obaidraj** [comment]
this is not working

**Comment by Jojoshua** [comment]
Did you await the formbuilder promise?
