### ISSUE TITLE
Edit Label

### ISSUE THREAD

**Issue by Obaidraj** [kevinchappell/formBuilder#1251]
I am Not able to edit the label of any field in form builder.

**Comment by Jojoshua** [comment]
Can you provide a fiddle to show reproduction?

**Comment by jayden-LD1** [comment]
Seconded with a fiddle https://jsfiddle.net/khfsvqjy/

Add any field to the builder, try to change the label.
Works on 3.7.3 but not 3.7.4

**Comment by Jojoshua** [comment]
Thanks, I believe I found the issue

**Comment by Jojoshua** [comment]
Fixed in latest release
