### ISSUE TITLE
Can we create module means collection of fields ?

### ISSUE THREAD

**Issue by Asifkrishaweb** [kevinchappell/formBuilder#1252]
### Description:

Can we create module (collection of fields) at one time and drag that module ?

### Environment Details:

 - formBuilder Version: 
 - Browser: 
 - OS:

**Comment by Jojoshua** [comment]
It is possible with inputSets, see https://formbuilder.online/docs/formBuilder/options/inputSets/

**Comment by Asifkrishaweb** [comment]
Thank you so much, it's very helpful.
