### ISSUE TITLE
Language dropdown not showing 

### ISSUE THREAD

**Issue by nirav-panchal** [kevinchappell/formBuilder#1253]
### Description:
Hello,

Language selection option not showing above the form builder 
how can i enable this ?

### Environment Details:

 - formBuilder Version: 
 - Browser: 
 - OS:

**Comment by kevinchappell** [comment]
@nirav-panchal The language select is not included with the plugin but there is an example of one in the demo: https://github.com/kevinchappell/formBuilder/blob/master/src/demo/index.html#L29

![image](https://user-images.githubusercontent.com/1457540/157807284-594b4e23-cde7-44a0-826f-f83b1f67e447.png)
