### ISSUE TITLE
assets/lang/en-US.lang 404

### ISSUE THREAD

**Issue by amityweb** [kevinchappell/formBuilder#1258]
Downloaded the files from your site, so have only 
```
form-builder.min.js
form-render.min.js
```
Added them to the page, they are stored in my /js/formbuilder/ folder:
```
<script src="<?php echo site_url('/js/formbuilder/form-render.min.js'); ?>"></script>
<script src="<?php echo site_url('/js/script.js'); ?>"></script>
```

But your JS files are trying to call other files not in your download, and also relative to the page I am on, so I get:
`https://mysite.co.uk/app/builder/edit/assets/lang/en-US.lang 404`

So a number of issues:

1. I would not have a folder called assets/lang/ under my edit page
2. I would not even have it at root if you called it like /assets/lang/
3. And the folder and files are not in the download anyway lang/en-US.lang
4. I assume there should be css files too seen as your form builder is styled nice? 

I know its all on Github but I dont use NPM and would not want all the files from the src folder, so it would be good that the download only includes all the files needed to get it working? 

Thanks 

I do have another error but not sure if its related:
`form-builder.min.js:19 Uncaught (in promise) TypeError: q.sortable is not a function`

**Comment by kevinchappell** [comment]
@amityweb The files used for the website are built specifically for that use and have configurations attempting to pull language files from the `assets/lang/` directory. If downloading from the site be sure to use the options from the dropdown:
![image](https://user-images.githubusercontent.com/1457540/157299776-e2669e33-630c-436a-a0ed-3572e0d12a99.png)

 The package is also available from npm: https://www.npmjs.com/package/formBuilder

**Comment by amityweb** [comment]
Hi Kevin. Yes thats where I got the files from. I clicked Download on your website, as per the screenshot. I downloaded form-builder.zip. In that zip is only the following files:
form-builder.min.js
form-builder.min.js.gz
form-render.min.js
form-render.min.js.gz

Those files then reference the assets/lang/ folder, and calling them relatively not from root.

**Comment by kevinchappell** [comment]
i see the issue now. Languages were moved to their own repo and no longer included with formBuilder downloads.

You can set the `i18n.location` config option to `https://formbuilder.online/assets/lang/` until a fix is released.

**Comment by PierreMesure** [comment]
Hi @kevinchappell, we're using your plugin in this rails module and we're going to add the files to our project (see [here](https://github.com/decidim-ice/decidim-module-decidim_awesome/issues/217)). Unfortunately, this is the only way we can do it without adding a link to a CDN that isn't GDPR-friendly.

Do you think it would be possible to provide these translations in a packaged version again in the future?

**Comment by appkery** [comment]
Just download the file from [https://formbuilder.online/assets/lang/en-US.lang](https://formbuilder.online/assets/lang/en-US.lang).
And put it in your /assets/lang folder.

**Comment by lucasnetau** [comment]
As advised by others, downyou your languages from https://github.com/kevinchappell/formBuilder-languages and serve them locally. en-US.lang is built in
