### ISSUE TITLE
required checkboxes group

### ISSUE THREAD

**Issue by toshkoen** [kevinchappell/formBuilder#1259]
### Description:
in control - select.js 

    if (type === 'checkbox-group' && data.required) {
      this.onRender = this.groupRequired
    }

when "      if (type === 'checkbox-group' && data.required) {  " -- true 

 checkbox data never populated with saved data

**Comment by kevinchappell** [comment]
@toshkoen i think this should be resolved by @lucasnetau PR [here](https://github.com/kevinchappell/formBuilder/pull/1233/files). Can you confirm?

**Comment by jayden-LD1** [comment]
This is resolved.

**Comment by davidbaselj** [comment]
I don’t know if this has anything to do with this issue or not. I will post it here so I don't open new issue.

Version 3.8.0

If I have checkbox group with required checked. Then on render I save the value and then when rendered again, the minimum 1 selection is required again, even if there is at least one checkbox checked.

![image](https://user-images.githubusercontent.com/7064170/158975346-f52bedc2-8e2e-4f46-bc58-9e650f87d3c2.png)

**Comment by lucasnetau** [comment]
Hi @davidbaselj,

Take a look at patch in https://github.com/kevinchappell/formBuilder/pull/1277 which switches the initialisation order, there is no change event fired after programatically changing the checkbox values and so the groupRequired events are not run to remove the input required flags.
