### ISSUE TITLE
JS Bug in form-builder.js

### ISSUE THREAD

**Issue by dannycamps** [kevinchappell/formBuilder#127]
Hi Kevin,

While working on the latest version of the class, I ran into an issue with re-populating the form builder from an XML string retrieved from a DB.

In form-buillder.js line 523:
`var maxlength = $('.fld-maxlength', field).val();
    if (maxlength) {
      **previewData.maxlength = maxlength.val();**
    }`

Gives the following error and breaks the form builder:
Object doesn't support property or method 'val'

Changing the code to what I have below appears to work correctly:
previewData.maxlength = maxlength

Just wanted to let you know.

Thanks,
-Daniel

**Comment by kevinchappell** [comment]
Thanks for the heads-up on this.
