### ISSUE TITLE
Custom checkbox-group in demo doesn't work

### ISSUE THREAD

**Issue by Jojoshua** [kevinchappell/formBuilder#1274]
### Description:
The demo page throws an exception when trying to add the custom checkbox group

```
  const typeUserAttrs = {
    'checkbox-group': {
      'custom-group': {
        customInput: {
          label: 'Custom Text Field',
          value: 'This field is added only to checkbox with specific subtype',
          type: 'text',
        },
      },
    },
  }
```

![image](https://user-images.githubusercontent.com/5598169/158914683-5eacdb5e-459f-455d-910f-c6841cd6a7e7.png)

**Comment by lucasnetau** [comment]
Cannot replicate with Chrome, Firefox, nor Safari. The screenshot makes reference to form-builder.ts which is not part of the current demo

**Comment by lucasnetau** [comment]
Cannot replicate with current version
