### ISSUE TITLE
Packagist config is set to not auto-updated leading to stale data

### ISSUE THREAD

**Issue by lucasnetau** [kevinchappell/formBuilder#1278]
### Description:

The config for Composer package https://packagist.org/packages/kevinchappell/form-builder is not set to auto-update

New releases are not available and dev-master is referencing January 2022. @kevinchappell  can you please enable the GitHub hooks to auto update the Composer package?

### Expected Behavior

After new commits to master or new releases the composer package is updated

### Actual Behavior

Package is not updated

**Comment by kevinchappell** [comment]
@lucasnetau packagist webhook is now setup to auto-update on the next push. For now i did a manual sync and its showing the latest version. 
![image](https://user-images.githubusercontent.com/1457540/160193861-3cd32fca-0f32-49a0-87da-6722d0b7d64a.png)
