### ISSUE TITLE
Release >= 3.8.0 has changed public formRender API

### ISSUE THREAD

**Issue by lucasnetau** [kevinchappell/formBuilder#1279]
### Description:

Per https://formbuilder.online/docs/formRender/actions/userData/ the userData property on the formRender object should be an object with the current form values

3.8.0 changed the API and now the userData property is a function that needs to be called to return the userData

Possible change triggering the issue [src/js/form-render.js#](https://github.com/kevinchappell/formBuilder/commit/9775ca7e89dc7718c6f88f88f3caf232c8af0f3f#diff-109b583dd8ca170479d4ef35fcdd057e504e4062b833f4c80c723acf9590184c)

### Environment Details:

 - formBuilder Version: >= 3.8.0
 - Browser: Any
 - OS: Any

### Expected Behavior

typeof formRenderInstance.userData (object)

### Actual Behavior

typeof formRenderInstance.userData (function)

### Steps to Reproduce

Render a form and retrieve the userData

**Comment by lucasnetau** [comment]
Issue is due to removing these lines

```
const instance = methods.init(this, methodOrOptions)
      Object.assign(methods, instance)
      return instance
```

and instance returning the instance as 

```
return { ...methods.instance, ...methods }
```

**Comment by lucasnetau** [comment]
@kevinchappell this commit https://github.com/kevinchappell/formBuilder/issues/1221 introduced the breaking change in API to src/js/form-render.js

**Comment by Kit105** [comment]
Facing the same issue as mentioned by @lucasnetau 
Unable to fetch any user data after the commit. Any alternative way to fetch the userData?

**Comment by kevinchappell** [comment]
@lucasnetau thanks for finding this. just opened #1289 to fix
