### ISSUE TITLE
Label Issue

### ISSUE THREAD

**Issue by 1netme** [kevinchappell/formBuilder#1280]
When building the form the Label field became Div and not Input so the title for the field could not be changed

![Screen Shot 2022-03-20 at 9 43 24](https://user-images.githubusercontent.com/46339930/159153091-10a1355e-c0a3-47d8-906b-e3d632fbb000.png)

**Comment by Harpal32** [comment]
I am also facing the same issue unable to edit label.

**Comment by Cozdemir** [comment]
I also face same issiue today.  I notice if you pass datatype as xml it works. But if i change it back to json i cannot change label
this works i can change the label
var options = {
    dataType: 'xml',
};

this doesn't work i cannot change the label
var options = {
    dataType: 'json',
};

**Comment by Jojoshua** [comment]
This should have been fixed in v3.8.1
