### ISSUE TITLE
Label is not editable.

### ISSUE THREAD

**Issue by Harpal32** [kevinchappell/formBuilder#1281]
Label is not editable. It stopped working suddenly.
I am using following cdn files.
<script src="https://formbuilder.online/assets/js/form-builder.min.js"></script>
<script src="https://formbuilder.online/assets/js/form-render.min.js"></script>

I also tried on website (https://formbuilder.online/) and its not working here too. 
![image](https://user-images.githubusercontent.com/40538507/159203260-0e884afa-eaae-4639-84be-bfbb8986761b.png)

**Comment by LGNaude** [comment]
Hi,

We also encountered the same issue on our side and concerning that it is also broken on the FormBuilder demo site.

Please advise.

**Comment by Taktile** [comment]
Hello - love formbuilder - Same issue, labels are not editable. I think the 'contenteditable' attribute currently has a value of 'contenteditable' when I think it should be 'True'. Thanks.

**Comment by Neeraj1005** [comment]
Hi,
Did anyone solved this issue..?

**Comment by Jojoshua** [comment]
This should be fixed in the latest version (not live on the website yet though)
