### ISSUE TITLE
Clone funtionality

### ISSUE THREAD

**Issue by trekco** [kevinchappell/formBuilder#1282]
How can you get the name or id of the original field when you clone a field? Is it currently possible? 

I know of the onclone event but provides no details of the original field.

thanks

**Comment by Jojoshua** [comment]
It looks like onclone provides the html field https://formbuilder.online/docs/formBuilder/options/typeUserEvents/

**Comment by trekco** [comment]
@Jojoshua the html fields don't provide details about the original fields. Like name/id.

I ended up overriding jquery clone to set attributes on the html element

**Comment by umangnine** [comment]
Hello, 
I have implement onclone event for one of the control. 

I have used following code: 

            onclone: function (fld) {
                console.log("onclone event!");
                console.log(fld);
            },
Query: 
As per above code, I am getting the HTML of the cloned field but how can I get formdata from onclone event? I want to change some properties onclone event. 

Your quick help would be highly appreciated!
