### ISSUE TITLE
404 on documentation page

### ISSUE THREAD

**Issue by arjunshibu** [kevinchappell/formBuilder#1290]
### Description:
Can't access the docs page as it shows 404.

### Environment Details:
N/A

### Steps to Reproduce
Visit https://formbuilder.online/docs/

**Comment by Jojoshua** [comment]
@kevinchappell not sure how this happened

**Comment by arjunshibu** [comment]
@Jojoshua @kevinchappell it's resolved now.

**Comment by kevinchappell** [comment]
Reopening because it's 404 for me. Will look into what with the deploy.

**Comment by kevinchappell** [comment]
this should be fixed now: https://formbuilder.online/docs/

for those interested, formBuilder uses mkdocs to generate the documentation section of the website. The issue that broke the build is here:
https://github.com/mkdocs/mkdocs/issues/2799

**Comment by arjunshibu** [comment]
Thanks @kevinchappell
