### ISSUE TITLE
formBuilder with React functional components

### ISSUE THREAD

**Issue by arjunshibu** [kevinchappell/formBuilder#1293]
### Description: 
I cannot get formBuilder to work with React functional components. Help is really appreciated.

**Comment by mehmood-v** [comment]
import $ from "jquery";
import { useEffect, useRef } from "react";
import { Button } from "antd";
import("jquery-ui-sortable");
import("formBuilder");

window.jQuery = $;
window.$ = $;

const FormBuilder = () => {
  const fb = useRef();
  var options = {
    onSave: function (evt, formData) {
      console.log();
    },
  };

  useEffect(() => {
    if (fb) $(fb.current).formBuilder(options);
  }, []);
  return (
    <>
      <div id="fb-editor" ref={fb} />
      <Button
      
      >
        Download HTML
      </Button>
    </>
  );
};

export default FormBuilder;

**Comment by lucasnetau** [comment]
A demo is also provided here https://formbuilder.online/docs/formBuilder/demos/react/
