### ISSUE TITLE
Idea: Hide advanced fields

### ISSUE THREAD

**Issue by bjnhuggins** [kevinchappell/formBuilder#130]
Would be great if there was an array to add items to exclude from the field options.
Eg: don't want to complicate users with options like access, name, className.
Currently doing it by just hiding them using class names

**Comment by albu77** [comment]
We are with this on the point I talk with Kevin, is the plugin developer oriented or user oriented. Actually I think it's more on the developer side and even if it's not my own way to use it but It would need  work if we want to satisfy both.

**Comment by ivuorinen** [comment]
How about hiding fields with CSS?
```css
.frm-holder .access-wrap {
    display: none;
}
```
