### ISSUE TITLE
Content Security Policy and formbuilder

### ISSUE THREAD

**Issue by mkgn** [kevinchappell/formBuilder#1300]
### Environment Details:

 - formBuilder Version: 3.7.2
 - Browser: Latest browsers
 - OS: Any

### Expected Behavior: 
Should align with CSP to maintain security

### Actual Behavior : 

complains with below error (see image as well)

[Report Only] Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'".

![image](https://user-images.githubusercontent.com/8392595/165689786-d36123c9-22f7-4422-96d9-f12420d4fc9b.png)

### Steps to Reproduce

Just include the script, set CSP headers and check browser console.

**Comment by kevinchappell** [comment]
@mkgn do you know what line of code is triggering that error? formBuilder doesn't use `eval` 
![image](https://user-images.githubusercontent.com/1457540/165795099-252f1ae8-6d22-4dc8-a056-3ac2d648499a.png)

**Comment by mkgn** [comment]
Hmm... it's funny... the line it shows in console is 19. When you apply a CSP policy with **"script-src 'self'** does it complain?

**Comment by jorgeuos** [comment]
Got a similar error, seems to load in a lang file.

I uglified the min file. I think you see which part of the code is trigger the CSP block.

<img width="1417" alt="Screen Shot 2022-09-04 at 23 39 54" src="https://user-images.githubusercontent.com/21176316/188334629-6d7471fd-8b4d-46ff-90d2-4e858544cf1c.png">
<img width="613" alt="Screen Shot 2022-09-04 at 23 40 30" src="https://user-images.githubusercontent.com/21176316/188334632-badd60cb-53fa-416a-80de-cf140e710793.png">

**Comment by lucasnetau** [comment]
@kevinchappell , The eval is injected by webpack 4.4 node.js global polyfill https://github.com/webpack/webpack/blob/webpack-4/buildin/global.js

`new Function("return this")()`

the simplest method to fix this is to disable injection of the polyfill in the webpack config

node: {
    global: false,
  }

I'll submit a PR

**Comment by lucasnetau** [comment]
> Got a similar error, seems to load in a lang file.
> 
> I uglified the min file. I think you see which part of the code is trigger the CSP block.
> 
> <img alt="Screen Shot 2022-09-04 at 23 39 54" width="1417" src="https://user-images.githubusercontent.com/21176316/188334629-6d7471fd-8b4d-46ff-90d2-4e858544cf1c.png">
> 
> <img alt="Screen Shot 2022-09-04 at 23 40 30" width="613" src="https://user-images.githubusercontent.com/21176316/188334632-badd60cb-53fa-416a-80de-cf140e710793.png">

@jorgeuos You either need to allow this in your CSP to load the language file, or download the required language file and deploy it as part of your applications assets.

You can configure which lang file to use via the 

```json
i18n: {
    locale: 'en-US',
    location: "/path/to/lang/files"
}```

**Comment by jorgeuos** [comment]
> 
> @jorgeuos You either need to allow this in your CSP to load the language file, or download the required language file and deploy it as part of your applications assets.
> 
> You can configure which lang file to use via the
> 
> ```json
> i18n: {
>     locale: 'en-US',
>     location: "/path/to/lang/files"
> }
> ```

Yes, I did that. Thank you.

```
      fbOptions: {
        i18n: {
          locale: 'en-US',
          location: '/path/to/formBuilder-languages/',
          extension: '.lang',
        },
```
