### ISSUE TITLE
Form works locally, but not online. Please help me dear Kevin Chappell

### ISSUE THREAD

**Issue by serges-axel-nombre** [kevinchappell/formBuilder#1301]
### Description:

Sir, I am contacting you to ask for help with the dynamic form, indeed I installed the package on my Laravel 8 application following the online documentation on formbuilder.online.
I added the back-end layer to be able to store the form, and it displays, I manage to create the form dynamically and display it, as well as save the submitted fields, locally.
So my problem is that online, in deployment on my LWS host I manage to create the form, but then it does not display, please help me dear Kevin Chappell. We could collaborate if possible, because I am very interested in this package for my project, I am still waiting for a favorable response.

### Environment Details:

 - form Builder Version:   v3.8.3
 - Browser: Chrome Version 100.0.4896.127
 - OS: Win10

**Comment by lucasnetau** [comment]
Please provide a script reproducing the issue you are having
