### ISSUE TITLE
Label missing after re-saving form

### ISSUE THREAD

**Issue by leeneshkPSS** [kevinchappell/formBuilder#1302]
### Environment Details:

 - formBuilder Version:  V 3.8.2
 - Browser: Chrome
 - OS: Windows 10
 - Application: .Net MVC C#

### Expected Behavior
Labels of current fields to keep their structure when adding a new field and clicking save.

### Actual Behavior
Labels of current fields on form are being overwritten when adding a new field and clicking save.

### Screenshot - *(optional)*
![FireShot Capture 047 - Edit Form](https://user-images.githubusercontent.com/105714399/168786706-69f10a3d-f1a2-4e9b-8f92-417ae45b90a3.png)
![FireShot Capture 048 - Edit Form](https://user-images.githubusercontent.com/105714399/168786719-8a95b22c-b3c3-472c-b54b-44520c376b7e.png)

**Comment by leeneshkPSS** [comment]
So it seems like if 1 field is added, the json value saves perfectly, but the moment a second field is added, it overwrites the json structure of the first field. This occurs in the following sequence, if 2 fields exists and you add a third field, it overwrites the label field in the json structure of the first 2 and so on.

**Comment by leeneshkPSS** [comment]
[https://jsfiddle.net/leeneshk/hsLojf01/9/](url)

**Comment by leeneshkPSS** [comment]
Also this is a screenshot on what we see if we click the ellipsis 
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/105714399/168815271-1425fb77-109f-48ac-98b2-058b6299f027.png)

**Comment by LGNaude** [comment]
@Jojoshua Hi - can you assist from your side? Would appreciate it!

**Comment by Jojoshua** [comment]
Using the fiddle I cannot reproduce. Please list exact steps to reproduce for the fiddle.

**Comment by leeneshkPSS** [comment]
Uhm its a bit difficult to create a fully functional fiddle because we are using mvc C# for the solution,

The formBuilder worked perfectly, except for the last week or so, its merely something that you could advise by going through the code in the fiddle and check if we perhaps missing something on our side,

I must stress upon though that we have added conditional logic recently but it had no impact on the functionality
