### ISSUE TITLE
Is there a way I can add conditional fields?

### ISSUE THREAD

**Issue by ZaheerAbbasAghani** [kevinchappell/formBuilder#1304]
### Description: I am working on a WordPress plugin where I am showing the form builder what I want is to add conditional fields controlled by the backend.

![1](https://user-images.githubusercontent.com/14222731/168859400-dc51cdb1-81c6-44f7-b2ef-7a2073d5a247.PNG)
![2](https://user-images.githubusercontent.com/14222731/168859412-5ffb671c-2cc7-4923-8798-7771afe740f3.PNG)

Show field one text field if use select radio button one and show 2 text fields in user select multiple.

### Environment Details:

 - formBuilder Version: 3.8.2
 - Browser: Chrome
 - OS: Windows

**Comment by Jojoshua** [comment]
That isn't an out of the box feature but it's possible with some custom development.
