### ISSUE TITLE
Phishing detected in main site

### ISSUE THREAD

**Issue by confettidc** [kevinchappell/formBuilder#1305]
### Environment Details:

 - formBuilder Version: 
 - Browser: Firefox 100.0.2
 - OS: Mac OS X

### Expected Behavior
Can visit https://formbuilder.online/ and cdn https://formbuilder.online/assets/js/form-builder.min.js

### Actual Behavior
Phishing detected by AVG, incluing main website https://formbuilder.online/ and cdn https://formbuilder.online/assets/js/form-builder.min.js

### Steps to Reproduce
Just visit above 2 sites

### Screenshot - *(optional)*
![圖片](https://user-images.githubusercontent.com/5524183/171113898-b861365d-98fb-4b20-8edf-b283daa1ccc8.png)
![圖片](https://user-images.githubusercontent.com/5524183/171114302-5191c576-82c4-4521-a482-e6df6f4f93ce.png)

**Comment by florent-dehanne** [comment]
Same here, websites are also blocked by Avast.

![avast](https://user-images.githubusercontent.com/6445402/171226749-72800032-ca24-48ee-946f-a5e414b480b7.png)

**Comment by lucasnetau** [comment]
Showing up clean

homepage
https://www.virustotal.com/gui/url/8de6f62c685ef3a5d4281da14521abebd51c4224264f6b9d48983842dcb54bf6

form-builder-min.js
https://www.virustotal.com/gui/url/ece9650643ad735c5e479e0d8ea2df24bb5389a51201d1261bd2ea07ee78ad9c

form-render.min.js
https://www.virustotal.com/gui/url/8f05294ea8394356081af25ec8b41c1833abb1fb0f79e311980f85a40b2a7f25/detection

**Comment by lucasnetau** [comment]
Closing as this looks more like a transient issue with some scanners
