### ISSUE TITLE
Append JSON Form when i am clicking on setform button  in form Builder

### ISSUE THREAD

**Issue by Mohini9557** [kevinchappell/formBuilder#1307]
hii , Kevinchappel My question is when i used this code to show my form it append form builder to show json form , pls help
setform: () => {
const Option = {
// dataType: 'json',
formData: '[{"type":"file","required":false,"label":"File Upload","className":"form-control","name":"file-1653970324087-0", "access": false, "subtype": "file", "multiple": false }, { "type": "text", "required": false, "label": "Text Field", "className": "form-control", "name": "text-1653970327364-0", "access": false, "subtype": "text", "readonly": false }, { "type": "button", "label": "Button", "subtype": "button", "className": "btn-default btn", "name": "button-1653970332064-0", "access": false, "style": "default" } ]'
}
$('.build-wrap').formBuilder(Option)
},
![ss_fom](https://user-images.githubusercontent.com/78868406/171343309-e5a8e112-4ba2-4c68-8ab7-738e36556c13.png)

**Comment by lucasnetau** [comment]
You are creating a new instance of formBuilder in the div.build-wrap when you call $('.build-wrap').formBuilder(Option)

You can use `formBuilderInstance.actions.setData(formData);` where formBuilderInstance is your previously created instance.
