### ISSUE TITLE
Get XML of Form after using Form Render

### ISSUE THREAD

**Issue by DanielC9522** [kevinchappell/formBuilder#131]
Hi Kevin, 
I am using version 1.8.2 of your plugin, I was wondering if there was a way to get the xml of the form after the form has been rendered using formRender(). This is so I can store the form as xml with the form elements filled in

**Comment by yuchaozh** [comment]
+1 also have the same issue. How to save the form after filled in?

**Comment by baochung26** [comment]
i get element have form, after saved, but i don't think it good

**Comment by kevinchappell** [comment]
I always thought this was outside the scope of formBuilder. The original idea was to build form templates, not store form data but I can see how the functionality would have value in some workflows. This feature will be considered for future versions but at this time focus is on 2.0 feature set.

**Comment by baochung26** [comment]
thank you, Kevinchappell !

**Comment by baochung26** [comment]
This is what I did
Go to form-builder.js find xmlButton.click(function (e) {}
add var formXml = elem.val(); console.log(formXml); in function
Run template form->click save -> f12 -> tab console
You see what is you need save -> you save it;
after uses -> <textarea id="fb-template">
	                     {{$call['formXml']}}
                    </textarea>
$call['formXml'] is data you save
