### ISSUE TITLE
Drag and drop of fields does not work on touch devices (iPhone, iPad)

### ISSUE THREAD

**Issue by tomcodes** [kevinchappell/formBuilder#1310]
### Description

Drag and drop of fields to re-order them does not work on touch devices using the `Basic Example` provided:

```html
<!DOCTYPE html>
<html>
<head>
    <title>Example formBuilder</title>
</head>
<body>
  <div id="fb-editor"></div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
  <script src="https://formbuilder.online/assets/js/form-builder.min.js"></script>
  <script>
  jQuery(function($) {
    $(document.getElementById('fb-editor')).formBuilder();
  });
  </script>
</body>
</html>
```

:warning: it actually works on the website homepage: https://formbuilder.online/

### Environment Details:

 - formBuilder Version: latest from CDN (3.8.2)
 - Browser: Firefox, Safari, Chrome latest versions
 - OS: iOS (iPad, iPhone SE)

### Expected Behavior

The fields should be drag and droppable to reorder them.

### Actual Behavior

The whole page is scrolling.

**Comment by ZaheerAbbasAghani** [comment]
Try to add jquery ui sortable script it might work.

[](https://jqueryui.com/sortable/)

**Comment by filip-remic** [comment]
any news here?

**Comment by lucasnetau** [comment]
A PR https://github.com/kevinchappell/formBuilder/pull/1402 has been raised for this with a workaround for touch devices. While drag and drop is not supported by jQuery sortable the sorting of fields is allowed through field action up/down buttons
