### ISSUE TITLE
How we can change date format?

### ISSUE THREAD

**Issue by bhavik45** [kevinchappell/formBuilder#1313]
### Description:
We need to change the date format for date picker control.

We need a date format like mm-dd-yyyy. Currently, form builder takes system format.

Can anyone help me to change the format?

**Comment by lucasnetau** [comment]
You can't if you are using the HTML5 date picker. Internally and when loading from value attribute and sending to the server it is represented by YYYY-MM-DD, when display in the Browser UI the input uses the user's system locale settings for display.

https://developer.chrome.com/blog/quick-faqs-on-input-type-date-in-google-chrome/
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

Look at using date picker plugin, using either a custom control or via setting a well known class name and enhancing the text input after load via Javascript
