### ISSUE TITLE
How to use enableColumnInsertMenu?

### ISSUE THREAD

**Issue by phpcontrols** [kevinchappell/formBuilder#1314]
### Description:

3.8 added column enhancement feature with a few [extra column settings](https://github.com/kevinchappell/formBuilder/commit/023f8b7bf040b21a18f8a8e7870da8918998bdc4
) which include an interesting property 'enableColumnInsertMenu'. The question is how do one use it? I've tried to play with the settings, but the form builder remain the same. How does it suppose to work?

### Environment Details:

 - formBuilder Version: 3.8
 - Browser: Chrome (latest)
 - OS: MacOS 11.6

### Expected Behavior

Additional column layout during form building 

### Actual Behavior

The form builder appears to be the same even with `enableColumnInsertMenu` set to true. 

### Steps to Reproduce

Tried with the following

```
jQuery(function($) {
    var options = {
        defaultGridColumnClass: 'col-md-6',
        cancelGridModeDistance: 100,
        enableColumnInsertMenu: true,
        enableEnhancedBootstrapGrid: false
    };

    $(document.getElementById('fb-editor')).formBuilder(options);
  });
```

**Comment by Jojoshua** [comment]
When you enable the setting then you should see an icon between fields when hovering over them

**Comment by lucasnetau** [comment]
enableEnhancedBootstrapGrid must be true for enableColumnInsertMenu to be active.

```javascript
var options = {
        enableColumnInsertMenu: true,
        enableEnhancedBootstrapGrid: true
    }
```
