### ISSUE TITLE
How to get formdata for cloned field?

### ISSUE THREAD

**Issue by umangnine** [kevinchappell/formBuilder#1316]
Hello,
I have implement onclone event for one of the control.

I have used following code:

        onclone: function (fld) {
            console.log("onclone event!");
            console.log(fld);
        },
Query:
As per above code, I am getting the HTML of the cloned field but how can I get formdata from onclone event? I want to change some properties onclone event.

Your quick help would be highly appreciated!

**Comment by lucasnetau** [comment]
The element has already been cloned and inserted by this stage. If you want to change anything you can then query the stage and update any fields you wish to change
