### ISSUE TITLE
 radio-group issues when checking Others

### ISSUE THREAD

**Issue by RASCAL-FG** [kevinchappell/formBuilder#1318]
### Description:
When I check Others and type in the textbox, the name attribute changes.
So the check remains.
### Environment Details:

 - formBuilder Version: last version
 - Browser: 
 - OS: 

### Expected Behavior
Do not change the name attribute

### Screenshot - *(optional)*
![ss](https://user-images.githubusercontent.com/100493546/179941046-c783730e-cdbb-4253-b859-db9de68ff874.png)

**Comment by lucasnetau** [comment]
Hi @RASCAL-FG , I've submitted PR#1331 for @kevinchappell to merge, please test it out in the mean time.
