### ISSUE TITLE
Problem to add custom header in the sortable section to divide it in 2 parts

### ISSUE THREAD

**Issue by Saraf-Piyush** [kevinchappell/formBuilder#132]
@kevinchappell
How to add custom header tag in the sortable section to divide it in 2 parts, say like i want to make the first header to be simple fields, which contains text ,text-area. The second section contains radio button, checkbox, checkbox list. The third section contains dropdown , select, multiselect. And the last one is for autocomplete, rich-text.

example : 
simple field
ul start
    li
    li
check fields
    li
    li
drop-down fields
    li
    li
Advance fields
    li
    li
ul ends

can you help me on this how to achieve it ?

**Comment by kevinchappell** [comment]
It sounds like you should be able to achieve this with CSS. Do you mean like adding a wrapper for groups of fields? If so you may need some additional JS for that. This isn't the best method, if you can get the style you want with css only I would try that option.

**Comment by Saraf-Piyush** [comment]
@kevinchappell 
thanks for the suggestion. I was wondering if you could look at this code pen and suggest me
http://codepen.io/saraf_piyush/pen/qZxMma

**Comment by kevinchappell** [comment]
After seeing your codepen I realized I had completely misunderstood the question.

I think the simplest solution would be to keep it how you have but add `cancel: '.disabled',` to the `sortable()` config for `cbUL`. Also to keep it valid html you could put the `<h4>` in a `<li>` and just use css to style the separator.

Good job on this, formBuilder could definitely use different sections with more types.

**Comment by Saraf-Piyush** [comment]
@kevinchappell 
Thanks for the appreciation, but would love to help you in any manner

**Comment by Saraf-Piyush** [comment]
@kevinchappell 
I tried your solution of " add cancel: '.disabled', to the sortable() config for cbUL " has made the current problem solved in my regarding.

**Comment by kevinchappell** [comment]
@Saraf-Piyush I got to check out your demo and it's pretty nice, I like the new field types. If there are no objections I will close this issue but I wanted to give you a sneak peak at how field types are handled in the next version of formBuilder.

![control-groups-preview](https://cloud.githubusercontent.com/assets/1457540/15380581/8749f06a-1d6f-11e6-8560-017f97022627.gif)
