### ISSUE TITLE
Error occurred in checkbox-group with Others

### ISSUE THREAD

**Issue by RASCAL-FG** [kevinchappell/formBuilder#1320]
### Description:
Check Others, then click checkbox, TypeError occurred.
### Environment Details:

 - formBuilder Version: 3.8.3
 - Browser: Chrome
 - OS: Windows

### Screenshot - *(optional)*
![img1](https://user-images.githubusercontent.com/100493546/181376993-6461b32d-dc79-4f05-bd25-efa29b80aaa6.png)
![img2](https://user-images.githubusercontent.com/100493546/181377066-291a1c95-b2b2-45ad-a182-c31f3f8f4b37.png)
![img3](https://user-images.githubusercontent.com/100493546/181377078-41a5314b-b147-4cec-91ad-8795a2afb5ad.png)

**Comment by lucasnetau** [comment]
@RASCAL-FG , I've added a PR to address this issue. Feel free to try it out in the meantime.
