### ISSUE TITLE
Question: How do I prevent HTML in labels?

### ISSUE THREAD

**Issue by robv8r** [kevinchappell/formBuilder#1324]
How do I prevent users from adding HTML to a Form Field Label?

There's a configuration option called [disableHTMLLabels](https://formbuilder.online/docs/formBuilder/options/disableHTMLLabels/).  The description of the configuration option states that it "Disables HTML labels."  Setting this value to true or false has no effect on adding HTML to labels.

The CodePen on the [disableHTMLLabels](https://formbuilder.online/docs/formBuilder/options/disableHTMLLabels/) page allows you to create hyperlinks in a field's label.

To recreate the issue:

1. Visit the disableHTMLLabels documentation page.
2. In the CodePen, drag a Form Field onto the Form Builder.
3. Edit the label by clicking the Pencil icon.
4. Change the value to `<a href="https://www.microsoft.com" target="blank">Autocomplete</a>`
5. Click "Close"
6. Click the Label that was just modified
7. A new tab opens showing Microsoft's webpage.

The preferred behavior would be to either disallow HTML in the label or escape the HTML so it isn't rendered as HTML.

If I'm missing something, I'd be grateful if someone could educate me.

**Comment by robv8r** [comment]
Thank you for creating formBuilder and making it a successful open source project.

I fully understand (and respect) that projects like formBuilder are often created and maintained by volunteers.

With respect, I ask if anyone has input on my question above.

Thank you.

**Comment by lucasnetau** [comment]
@kevinchappell , what are your thoughts on this issue?

**Comment by lucasnetau** [comment]
@robv8r PR #1416 has been raised which should complete the implementation of text only labels. This only forces HTML to be treated as text. If you wish to strip HTML I would suggest implementing DOMPurify in your code.
