### ISSUE TITLE
Problem save and load xml data with special char

### ISSUE THREAD

**Issue by xeys** [kevinchappell/formBuilder#133]
When i save and load data with special chars, i have encode problem in label
it's correct in option

example : 
1) I create form with label : &é"'(-è_çà)=
2) I save data in XML in the database, special chars are encode : &amp;&eacute;&quot;'(-&egrave;_&ccedil;&agrave;)=
3) I load formbuilder with xml data and it's automatically transform to &amp;&eacute;&quot;'(-&egrave;_&ccedil;&agrave;)=
4) If I save again, special chars are transform to "undefined"

**Comment by kevinchappell** [comment]
I finally had a chance to really get into this and found it would require a major rewrite of the way XML data is handled. Even after replacing the current xml escaping techniques with `XMLSerializer` there were still issues with parsing. So then the parser was replaced with `DOMParser`, still issues with certain characters.

Unfortunately there is no simple fix and at this time I'd like to focus efforts on 2.0 where issues like these are resolved by using JSON.
