### ISSUE TITLE
It does not load the min/max 0 of the input number

### ISSUE THREAD

**Issue by mcolominas** [kevinchappell/formBuilder#1337]
### Description:
As I have indicated in the title, when I select the input number, and in the min/max I set it to 0, save the data, and reload the form (refreshing the page), the 0 of the min/max disappears, however , in the json the min/max appears at 0, the problem is when I save again, as the min/max was empty it is removed from the json

**Comment by lucasnetau** [comment]
Give the PR #1338 a go.
