### ISSUE TITLE
Multiple Formbuilder Forms on a single page not working properly.

### ISSUE THREAD

**Issue by Sharad2390** [kevinchappell/formBuilder#1340]
### Environment Details: I am working on a staging environment having PHP on the stack side

 - formBuilder Version: Latest one
 - Browser: Chrome
 - OS: Windows

### Steps to Reproduce: Below is complete code which I am working on:
**JS** 
```
jQuery(function($) {
  var fbTemplate = document.getElementById('fb-editor');
  var options = {
    disabledActionButtons: ['data','clear','save']
  };
  var formBuilder = $(fbTemplate).formBuilder(options);
  document.getElementById('getJSON').addEventListener('click', function() {
    alert(formBuilder.actions.getData('json'));
  });
  var fbTemplate1 = document.getElementById('fb-editor1');
  var options1 = {
    disabledActionButtons: ['data','clear','save']
  };
  var formBuilder2 = $(fbTemplate1).formBuilder(options1);
  document.getElementById('getJSON1').addEventListener('click', function() {
    alert(formBuilder2.actions.getData('json'));
  });
});

```
**HTML**
```
<div id="fb-editor"></div>
<button id="getJSON" type="button">Get JSON Data</button>
<div id="fb-editor1"></div>
<button id="getJSON1" type="button">Get JSON Data</button>
```

**Comment by Sharad2390** [comment]
Hi @kevinchappell,
Please help me with this as I am totally stuck with this issue.
Thanks!

**Comment by lucasnetau** [comment]
Take a look at https://formbuilder.online/docs/formBuilder/promise/ and use the result of the initialisation promise

**Comment by kirykr** [comment]
I can see this in [Section](https://formbuilder.online/docs/formBuilder/actions/getData/). But when I use promise and store the objects in an array, all the other objects get overridden by the last object.

```coffee
  @formBuilder = []
  for element in $('#tab1, #tab2')
      dataElement = JSON.parse($(element).children('span').text())
      _initProgramBuilder(element, (dataElement || []))
  
  _initProgramBuilder = (element, data) ->
    $(element).formBuilder().promise.then (fb) ->
      @formBuilder.push fb
   
```

**Comment by Abacaxi-Nelson** [comment]
Same here @kirykr 
Did you find a solution, i have two form builder, and calling "actions.getData()" only return last one..
I am already using promises...

**Comment by Repechinskyi** [comment]
Hello. Who was able to solve this problem? I ran into it and all methods do not help

**Comment by lucasnetau** [comment]
You can only initialise a single formBuilder instance at a time and need to wait for the promise to resolve before moving onto initialising the next instance.

This can be done either via a recursive function per https://github.com/kevinchappell/formBuilder/issues/1087#issuecomment-648609752

or via awaiting the promise per the documentation.

The initial code by @Sharad2390 can be rewritten with the ready callback being async and the initialisation await the promise object of formBuilder

```js
jQuery(async function($) {
  var fbTemplate = document.getElementById('fb-editor');
  var options = {
    disabledActionButtons: ['data','clear','save']
  };
  var formBuilder = await $(fbTemplate).formBuilder(options).promise;
  document.getElementById('getJSON').addEventListener('click', function() {
    alert(formBuilder.actions.getData('json'));
  });
  var fbTemplate1 = document.getElementById('fb-editor1');
  var options1 = {
    disabledActionButtons: ['data','clear','save']
  };
  var formBuilder2 = await $(fbTemplate1).formBuilder(options1).promise;
  document.getElementById('getJSON1').addEventListener('click', function() {
    alert(formBuilder2.actions.getData('json'));
  });
});
```

**Comment by Repechinskyi** [comment]
Hello. Thank you for giving a hint, which helped partially, but now I have encountered another problem in the form, the fields are displayed correctly, but when I want to get data from the form in json format, I have the same code on page 2 and 3. I've been struggling with this code for several days, I don't know what to do anymore.

I have 3 pages now:
1 - Text field
2 - Date field
3 - Header fields

These fields in the form will visually display correctly. There is no error with "actions.getData" now, but when I view the result var json = fb.actions.getData('json', true); then I get

1 - Text field
2 - Header fields
3 - Header fields

After the first it is duplicated

document.addEventListener('DOMContentLoaded', async function() {
	jQuery( function ($) {

		 var fbOptions = {...};

		 fbInstances.push($(".build-wrap").formBuilder(fbOptions));

	     setTimeout(function() {
	        $.each(setFormData, function(i, item) {

	            if(fbInstances[i]) {
	                fbInstances[i].actions.setData(item);
	            } else {
	                addPageLoading(item);
	            }
	        });
	    }, 2000);

	    // add pages form 
        async function addPageLoading(data){
	        console.log('addPageLoading')
	        const tabCount = document.getElementById("tabs").children.length;
	        const tabId = "page" + tabCount.toString();
	        const newPageTemplate = document.getElementById("new-page");
	        const newTabTemplate = document.getElementById("add-page-tab");
	        const newPage = newPageTemplate.cloneNode(true);
	        newPage.setAttribute("id", tabId);
	        newPage.classList.add("build-wrap");
	        const $newTab = newTabTemplate.cloneNode(true);
	        $newTab.removeAttribute("id");
	        const tabLink = $newTab.querySelector("a");
	        tabLink.setAttribute("href", "#" + tabId);
	        tabLink.innerText = "Page " + tabCount;
	        $newTab.append($("<a class='remove-page' data-id="+tabCount+">X</a>")[0])

	        newPageTemplate.parentElement.insertBefore(newPage, newPageTemplate);
	        newTabTemplate.parentElement.insertBefore($newTab, newTabTemplate);


	        fbPages.tabs("refresh");
	        fbPages.tabs("option", "active", tabCount - 1);


	        if(data.length){
	            fbOptions.formData = data;
	        }else{
	            fbOptions.formData = [];
	        }

	        var formBuilder_load = await $(newPage).formBuilder(fbOptions).promise;
	        fbInstances.push(formBuilder_load);

   	 	}	


 		// Get JSON and send form
	    $(document.getElementById("getJSON")).click(function () {

	        const allData = fbInstances.map((fb) => {
	            var json = fb.actions.getData('json', true);
	            return json;
	        });
	        $("input[name='json']").val("["+allData+"]");
	        $("#design-form").submit();
	       
	    });

    });
});

**Comment by kirykr** [comment]
> Same here @kirykr Did you find a solution, i have two form builder, and calling "actions.getData()" only return last one.. I am already using promises...
Hi @Abacaxi-Nelson here is what I did 
  ```coffee
@formBuilder = []
startIndex = 0
  _initMultipleFormBuilder = (startIndex, elements) ->
    if startIndex < elements.length
    $(elements[startIndex]).formBuilder(
      ...
    ).promise.then((form) ->
        form.element = elements[startIndex]
        @formBuilder.push form
        startIndex++
        _initMultipleFormBuilder(startIndex, elements)
      )
```
I use a recursive function. I haven't tracked it down why it works this way yet. Let me know if there is still a problem.

**Comment by lucasnetau** [comment]
@Repechinskyi the first time you initialise formBuilder you don't use the promise

`fbInstances.push($(".build-wrap").formBuilder(fbOptions));`

and then further on you use do 

```javascript
var formBuilder_load = await $(newPage).formBuilder(fbOptions).promise;
fbInstances.push(formBuilder_load);
```

Fix up the first initialisation and it should work for you.

@kirykr The recursive method works well too.
