### ISSUE TITLE
SELECT Options Broken

### ISSUE THREAD

**Issue by johnpg82** [kevinchappell/formBuilder#1346]
### Description:
Here is a quick video demonstration.
https://watch.screencastify.com/v/RwWE0onI8VgV5Xrm3tUz

When selecting an option for any type it doesn't de-select the other option and there is also no way to unselect an option by clicking it again either. Although logically radio buttons should be grouped and you should only be able to select one option.

### Environment Details:

 - formBuilder Version: 3.8.3
 - Browser: Chrome
 - OS: Mac

### Expected Behavior

De-select other radio options under radio group or select button when selecting a new option.

### Actual Behavior
You can't unselect radio options from radio group or select.

### Steps to Reproduce
Create a radio group or select

### Screenshot - *(optional)*
https://watch.screencastify.com/v/RwWE0onI8VgV5Xrm3tUz

**Comment by lucasnetau** [comment]
Please try out PR https://github.com/kevinchappell/formBuilder/pull/1333

**Comment by johnpg82** [comment]
> Please try out PR #1333

Thanks for your contributions @lucasnetau. I'm not shure why this isn't port of the core Formbuilder? If you're available for Hire I could use some help modifying your existing media plugin to utilize server side uploading via a plugin such as jQuery file upload. 

https://blueimp.github.io/jQuery-File-Upload/

**Comment by johnpg82** [comment]
@lucasnetau It looks like you committed it but it hasn't been updated in the https://formbuilder.online/assets/js/form-builder.min.js because it isn't working on 3.8.2.

**Comment by lucasnetau** [comment]
> @lucasnetau It looks like you committed it but it hasn't been updated in the https://formbuilder.online/assets/js/form-builder.min.js because it isn't working on 3.8.2.

It's waiting for @kevinchappell to merge. I have a few PRs sitting in the queue.

**Comment by johnpg82** [comment]
@lucasnetau Ok thanks. I just cloned it. I'll try and test it out tomorrow or this weekend and make a comment or approval notice. I haven't used anything besides the .min so I have to familiarize myself with the rest. I'm going to close this ticket and I'll comment on #1333 when I've finished testing.

**Comment by lucasnetau** [comment]
@johnpg82 , I've attached a built version of the form-builder.min.js to the PR for you to test with. Feel free to reach out to me on linkedin (james-lucas-aus)
