### ISSUE TITLE
Header not rendering properly in editor when pre-loading XML into the textarea

### ISSUE THREAD

**Issue by thewizster** [kevinchappell/formBuilder#135]
I am loading some previously created form xml data into the textarea of the formbuilder. The Header field is not rendering properly in the editor.

Here are the steps I take:

1) Create a form. Add a header to it. appears normal in editor. I save the XML.
2) Load the previously saved XML into the textarea when building the page. (I am using PHP)
3) The formbuilder loads the XML into the editor. Header does not render as it should. I can preview the form, using form-render, at this point and header renders fine. **XML is proper for the header field at this point**
`<field class="header" label="Header" type="header" subtype="h1"></field>`
4) Now I click save and header XML is changed to: 
`<field class="header" label="Header" type="header"></field>`

I am using formbuilder v1.9.26

Here is what the header rendering looks like.
![header rendering](https://cloud.githubusercontent.com/assets/1342438/14414173/0fae3b58-ff54-11e5-8044-55d03f965fe6.JPG)

Thanks in advance for any feedback you can give.

**Comment by kevinchappell** [comment]
@thewizster Thanks for catching this. I'll work on a fix now.

**Comment by kevinchappell** [comment]
Should be all set now. Thanks for the well-written issue, it helped me get to the bottom of this faster. Please test when you have a chance: http://codepen.io/kevinchappell/pen/wGyzLb

**Comment by thewizster** [comment]
Works perfect now...Appreciate the quick response and all your efforts!
