### ISSUE TITLE
bootstrap grid system activate

### ISSUE THREAD

**Issue by newbreed77** [kevinchappell/formBuilder#1352]
Hello.
How do I activate the bootstrap grid system using drag & drop in the form design window?
We don't see that in the demo and the API demo.

**Comment by lucasnetau** [comment]
Hi @newbreed77 , I cannot find any doco for this feature however looking at the code it can be enabled with the formBuilder option `enableEnhancedBootstrapGrid: true`

**Comment by lucasnetau** [comment]
Opened #1439 to track adding documentation
