### ISSUE TITLE
Switch to sass from node-sass breaks my icons for some reason.

### ISSUE THREAD

**Issue by erpdatallc** [kevinchappell/formBuilder#1353]
### Description:
On my little web app (expansion of the standard demo) that I developed using v3.6.1 it has been working fine, tried upgrading to 3.8.3 and the icons were replaced with "funky text".  Traced it to breaking at 3.7.4 when the sass processor was changed from "node-sass" to "sass".
### Environment Details:

 - formBuilder Version: 3.7.4+
 - Browser: Chrome
 - OS: Windoze

### Expected Behavior
Icons on the formbuilder
### Actual Behavior
Crazy text instead of icons
### Steps to Reproduce
Under sass processor, the form-builder.min.js entries for icons that are dynamically loaded are of the form:
.formbuilder-icon-autocomplete:before{content:"î €"}
.formbuilder-icon-date:before{content:"î "}

When I rebuild 3.8.3 using node-sass instead I get the old behaviour in that section of the js:
.formbuilder-icon-autocomplete:before{content:'\\\\e800'}
.formbuilder-icon-date:before{content:'\\\\e801'}

**Comment by lucasnetau** [comment]
Do you have <meta charset="utf-8"/> in your HTML document? 

Looking a the webpack output between development and production builds, Webpack CSS Loader appears to be dropping the `@charset "UTF-8";` declaration of the injected CSS styles. It's possible that Windows is picking the wrong encoding, the meta tag should give the appropriate hint for the styles.

**Comment by lucasnetau** [comment]
@erpdatallc I was able to replicate this and adding `<meta charset="utf-8"/>` into my HTML head section resolved the issue. It's a required tag for libraries like Bootstrap.

**Comment by lucasnetau** [comment]
Related upstream issues
https://github.com/webpack-contrib/sass-loader/issues/973
https://github.com/sass/dart-sass/issues/1387

The correct way to handle this is to either include `<meta charset="utf-8"/>` into the HTML document or load form-builder.min.js with a charset assigned `<script src="form-builder.min.js" charset="UTF-8"></script>`

**Comment by lucasnetau** [comment]
Documentation should be updated to ensure that the charset is configured correctly. For example Bootstrap requires this tag to be set https://getbootstrap.com/docs/5.3/getting-started/introduction/#quick-start
