### ISSUE TITLE
userData checkbox-group is not working

### ISSUE THREAD

**Issue by malikust** [kevinchappell/formBuilder#1355]
### Description:
Hi, all co team of form builder , I have problem with multi checkbox-group . When i save the data to DB after getting checked value is not working, please help me.  
### Environment Details:
xampp, php/mysql
 - formBuilder Version: 3.4.1
 - Browser: chrome
 - OS: window 10

### Expected Behavior
Update checkbox checked not working correctly
### Screenshot - *(optional)*
![image](https://user-images.githubusercontent.com/9428105/213368648-11e76347-929a-4368-b7bc-e42842020d76.png)

I checked one but it save the unchecked also please help me

**Comment by lucasnetau** [comment]
Can you please check with a recent release of formBuilder. v3.4.1 is a three year old version.

**Comment by vijay-torani** [comment]
still it not working in my form  when i show the form with  checkbox group it remain checked  but i unchecked the checkbox
