### ISSUE TITLE
checkbox 'other' value not rendered

### ISSUE THREAD

**Issue by netingweb** [kevinchappell/formBuilder#1356]
### Description:

Whenever we enable the option "Other" to checkbox, the value entered in the input box is not rendered although the value is correctly saved in json

### Environment Details:

 - formBuilder Version: current
 - Browser: chrome
 - OS: MAC iOS / Windows

### Expected Behavior

'Other' value should be rendered when we render the form from json

### Actual Behavior

This behavior can be tested in demo

**Comment by imniranjandev** [comment]
Facing issue on setData()
radio button and checkbox option name and values are not showing

**Comment by lucasnetau** [comment]
@netingweb Can you please provide a reproducible code example. I cannot replicate your issue with formRender

<img width="252" alt="image" src="https://github.com/kevinchappell/formBuilder/assets/9331242/fca65868-0510-4419-a702-55e853d5d4c3">

**Comment by lucasnetau** [comment]
I'm unable to reproduce this issue, If it is still an issue please reopen and attach a reproduction.
