### ISSUE TITLE
formBuilder does not work in IE11 or IE Mode in Microsoft Edge

### ISSUE THREAD

**Issue by richlux** [kevinchappell/formBuilder#1357]
### Description:
According to the documentation, Internet Explorer 11 is supported, but formBuilder doesn't work in IE11 or Edge with IE Mode enabled. The page does not render correctly and there are JavaScript errors.

### Environment Details:
 - formBuilder Version: 3.8.3
 - Browser: Edge in IE Mode
 - OS: Windows 10

### Expected Behavior
The page should load properly as it does in other browsers

### Actual Behavior
The page does not render and the JS console shows JavaScript errors

### Steps to Reproduce
Simply go to the [formbuilder.online homepage](https://formbuilder.online/) and you will see that the page does not load properly

**Comment by lucasnetau** [comment]
IE11 is considered a dead (browserslist) and unsupported (Microsoft) browser, it is no longer a part of the browserslist >1% configuration for FormBuilder. Documentation has been updated in PR #1430 to correct the documentation.
