### ISSUE TITLE
field 'name' is disabled on formBuilder demo

### ISSUE THREAD

**Issue by tacman** [kevinchappell/formBuilder#1359]
### Description:

I need to be able to set and modify the 'name' field of a form element, but it is not available.  This is from https://kevinchappell.github.io/formBuilder/

![image](https://user-images.githubusercontent.com/619585/218310205-f7161131-ee73-4044-a421-bb7c82fcfa6d.png)

When I fill out the form 

![image](https://user-images.githubusercontent.com/619585/218310267-3db27ca3-edea-455b-90e7-90dde2760103.png)

and submit it, I get

```json
{'text-1676203733139-0': 'Google'}
```

what I'd like to get is

```json
{'org_name': 'Google'}
```

When I run this same demo on https://formbuilder.online/, I do get a name field.

![image](https://user-images.githubusercontent.com/619585/218310349-dd1d8a07-2e46-4ddb-8968-0c8abaca9b36.png)

These are running from the live demos, when I run it locally, I see the name field (as above), but when I load the JSON, the name field is blank.

**Comment by lucasnetau** [comment]
In the demo the name attribute is disabled via this option:

`disabledAttrs: ["placeholder", "name"],`

**Comment by tacman** [comment]
Hmm, name is pretty important, why disable it in the demo?

**Comment by lucasnetau** [comment]
Comment in the demo code suggests it was done as an example.

```javascript
  // test disabledAttrs
  const disabledAttrs = ['placeholder', 'name']
```

**Comment by prakomkumham** [comment]
How the name field not editable? 

As html input tag set to disabled.

Thanks

**Comment by lucasnetau** [comment]
@tacman Name and className are special attributes in that disabling them doesn't remove them, it instead hides them from the edit panel. Each control is still allocated a generated name and this is provided in the save data.

If you wish to edit your name attribute you'll need to run FormBuilder locally and not via the API demo site

**Comment by tacman** [comment]
I'm having a hard time understand the value of the demo specifically disabling the Name, arguable the most important attribute of the field.  It seems confusing, and unnecessarily so.
