### ISSUE TITLE
Formbuilder HTTP request failure.

### ISSUE THREAD

**Issue by Seyyid64** [kevinchappell/formBuilder#1360]
Each time the page is loaded, formbuilder makes an HTTP request to load the language packages, which always fails.

Access to XMLHttpRequest at 'https://codepen.io/kevinchappell/fullpage/assets/lang/ru-RU.lang' (redirected from 'https://cdpn.io/kevinchappell/fullpage/assets/lang/ru-RU.lang') from origin 'https://cdpn.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by lucasnetau** [comment]
You need to set a `location: 'http://languagefile.url/directory/'` i18n option value for the location of your language files. Only en-US is embedded into formBuilder

For the demo on https://formbuilder.online/docs/formBuilder/options/i18n/ you can adjust by changing the codepen to use and load the language files from github

```javascript
{
      i18n: {
        location: 'https://raw.githubusercontent.com/kevinchappell/formBuilder-languages/master/',
        locale: 'ru-RU'
      }
}
```
