### ISSUE TITLE
UI broken for checkbox group and radio group

### ISSUE THREAD

**Issue by experionathira** [kevinchappell/formBuilder#1361]
### Description:
The required error message for the fields checkox group and radio group is showing as collapsed with the first option value. Any fix for this?

### Screenshot - *(optional)*
![required_UI](https://user-images.githubusercontent.com/23093016/220879330-b006188e-9b99-4013-a219-6ba0dd09a537.PNG)

**Comment by lucasnetau** [comment]
Can you please provide a reproducible example of this? What browsers is being used? What CSS libraries are you using?

formBuilder doesn't inject required messages into the fields.
