### ISSUE TITLE
add two parametre ( options and fields ) in formBuilder function 

### ISSUE THREAD

**Issue by Imadboushaba** [kevinchappell/formBuilder#1363]
### Description:
i want to add two parametre in function formBuilder({fields },options ) , but not working 
### Environment Details:

 - formBuilder Version: 
 - Browser: 
 - OS: 

### Screenshot - *(optional)*

var options = {
                disableFields: ['autocomplete']
                };
            var fields = [{
                label:'{{__('Add-Item-drag')}}',
                type: "text",
                subtype: "email",
                name :"itemsDrab[0][email]",
                required: false,
                icon: "✉"
                }];
$fbTemplate.formBuilder();

**Comment by lucasnetau** [comment]
fields is an option. Please try

```javascript
let options = {
  disableFields: ['autocomplete'],
  fields: [{
    label:'{{__('Add-Item-drag')}}',
    type: "text",
    subtype: "email",
    name :"itemsDrab[0][email]",
    required: false,
    icon: "✉"
  }];
};
$fbTemplate.formBuilder(options);
```
