### ISSUE TITLE
formRender action - clear

### ISSUE THREAD

**Issue by ArjunDosajh** [kevinchappell/formBuilder#1371]
### Description:
formRender action - clear does not work, it gives the following error: 'Uncaught TypeError: formRenderInstance is not a function' 

### Screenshot of error is attached
<img width="239" alt="image" src="https://user-images.githubusercontent.com/92713906/232304731-ddbb8732-467a-4525-9b1d-ee8baae194e8.png">

**Comment by flipdoubt** [comment]
Try `formRenderInstance.clear()`. The docs may be inaccurate.

**Comment by lucasnetau** [comment]
Thank you for the report. Documentation is incorrect.

You can use either:

`$('#render-container').formRender('clear')` or `formRenderInstance.clear()`
