### ISSUE TITLE
CSS classes for icons are too generic

### ISSUE THREAD

**Issue by TommiSalonen** [kevinchappell/formBuilder#1375]
### Environment Details:

 - formBuilder Version: 3.4.1
 - Browser: Chrome
 - OS: OSX

### Expected Behavior
Using plugin shouldn't mess with css too easily.

### Actual Behavior
Adding plugin messed up my css.
Especially the following selectors are far too generic:
[class^=\"icon-\"]:before,[class*=\" icon-\"]:before

### Steps to Reproduce
use any styles starting "icon-" on your project and add formbuilder as plugin.

**Comment by lucasnetau** [comment]
Your formBuilder version is very out of date. 3.4.1 was released March 3rd 2020, current release is 3.8.3 released 2 years after your version.

Conflict was resolved in 3.5.2 (August 24th 2020) https://github.com/kevinchappell/formBuilder/releases/tag/v3.5.2

**Comment by lucasnetau** [comment]
Fixed by https://github.com/kevinchappell/formBuilder/commit/1231aae178edad3dad8cdffb753020db3bc6a24c
