### ISSUE TITLE
Read Only form

### ISSUE THREAD

**Issue by NipunTulsian** [kevinchappell/formBuilder#1376]

**Comment by asimp51** [comment]
var formData = '[{"type":"text","label":"Full Name","subtype":"text","className":"form-control","name":"text-1476748004559"},{"type":"select","label":"Occupation","className":"form-control","name":"select-1476748006618","values":[{"label":"Street Sweeper","value":"option-1","selected":true},{"label":"Moth Man","value":"option-2"},{"label":"Chemist","value":"option-3"}]},{"type":"textarea","label":"Short Bio","rows":"5","className":"form-control","name":"textarea-1476748007461"}]';

    var formRenderOptions = { formData };
    var formRenderInstance = $('#fb-editor').formRender(formRenderOptions);



Hope this will help!
