### ISSUE TITLE
Rendering field values using XML

### ISSUE THREAD

**Issue by thewizster** [kevinchappell/formBuilder#138]
I found that I can place a value in a text field within XML like this.

`<field class="form-control text-input" label="Text Field" name="text-1460406285009" type="text" subtype="text" value="This is a test value">`

When this is rendered using form-render the value is loaded in the text box.

I was trying this with other field types but could not get them to behave the same way. Is there a way to do this for other field types?

**Comment by kevinchappell** [comment]
formRender would need to be modified to handle other field types. The reason this works for inline fields is they use a `value` attribute that gets generated with other attributes but fields like `<select>` and `<textarea>` handle their values differently from inline fields.

**Comment by thewizster** [comment]
Makes sense. Thanks for the clarification.
