### ISSUE TITLE
Ongoing Maintenance?

### ISSUE THREAD

**Issue by lucasnetau** [kevinchappell/formBuilder#1380]
@kevinchappell do you still plan on maintaining formBuilder or do you want assistance with maintenance? I am willing  to review/test PRs. 

I've had multiple PRs for bug fixes for over 9 months with no acknowledgement nor has there been any commits during that time period. Appreciate if you could take a look at them as they are bugs others in the community have encountered too.

**Comment by kevinchappell** [comment]
@lucasnetau that is a long time without a response, my apologies for the delay. I will review the PRs tomorrow. 

I could definitely use help maintaining formBuilder these days and will message you about being a maintainer. Thank you.

**Comment by lucasnetau** [comment]
No problems. Likely easiest way is to contact via LinkedIn (Links on https://blog.lucas.net.au/)

I've been experimenting with Jest (https://jestjs.io/) to provide test coverage for FormBuilder. While it has a long way to go to get full coverage it would be a nice addition to the CI and aid in testing PRs

**Comment by lucasnetau** [comment]
@kevinchappell a few more PRs are no open for your approval.

**Comment by kevinchappell** [comment]
@lucasnetau all non-dependabot PRs should all be merged @Jojoshua's Typescript PR merge. I would like to get [his Typescript PR](https://github.com/kevinchappell/formBuilder/pull/1284) merged but considering it's size I think we'll need a major version bump to avoid any regression. To be clear, I didn't find any regressions when i tested but I prefer to be cautious considering it's size.

regarding test coverage, formBuilder could definitely use some. I am familiar with jest but have never tested jQuery components with it.
