### ISSUE TITLE
Uncaught TypeError: fb.actions.getData is not a function

### ISSUE THREAD

**Issue by Repechinskyi** [kevinchappell/formBuilder#1383]
Hello. I can't solve the problem for several days now. When I create a multi form, I add pages, fields. I will keep everything. But when I want to change this form and have more than 2 pages, I get an error on the second element "Uncaught TypeError: fb.actions.getData is not a function".

I think that the problem is in the class instance for 2 elements, but the same situation when, for example, 6 elements, 1 and the last element work fine, but all the others do not - an error

But this functionality loads the form, that is, I see all the saved fields after creation, everything is fine. but I can't save. I tried to add/remove fields all exactly error. The error disappears when I remove the intermediate pages of the form.

//--------------------

    fbInstances.push($(".build-wrap").formBuilder(fbOptions));

    $(document).ready(function() {
        setTimeout(function() {
            $.each(setFormData, function(i, item) {

                if(fbInstances[i]) {
                    fbInstances[i].actions.setData(item);
                } else {
                    addPageLoading(item);
                }

            });
        }, 2000);
    });

  /***/
  
    function addPageLoading(data){
        if(data.length){
            fbOptions.formData = data;
        }else{
            fbOptions.formData = [];
        }
        fbInstances.push($(newPage).formBuilder(fbOptions));
    }
    
    
        $(document.getElementById("getJSON")).click(function () {

        const allData = fbInstances.map((fb) => {
            var json = fb.actions.getData('json', true);
            return json;
        });
        $("input[name='json']").val("["+allData+"]");
        $("#design-form").submit();
   
    });

**Comment by Repechinskyi** [comment]
@lucasnetau 

Hello. Thank you for giving a hint, which helped partially, but now I have encountered another problem in the form, the fields are displayed correctly, but when I want to get data from the form in json format, I have the same code on page 2 and 3. I've been struggling with this code for several days, I don't know what to do anymore.

I have 3 pages now:
1 - Text field
2 - Date field
3 - Header fields

These fields in the form will visually display correctly. There is no error with "actions.getData" now, but when I view the result var json = fb.actions.getData('json', true); then I get

1 - Text field
2 - Header fields
3 - Header fields

After the first it is duplicated


`document.addEventListener('DOMContentLoaded', async function() {
	jQuery( function ($) {

		 var fbOptions = {...};

		 fbInstances.push($(".build-wrap").formBuilder(fbOptions));

	     setTimeout(function() {
	        $.each(setFormData, function(i, item) {

	            if(fbInstances[i]) {
	                fbInstances[i].actions.setData(item);
	            } else {
	                addPageLoading(item);
	            }
	        });
	    }, 2000);

	    // add pages form 
        async function addPageLoading(data){
	        console.log('addPageLoading')
	        const tabCount = document.getElementById("tabs").children.length;
	        const tabId = "page" + tabCount.toString();
	        const newPageTemplate = document.getElementById("new-page");
	        const newTabTemplate = document.getElementById("add-page-tab");
	        const newPage = newPageTemplate.cloneNode(true);
	        newPage.setAttribute("id", tabId);
	        newPage.classList.add("build-wrap");
	        const $newTab = newTabTemplate.cloneNode(true);
	        $newTab.removeAttribute("id");
	        const tabLink = $newTab.querySelector("a");
	        tabLink.setAttribute("href", "#" + tabId);
	        tabLink.innerText = "Page " + tabCount;
	        $newTab.append($("<a class='remove-page' data-id="+tabCount+">X</a>")[0])

	        newPageTemplate.parentElement.insertBefore(newPage, newPageTemplate);
	        newTabTemplate.parentElement.insertBefore($newTab, newTabTemplate);


	        fbPages.tabs("refresh");
	        fbPages.tabs("option", "active", tabCount - 1);


	        if(data.length){
	            fbOptions.formData = data;
	        }else{
	            fbOptions.formData = [];
	        }

	        var formBuilder_load = await $(newPage).formBuilder(fbOptions).promise;
	        fbInstances.push(formBuilder_load);

   	 	}	


 		// Get JSON and send form
	    $(document.getElementById("getJSON")).click(function () {

	        const allData = fbInstances.map((fb) => {
	            var json = fb.actions.getData('json', true);
	            return json;
	        });
	        $("input[name='json']").val("["+allData+"]");
	        $("#design-form").submit();
	       
	    });

    });
});`

**Comment by lucasnetau** [comment]
Can you provide a single html page to replicate your issue? 

The first initialisation of formBuilder you are not waiting for the promise to resolve, this will likely mean actions is initialised incorrectly.

`fbInstances.push($(".build-wrap").formBuilder(fbOptions));`

**Comment by Repechinskyi** [comment]
> Can you provide a single html page to replicate your issue?
> 
> The first initialisation of formBuilder you are not waiting for the promise to resolve, this will likely mean actions is initialised incorrectly.
> 
> `fbInstances.push($(".build-wrap").formBuilder(fbOptions));`

Hello. Thank you for your reply. Can I send you an archive with the code?

**Comment by lucasnetau** [comment]
Sure, are you able to share via GitHub gist or codepen.io setup with the code?

**Comment by ashotpamb** [comment]
Hi i have fixed this issue using async functions 
      async function initializeFormBuilder() {
            return new Promise(async (resolve, reject) => {
                formBuilder = await getFormBuilder();
                resolve(formBuilder);
            });
        }

        function sleep(ms) {
            return new Promise(resolve => setTimeout(resolve, ms));
        }
                async function processFields() {
            try {
                const fieldsData = await fetchSomeFields(modelId);
                const formBuilder = await initializeFormBuilder();

                if (fieldsData && fieldsData.data.fields) {
                    var data = JSON.parse(fieldsData.data.fields);
                    const jsonString = JSON.stringify(data, (key, value) => {
                        if (value === 'true') return true;
                        if (value === 'false') return false;
                        return value; 
                    }, 2);
                    await sleep(1000)
                    formBuilder.actions.setData(JSON.parse(jsonString));
                } else {
                    const formBuilder = await initializeFormBuilder(true);

                    console.log('Fields data is null or undefined.');
                }
            } catch (error) {
                console.error('Error initializing formBuilder:', error);
            }
        }
        await sleep(1000)
        there was such a problem but I solved it this way

**Comment by lucasnetau** [comment]
@Repechinskyi were you able to resolve your issue or come up with a reproduction?

**Comment by lucasnetau** [comment]
Closing this question as answer has been provided.
