### ISSUE TITLE
#Field size option included

### ISSUE THREAD

**Issue by samparkjaiswal** [kevinchappell/formBuilder#1386]
### Description:

Subject- Regarding Filed Size option when we edit filed attributes

in form builder , i am not found and filed size option for edit field size [small,medium,large]
can u please help me regarding this ?

**Comment by lucasnetau** [comment]
Can you please follow the new issue template and explain your issue. I am uncertain as to what you are asking.

**Comment by kevinchappell** [comment]
this seems a little out of scope. sizing should be depending on your css framework.
https://codepen.io/kevinchappell/pen/GRPwmyP
