### ISSUE TITLE
Question - Support with multi page feature

### ISSUE THREAD

**Issue by ThangPk** [kevinchappell/formBuilder#139]
Hello,

Can we support with multi pages feature in the future? Thanks you.

**Comment by kevinchappell** [comment]
Possibly, though it shouldn't be too difficult to add a wrapper in your app to make this happen now. Would something like this work for your needs? http://codepen.io/kevinchappell/pen/BKYPRp?editors=1010

**Comment by mvanvu** [comment]
@kevinchappell Good Idea. Hope it will come soon. One more, how about validation rules ?
Thank you.

**Comment by kevinchappell** [comment]
Next version has full support for constraint validation api as well as ability to add custom validators through formBuilder fields api.
