### ISSUE TITLE
typeUserAttrs checkbox label does not use i18n value

### ISSUE THREAD

**Issue by mtthwprtchrd** [kevinchappell/formBuilder#1391]
### Description:
When adding a readonly checkbox attribute to a text field the label does not use the value specified in the i18n structure whereas the name attribute of a text field will use the i18n value.

### Environment Details:

 - formBuilder Version: 3.8.2
 - Browser: Chrome 115.0.5790.171 (Official Build) (64-bit)
 - OS: Windows 10

### Expected Behavior
A typeUserAttrs checkbox sub-type should retrieve it's label from the i18n structure.

### Actual Behavior
A typeUserAttrs checkbox sub-type retrieves it's label from the i18n structure.

### Steps to Reproduce
Single page repro.

Drag a text field onto the form builder
Edit the component
The name attribute is renamed to Field Id from the i18n structure
The Read-only field takes its label from the attribute name instead of the i18n structure.

See this code pen https://codepen.io/Matthew-Pritchard/pen/KKbPbxQ for a repro of the problem (adapted from the original  i18n sample https://codepen.io/kevinchappell/pen/EMqvbG)

**Comment by lucasnetau** [comment]
Hi @mtthwprtchrd please give PR https://github.com/kevinchappell/formBuilder/pull/1392 a go, it should resolve your issue.

Also note that in your codepen `type: 'check-box'` should be `type: 'checkbox'` without the hyphen

**Comment by mtthwprtchrd** [comment]
Hi @lucasnetau Thank you very much for the quick response. Your PR #1392 resolves my issue. Thanks again.

Thanks, the "check-box" was just a typo.
