### ISSUE TITLE
FormBuilder 2.0 Demo

### ISSUE THREAD

**Issue by Krato** [kevinchappell/formBuilder#140]
Hi, there is some way to try new 2.0 version?

Will be great to take a preview of new features.

Thanks

**Comment by kevinchappell** [comment]
Hi Krato,
It has a little way to go before making it public but it will be available is an alpha version for preview. Bugs can be expected in this version as a lot has changed. I've been meaning to publish a full feature list and should get to that this week. I'll make it available on the website.

**Comment by Krato** [comment]
@kevinchappell ok. WIll keep our eyes in it. Thanks!

**Comment by jmls** [comment]
I would be interested in taking it for a spin and giving feedback. Is there a feature list / changelog around for 2.0 ?

**Comment by Krato** [comment]
Sure! I can take a preview and give you feedback about it. I'm now developing a Laravel package with this plugin.

**Comment by jmls** [comment]
any news ?

**Comment by kevinchappell** [comment]
I know its been a while but thought I should update this issue. Complete feature list is still coming but the new version can be test driven here for now: [2.0](http://draggable.github.io/formeo/)

Please provide feedback to the new repository here: https://github.com/Draggable/formeo

**Comment by albu77** [comment]
FIrst look et V2 on Firefox, when I rearrange the form element in the list on the right put the element in the form. It's ok with Chrome. On both browsersthe three icon of the element once on the form (delete, edit and move) only appear when the mouse hover the move icon not the whole icons area.
I think the user first should be considered, for example for the select, a normal user should be able to set the options directly so the order would be better options and afeter Attrs.
Regards
Alain

**Comment by kevinchappell** [comment]
@albu77 Thanks for the feedback. I see what you mean about how rearranging the elements appends a field. In FireFox the click action is handled differently, I've created an issue for that bug [here](https://github.com/Draggable/formeo/issues/2)

The field edit buttons are initially hidden on purpose with only the handle always being available however this may change or become an option.

Field edit panel order is configurable :)
