### ISSUE TITLE
Not able to change language

### ISSUE THREAD

**Issue by bourk94** [kevinchappell/formBuilder#1404]
Maybe I am dumb, but I tried 100 different things and I can't change the language to fr-FR

**Comment by lucasnetau** [comment]
What have you tried? It is always good to provide code examples.

You can find the documentation on changing the language here https://formbuilder.online/docs/formBuilder/demos/translation/

You will need to download the fr-FR language file https://github.com/kevinchappell/formBuilder-languages and make it accessible. The use set the path to the language file with the i18n config variable https://formbuilder.online/docs/formBuilder/options/i18n/

```javascript
var options = {
  i18n: {
    locale: 'fr-FR'
    location: 'https://languagefile.url/directory/'
  }
};
$(container).formBuilder(options);
```

**Comment by lucasnetau** [comment]
Hi @bourk94 , can you please confirm if this resolved your issue?
