### ISSUE TITLE
Render

### ISSUE THREAD

**Issue by mreza98** [kevinchappell/formBuilder#1406]
Thank you for this great project!
I have a begginer  question about render function
I don't understand how it work
Can you please explain?

**Comment by lucasnetau** [comment]
Hi @mreza98 glad you like it.

You take your output from formBuilder and provide it to formRender generally on another page. Have you looked at the examples? https://formbuilder.online/docs/formRender/demos/preview-popup/ provides an example of the workflow, in this case producing a formRender preview when saving a formBuilder

**Comment by mreza98** [comment]
Thank you so much!

در تاریخ دوشنبه ۱۱ سپتامبر ۲۰۲۳،‏ ۱۱:۱۵ James Lucas <
***@***.***> نوشت:

**Comment by lucasnetau** [comment]
I will close this issue for now. If you encounter any issues in the future please open a new issue and provide code for reproduction
