### ISSUE TITLE
Save form into template 

### ISSUE THREAD

**Issue by umesh190690** [kevinchappell/formBuilder#141]
how to save ilding form into template ,so later it can be use

**Comment by kevinchappell** [comment]
@umesh190690 do you mean the actual form data or template data? Currently formBuilder is really for building templates.

**Comment by umesh190690** [comment]
dear.. i want to build a form and and save it into mysql database

**Comment by umesh190690** [comment]
actual form data

**Comment by kevinchappell** [comment]
@umesh190690 There are so many ways this would be done, it really depends on your specific app/site. Form data itself would be saved the same as any normal form data received from a POST. Maybe something like this is what you mean? http://www.johnmorrisonline.com/how-to-insert-form-data-into-a-mysql-database-using-php/

If you are using a framework of any kind it will likely have its own best practices that should be followed.

**Comment by umesh190690** [comment]
ok dear thank you
