### ISSUE TITLE
Adding Autocomplete results to "t.querySelectorAll is not a function"

### ISSUE THREAD

**Issue by MaelStorm176** [kevinchappell/formBuilder#1420]
### Description:
When i simply add a new Autocomplete with Form Builder an error appears.

### Environment Details:

 - formBuilder Version: 3.10.0
 - Browser: Mozilla
 - OS: Windows 10

### Actual Behavior
t.querySelectorAll is not a function

### Steps to Reproduce
- In Form Builder click on "Autocomplete" to add a new autocomplete

### Screenshot - *(optional)*

![image](https://github.com/kevinchappell/formBuilder/assets/57861637/f7d8a4be-ac61-4a81-a65f-6ab4473648cf)

**Comment by lucasnetau** [comment]
@MaelStorm176 , thank you for you report. Can reproduce locally, will prepare a fix
