### ISSUE TITLE
Row and columns

### ISSUE THREAD

**Issue by ilariotr68** [kevinchappell/formBuilder#1427]
Hello, is it possible to insert rows with different columns in the form?

**Comment by lucasnetau** [comment]
Please take a look at the documentation here https://formbuilder.online/docs/formBuilder/demos/bootstrap-grid/

**Comment by ilariotr68** [comment]
Hi, I saw but unfortunately the system always puts a div before each field, making the column class useless, I attach an example:

<div class="rendered-form"><div class="formbuilder-text form-group field-text-1695905111801-0 col-md-6"><label for="text-1695905111801-0" class="formbuilder-text-label">Text Field</label><input type="text" class="form-control" name="text-1695905111801-0" id="text-1695905111801-0"></div><div class="formbuilder-select form-group field-select-1695905122088-0 col-md-6"><label for="select-1695905122088-0" class="formbuilder-select-label">Select</label><select class="form-control" name="select-1695905122088-0" id="select-1695905122088-0"><option value="option-1" selected="selected" id="select-1695905122088-0-0">Option 1</option><option value="option-2" id="select-1695905122088-0-1">Option 2</option><option value="option-3" id="select-1695905122088-0-2">Option 3</option></select></div></div>

**Comment by lucasnetau** [comment]
Can you please provide screenshots and also the output of your formBuilder formData for what you believe is incorrect?

Please see this screenshot of the columns in action.

<img width="1702" alt="image" src="https://github.com/kevinchappell/formBuilder/assets/9331242/4cbf8158-faa8-42bb-8a8e-45dc4ea15715">

**Comment by ilariotr68** [comment]
Here are the requested screenshots

![Immagine 2023-10-03 083110](https://github.com/kevinchappell/formBuilder/assets/5508052/41a69f9c-f1aa-4d9f-a75a-6ea7a3cca141)
![Immagine 2023-10-03 083140](https://github.com/kevinchappell/formBuilder/assets/5508052/35d8ddfc-6881-435b-ba33-5226bb6ca635)
![Immagine 2023-10-03 083126](https://github.com/kevinchappell/formBuilder/assets/5508052/49c3cf04-d79c-424d-b59d-57a1ddabcc7b)

**Comment by lucasnetau** [comment]
formRender correctly renders this as one row and two columns.

<img width="1008" alt="image" src="https://github.com/kevinchappell/formBuilder/assets/9331242/d7c0db05-e336-4f0a-bbb5-398c3faabf69">

The formBuilder stage does not render the previews as columns.

**Comment by ilariotr68** [comment]
this is the html code generated by the renderform:

<div class="rendered-form">
	<div id="row-row-1" class="row">
		<div class="formbuilder-text form-group field-text-1695905111801-0 row-1 col-md-6">
			<label for="text-1695905111801-0" class="formbuilder-text-label">Text Field</label>
			<input type="text" class="form-control" name="text-1695905111801-0" id="text-1695905111801-0">
		</div>
	</div>
	<div id="row-row-1" class="row">
		<div class="formbuilder-select form-group field-select-1695905122088-0 row-1 col-md-6">
			<label for="select-1695905122088-0" class="formbuilder-select-label">Select</label>
			<select class="form-control" name="select-1695905122088-0" id="select-1695905122088-0">
				<option value="option-1" selected="selected" id="select-1695905122088-0-0">Option 1</option>
				<option value="option-2" id="select-1695905122088-0-1">Option 2</option>
				<option value="option-3" id="select-1695905122088-0-2">Option 3</option>
			</select>
		</div>
	</div>
</div>

as you can see there are two divs with the row class, how do I put the two fields on a single line?

thanks for our help :)

**Comment by lucasnetau** [comment]
Hi, you are only pasting text so that's impossible to see what is going on with the HTML.

I realised I forgot to ask if you have included Bootstrap CSS into your page? Something like this?!

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

**Comment by ilariotr68** [comment]
this is a complete html code:

<html>
<head>
<link href=" https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css " rel="stylesheet">
</head>
<body>

<div class="rendered-form">
	<div id="row-row-1" class="row">
		<div class="formbuilder-text form-group field-text-1695905111801-0 row-1 col-md-6">
			<label for="text-1695905111801-0" class="formbuilder-text-label">Text Field</label>
			<input type="text" class="form-control" name="text-1695905111801-0" id="text-1695905111801-0">
		</div>
	</div>
	<div id="row-row-1" class="row">
		<div class="formbuilder-select form-group field-select-1695905122088-0 row-1 col-md-6">
			<label for="select-1695905122088-0" class="formbuilder-select-label">Select</label>
			<select class="form-control" name="select-1695905122088-0" id="select-1695905122088-0">
				<option value="option-1" selected="selected" id="select-1695905122088-0-0">Option 1</option>
				<option value="option-2" id="select-1695905122088-0-1">Option 2</option>
				<option value="option-3" id="select-1695905122088-0-2">Option 3</option>
			</select>
		</div>
	</div>
</div>

</body>
</html>

**Comment by lucasnetau** [comment]
Hi @ilariotr68 , what you are attaching is just plain text saying Text Field, There is no HTML to be seen.

**Comment by ilariotr68** [comment]
`<html>
<head>
<link href=" https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css " rel="stylesheet">
</head>
<body>

<div class="rendered-form">
	<div id="row-row-1" class="row">
		<div class="formbuilder-text form-group field-text-1695905111801-0 row-1 col-md-6">
			<label for="text-1695905111801-0" class="formbuilder-text-label">Text Field</label>
			<input type="text" class="form-control" name="text-1695905111801-0" id="text-1695905111801-0">
		</div>
	</div>
	<div id="row-row-1" class="row">
		<div class="formbuilder-select form-group field-select-1695905122088-0 row-1 col-md-6">
			<label for="select-1695905122088-0" class="formbuilder-select-label">Select</label>
			<select class="form-control" name="select-1695905122088-0" id="select-1695905122088-0">
				<option value="option-1" selected="selected" id="select-1695905122088-0-0">Option 1</option>
				<option value="option-2" id="select-1695905122088-0-1">Option 2</option>
				<option value="option-3" id="select-1695905122088-0-2">Option 3</option>
			</select>
		</div>
	</div>
</div>

</body>
</html>
`

**Comment by lucasnetau** [comment]
@ilariotr68 I still cannot replicate you issue and your pasted HTML is still only text, no HTML

You can see here with enableEnhancedBootstrapGrid: true and the Bootstrap CSS included that formBuilder will render your fields as rows and columns

<img width="2333" alt="image" src="https://github.com/kevinchappell/formBuilder/assets/9331242/c869822f-251b-48f6-80f5-49af569e4469">

**Comment by ilariotr68** [comment]
The rendering is now correct, but if I take the html to use it on a page the two columns appear on two different lines... unfortunately I don't see a solution, thanks anyway for your help.

**Comment by lucasnetau** [comment]
I'm sorry, with the lack of html files or javascript files to reproduce your issue there is not much to go on here. The HTML is rendered correctly by formBuilder so as long as your page have the Bootstrap CSS loaded it will show fine, otherwise each will be on a new page.
