### ISSUE TITLE
Form builder setData

### ISSUE THREAD

**Issue by ashotpamb** [kevinchappell/formBuilder#1429]
### Description:

setData issue or incorrect instalation

#Issue

after getting json data from db and setting in builder all checkboxes have checked

### Environment Details:

 - formBuilder Version:3.10.6 
 - Browser:Chrome 
 - OS:Linux 

###Data from database 
![Screenshot from 2023-10-02 14-11-20](https://github.com/kevinchappell/formBuilder/assets/39556387/c47c4403-e0bf-4023-a657-cf2f623d4f35)

edit:857 [{"type":"text","required":"true","label":"First Name","placeholder":"Enter your first name","className":"form-control","name":"first-name","access":"true","subtype":"text"},{"type":"text","required":"true","label":"Last Name","placeholder":"Enter your last name","className":"form-control","name":"last-name","access":"true","subtype":"text"},{"type":"text","subtype":"email","required":"true","label":"Email","placeholder":"Enter your email","className":"form-control","name":"email","access":"true"},{"type":"number","required":"true","label":"Phone","placeholder":"Enter your phone","className":"form-control","name":"phone","access":"true"},{"type":"file","required":"false","label":"File Upload","className":"form-control","name":"file-1696240899150-0","access":"true","subtype":"file","multiple":"true"}]

### Code for init 

 var options = {
            disabledActionButtons: ['data'],
            disableFields: ['autocomplete', 'button', 'hidden', 'paragraph'],
            fields: [{
                label: "Email",
                type: "text",
                subtype: "email",
                icon: "✉"
            }],
            defaultFields: [{
                className: "form-control",
                label: "First Name",
                placeholder: "Enter your first name",
                name: "first-name",
                required: true,
                type: "text"
            }, {
                className: "form-control",
                label: "Last Name",
                placeholder: "Enter your last name",
                name: "last-name",
                required: true,
                type: "text"
            }, {
                className: "form-control",
                label: "Email",
                placeholder: "Enter your email",
                name: "email",
                required: true,
                type: "text",
                subtype: "email"
            }, {
                className: "form-control",
                label: "Phone",
                placeholder: "Enter your phone",
                name: "phone",
                required: true,
                type: "number"
            }]

        }

        function getFormBuilder(initState) {
            
            return $(document.getElementById('fb-editor')).formBuilder(options);
        }

        async function initializeFormBuilder() {
            return new Promise(async (resolve, reject) => {
                formBuilder = await getFormBuilder();
                resolve(formBuilder);
            });
        }

        function sleep(ms) {
            return new Promise(resolve => setTimeout(resolve, ms));
        }

        async function processFields() {
            try {
                const fieldsData = await fetchSomeFields(modelId);
                const formBuilder = await initializeFormBuilder();

                if (fieldsData && fieldsData.data.fields) {
                    await sleep(1000)
                    formBuilder.actions.setData(JSON.parse(fieldsData.data.fields));
                } else {
                    const formBuilder = await initializeFormBuilder(true);

                    console.log('Fields data is null or undefined.');
                }
            } catch (error) {
                console.error('Error initializing formBuilder:', error);
            }
        }

**Comment by lucasnetau** [comment]
Can you please provide the data you are sending to setData, ? There are no checkboxes in your example or screenshots

**Comment by ashotpamb** [comment]
[{"type":"text","required":"true","label":"First Name","placeholder":"Enter your first name","className":"form-control","name":"first-name","access":"true","subtype":"text"},{"type":"text","required":"true","label":"Last Name","placeholder":"Enter your last name","className":"form-control","name":"last-name","access":"true","subtype":"text"},{"type":"text","subtype":"email","required":"true","label":"Email","placeholder":"Enter your email","className":"form-control","name":"email","access":"true"},{"type":"number","required":"true","label":"Phone","placeholder":"Enter your phone","className":"form-control","name":"phone","access":"true"},{"type":"file","required":"false","label":"File Upload","className":"form-control","name":"file-1696240899150-0","access":"true","subtype":"file","multiple":"true"}]

This is json data 

![Screenshot from 2023-10-02 14-11-20](https://github.com/kevinchappell/formBuilder/assets/39556387/d72a4565-f6ed-4b16-8d7f-aa4ce8fa626f)

{"type":"file","required":"false","label":"File Upload","className":"form-control","name":"file-1696240899150-0","access":"true","subtype":"file","multiple":"true"}]

this json is for file uploader required is false but after setting data automatically required checkbox have checked

**Comment by ashotpamb** [comment]
![Uploading Screenshot from 2023-10-02 14-34-32.png…]()

**Comment by ashotpamb** [comment]
![Screenshot from 2023-10-02 14-34-32](https://github.com/kevinchappell/formBuilder/assets/39556387/d860b4e0-24f4-4fdc-9174-d56032664bf4)

All checkboxes have checked

**Comment by lucasnetau** [comment]
"required":"false",

This is a string with the value false rather than a Boolean value false. Can you please adjust to a Boolean and see if this resolves your issue.

**Comment by ashotpamb** [comment]
Oh its work thanks))
