### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by orionrush** [kevinchappell/formBuilder#143]
What licence are you releasing this under?
It looks great!

**Comment by kevinchappell** [comment]
Thanks, license is [GNU GPL] (http://formbuilder.readthedocs.io/en/latest/license/)

**Comment by kevinchappell** [comment]
Thanks, license is [GNU GPL] (http://formbuilder.readthedocs.io/en/latest/license/)

**Comment by jmls** [comment]
ah, bummer. Are you using the same licence for 2.0 ? We're simply not allowed to use any GPL javascript lib :(

**Comment by kevinchappell** [comment]
no, 2.0 will be MIT license. I'd like formBuilder to be usable by anyone that needs it.

**Comment by jmls** [comment]
great news! thanks very much. Is there anywhere I could get hold of 2.0 to start playing with it ?

**Comment by kevinchappell** [comment]
Sorry, not yet. I wanted to hold off on putting it out there until I'm ready to address the bugs and questions the alpha release will generate.

**Comment by ivuorinen** [comment]
Should this be closed now as the [license has been changed to MIT](https://github.com/kevinchappell/formBuilder/commit/d3c809bcae2d5984bb059d52341e0fe8e14dab48)?

**Comment by kevinchappell** [comment]
absolutely. thanks @ivuorinen
