### ISSUE TITLE
filling in and submitting form and showing the values as default

### ISSUE THREAD

**Issue by maatata** [kevinchappell/formBuilder#144]
Hiya,

I have recently been looking at your perfect form builder plugin. Well done to you it's a really good plugin.

When I was playing up with the plugin I could not find how I can pre-fill in the form created by the values submitted.

Imagine I create a form. I then render the form for user to fill it in. The user fill in the form and submit. I would like to show the values he has entered to be shown back to him as pre-filled type thing.

I managed to get this working by myself though but I was wondering if this functionality is currently available in your fabulous plugin?

If not I am happy to commit my change to your plugin so it would be available for everyone.

Thanks guys.

**Comment by kevinchappell** [comment]
Currently no. This is something I've considered back-porting from the next version but if you have it working already please feel free to open a pull request. 

formBuilder was originally designed as a template only solution but saving values has been a popular request for a while now and I'm sure we'd love to see your implementation.

**Comment by maatata** [comment]
Hi Kevin

I just make a pull request. Please review.

Thanks mate

**Comment by kevinchappell** [comment]
Checking it out now. Looks good so far. going to test it before merging.

**Comment by maatata** [comment]
Sorry mate just made another commit to fix a small bug with text area default values.

**Comment by kevinchappell** [comment]
@maatata I just closed the PR as I was not able to get it running properly but I'm pretty sure the issue should be solved. Field values can now be saved and will appear in the edit window also.
