### ISSUE TITLE
How to do something after the 'onAddOption' event occurs?

### ISSUE THREAD

**Issue by khanh1808** [kevinchappell/formBuilder#1440]
### Description:
Hello, I'm trying to perform an action after the "onAddOption" event occurs. However, I can't find this trigger in the documentation. Have I missed something, or how can it be implemented? If this indeed doesn't exist, I hope it will be updated soon. This is really important to me.
I look forward to hearing from you.

Regards

### Environment Details:

 - formBuilder Version: 3.8.2

### Screenshot - *(optional)*
I need it to look like this:
![image](https://github.com/kevinchappell/formBuilder/assets/56547324/3c99e2ba-2901-48ab-884b-0f9239aa6790)

**Comment by lucasnetau** [comment]
What are you trying to perform? onAddOption is expecting you to return an option template.

https://formbuilder.online/docs/formBuilder/options/onAddOption/#onaddoption

Example
```javascript
onAddOption: (optionTemplate, optionIndex) => {
                    if (optionTemplate.label === "" && optionTemplate.value === "") {
                        //New option
                        optionTemplate.label = `Option ${optionIndex.index + 1}`
                        optionTemplate.value = `option-${optionIndex.index + 1}`
                    }
                    return optionTemplate
                }
```
