### ISSUE TITLE
Disable Button field once dragged into Form and Re-enable after removing form the Form

### ISSUE THREAD

**Issue by FARAZFRANK** [kevinchappell/formBuilder#1445]
### Description
Once a button field is added using drag and drop into the form, want to disable the button in the fields list.
And if the user removes the button field I want to re-enable the button into the fields list.

### Environment Details:

 - formBuilder Version: Latest
 - Browser: Chrome
 - OS: Windows

### Expected Behavior
After dragging and dropping the button field into the form, I want the Button field should be disabled from the list.
If I removed the button field from the Form and then the Button field enabled again in the fields list.

### Actual Behavior
The button field is enabled once you add it to the form. So, you can add multiple buttons to the form. Which I don't want.

### Steps to Reproduce
Drag and drop button field

### Screenshot - *(optional)*
![Screenshot_1](https://github.com/kevinchappell/formBuilder/assets/1661793/c2bfcd86-20a0-4a74-91e3-6de2e46e3a91)

**Comment by lucasnetau** [comment]
Hook into the typeUserEvents for button and disable in onadd() and enable in onremove()

```javascript
        typeUserEvents: {
            button: {
                onadd: () => {
                    $('.input-control[data-type=button]').css('pointer-events', 'none');
                },
                onremove: () => {
                    $('.input-control[data-type=button]').css('pointer-events', '');
                },
            }
        }
```

**Comment by FARAZFRANK** [comment]
Thanks so much, @ivuorinen,  that worked for me.

I followed this approach:

```
jQuery(function($) {

	// Disable the button once it dragged or enable the button once it removed form Form
	const typeUserEventsConfig = {
		button: {
			onadd: () => {
				jQuery('.input-control[data-type=button]').css('pointer-events', 'none');
			},
			onremove: () => {
				jQuery('.input-control[data-type=button]').css('pointer-events', '');
			},
		}
	};
	
	// Initialize the form builder with the defined configuration
	const fbEditor = document.getElementById("build-wrap");
	const formBuilder = jQuery(fbEditor).formBuilder({
		disabledActionButtons: ['data', 'save'],
		disableFields: ['autocomplete', 'hidden'],
		controlOrder: [ 'header', 'paragraph', 'text', 'textarea', 'select', 'radio-group', 'checkbox-group', 'date', 'number', 'file', 'button'],
		disabledAttrs: [ 'access', 'multiple', 'other', 'toggle', 'inline' ],
		disabledSubtypes: {
			paragraph: ['address', 'blockquote', 'canvas', 'output'],
			button: ['button', 'reset'],
			textarea: ['tinymce', 'quill'],
		},
		typeUserEvents: typeUserEventsConfig, // Apply the configuration here
	});
});
```

**Comment by ivuorinen** [comment]
It seems thanks went to a wrong person this time, @lucasnetau should have the credit.

**Comment by FARAZFRANK** [comment]
Thanks @ivuorinen, my bad. Fixed it.
