### ISSUE TITLE
TypeError: $sortableFields.sortable is not a function

### ISSUE THREAD

**Issue by jmls** [kevinchappell/formBuilder#146]
trying this out for the first time (waiting for 2.0 beta with bated breath!) , but after I fire it all up, I get this error

```
angular.js:13540 TypeError: $sortableFields.sortable is not a function
    at new FormBuilder (https://mysite/bower_components/formBuilder/dist/form-builder.js:1464:21)
```
I removed the .min.js file from the dist folder to ensure I loaded the unminified version

Am I missing some dependency ?

**Comment by jmls** [comment]
ah - yes - I am . Jquery-ui is needed. It is not listed as a dependency in bower.json

**Comment by kevinchappell** [comment]
Oh yeah, I should add that dependency

**Comment by kheengz** [comment]
@jmls thanks did work for me after add the jquery-ui
