### ISSUE TITLE
Getting This issue Running Form Builder . Previously this is working

### ISSUE THREAD

**Issue by shiv-manektech** [kevinchappell/formBuilder#1464]
Getting This issue Running Form Builder .
previously this is working
![image](https://github.com/kevinchappell/formBuilder/assets/91069210/398a1c92-2ace-462d-9fcd-eddf5f89b568)

**Comment by shiv-manektech** [comment]
[script.zip](https://github.com/kevinchappell/formBuilder/files/13071514/script.zip)
Hi uploaded my scripts yes i am adding custom control.
I have added icon like highlighted this has resolved my issue but UI is looking like below
![image](https://github.com/kevinchappell/formBuilder/assets/91069210/f5e22d78-b081-405d-a526-7763f9dbab83)
but in UI it is displaying like this
![image](https://github.com/kevinchappell/formBuilder/assets/91069210/eb83e271-8f19-4d72-8a0f-0ca803507de4)

**Comment by lucasnetau** [comment]
Thank you for your report. PR #1465 has been raised to resolve this issue. I have added your test case to the list of tests.
