### ISSUE TITLE
Need codepen example for closeAllFieldEdit

### ISSUE THREAD

**Issue by vinokumark** [kevinchappell/formBuilder#1467]
For formbuilder all action field have code pen example. But the https://formbuilder.online/docs/formBuilder/actions/closeAllFieldEdit/ no example. The code not working as expected.

I need to close the drag and drop field when user click close button and show preview.

    $(document).ready(function() {
      // Initialize formBuilder and store it in a variable
      const fbEditor = document.getElementById('build-wrap');
      const formData = JSON.stringify([
        {
          type: 'header',
          subtype: 'h1',
          label: 'Header',
        },
        {
          type: 'paragraph',
          subtype: 'p',
          label: 'Lots of text goes here',
        },
      ]);

      const formBuilder = $(fbEditor).formBuilder({ formData });

      // Add a click event handler for the button to close field editors
      $('#closeFieldEditorsButton').click(function() {
        formBuilder.actions.closeAllFieldEdit();
      });
    });

**Comment by lucasnetau** [comment]
Per documentation: closeAllFieldEdit() will programmatically close all field edit panels on the stage.

The example code you have provided works correctly, if you have a button with id closeFieldEditorsButton on your page.

By drag and drop field I assume you are talking about the stage. If you want to hide the stage you can do so by finding it by class '.frmb.stage-wrap' and setting display:none
