### ISSUE TITLE
How to save formbuilder form template not the form data.

### ISSUE THREAD

**Issue by krishanusa** [kevinchappell/formBuilder#147]
How to save formbuilder form template not the form data. am using asp.net c#

**Comment by kevinchappell** [comment]
This depends on your database. the simplest way is to save as longtext but that requires sanitizing and how the data is saved really depends on your app. Backend operations are really outside the scope of the current version of formBuilder.

**Comment by krishanusa** [comment]
On form builder default designed save button click I need to get the template, can you just help me out how to get that template  . hope this will fire save event in client side , but how to get the template design  in XML or json with in it. 
 $('.form-builder-save').click(function() {
   
  });

**Comment by zahedkamal87** [comment]
yeah.. how to get the form's template's codes and how to put them back and enable the elements to be drag and drop and editable?

**Comment by Caimilan** [comment]
A quick & dirty solution:
in form-builder.js near Line 2311 uncomment the following lines:
```
/*
var xmlButton = $(document.getElementById(frmbID + '-view-data'));
xmlButton.click(function (e) {
  e.preventDefault();
  var xml = _helpers.htmlEncode(elem.val()),
      code = _helpers.markup('code', xml, { className: 'xml' }),
      pre = _helpers.markup('pre', code);
  _helpers.dialog(pre, null, 'data-dialog');
});
*/
```
and insert this code:
```
$('#YorSaveButton').click(function (e) {
	 e.preventDefault();
  	 var xml = _helpers.htmlEncode(elem.val());
  	 var html = _helpers.htmlEncode($('#rendered-form').html());
  	 $.ajax({
        url : 'path/to/your/AjaxFile.php',
        dataType : "JSON",
        data :  {'html':html, 'xml':xml},
        type: 'POST',
        success: function(data){
    		// do something you want
		},
		error: function (error){
    		// do something you want
		}
    });
});
```
hope this helps someone

**Comment by kevinchappell** [comment]
Going to close this as it looks resolved but wanted to that you can also hook onto the save button or save event that is fired by the plugin.

**Comment by harsh-dev007** [comment]
and what about file how to postback to Server ??  need convert in binary something ?
