### ISSUE TITLE
Any Example To Bind Drop Down Values form API ?

### ISSUE THREAD

**Issue by shiv-manektech** [kevinchappell/formBuilder#1471]
Hi Team,

Do you have any example where i can bind dropdown values from api ?

**Comment by lucasnetau** [comment]
Please take a look at my example custom control repo. For the dropdown (select) you can hook into build() and dynamically load your options before the element is built.

https://github.com/lucasnetau/formBuilder-plugins/blob/main/plugins/customSelect.js
