### ISSUE TITLE
why can't use fineuploader ???

### ISSUE THREAD

**Issue by 24565** [kevinchappell/formBuilder#1473]
I am using "Fineuploader" but it has been unavailable since it was updated.|

https://fineuploader.com/

**Comment by lucasnetau** [comment]
Fineuploader was removed from v3.16.0 as the external library has been EOL for 5 years and it was discovered during automated testing that the CDN links to the version released in 2017 were no longer available (however I do note the CDN does have those version 5.14.2 available again)

The rational for removing it was in https://github.com/kevinchappell/formBuilder/pull/1451 

If you wish to use Fineuploader you can load it as a custom plugin
