### ISSUE TITLE
How to add maxtrix to form builder

### ISSUE THREAD

**Issue by trongsau96** [kevinchappell/formBuilder#148]
Hello,

I want to add more a function to create a maxtrix with form builder.
How can i do it.
Please help me.

Thank you so much!
![maxtrix](https://cloud.githubusercontent.com/assets/1767903/15040901/5c38030e-12e2-11e6-90c7-f17575d2c90a.JPG)

**Comment by kevinchappell** [comment]
I think this is a good idea. Could you accomplish this by adding multiple radio groups and then styling it with CSS?

**Comment by trongsau96** [comment]
Thank you so much!
I understood your idea. But i don't know where should i write my code to add more functions?
I want to drag and drop to create maxtrix.
![capture](https://cloud.githubusercontent.com/assets/1767903/15062016/21088b4e-1366-11e6-94e0-f82398b365e3.JPG)

**Comment by kevinchappell** [comment]
I see what you mean. This would take quite a bit of work but your custom field could essentially be a wrapper for multiple radio groups. In fact you could follow the pattern for `radio-group` field type as it and `checkbox-group` are really wrappers for calling multiple `checkbox`.

If you could hold off for another month on this feature it will be a lot easier to implement in version 2 of the plugin.

**Comment by trongsau96** [comment]
It's done. Here is my source code.
http://www.mediafire.com/download/lbbaessb3gdd9b2/form-builder.zip

Thanks for your support.

**Comment by kevinchappell** [comment]
Since you got your feature worked out I'm going to close this issue. Thanks for sharing your implementation.
