### ISSUE TITLE
How add personnel fields like sociel button

### ISSUE THREAD

**Issue by angelzeke** [kevinchappell/formBuilder#149]
I begin work add social button on form builder like facebook, twitter, google...
what is for you the best way for do that?
<img width="495" alt="capture d ecran 2016-05-10 a 16 25 26" src="https://cloud.githubusercontent.com/assets/179226/15150021/11258560-16cc-11e6-959f-6cd0778ac843.png">

**Comment by angelzeke** [comment]
<img width="498" alt="capture d ecran 2016-05-19 a 11 05 56" src="https://cloud.githubusercontent.com/assets/179226/15388351/d67a5034-1db1-11e6-9bcc-d0ab7ed6e73e.png">
<img width="506" alt="capture d ecran 2016-05-19 a 11 06 10" src="https://cloud.githubusercontent.com/assets/179226/15388350/d67972d6-1db1-11e6-892c-7da0733f78eb.png">

**Comment by kevinchappell** [comment]
Looking good! Checkbox group would be the best type to modify as you could set values to be the generated link.

**Comment by angelzeke** [comment]
Next step , i would add select for each service, user could select his account to generate the social button

**Comment by angelzeke** [comment]
<img width="508" alt="capture d ecran 2016-05-19 a 12 50 52" src="https://cloud.githubusercontent.com/assets/179226/15391227/5d27d62a-1dc0-11e6-92f9-a36c6eade6d3.png">
Do the same with input text and subtype email

**Comment by angelzeke** [comment]
i would like to now the best way to implement my code based on Version: 1.9.27 to profit other user and have the last release. Can send you my code if you want

**Comment by kevinchappell** [comment]
How did you make out on this feature?

**Comment by kevinchappell** [comment]
Looks like you made pretty good progress.
