### ISSUE TITLE
same data in multiple instances (tabs)

### ISSUE THREAD

**Issue by Vikash861** [kevinchappell/formBuilder#1493]
### Description:
I have problem in form builder same data is coming after updation in between tabs. For example: tab 7 and 8 has and 19 and 20 has same data.

### Environment Details:

 - formBuilder Version: 3.7.2
 - Browser: Chrome
 - OS: ubuntu

### Expected Behavior
After submitting the when I open forms again tabs should have their data
### Actual Behavior
After submitting the when I open forms again tabs has different data. For example tab 19 has tab 20 data and tab 20 also has tab 20 data
### Screenshot - *(optional)*
![Screenshot from 2023-12-30 15-56-56](https://github.com/kevinchappell/formBuilder/assets/73531710/ba76ca2b-5e36-47aa-b7c3-79c070317d48)

**Comment by lucasnetau** [comment]
Please update to the most recent version and verify that the issue still exists. 

Current release is 3.17.3

**Comment by Vikash861** [comment]
Thanks, I will try

**Comment by kevinchappell** [comment]
Also if the issue persists can you create a codepen (or similar) demonstrating the problem?

**Comment by Vikash861** [comment]
solution worked, thanks for helping out.
