### ISSUE TITLE
I want to add data attribute for every field of form builder is it possible? If yes then how to do that?

### ISSUE THREAD

**Issue by 25dhara** [kevinchappell/formBuilder#1496]
### Environment Details:

 - formBuilder Version: 
 - Browser: 
 - OS:

**Comment by lucasnetau** [comment]
Please read the documentation for typeUserAttrs config option on how to add an Attribute for all controls

**Comment by kevinchappell** [comment]
@25dhara here is an example: https://codepen.io/kevinchappell/pen/VwRKNbq

```javascript
  const container = document.getElementById('build-wrap');
  const typeUserAttrs = {
    '*': {
      'data-title': {
        label: 'Data Attribute',
        value: 'Data value'
      }
    }
  };

  const options = { typeUserAttrs };
  $(container).formBuilder(options);
```

which renders:
![image](https://github.com/kevinchappell/formBuilder/assets/1457540/22f681a2-e4ad-472a-9ac1-e4629a5c0709)

**Comment by 1995ankita** [comment]
@kevinchappell @lucasnetau how to set this attribute while setdata???

**Comment by 1995ankita** [comment]
> @kevinchappell @lucasnetau how to set this attribute while setdata??? 

is this possible??
