### ISSUE TITLE
How to hide options for a custom plugin?

### ISSUE THREAD

**Issue by dineshck** [kevinchappell/formBuilder#1497]
### Question: how to hide options or disable attributes for a custom plugin , for example we can hide options using 
disabledAttrs: ['placeholder', 'description', 'required', 'access', 'maxlength',  'rows'], 
### Environment Details:

 - formBuilder Version: 
 - Browser: 
 - OS: 

### Screenshot - *(optional)*
![plugin-option](https://github.com/kevinchappell/formBuilder/assets/34182009/0e501e2c-7434-44d8-8c9f-a8487f243ce9)

**Comment by lucasnetau** [comment]
HI @dineshck typeUserDisabledAttrs is the config option you are looking for 

https://formbuilder.online/docs/formBuilder/options/typeUserDisabledAttrs/

```javascript
typeUserDisabledAttrs: {
    'plugin-name': [
      'placeholder', 'description', 'required', 'access', 'maxlength', 'rows'
    ]
  }
```

It might be good if plugins can define default attributes that should be disabled. Will take that on as an enhancement request

**Comment by dineshck** [comment]
@lucasnetau Thanks for the solution.  As you suggested it might be good if plugins can disable default attributes.
