### ISSUE TITLE
Slight bug in XML creation

### ISSUE THREAD

**Issue by dannycamps** [kevinchappell/formBuilder#15]
Hi Kevin,

Hope you are doing well.  Thank you for your continued work on this especially correcting some issues with the last release.

However, there is an error in your generated XML when creating RadioGroups (CheckboxGroups appear to be okay).

The XML generated for a RadioGroup is as follows:
`
<field name="radio-group-1445351957780" label="Did you enjoy the presentation and will you attend another one?" description="" required="true" type="radio-group"/>
			<option label="I like it and would attend.">1</option>
			<option label="I like it but would not attend.">2</option>
			<option label="I am indifferent to it.">3</option>
			<option label="I don't really care for it.">4</option>
		</field>`

Notice the starting field element is self-closing.  You need to remove the / at the end of the tag otherwise it is breaking as non-valid XML.

Just a heads up.

Thanks,
-Daniel

**Comment by kevinchappell** [comment]
@dannycamps good catch. PR #16 should fix this.
