### ISSUE TITLE
Paragraph and Header not showing full options ( default attributes).

### ISSUE THREAD

**Issue by dineshck** [kevinchappell/formBuilder#1502]
### Environment Details:

 - formBuilder Version: 
 - Browser: 
 - OS: 

### Expected Behavior

I should get all the options as in the second screenshot

### Screenshot - *(optional)*
![para_and_header](https://github.com/kevinchappell/formBuilder/assets/34182009/46a4f76b-3841-4141-968d-189eb4802631)
![p_h_full](https://github.com/kevinchappell/formBuilder/assets/34182009/0ea33e5b-8c32-4134-8a53-c6871a60b548)

**Comment by lucasnetau** [comment]
Please complete the issue template when opening issues. That includes Environment Details and Steps to reproduce including config. Without this information all support is just a guess.

A guess would be you have disabled those fields via `disabledAttrs` config option

<img width="795" alt="image" src="https://github.com/kevinchappell/formBuilder/assets/9331242/2cbf142e-7dfd-4ccd-85bd-cab333b65c30">

**Comment by dineshck** [comment]
Thanks for the reply.  I have traced the issue, it was a css issue, "subtype-wrap" class was styled with display none property.
