### ISSUE TITLE
checkbox is auto seleced when dragged and dropped, should be deselected initially when dragged and dropped

### ISSUE THREAD

**Issue by hidayathBR** [kevinchappell/formBuilder#1514]
checkbox is auto seleced when dragged and dropped, should be deselected initially when dragged and dropped

**Comment by lucasnetau** [comment]
@kevinchappell , thoughts on this one. Checkbox group currently defaults to selecting the first option on adding to stage. Radio group does not (and should not)

**Comment by hidayathBR** [comment]
basically the issue here is if i drag and drop the check box while building the form, its getting auto checked. Considering i have saved the form when the checkbox is selected. When i open the form render to save my data suppose i have deselected it and when i try and edit the form, the checkbox is still selected which should be deselected ( cause i had deselected it when saving my response for the 1st time).

**Comment by lucasnetau** [comment]
OK that's a different issue. Please provide you environment details per the Issue template.

Where does the issue occur? formBuilder or formRender?

**Comment by lucasnetau** [comment]
I've tracked this down to the sanitizer being overzealous when filtering the control definitions. A PR has been raised to correct the issue and should be in the next release. Thank you for your report.

**Comment by hidayathBR** [comment]
does this solve the checkbox related issue which is autochecked during creating the form ?
