### ISSUE TITLE
Checkboxes should not have default selected when userData present

### ISSUE THREAD

**Issue by hipy** [kevinchappell/formBuilder#1518]
Hi all,

I've noticed an issue with the checkbox group field. When userData exists, but is an empty array, the formrenderer checks the default value that was given in the formbuilder. Because of this, it is not possible to save a form where none of the checkboxes are checked, because on loading the formdata, it will automatically check the default value.

Steps to reproduce:

Setup a checkbox group with one or more default values:
![image](https://github.com/kevinchappell/formBuilder/assets/98886473/3949dd1e-3cef-41ce-b5d3-9422fe9e0bed)

In the formrenderer uncheck all checkboxes and submit, the json data will look like this:
![image](https://github.com/kevinchappell/formBuilder/assets/98886473/455c1d80-08ae-4a13-acb6-6dd70ed10ef8)

userData empty should suggest none are checked, but when we load the form data, we get this:
![image](https://github.com/kevinchappell/formBuilder/assets/98886473/b2daf79f-b4b1-4651-b268-bb3cf484496d)

Thanks for looking into this!

**Comment by lucasnetau** [comment]
Thank you for the report. This has been identified recently and a PR is awaiting merging

Fixed by: #1515

**Comment by lucasnetau** [comment]
Fixed in 3.19.1
