### ISSUE TITLE
Using radio buttons instead of a dropdown in edit mode

### ISSUE THREAD

**Issue by mtthwprtchrd** [kevinchappell/formBuilder#1519]
### Description:
I have created a custom control and am using @lucasnetau's [media control plugin](https://github.com/lucasnetau/formBuilder-plugin-media) sample as an example and can get the functionality I want using something like the below in the definition() function.

`'subtype': {
    label: 'Media Type', 
    options: {  
        'image': 'Image',  
        'video': 'Video',  
        'audio': 'Audio',
    },
},` 

However, what I would like is to be able to replace that dropdown and it's 3 options with 3 radio buttons operating as a mutually exclusive group.
I can get one radio button to show up using `type:'radio'` but as soon as I specify the `options` field a select dropdown is generated. Even specifying a radio-group just generates a select dropdown.

Is this possible?

Thanks

### Environment Details:

 - formBuilder Version: 3.9.9
 - Browser: Chrome 121
 - OS: Windows 11

**Comment by lucasnetau** [comment]
Hi @mtthwprtchrd there is nothing in the code to support generating a radio-group for field attributes in formBuilder.

Is there a reason for needing radio buttons instead of a dropdown? The stage space is limited.

**Comment by mtthwprtchrd** [comment]
Hi @lucasnetau Thanks for replying. The reason was purely cosmetic, we wanted to style the radio buttons with icons. However, the standard drop down provides us with the necessary functionality.

Thanks
Matt
