### ISSUE TITLE
form builder elements label issue.

### ISSUE THREAD

**Issue by hidayathBR** [kevinchappell/formBuilder#1529]
### Environment Details:

 - formBuilder Version: 3.17.3
 - Browser: 
 - OS: 

### Screenshot - *(optional)*
![image](https://github.com/kevinchappell/formBuilder/assets/153521501/a338cba3-290d-4928-8298-e36d6b84bc82)

**Comment by hidayathBR** [comment]
there is no label field itself in the Json when i give empty firld name.
[
  {
    "type": "radio-group",
    "name": "radio-group-1709290274821-0",
    "other": false,
    "values": [
      {
        "label": "Option 1",
        "value": "option-1",
        "selected": false
      },
      {
        "label": "Option 2",
        "value": "option-2",
        "selected": false
      },
      {
        "label": "Option 3",
        "value": "option-3",
        "selected": false
      }
    ]
  },
  {
    "type": "radio-group",
    "label": "Radio Group",
    "name": "radio-group-1709290333506-0",
    "other": false,
    "values": [
      {
        "label": "Option 1",
        "value": "option-1",
        "selected": false
      },
      {
        "label": "Option 2",
        "value": "option-2",
        "selected": false
      },
      {
        "label": "Option 3",
        "value": "option-3",
        "selected": false
      }
    ]
  }
]

**Comment by lucasnetau** [comment]
It is not generating a random label value, FormBuilder is showing the name of the field because you have set no label. This is so you can see locate fields easily in builder stage (especially for elements like Headers where the label is the whole element). In formRender this does not occur.
