### ISSUE TITLE
I am trying to print my form which has an HTML5 date picker, even if the format is dd-mm-yyyy after i initiate the print, the date is coming in reverse order, i.e., yyyy-mm-dd.

### ISSUE THREAD

**Issue by hidayathBR** [kevinchappell/formBuilder#1532]
### Environment Details:

 - formBuilder Version: 
 - Browser: 
 - OS: 

### Screenshot - *(optional)*
![image](https://github.com/kevinchappell/formBuilder/assets/153521501/ad02edfa-e7bc-4887-9c3c-80d5585d519e)
![image](https://github.com/kevinchappell/formBuilder/assets/153521501/66b44215-edb9-419b-b3be-d769464c4157)

**Comment by lucasnetau** [comment]
This is not really a formBuilder issue, you have the form elements per spec.

I would suggest creating a paragraph that only shows when in print view `@media print` and hide the date element in print view. Then attach an event listened to the date change event and update the paragraph with your formatted date.

You could do all of this with a custom control or override the control with a custom field definition and template, or just implement the event listeners in your post render code block

**Comment by lucasnetau** [comment]
Hi @hidayathBR did this work for your printing issue?

**Comment by kevinchappell** [comment]
closing as there are a couple workarounds posted and the issue seems outside the scope of formBuilder
