### ISSUE TITLE
TinyMCE fields don't load userData

### ISSUE THREAD

**Issue by TrueSpins** [kevinchappell/formBuilder#1535]
### Description:

formRender is able to both capture the form data and inject the data into the controls. This is useful if you want end users to be able to save their progress.

However, when injecting this data, TinyMCE fields do not show the userData contained within the JSON, but instead their original 'value' data. 

### Environment Details:

 - formBuilder Version: latest
 - Browser: all
 - OS: all

### Expected Behavior

When injecting JSON with userData present, formRender should load this data into the relevant fields. 

### Actual Behavior

For TinyMCE fields, userData is not rendered. Instead it displays the original value data for the field.

### Steps to Reproduce

Simply create a TinyMCE field with some default content. Load via formRender and update the field. Generate the JSON and then inject it back into formRender - the TinyMCE field will not load the userData content.

**Comment by lucasnetau** [comment]
Thank you. I can see the issue in the TinyMCE control plugin. A PR will be raised.
