### ISSUE TITLE
How to Store each component id save in database and retrieve id and back to editing phase

### ISSUE THREAD

**Issue by umesh190690** [kevinchappell/formBuilder#154]
how to store each component id or name in MySQL database and retrieve when editing the components again

**Comment by kevinchappell** [comment]
saving and retrieving data is really an application specific question and outside the scope of formBuilder. formBuilder is strictly a front-end tool, saving data is a backend process.

**Comment by umesh190690** [comment]
ok so any idea ..how it will done ?

**Comment by umesh190690** [comment]
ok so any idea ..how it will done ?
