### ISSUE TITLE
Error label value set data

### ISSUE THREAD

**Issue by Fharhanamrin** [kevinchappell/formBuilder#1540]
### Environment Details:

 - formBuilder Version: 
```
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/jquery-ui.min.js"></script>
    <script src="https://formbuilder.online/assets/js/form-builder.min.js"></script>
```
 
 - Browser: 
 crome version Version 122.0.6261.112 (Official Build) (x86_64)

 - OS: 
 mac intel

### Steps to Reproduce
```
 const fbEditor = document.getElementById("build-wrap");
    const templateSelect = document.getElementById("formTemplates");
    
    var fields = [{
            label: "Select",
            type: "select",
            subtype: "Select",
            icon: "✉",
            values: [{
                    label: "Label Indonesia",
                    value: "Label Inggris",
                    // selected: true
                },
                {
                    label: "",
                    value: "",
                },
                {
                    label: "",
                    value: "",
                }
            ]
        },
        {
            label: "FullName",
            type: "text",
            icon: "✉"
        }
    ];

    var options = {
        roles: {
            1: 'Form',
            2: 'Copy Data from Buyer',
            3: 'Urutan',
            4: 'Ticket Name'
        },
        replaceFields: [{
                type: "checkbox-group",
                label: "Checkbox",
                values: [{
                    label: "Label Indonesia",
                    value: "Label Inggris"
                }],
                icon: "☑"
            },
            {
                type: "radio-group",
                label: "Radio Group",
                values: [{
                    label: "Label Indonesia",
                    value: "Label Inggris"
                }],
                icon: "☑"
            }
        ],
        disableFields: [
            'autocomplete',
            'hidden',
            'number',
            'date',
            'paragraph',
            'select',
            'button'
        ],
        typeUserDisabledAttrs: {
            'text': [
                'name',
                // 'label',
                'subtype',
                // 'access',
                'helptext',
                // 'placeholder',
                'value',
                'maxlength',
                'description',
            ],
            'select': [
                'name',
                // 'label',
                'multiple',
                'class',
                'subtype',
                // 'access',
                'helptext',
                'placeholder',
                'value',
                'maxlength',
                'description',
            ],
            'checkbox-group': [
                'name',
                // 'label',
                'multiple',
                'class',
                'subtype',
                // 'access',
                'helptext',
                'placeholder',
                'value',
                'maxlength',
                'description',
                'toggle',
                'inline',
                'other'
                // 'options'
            ],
            'radio-group': [
                'name',
                'label',
                'multiple',
                'className',
                'subtype',
                // 'access',
                'helptext',
                'placeholder',
                'value',
                'maxlength',
                'description',
                'toggle',
                'inline',
                'other'
                // 'options'
            ],
            'file': [
                // 'label',
                'className',
                'name',
                'multiple',
                'class',
                // 'access',
                'description',
                // 'placeholder',
                'value'
            ],
            'header': [
                'label',
                'className',
                'name',
                'multiple',
                'class',
                // 'access',
                'description',
                'placeholder',
                'value'
            ]
        },
        typeUserAttrs: {
            '*': {
                lebel_id: {
                    label: 'Label Indonesia',
                    value: '',
                },
                label: {
                    label: 'Label Inggris',
                    value: '',
                },
            },
            // file: {
            //     roles: {
            //         1: 'Form',
            //         2: 'Copy Data from Buyer'
            //     },
            // },
            text: {
                className: {
                    label: 'Responsive Web Page',
                    options: {
                        'col-md-1 form-control': 'col-md-1',
                        'col-md-2 form-control': 'col-md-2',
                        'col-md-3 form-control': 'col-md-3',
                        'col-md-4 form-control': 'col-md-4',
                        'col-md-5 form-control': 'col-md-5',
                        'col-md-6 form-control': 'col-md-6',
                        'col-md-7 form-control': 'col-md-7',
                        'col-md-8 form-control': 'col-md-8',
                        'col-md-9 form-control': 'col-md-9',
                        'col-md-10 form-control': 'col-md-10',
                        'col-md-11 form-control': 'col-md-11',
                        'col-md-12 form-control': 'col-md-12',
                    },
                    style: 'border: 1px solid red'
                },
                roles: {
                    1: 'Form'
                },
                // x:true
            },
            select: {
                className: {
                    label: 'Responsive Web Page',
                    options: {
                        'col-md-1 form-control': 'col-md-1',
                        'col-md-2 form-control': 'col-md-2',
                        'col-md-3 form-control': 'col-md-3',
                        'col-md-4 form-control': 'col-md-4',
                        'col-md-5 form-control': 'col-md-5',
                        'col-md-6 form-control': 'col-md-6',
                        'col-md-7 form-control': 'col-md-7',
                        'col-md-8 form-control': 'col-md-8',
                        'col-md-9 form-control': 'col-md-9',
                        'col-md-10 form-control': 'col-md-10',
                        'col-md-11 form-control': 'col-md-11',
                        'col-md-12 form-control': 'col-md-12',
                    },
                    style: 'border: 1px solid red'
                },
                roles: {
                    1: 'Form'
                },

            },
            'checkbox-group': {
                roles: {
                    1: 'Form',
                    2: 'Copy Data from Buyer'
                },
                className: {
                    label: 'Responsive Web Page',
                    options: {
                        'col-md-1': 'col-md-1',
                        'col-md-2': 'col-md-2',
                        'col-md-3': 'col-md-3',
                        'col-md-4': 'col-md-4',
                        'col-md-5': 'col-md-5',
                        'col-md-6': 'col-md-6',
                        'col-md-7': 'col-md-7',
                        'col-md-8': 'col-md-8',
                        'col-md-9': 'col-md-9',
                        'col-md-10': 'col-md-10',
                        'col-md-11': 'col-md-11',
                        'col-md-12': 'col-md-12',
                    },
                    style: 'border: 1px solid red'
                }
            }
        },
        onSave: function(evt, formData) {
            console.log("formbuilder update saved");
            UpdatePostCustomForm(formBuilder.actions.getData());
            // console.log(JSON.stringify(formBuilder.actions.getData()));
        }
    };


    // const formBuilder = $(fbEditor).formBuilder();
    const formBuilder = $(fbEditor).formBuilder({
            ...options,
            fields
        });
```

data from api json
[{"type":"header","subtype":"h4","access":true,"lebel_id":"Peserta","label":"Participant"},{"type":"checkbox-group","required":false,"access":false,"lebel_id":"Salin Data dari Informasi Pembeli","label":"Label Inggris","className":"col-md-12","values":[{"label":"","value":"","selected":false}]},{"type":"text","required":true,"access":false,"lebel_id":"Nama Lengkap","label":"Full Name","className":"col-md-12 form-control"},{"type":"text","required":true,"access":false,"lebel_id":"Handphone","label":"Number Phone","className":"col-md-12 form-control"},{"type":"text","required":true,"access":false,"lebel_id":"Email","label":"Email","className":"col-md-12 form-control"},{"type":"text","required":true,"access":false,"lebel_id":"Jabatan","label":"Position","className":"col-md-12 form-control"},{"type":"text","required":true,"access":false,"lebel_id":"Nama Perusahaan","label":"Company Name","className":"col-md-12 form-control"},{"type":"text","required":true,"access":false,"lebel_id":"Alamat","label":"Address","className":"col-md-12 form-control"},{"type":"select","required":true,"access":false,"lebel_id":"Provinsi","label":"Province","className":"col-md-12 form-control","values":[{"label":"Not Selected","value":"Not Selected","selected":true},{"label":"","value":"","selected":false}]},{"type":"select","required":true,"access":false,"lebel_id":"Kota","label":"City","className":"col-md-12 form-control","values":[{"label":"Not Selected City","value":"Not Selected City","selected":true},{"label":"Option 2","value":"option-2","selected":false}]},{"type":"text","required":false,"access":false,"lebel_id":"Website","label":"Website","className":"col-md-12 form-control"},{"type":"checkbox-group","required":false,"access":false,"lebel_id":"Klasifikasi Pengunjung","label":"Who are you ?","className":"col-md-12","values":[{"label":"Supplier","value":"Supplier","selected":false},{"label":"Buyer","value":"Buyer","selected":false}]},{"type":"checkbox-group","required":true,"access":false,"lebel_id":"Industri Bisnis Anda","label":"What is Your Main Business Activity","className":"col-md-12","values":[{"label":"Food And Beverages","value":"Food And Beverages","selected":false},{"label":"Fashion, Bags, shoes and Accessories","value":"Fashion, Bags, shoes and Accessories","selected":false},{"label":"Furniture, Home Equipment and Handicraft","value":"Furniture, Home Equipment and Handicraft","selected":false},{"label":"Textiles and Leather Products","value":"Textiles and Leather Products","selected":false},{"label":"Sport and Entertainment","value":"Sport and Entertainment","selected":false},{"label":"Electronic","value":"Electronic","selected":false},{"label":"Business and Office Equipment","value":"Business and Office Equipment","selected":false},{"label":"Machines and Tools","value":"Machines and Tools","selected":false},{"label":"Product Materials ","value":"Product Materials ","selected":false},{"label":"Services","value":"Services","selected":false},{"label":"Automotive and Accessories","value":"Automotive and Accessories","selected":false},{"label":"others","value":"others","selected":true}]},{"type":"text","required":false,"access":true,"lebel_id":"Lainnya Industri Bisnis Anda","label":"Others What Is Your Main Business Activity","className":"col-md-12 form-control"},{"type":"checkbox-group","required":false,"access":false,"lebel_id":"Tujuan Datang Ke Pameran?","label":"Purposes of Joining inabuyerB2B2G Expo ?","className":"col-md-12","values":[{"label":"Gather Information","value":"Gather Information","selected":false},{"label":"To Seek Representation","value":"To Seek Representation","selected":false},{"label":"To Purchase","value":"To Purchase","selected":false},{"label":"Contact / Visit Supplier","value":"Contact/Visit Supplier","selected":false},{"label":"Research and Development ","value":"Research and Development ","selected":false},{"label":"To Evaluate Future Participation","value":"To Evaluate Future Participation","selected":false},{"label":"Marketing & Sales ","value":"Marketing & Sales ","selected":false},{"label":"others","value":"others","selected":false}]},{"type":"text","required":false,"access":true,"lebel_id":"Lainnya Tujuang Datang Ke Pameran?","label":"Other Purpose Of Joining","className":"col-md-12 form-control"},{"type":"text","required":false,"access":false,"lebel_id":"Produk apa yang sedang Anda butuhkan:","label":"What Product Do You Need?","className":"col-md-12 form-control"},{"type":"checkbox-group","required":false,"access":false,"lebel_id":"Apakah Anda Tertarik Untuk Mengikuti Business Matching","label":"Are you Interested in joining Business Matching","className":"col-md-12","values":[{"label":"Tidak","value":"No","selected":false},{"label":"Ya","value":"Yes","selected":false}]},{"type":"checkbox-group","required":false,"access":false,"lebel_id":"Darimana Anda mengetahui event Inabuyer B2B2G Expo 2024?","label":"How do you know about Inabuyer B2B2G Expo 2024?","className":"col-md-12","values":[{"label":"Instagram","value":"Instagram","selected":false},{"label":"Facebook","value":"Facebook","selected":false},{"label":"Berita Online","value":"Online News","selected":false},{"label":"Kolega/Rekan","value":"Friends/Collegues","selected":false},{"label":"Radio","value":"Radio","selected":false},{"label":"WhatsApp","value":"WhatsApp","selected":false},{"label":"Lainnya","value":"Others","selected":true}]},{"type":"text","required":false,"access":true,"lebel_id":"Lainnya Darimana Anda mengetahui event Inabuyer B2B2G Expo 2024?","label":"Others How do you know about Inabuyer B2B2G Expo 2024?","className":"col-md-12 form-control"}]
formBuilder.actions.setData(JSON.parse(response.data));

### Screenshot - *(optional)*
![image](https://github.com/kevinchappell/formBuilder/assets/27546921/eee9b314-d0d4-41f9-9b0f-cde1ea2cf531)

**Comment by Fharhanamrin** [comment]
I've edited is, sir🙏

Pada tanggal Kam, 14 Mar 2024 19.38, James Lucas ***@***.***>
menulis:

**Comment by lucasnetau** [comment]
Your configuration is very convoluted. You are disabling the built in label field with typeUserDisabledAttrs on some but not all controls, then you are re-defining label as a typeUserAttr of the same type just to change the label's text. 

Use the translation facility instead of disabling built in attributes and trying to override them.

This will achieve the same thing you are attempting with much less configuration changes
```javascript
i18n: {
                location: "https://raw.githubusercontent.com/kevinchappell/formBuilder-languages/master/",
                override: {
                    'en-US': {
                        label: 'Label Inggris',
                    }
                }
            },
```

**Comment by Fharhanamrin** [comment]
![image](https://github.com/kevinchappell/formBuilder/assets/27546921/037e1234-c5f3-4368-888a-e38da7f393be)

How do I change the position, sir, I'm very confused, so I guess we rewrite the code in typeUserAttrs? Can you give an example of changing the position of field2

**Comment by lucasnetau** [comment]
There is no ability to customise the positioning of attributes.

**Comment by kevinchappell** [comment]
As @lucasnetau mentioned it is not possible to position attributes in the editor however that may be a good future feature

**Comment by Fharhanamrin** [comment]
Thank you, sir
