### ISSUE TITLE
How To selected setData element select multiple

### ISSUE THREAD

**Issue by Fharhanamrin** [kevinchappell/formBuilder#1543]
### Environment Details:

 - formBuilder Version: 
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/jquery-ui.min.js"></script>
    <script src="https://formbuilder.online/assets/js/form-builder.min.js"></script>
 - Browser: 
   Crome
 - OS: 
   Mac/unix

### Screenshot - *(optional)*
![image](https://github.com/kevinchappell/formBuilder/assets/27546921/9412aad7-6313-41c9-ac3c-890ef2123f27)

I have saved the data, but when I edit it it doesn't select the last one I saved?

**Comment by lucasnetau** [comment]
Please provide a reproducible script. formBuilder options array and the formData you are passing to setData at a minimum.

Restoring multiple select controls is passing tests

<img width="479" alt="image" src="https://github.com/kevinchappell/formBuilder/assets/9331242/e4ba79ad-7a8f-4f2c-b554-ff52b953e7e6">

**Comment by lucasnetau** [comment]
Unable to replicate. No response
