### ISSUE TITLE
How to get HTML code in formBuilder using react

### ISSUE THREAD

**Issue by balajiwork** [kevinchappell/formBuilder#1545]
### Description:
we need to get Raw HTML code in FormBuilder in react js

How can we use Get HTML function in React JS

### Screenshot - *(optional)*
![Screenshot 2024-03-22 201030](https://github.com/kevinchappell/formBuilder/assets/90555395/eae3fb73-7c5b-47bb-bc94-ad08037b332e)

**Comment by kevinchappell** [comment]
@balajiwork im not sure this is a valid issue, the getHTML action seems to be working as expected. In the demo from your screenshot, the button will log the html string to the console when clicked. `getHTML` would function in a react app the same way as other JS apps.
