### ISSUE TITLE
Inline Controls

### ISSUE THREAD

**Issue by firewater** [kevinchappell/formBuilder#1549]
### Description:
First-time user of formBuilder here. Thanks for creating such a helpful library. Didn't see an obvious way to display controls line, meaning two or more controls placed next to each other instead of on top of each other. Wondering if it's possible. Thanks for your help.

### Environment Details:

 - formBuilder Version: latest
 - Browser: Google Chrome 121.0.6167.161
 - OS: Windows 10

### Expected Behavior
Drag and drop a control onto the page. Drag another control onto the page but drop it to the right or left of the first control. The second control now sits to the left or right of the first control.

### Actual Behavior
The second control sits above or below the first control.

**Comment by kevinchappell** [comment]
@firewater formBuilder currently only has support for inline controls from bootstrap grid.
https://formbuilder.online/docs/formBuilder/demos/bootstrap-grid/

If you set the `enableEnhancedBootstrapGrid` option to `true` you should be able to replicate the functionality in the [demo](https://kevinchappell.github.io/formBuilder/).


https://github.com/kevinchappell/formBuilder/assets/1457540/1efef564-16ab-4745-89fc-ac7bd7b1df3d
