### ISSUE TITLE
Group Control - Super Urgent, please advise.

### ISSUE THREAD

**Issue by rajindersinghugw** [kevinchappell/formBuilder#1552]
Right now, we can drag element individually, this is great.

Now i needed group control,  as a example... i will drag and drop text box and date filed in one group, that should be work as group not individual. 

I dont want to add manually, it should be drag and drop. 

Please let me know idea how i can do it in your script. 

Waiting your response.

Thank you

**Comment by rajindersinghugw** [comment]
@kevinchappell .. can you please advice, this is super urgent now. please help me.

**Comment by curala70** [comment]
@kevinchappell + 1

**Comment by lucasnetau** [comment]
https://formbuilder.online/docs/formBuilder/options/inputSets/ for drag and drop multiple controls.

FormBuilder does not currently support grouping controls together on the stage

**Comment by rajindersinghugw** [comment]
@lucasnetau  thank you for update.


1) I can not use input set because this is manually process to add element in group section. 
2) i can not see different between single element and group of elements in json format

We need a best drag drop options that will make group of set within container and keep same functionality that we have already exist. 

Let me know if you have method or key that can easy for us to complete this point. Please let me know your thoughts.


Thank you
