### ISSUE TITLE
Text Area Component allows input of negative value in the Rows field

### ISSUE THREAD

**Issue by breagol37** [kevinchappell/formBuilder#1555]
### Description:
When editing the Text Area component's Rows field will allow you to input negative values.

### Environment Details:

 - formBuilder Version: 3.19.7
 - Browser:  Chrome
 - OS: Windows

### Expected Behavior
The negative should be removed as the same behaviour in the Max Length field

### Actual Behavior
Negative does not get removed

### Steps to Reproduce
* Add a Text Area component to your form and select edit. 
* Either type or use the incrementation buttons to add a negative number under the Rows field.

**Comment by lucasnetau** [comment]
Thank you @breagol37 for your report. This patch will treat rows in the same way as maxlength. The function utils.forceNumber() is only used by the maxlength field and really is a force string to positive integer, I'll make a note to update that function signature

```patch
diff --git a/src/js/form-builder.js b/src/js/form-builder.js
index 1761fdf..120f403 100644
--- a/src/js/form-builder.js
+++ b/src/js/form-builder.js
@@ -1817,7 +1817,7 @@ function FormBuilder(opts, element, $) {
     }
   })
 
-  $stage.on('blur', 'input.fld-maxlength', e => {
+  $stage.on('blur', 'input.fld-maxlength, input.fld-rows', e => {
     e.target.value = forceNumber(e.target.value)
   })
 
diff --git a/src/sass/_stage.scss b/src/sass/_stage.scss
index abe31b2..382560f 100644
--- a/src/sass/_stage.scss
+++ b/src/sass/_stage.scss
@@ -656,7 +656,7 @@
         border: 1px solid $error;
       }
 
-      &.fld-maxlength {
+      &.fld-maxlength, &.fld-rows {
         width: 75px;
       }
```
