### ISSUE TITLE
How to custom label header ?

### ISSUE THREAD

**Issue by jobsrey** [kevinchappell/formBuilder#1559]
Hi, I'm confused about how to customize a label that takes data from an input label, from an image like this: 
![image](https://github.com/kevinchappell/formBuilder/assets/25948056/47c0b417-1c89-4d40-af33-b7528f0c7b3b)

to look like this:  
![image](https://github.com/kevinchappell/formBuilder/assets/25948056/81511426-5f7d-49fd-bb47-cf918c385c63)

Is there a solution to this issue? Thank you.

**Comment by kevinchappell** [comment]
@jobsrey that is strange, it should have shown up as a custom attribute. can you share the config that led to this? creating a sandbox or codepen will help diagnose the issue

**Comment by lucasnetau** [comment]
You'll want to look at the template override for label and append the custom attribute status to the label.

https://formbuilder.online/docs/formBuilder/overview/#customising-label-help-layouts
