### ISSUE TITLE
How can I render existing form fields?

### ISSUE THREAD

**Issue by codefullon** [kevinchappell/formBuilder#156]
I'm creating an option wherein the user can edit a form they've already created. Curious, what elements from the DOM do I need to save in order to re-render the form?

Here's what I tried:
As the user clicks on save, the app stores all elements under following selector: '#frmb-0' and in the edit mode, I append those elements back to 'frmb-0' but it does not render properly and things break. To make things consistent with the classname etc, I've assigned a static value to the 'epoch' variable (not sure if that helps)

Perhaps there's a simpler way to do this that I'm not aware of, would be awesome to get your guys's feedback on this

Cheers

**Comment by kevinchappell** [comment]
Do you have some example code in a jsfiddle or codepen you can share? There aaaaaaaaaarea  few ways of rendering formData:

popup
http://codepen.io/kevinchappell/pen/mPQMYZ

in container
http://codepen.io/kevinchappell/pen/bprXzw

**Comment by codefullon** [comment]
Thanks a lot Kevin, that solved it :)
