### ISSUE TITLE
Adding field type button - Label not set

### ISSUE THREAD

**Issue by kasperlau** [kevinchappell/formBuilder#1560]
When adding button field, using actions.addField.. The label submitted is not set in the textbox, only as the title.

`addField({
                "type": "button",
                "label": 'Submit 22',
                "className": "btn btn-primary",
                "style": "primary"
            }, undefined);`

![image](https://github.com/kevinchappell/formBuilder/assets/20812455/52a90461-1ef5-49b6-b734-89307855b235)

**Comment by kevinchappell** [comment]
can you share your config? i was not able to replicate this behavior.
![image](https://github.com/kevinchappell/formBuilder/assets/1457540/e24bf01b-a41e-43aa-a83a-5cfec046468b)
![image](https://github.com/kevinchappell/formBuilder/assets/1457540/e62c9ccc-e254-4f00-8dc2-40397d416c23)

**Comment by lucasnetau** [comment]
I am also unable to replicate the original report.

<img width="945" alt="image" src="https://github.com/kevinchappell/formBuilder/assets/9331242/8248a683-4000-4a42-a279-ec01180b8497">
