### ISSUE TITLE
Required Checkbox Group - Other with text box - not validating blank value

### ISSUE THREAD

**Issue by rawalprashant** [kevinchappell/formBuilder#1565]
### Description:
Required Checkbox Group - Other with a text box - not validating the blank value

### Environment Details:
 - formBuilder Version: 2.9.8
 - Browser: Chrome
 - OS: Windows

### Expected Behavior
When there is a required checkbox group and the 'other' option is selected then the text box should validate the blank value. 

### Actual Behavior
Right now it allows to save blank data when 'other' option is selected.

### Screenshot - *(optional)*
![image](https://github.com/kevinchappell/formBuilder/assets/405821/cf160d31-9bea-4bdd-93e9-fe75c716a7b9)

**Comment by lucasnetau** [comment]
Thank you for the report. I can reproduce. This patch will likely fix the issue https://github.com/kevinchappell/formBuilder/commit/ec01de97045038ce2a17579b3b44a6881c4e8e74

Radio-Group will also need to call groupRequired to ensure the value is not empty.
