### ISSUE TITLE
Form builder questions - Issue with data are not saving while edit/update the form builder questions

### ISSUE THREAD

**Issue by autoamation-2021** [kevinchappell/formBuilder#1566]
### Description:
We have integrated jquery form builder on our application for adding custom questions to the form.

**User Flow:**

1)We have public form(where user will submit the form).

2)Once user will submit the form, it will save in the backend application.

3)Backend application admin can also update the form questions.

**Issue we are facing:** When admin updates the form, all the questions and answers become empty and nothing is shown in the database. Could you please explain us why the issue will happen. And also probabality that our customer might copy and paste the content from the word doc, and other browser etc.

We have around 8-10 custom questions which we created with the help of form builder. There may be a chance to edit one or two questions withe copy and paste the content from the word doc, and other browser etc. but all the 8-10 got deleted that particualr records along with answers i.e., entire json array got deleted.

Could you please help us out resolving this issue?

### Environment Details:

 - formBuilder Version: 
 - Browser: 
 - OS:

**Comment by autoamation-2021** [comment]
Hello @kevinchappell ,

Please give us solution for this issue we are facing.

**Comment by autoamation-2021** [comment]
Hi,

Could you please help us to resolve this issue?

Backend Language: PHP
Front-end: HTML, CSS, Javascript,Jquery

**Comment by autoamation-2021** [comment]
Hello @kevinchappell,@Jojoshua 

Is there any way to prevent this problem?

**Comment by lucasnetau** [comment]
You will need to provide some reproducible code for this. FormBuilder and FormRender are two different components, if you are loading the results of formRender back into formBuilder then you need to take care of processing userData
