### ISSUE TITLE
How to create  Master Detail Form Generator

### ISSUE THREAD

**Issue by nahalrazeghi** [kevinchappell/formBuilder#157]
Hi ,
First of all thank you for your consideration ,
I wanna create forms which have some subforms or detail forms ?
how can  I create it ?  please help me ,  it is  vitally important ...

**Comment by kevinchappell** [comment]
Not sure I understand the concept of subforms but could you do something like this? http://codepen.io/kevinchappell/pen/BKYPRp

**Comment by nahalrazeghi** [comment]
thank you for your response , 
how can I add existance form(a form which had created befor by me ) to the main form ?
is it possible ?

**Comment by orionrush** [comment]
Perhaps he means conditional sections? As in a response is 'true' to a
target question, then a section is revealed that asks further questions?

For example, if the user is asked when filling in a survey:
 "do you also want to join the mailing list?"
Then additional fields are revealed that are about collecting contact
fields, post code etc.

-- Ben


On Sunday, 5 June 2016, nahalrazeghi <notifications@github.com> wrote:

> thank you for your response ,
> how can I add existance form(a form which had created befor by me ) to the
> main form ?
> is it possible ?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/kevinchappell/formBuilder/issues/157#issuecomment-223795119>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAwGtrbCMoZrBNNXUnoVw3jsYTLgT-ZJks5qImbagaJpZM4IrSrR>
> .
>


-- 
Sent from a mobile phone

**Comment by kevinchappell** [comment]
@nahalrazeghi You'd have to modify the plugin for that, current version not that kind of extensibility.

@orionrush I like your idea, and already have it on my list of to dos but its not likely to be included even in the next version or the plugin. Conditional fields require a good amount of configuration and I think it would be better suited for a form building service than a stand alone plugin.

**Comment by nahalrazeghi** [comment]
@orionrush  @kevinchappell  thanks buddies , i decide to add table control to this plugin . is it good idea ? is there  any best idea ?

**Comment by kevinchappell** [comment]
I think it's a great idea but there are a lot of considerations to keep in mind. In the example table you shared I see: 
- bolded and unbolded labels
- left and right aligned labels
- nested table
- multiple border styles
- thead and varied cell padding

You would need definable settings for the above listed and given the complexity it may be better to develop the feature as an add-on for formBuilder. You would still need to make a modification to the plugin in the form of a `fieldAdded` event hook that returns a type and `table` template. Then your add-on could listen for the event to be fired and replace the contents of the added field with a table editor and table preview.

A bit complicated but doable.

**Comment by nahalrazeghi** [comment]
@kevinchappell   I really appreciate all the help you gave me .

**Comment by kevinchappell** [comment]
Going to close this issue as its a bit outside the scope of formBuilder. Would be happy to see how you solved the issue though.
