### ISSUE TITLE
How to create a checkbox group with monetry value to each checkbox.

### ISSUE THREAD

**Issue by BradDoesCode** [kevinchappell/formBuilder#1574]
### Description:
Not an issue, but was hoping someone could help me create a custom control that is a checkbox group where each option has a custom monetry value.

**Comment by lucasnetau** [comment]
Can you please describe in a bit more detail what you are after, or some mock ups of the result? You could possibly be able to use a normal checkbox-group with updating of the values attribute for the checkbox-group prior to calling render

**Comment by BradDoesCode** [comment]
After some tinkering I managed to work it out. Thanks for the reply @lucasnetau
