### ISSUE TITLE
How to make bootstrap classes not disappear when removing a field from a row and putting it in an empty place

### ISSUE THREAD

**Issue by giannicolac** [kevinchappell/formBuilder#1575]
### Description:
Hello, i have a question. When i put two elements on a row, and then take one of them outside of it, it loses the bootstrap classes it had by default. I have enableEnhancedBootstrapGrid and enableColumnInsertMenu as true. I would like the elements to keep the classes after the process. 

### Environment Details:

 - formBuilder Version: 3.19.7
 - Browser: Firefox
 - OS: Linux Mint

### Expected Behavior
For the elements to keep the classes when taken out of a row.

### Actual Behavior
They lose the col, row and form-control classes

**Comment by lucasnetau** [comment]
Hi @giannicolac , thank you for your report. I can reproduce the form-control class bring dropped, will investigate why.

row and col I cannot reproduce being dropped, they are recalculated when moving to a new row

**Comment by lucasnetau** [comment]
Please test out https://github.com/kevinchappell/formBuilder/pull/1579, I've rewritten the syncFieldWithNewRow function which was corrupting the className string when dropped.

**Comment by giannicolac** [comment]
I replaced my form-builder.js file in src/js with the one you changed, but it doesnt seem to have changed anything about the behavior. The form-control classes disappear, and row and col are not in the data.

**Comment by lucasnetau** [comment]
Hi @giannicolac did you ensure to rebuild after applying the patch? I've done additional refactoring this morning and also added Jest test cases plus manual testing. Classes are no longer being mangled

**Comment by lucasnetau** [comment]
Please try this patched version [form-builder.min.js.gz](https://github.com/user-attachments/files/16104398/form-builder.min.js.gz)

**Comment by giannicolac** [comment]
This made it work, thank you.
