### ISSUE TITLE
Labels for fields and replaceFields options do not use localized strings

### ISSUE THREAD

**Issue by mtthwprtchrd** [kevinchappell/formBuilder#1578]
### Description:
When using the fields or replaceFields option the label attribute does not use the string from the language file.
e.g.
```
jQuery(function ($) {

    var options = {
        i18n: {
            locale: 'en-US',
            location: 'languages',
       },
       replaceFields: [{
        	label: ['dateAndTimeLabel'],
		type: 'date' 
	}]
	}
        var fbEditor = document.getElementById('fb-editor');
        var formBuilder = $(fbEditor).formBuilder(options);
});
```

What I was originally tying to achieve was to rename the date control to "Date and Time" and have the drop down list say "Date". Currently, they both share the same variable e,g, "dateField" so always end up with a shared string.
e.g.
The circled strings all share the same variable
![image](https://github.com/kevinchappell/formBuilder/assets/132384741/59532fd1-8b62-4150-959c-3bcb061aaf54)

### Environment Details:

 - formBuilder Version: v3.19.7
 - Browser: Chrome
 - OS: Windows

### Expected Behavior
The label for the object in the replaceFields array should be taken from the language specific file e.g. en-US.lang

### Actual Behavior
The label for the object in the replaceFields array just uses the specified string literal.

### Steps to Reproduce
See code above

### Minimal sample
[datetest.html.txt](https://github.com/user-attachments/files/16086783/datetest.html.txt)
[en-US.lang.txt](https://github.com/user-attachments/files/16086785/en-US.lang.txt)

**Comment by lucasnetau** [comment]
Thank you for the reproducer, I have replicated the issue and are preparing a PR to correct.

**Comment by lucasnetau** [comment]
Hi @mtthwprtchrd Please test out PR #1580

**Comment by mtthwprtchrd** [comment]
Hi @lucasnetau 
The PR has resolved my issue.
Thank you very much for the quick response.
