### ISSUE TITLE
class attributes for headers and paragraphs not showing

### ISSUE THREAD

**Issue by wordsandwriting** [kevinchappell/formBuilder#158]
https://github.com/kevinchappell/formBuilder/blob/master/dist/form-render.js#L276 should change from this:

`fieldMarkup = '<' + fieldAttrs.type + '>' + fieldLabelText + '</' + fieldAttrs.type + '>';`

to this:

`fieldMarkup = '<' + fieldAttrs.type + ' class="'+ fieldAttrs.class +'">' + fieldLabelText + '</' + fieldAttrs.type + '>';`

**Comment by kevinchappell** [comment]
This should be sorted out now in 1.9.30. @wordsandwriting please test if you have a chance. Thanks for opening this issue.
