### ISSUE TITLE
Form render error with custom controls

### ISSUE THREAD

**Issue by mtthwprtchrd** [kevinchappell/formBuilder#1581]
### Description:
We have a number of simple custom controls that we have written than were working as of version 3.9.9. We have just upgraded to the latest version of formbuilder 3.19.12.
For example after rendering the signing on our signature pad control (based on https://github.com/szimek/signature_pad ) no longer works but it does work in design mode.
We see this error in the inspector
![image](https://github.com/kevinchappell/formBuilder/assets/132384741/3050c4a0-389a-4582-8fd1-c7d0360b4adc)

### Environment Details:

 - formBuilder Version: 3.19.12
 - Browser: Chrome/CEFSharp
 - OS: Windows 10

### Expected Behavior
Able to sign in the signature area

### Actual Behavior
Not able to draw in the signature area

### Steps to Reproduce
Host and load the attached repro files.
Drag a signature onto the form
Click the Render button
Try to sign in the signature panel
Open the inspector and view the console. 
You can see the above error

### Minimal repro sample
Remove .txt from zip file
[repro.zip.txt](https://github.com/user-attachments/files/16178847/repro.zip.txt)

**Comment by kevinchappell** [comment]
thank you for reporting this. I'm looking into it now

**Comment by kevinchappell** [comment]
There was a syntax error in your custom control. Try this updated version:
[sigPad.zip](https://github.com/user-attachments/files/16242298/sigPad.zip)

**Comment by mtthwprtchrd** [comment]
Hi @kevinchappell This fixed the issue. Thank you very much for resolving this for us. Apologies for wasting your time.

**Comment by kevinchappell** [comment]
@mtthwprtchrd no worries, it was good experience for me
