### ISSUE TITLE
Add custom option to my custom field

### ISSUE THREAD

**Issue by hakimicones** [kevinchappell/formBuilder#1586]
### Description:
Hi 

i need to add custom element (type select ) with a custom options i have try to do like this ,

$(document).ready(function() {
    // Définir les options pour le champ select
    var customSelectOptions = {
        'Option 5': 'value1',
        'Option 4': 'value2',
        'Option 3': 'value3',
        'Option 2': 'value4'
    };

    // Définir les champs personnalisés
    var fields = [
        {
            label: 'Produits/Services',
            type: 'select', // Type du champ
            options: customSelectOptions, // Options du champ
            icon: '🔽' // Icône du champ
        }
    ];

    // Initialiser formBuilder avec les champs personnalisés
    var formBuilder = $('#build-wrap').formBuilder({
        fields: fields
    });

    // Gérer l'enregistrement des données du formulaire
    $('#saveBtn').on('click', function() {
        var formData = formBuilder.formData; // Récupérer les données du formulaire
        console.log('Données du formulaire :', formData);
        // Ajoutez ici votre logique pour sauvegarder les données
    });
});

 without success
 i need help

### Environment Details:

 - formBuilder Version: [v3.19.12](https://formbuilder.online/)
 - Browser: chrome
 - OS: windows

**Comment by lucasnetau** [comment]
https://formbuilder.online/docs/formBuilder/options/defaultFields/ has an example using the values: key 

```javascript
values: [{
          label: 'Custom Option 1',
          value: 'test-value'
        }, {
          label: 'Custom Option 2',
          value: 'test-value-2'
        }]
```
