### ISSUE TITLE
Mouse cursor moving to the end of the line on keyup

### ISSUE THREAD

**Issue by Lormen** [kevinchappell/formBuilder#160]
Not sure if this was done on purpose but If you use a text field and edit either the max-length or name fields the cursor goes back to the end of the line on keyup. Is this done on purpose and is there a way to turn it off?

**Comment by kevinchappell** [comment]
The only property that should be happening on is class so I'll take a look and see the problem.

**Comment by Lormen** [comment]
Thanks, hopefully I described what I was talking about well enough!

**Comment by Lormen** [comment]
Did you manage to find the issue?

**Comment by kevinchappell** [comment]
@Lormen Yes, thanks for reminding me. Should be resolved in #164
