### ISSUE TITLE
Loading an editable form

### ISSUE THREAD

**Issue by arthur1993** [kevinchappell/formBuilder#165]
Hey,

First of all thanks for all the work you've done, the form builder is great.
I was wondering if it is possible to save the editable form (not the rendered version) and/or import forms to re-edit them. I saw that on Formeo it cache saved your form but you can't import one..
Any plans on this?

Thanks

**Comment by kevinchappell** [comment]
Absolutely! On formBuilder you can load existing formData by setting the `textarea` value. Formeo takes 2 arguments and can be called with data like so:
```
var formeo = new Formeo(options, formData);
```

You will also be able to read and write formData after creating an instance of Formeo with `getData` and `setData(formData)` respectively, though these methods have not yet been implemented.

**Comment by arthur1993** [comment]
Thanks for your help man worked great, just have to adjust to my changes !

**Comment by tnory56** [comment]
When doing this it generates new IDs for each formData element.. Is this by design or a bug?

**Comment by kevinchappell** [comment]
@tnory56 would have to see your implementation but have a look at this demo: https://kevinchappell.github.io/formBuilder/

Clicking save will save the formData to `window.sessionStorage` so refreshing the page will funciton as if saved data was loaded. You should see the IDs do not change on the demo.

In the current version (1.24.2) textarea is not well supported however in 1.25.0 legacy support for `textarea` should ensure values are still loaded. Until then you can manually pass the formData through the `formData` option.

**Comment by santosh-k1** [comment]
Hi @kevinchappell, how to disabled actionButtons on page load rendered form ?
