### ISSUE TITLE
can we create the drag and drop fields to appear two or three in a row

### ISSUE THREAD

**Issue by Saraf-Piyush** [kevinchappell/formBuilder#166]
@kevinchappell

**Comment by Saraf-Piyush** [comment]
@kevinchappell 
@githubjeka @ivuorinen @GarryOne @basitsattar 

can we create two or three fields in a single row to make the form builder look as we like to make it more stylish

**Comment by kevinchappell** [comment]
@Saraf-Piyush Do you mean like columns, inline fields or like bootstrap input groups?

**Comment by kevinchappell** [comment]
Would something like this work for you?
![formeo-columns](https://cloud.githubusercontent.com/assets/1457540/16377043/b50c2030-3c5b-11e6-9c80-95612f267bcf.gif)

**Comment by chrisjelerang** [comment]
@kevinchappell This would be awsome, any plans to add soon?

**Comment by chrisjelerang** [comment]
Sorry, just seen that you are working on 2.0 alpha. I'll keep an eye on things over at https://github.com/Draggable/formeo

**Comment by adamlacombe** [comment]
@kevinchappell When do you expect this feature to be released?

https://github.com/Draggable/formeo doesn't exist anymore

I'm looking for a way wrap fields with the bootstrap class 'row' so on the front end it'll render fields in multiple columns.

`<div class="row">
            <div class="col-sm-6">            <div class="fb-text form-group field-first-name">
                <label for="text-1493058007299" class="fb-text-label">First Name <span class="required">*</span> </label> 
                <input type="text" name="text-1493058007299" class="form-control" required="required" style="">
            </div>
            </div><div class="col-sm-6">            <div class="fb-text form-group field-last-name">
                <label for="text-1493058027342" class="fb-text-label">Last Name <span class="required">*</span> </label> 
                <input type="text" name="text-1493058027342" class="form-control" required="required">
            </div>
  </div>   </div>`
![bootstrap-formbuilder](https://cloud.githubusercontent.com/assets/2395597/25624317/fa77a338-2f26-11e7-8866-307472dbb015.PNG)
