### ISSUE TITLE
Show/Hide Certain Attributes

### ISSUE THREAD

**Issue by dannycamps** [kevinchappell/formBuilder#17]
Hi Kevin,

I was wondering if you could tell me a way to hide the following items (possibly using CSS display:none):
"Save Template" button
"View XML" link

For each form item:
Name field
"Access" field

I just don't want them to appear on screen.

Thank you.
Daniel

**Comment by kevinchappell** [comment]
Oh man, that was actually a feature. In previous versions the name attribute could only be revealed with the hidden developer tools. I'll send the needed css to hide them when I get to my computer.

**Comment by Jos1k** [comment]
Could you please share for me too please?

**Comment by kevinchappell** [comment]
I think the simplest way to do this would be:

```
.fld-name,
.save-btn-wrap,
.view-xml {
  display: none;
}
```

**Comment by dannycamps** [comment]
This works.  Can you also tell me how to hide the "Access" option as well (e.g. Access should be granted to the following roles)?  Also any way to hide the actual label in addition to the text boxes?

**Comment by kevinchappell** [comment]
@dannycamps I realized after posting the first solution. I updated my original comment to account for labels and access field.

**Comment by dannycamps** [comment]
Thanks - works perfectly.

Just a minor correction for future reference:
The CSS for the name field is .frm-fld.name_wrap

Thanks,
-Daniel

**Comment by kevinchappell** [comment]
@dannycamps `name_wrap` was changed to `name-wrap` in the latest update.

**Comment by dannycamps** [comment]
Hi Kevin,

Hope you're doing well.  I just updated my code to the latest posted version (1.9.23) from the previous version I am using (1.35).  Incredible progress made on the project and lots of improvements.

That being said, I am having an issue - the previous CSS code I was using to hide certain elements is no longer working.

I need to hide the following items on screen:
Placeholder
Class
Name
Access
View XML button
Save button

Can you please tell me how I can hide those items?

Thanks,
-Daniel

**Comment by kevinchappell** [comment]
Sorry for the breaking changes, this css should get you on your way.
```
.form-elements .placeholder-wrap,
.form-elements .className-wrap,
.form-elements .access-wrap,
.form-elements .name-wrap,
.form-actions .view-data,
.form-actions .fb-save {
  display:none;
}
```
[Demo](http://codepen.io/kevinchappell/pen/VarLBL)

**Comment by dannycamps** [comment]
Yep - worked perfectly.

Thanks,
-Daniel
