### ISSUE TITLE
Is there a way to have a multiselect as a default field?

### ISSUE THREAD

**Issue by nateplusplus** [kevinchappell/formBuilder#170]
Hi, this form builder is really awesome, thanks for keeping this open source!

Just wondering, I saw [your codepen for default fields](http://codepen.io/kevinchappell/pen/pgxYEW), but I'm having a hard time figuring out how to have a default field that automatically allows multiple selections. Is there currently a way to do this?

I also tried doing this by including XML within the fb-template textarea (codepen: http://codepen.io/nateplusplus/pen/MejLNM), it seems like everything else works this way but not the multiselect field.

Thanks again!

**Comment by kevinchappell** [comment]
Thanks for reporting this, should be working now in 1.10.3.

**Comment by nateplusplus** [comment]
👍 works beautifully, thanks Kevin!
