### ISSUE TITLE
Suggestion of signature input box

### ISSUE THREAD

**Issue by leo1989work** [kevinchappell/formBuilder#171]
This plugin is great, it helps me a lot. 

There is one suggestion, in daily usage I realize there are many case I need to provide a signature box    in the form.

Would you mind integrate this signature plugin to the form builder? 

http://keith-wood.name/signature.html 

I found this plugin is also great as the signature is just JSON data, the signature box can add along with an hidden textarea , it simplify a lot for the process.

Thanks for your attention

**Comment by kevinchappell** [comment]
A signature field is a great idea and will be included in the next version however the new builder is not jQuery. Between that dependency and the limited touch functionality of jQuery UI Signature I think we cannot use it.

I was looking to base the new signature field off of this [plugin](https://github.com/szimek/signature_pad)
It has touch support, variable line width based on write speed and higher resolution images. To my knowledge it won't output the signature as JSON but I think the base64 encoded image it provides should be ok.

**Comment by leo1989work** [comment]
great looking forward to it

**Comment by justintoth** [comment]
Hey guys, any update on including a signature element? I'm trying to create a form builder for tenant forms (lease agreements, applications, etc...), so adding signatures to the form is a must-have.

**Comment by kevinchappell** [comment]
@justintoth this is doable with an external plugin and replacing an unused field such as `autocomplete`.

**Comment by soumyojit** [comment]
Hi Kevin.  We want the Label of the control to appear on the left side of the control instead of the top . How can this be done ? Can you let me know step by step . I am new to javascript.

**Comment by MisterDuval** [comment]
Hi @kevinchappell , do you have any update on this feature request? Signature could be nice!
