### ISSUE TITLE
Issue on Internet Explorer with radio-group

### ISSUE THREAD

**Issue by AlienFX** [kevinchappell/formBuilder#181]
Hi there,
I have an issue on Internet Explorer, Impossible to render when I use radio-group in a form builder.
You can see the following screenshot to understand my problem.
I don't know how to fix this line.
Thank you so much in advance.

![screen1](https://cloud.githubusercontent.com/assets/195319/16558769/36e64126-41e8-11e6-82a9-cd2b25590f33.png)
![screen2](https://cloud.githubusercontent.com/assets/195319/16558770/37046340-41e8-11e6-9aa0-539b78b6826c.png)

**Comment by kevinchappell** [comment]
Should be resolved in v1.10.4

**Comment by AlienFX** [comment]
Thank you Kevin for your quick answer !
Do you already have a release date?
Thanks :)

**Comment by kevinchappell** [comment]
Yep, July 4th 2016. Changes should be available now.
 https://formbuilder.online

**Comment by kevinchappell** [comment]
Oops, I just saw that it was a formRender issue, not formBuilder. I'll patch there also

**Comment by kevinchappell** [comment]
edit: formRender and formBuilder should both be patched now.

**Comment by AlienFX** [comment]
Yes I got it! Thank you & good job ;)
