### ISSUE TITLE
json implementation

### ISSUE THREAD

**Issue by Yc-Chen** [kevinchappell/formBuilder#184]
Hi,

I have been looking into integrating formBuilder and a [form generator](http://brutusin.org/json-forms/). If these two are integrated, many features mentioned in other issues will become available or easy to implement. The biggest gap now is between xml and json. I see there are 'coming soon' comment for json in the codes. However what is the progress? I'm willing to implement this if nothing is done yet.

**Comment by kevinchappell** [comment]
@Yc-Chen, that would be a huge help. JSON form data has not been implemented in formBuilder, instead it was added to [Formeo](http://draggable.github.io/formeo/) which is the next major release of formBuilder (explaination of namechange on formbuilder.online News section). However Formeo is not ready for production and a number of people will likely stick with formBuilder even after it is so having JSON as an option would be huge.

**Comment by blaketan** [comment]
I wrote something quick and dirty a few weeks back to encode the form into JSON in order to save the form at the back end using AJAX calls. Let me know if this helps.

`        fjson += '{"questions": [';
        var qs = "";
        $("div.frmb-wrap ul.frmb li.form-field").each(function(){
          var q = ""
          //T Or F (TRF)
          if ($(this).hasClass("checkbox")){q='{"title": "'+ validQCheck($(this).find("input.fld-label").val()) + '", "qtype": "TRF"}, ';}
          //Rating (GRS)
          else if ($(this).hasClass("radio-group")){q='{"title": "'+ validQCheck($(this).find("input.fld-label").val()) + '", "qtype": "GRS"}, ';}
          //TXT
          else if ($(this).hasClass("text")){q='{"title": "'+ validQCheck($(this).find("input.fld-label").val()) + '", "qtype": "TXT"}, ';}
          //MS
          else if ($(this).hasClass("checkbox-group")){
            q='{"title": "'+ validQCheck($(this).find("input.fld-label").val()) + '", "qtype": "MS",';
            q+='"detail": "'
            var res = "";
            $(this).find('input.option-label').each(function(){res += ''+ validCheck($(this).val()) + ',';});
            q += res.substring(0,(res.length -1)) + '" }, ';
          }
          //MC
          else if ($(this).hasClass("select")){
            q='{"title": "'+ validQCheck($(this).find("input.fld-label").val()) + '", "qtype": "MC",';
            q+='"detail": "'
            var res = "";
            $(this).find('input.option-label').each(function(){res += ''+ validCheck($(this).val()) + ',';});
            q += res.substring(0,(res.length -1)) + '" }, ';
          };
          qs+=q
        });
        fjson += qs.substring(0,(qs.length-2)) + " ] } } "`

**Comment by Yc-Chen** [comment]
@blaketan I'm thinking about integrating with json-schema, so it will make form validation also easier. But json-schema is designed from the value point of view and formBuilder xml is designed from the visualization point of view. So a refactor is needed. For now I have written something like this:

```
            var jsonAttrs = {
              className: fieldData.className,
              title: $('.fld-label', $field).val(),
              description: $('input.fld-description', $field).val(),
              placeholder: $('input.fld-placeholder', $field).val(),
              maxlength: $('input.fld-maxlength', $field).val(),
              multiple: $('input[name="multiple"]', $field).is(':checked'),
              // name: $('input.fld-name', $field).val(),
              required: $('input.required', $field).is(':checked'),
              toggle: $('.checkbox-toggle', $field).is(':checked'),
            //   type: types.type,
            //   subtype: types.subtype,
            };
            // NOTE: refactor types
            console.log('logged from toJSON');
            console.log(types);
            if (types.type.match(/text\b/)) {
                jsonAttrs['type'] = "string";
                if (types.subtype.match(/color/)) {
                    jsonAttrs['format'] = "color";
                }
            } else if (types.type.match(/select/)) {
              jsonAttrs['type'] = "string";
            } else if (types.type.match(/textarea/)) {
              jsonAttrs['type'] = "string";
              jsonAttrs['format'] = "text";

            } else if (types.type.match(/date/)) {
                jsonAttrs['type'] = "string";
                jsonAttrs['format'] = "date";
            } else if (types.type.match(/file/)){
                jsonAttrs['type'] = "string";
                jsonAttrs['format'] = "inputstream";
            }
```

**Comment by Yc-Chen** [comment]
Hi Kevin,

I have tried to implement part of the json schema features and it already seems to have dramatic impact of the whole package. I have on my own repository created a branch [assets](https://github.com/Yc-Chen/formBuilder/tree/assets) to do all the messy work.. and I have created [another repository to show an example](https://github.com/Yc-Chen/json-schema-form-builder).

To continue further, I think it would be better to have some json data structure as a global variable(like opts). Each drag/drop operation and fields editing will directly affect the json data structure. Therefore the package will be more structured. However there could be only one choice between json and xml. For now it is xml. Would you like it if the whole package is restructured to be based on json?

**Comment by kevinchappell** [comment]
This difficulty between the 2 data structures is one of the many reasons I created Formeo as a whole new module. As much as I'd like to ditch xml, a lot of sites and apps use it and I think removing it could cause more problems than it solves. 

I'll have a closer look on the computer at your dev branches. My only comment for now would be to make sure to edit the files in /src. FormBuilder has a gulp build process and everything in /dist will be replaced by the output from /src when it's run.

**Comment by Yc-Chen** [comment]
I looked into the Formeo codes a bit and I saw some json related methods. Im using a specific json standard, json-schema. I like it as it defined some restrictions for form validation. And the other package json-form has implemented a useful feature of flexible fields.(see [http://brutusin.org/json-forms/#2](http://brutusin.org/json-forms/#2) 'Query terms') Quite many JSON-schema validation are out there. You can define extra fields to help visualisation too:
[http://json-schema.org/latest/json-schema-core.html#anchor20](http://json-schema.org/latest/json-schema-core.html#anchor20). 

When I make it stable I will edit in /src. And please please ignore all the 'console.log' in my dev,,, I have to use that to understand the logic,,,

**Comment by kevinchappell** [comment]
I like json-schema but at the time felt it was too verbose and I wanted the data structure to better represent the fields it was creating, ie. instead of `patternProperties` on the root of a field object I felt it worked better as:
~~~
{
  "tag": "input",
  "attrs": {
    "type": "email",
    "pattern": "^[A-Za-z0-9._%+-]+@specific-domain.com$"
  }
}
~~~
The above will create an email input field that uses constraint api to ensure the input is an email is from "specific-domain.com". 

Anyways json-schema is not off the table as I've been looking at json-hyper-schema for the Formeo service API and it would only makes sense that the editor use it as well.

@idelvall did an amazing job on json-forms but again it seemed off the mark for what I was trying to build with Formeo. I may also have not understood how it could meet the project's needs but I was confident the data structure I was designing would work so I went with that. In hindsight I probably could have spent more time with json-schema and will likely circle back when the need arises.

I had a look at your dev branches and it looks good. Seeing how close `toJSON` is to `toXML` makes me think we should merge them into one `saveData` function and pass the save type (json or xml) as an argument. What do you think?

**Comment by jonrcable** [comment]
Since this conversation is relevant, i'm going to link this back to another thread:
https://github.com/kevinchappell/formBuilder/issues/30

In particular see @him-developer's note on the using the following lib: https://github.com/abdmob/x2js

This method worked easily for me on the formBuilder (save) post side. Something like this added to the -save action returns a json result to the console.

`// Save Idea Template
    $(document.getElementById(frmbID + '-save')).click(function (e) {
      e.preventDefault();
      _helpers.save();
      _helpers.validateForm(e);

      // modified for XML to JSON POST
      var fbTemplate = document.getElementById('fb-template');
      var x2js = new X2JS();
      var xml_str = fbTemplate.value;
      var form_json =  x2js.xml_str2json(xml_str);
      form_json = JSON.stringify(form_json["form-template"]["fields"]["field"]);
      console.log(form_json);

    });`

**Comment by burgoyn1** [comment]
I just got tasked to create a form builder for our admin interface, but this does exactly what I am looking for. However, right now we save all of our forms in json, so it would be awesome to have a json output built into it. In the meantime, what @jonrcable suggested works great! Good suggestion.

**Comment by Yc-Chen** [comment]
I also implemented the loading method getJSON. However which action will call this method? I have no clue how to check whether my implementation works.

**Comment by kevinchappell** [comment]
Yeah I was having trouble getting it working myself. `getJSON` would be used to load data to the builder. I'll post some details on the pull request.

**Comment by mimrank** [comment]
hi, can i use this plugin for form generation and save output in json?

**Comment by kevinchappell** [comment]
JSON support added in #243
