### ISSUE TITLE
How to restrict only one file input per form? 

### ISSUE THREAD

**Issue by leo1989work** [kevinchappell/formBuilder#189]
Thanks for the great plugin , 
to simplify the use case, I would like to make the file input only happen once.

One suggestion is after drag the input file box to the form area, then the input file options will be hidden, if the input file box is removed , then the options is show again,

are there any workaround right now? 

Thanks a lot for your help

**Comment by kevinchappell** [comment]
@leo1989work Someone (*you?*) had asked for this exact feature months ago and I put together this work around: http://codepen.io/kevinchappell/pen/eZReEB

Let me know if that works for you.

**Comment by leo1989work** [comment]
great ,  someone has the same use case

**Comment by kevinchappell** [comment]
I'm going to close this issue but feel free to re-open if it needs more attention.
