### ISSUE TITLE
Possible to use "pre" as data type to store the paragraph?

### ISSUE THREAD

**Issue by leo1989work** [kevinchappell/formBuilder#192]
Currently there are some choices to choose from

e.g. p, canvas , output etc...

it works fine. only one small problem , some user would like to have a new line / line break at the paragraph , right now the style choices can not fulfill this requirement.

Thanks for helping.

**Comment by kevinchappell** [comment]
That's a good point. I'll be fixing HTML encoding for block elements to solve another issue and will make sure the extra types get the fix as well.
