### ISSUE TITLE
Loading elements with options missing defaults

### ISSUE THREAD

**Issue by jonrcable** [kevinchappell/formBuilder#194]
When you pre-load any type of form element that has multiple options... and any of those options have a default selection set in the xml. when the form gets preloaded the default selection is not populated in the element's options (html), so any subsequent saves will overwrite previous selections.

In the following Pen:
http://codepen.io/kevinchappell/pen/Vedrqr

- add a radio-group
- selection option-1 as the default
- refresh the browser
- does not preload select for html, but the Dom still has the default set in the fbTemplate.value (at least till the next save)

I might be able to find it, just haven't looked (yet) maybe its a quick find for you @kevinchappell 

Thanks, great stuff. cheers

**Comment by kevinchappell** [comment]
That's a good catch. I'll see what's up with that.
