### ISSUE TITLE
$(...).formRender is not a function

### ISSUE THREAD

**Issue by eldyvoon** [kevinchappell/formBuilder#195]
$(...).formRender is not a function(anonymous function) at main.js:27

This is my main.js

````
$(document).ready(function($) {

  var options = {
  controlPosition: 'left',
  messages: {
    select: 'Dropdown',
  },
  disableFields: ['autocomplete,hidden'],
  stickyControls: true,
  controlOrder: [
  	'text',
  	'textarea',
  	'select',
  	'date',
  	'radio-group',
    'checkbox',
    'checkbox-group',
    'file',    
    'button',
  ]};

  var fbTemplate = document.getElementById('fb-template');
  $(fbTemplate).formBuilder(options);

  $('.form-builder-save').click(function(){
  	console.log($(fbTemplate));
  	  var outputHtml = $(fbTemplate).formRender();
  	  //console.log(outputHtml);
  });
});
````

**Comment by eldyvoon** [comment]
I forgot to include https://formbuilder.online/assets/js/form-render.min.js

but still I got undefined doing `console.log(outputHtml);`

**Comment by kevinchappell** [comment]
formRender could use some better documentation. I'll try to find time to add that. The reason you're not seeing output though is because by default formRender will replace the element it's called on. Set `render` to false and it will return markup instead. Maybe be easier to access the core function directly.

See codepen: http://codepen.io/kevinchappell/pen/bZarNd

**Comment by kevinchappell** [comment]
Posted some new documentation for formRender [here](http://formbuilder.readthedocs.io/en/latest/formRender/options/render/) that should solve your issue. Reopen issue if youre still having trouble.

**Comment by abhayathapa** [comment]
On react-app with rails, everything is working fine. But formRender is not working.

`Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_0_jquery___default(...)(...).formRender is not a function`

**Comment by PTRPlay** [comment]
@abhayathapa Did you solve your problem?
I've got the same one.

**Comment by abhayathapa** [comment]
@PTRPlay `require('formBuilder/dist/form-render.min.js')` worked for me

**Comment by PTRPlay** [comment]
> @PTRPlay `require('formBuilder/dist/form-render.min.js')` worked for me

Thanks

**Comment by ppshein** [comment]
> @PTRPlay `require('formBuilder/dist/form-render.min.js')` worked for me

perfect

**Comment by tacman** [comment]
I'm using webpack to manage my javascript files, but am having an issue I think with the global jQuery object.

```javascript
const $ = require('jquery');
require('formBuilder');
require('formBuilder/dist/form-render.min.js');
$('#fb-editor').formBuilder(); // fails
```

FWIW, this works.  So perhaps there's some difference in how formBuilder handles the global $?
```javascript
const $ = require('jquery');
require('jstree');
$('#somelist').jstree();
```

**Comment by dsk-group** [comment]
ok fine

**Comment by dsk-group** [comment]
<!DOCTYPE html>
<html>
<head>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
  <script src="http://formbuilder.online/assets/js/form-builder.min.js"></script>
  <script src="https://formbuilder.online/assets/js/form-render.min.js"></script>
	<title>form show to users</title>
</head>
<body>
	<?php if(isset($_POST['Save']))
	{
		$name = $_POST['name'];
		print_r($name);die;
	} ?>
	<form id="fb-render"></form>
	<button type="button" id="get-user-data">Get Updated formData</button>
</body>
</html>
<script>
	const getUserDataBtn = document.getElementById("get-user-data");
	const fbRender = document.getElementById("fb-render");

	const originalFormData = [{
    "type": "text",
    "required": false,
    "label": "Name",
    "placeholder": "name",
    "className": "form-control",
    "name": "text-1594898843033",
    "access": false,
    "subtype": "text"
  },
  {
    "type": "textarea",
    "required": false,
    "label": "Address",
    "placeholder": "address",
    "className": "form-control",
    "name": "textarea-1594898865273",
    "access": false,
    "subtype": "textarea",
    "rows": 3
  },
  {
    "type": "radio-group",
    "required": false,
    "label": "Radio Group",
    "inline": false,
    "name": "radio-group-1594898898697",
    "access": false,
    "other": false,
    "values": [
      {
        "label": "Male",
        "value": "1"
      },
      {
        "label": "Female",
        "value": "2",
        "selected": true
      }
    ]
  },
  {
    "type": "button",
    "label": "Save",
    "subtype": "button",
    "className": "btn-default btn",
    "name": "button-1594898945513",
    "access": false,
    "style": "default"
  }];
  jQuery(function($) {
  const formData = JSON.stringify(originalFormData);

  $(fbRender).formRender({ formData });
  getUserDataBtn.addEventListener(
    "click",
    () => {
      window.alert(window.JSON.stringify($(fbRender).formRender("userData")));
      console.log(window.JSON.stringify($(fbRender).formRender("userData")))
    },
    false
  );
});
</script>


// this is very helpfull it's work for me

**Comment by dsk-group** [comment]
> I forgot to include https://formbuilder.online/assets/js/form-render.min.js
> 
> but still I got undefined doing `console.log(outputHtml);`

thankyou it's working for me

**Comment by junaidansari95** [comment]
> @PTRPlay `require('formBuilder/dist/form-render.min.js')` worked for me

thanks alot !!!!!!!!

**Comment by jahids** [comment]
my react app form builder working fine.. but form runder not working..plese anyone help me

**Comment by asrafulislamgh** [comment]
> @PTRPlay `require('formBuilder/dist/form-render.min.js')` worked for me

Worked perfectly
