### ISSUE TITLE
What does the swf files do?

### ISSUE THREAD

**Issue by keoflex** [kevinchappell/formBuilder#2]

**Comment by kevinchappell** [comment]
Those files are for the hidden developer mode to allow copying variables to the clipboard. I am just wrapping up a refactor and they have been removed though click to copy feature remains.

![screenshot from 2015-09-15 04 58 18](https://cloud.githubusercontent.com/assets/1457540/9867518/9acdefc2-5b66-11e5-99ec-2697e4e4c3b5.png)

**Comment by keoflex** [comment]
Thanks, would it be possible to output the xml to a textarea box?

Also do you have a paypal donate link

**Comment by kevinchappell** [comment]
Absolutely, the plugin uses a textarea as the read and write canvas, it can be revealed with Dev Mode also. Sure do, just at the bottom of the demo: http://kevinchappell.github.io/formBuilder/ Thanks!

[![Video](http://i.ytimg.com/vi/ReKGRUIGgig/maxresdefault.jpg)](https://youtu.be/ReKGRUIGgig)
