### ISSUE TITLE
Formbuilder and ampersands in fields

### ISSUE THREAD

**Issue by johnhowson** [kevinchappell/formBuilder#203]
Hi Kevin
Thanks for your formbuilder project. It is great. 
I came across an issue while saving and uploading fields notably if you store an ampersand in a field and save it to a database when you try to load the form the output is something like this
&lt;field name="thefield" label="This &amp;amp; that " class="input-normal" type="text"  /&gt;
However, the presence of an ampersand in the field prevents the form from loading in Formbuilder. If I remove the ampersand it renders fine. I have experimented and found that if the ampersand is saved as &amp;amp;amp; it renders correctly and does not break formbuilder. However, I should like to get it working for the right reason so to speak.
I shall be very grateful for any ideas
Wishes
John Howson

**Comment by kevinchappell** [comment]
Thanks John,
Is the formData being passed through another data sanitizer? As you pointed out ampersands should be converting to `&amp;amp;` in the XML but normally. See gif:
![bernie-ampersanders](https://cloud.githubusercontent.com/assets/1457540/16952566/a29fe11c-4dc1-11e6-9365-aa56702ffb61.gif)

**Comment by johnhowson** [comment]
Thanks Kevin
I am not passing it through any other process so far as I know. But I will check. There must be something that is removing the second &amp

**Comment by johnhowson** [comment]
PHPs SimpleXMLElement appears to remove the second &amp;&amp;
I have corrected so is working now thanks!

**Comment by kevinchappell** [comment]
Excellent, glad to hear you solved it.
