### ISSUE TITLE
composer package

### ISSUE THREAD

**Issue by alien-art** [kevinchappell/formBuilder#205]
You can make the package composer, because when you try to install formBuilder of bower composer means it loads quite another package of the same name, namely https://github.com/dobtco/formbuilder

**Comment by kevinchappell** [comment]
I'm not too familiar with composer. Would a file named `composer.json` with the following in it do the trick?

```
{
  "name": "kevinchappell/formBuilder",
  "type": "library",
  "description": "jQuery formBuilder",
  "keywords": [
    "form",
    "builder",
    "formbuilder",
    "form builder"
  ],
  "homepage": "https://formbuilder.online",
  "license": "MIT",
  "authors": [{
    "name": "Kevin Chappell",
    "email": "kevin.b.chappell@gmail.com",
    "homepage": "https://kevin-chappell.com",
    "role": "Developer"
  }],
  "require": {
    "composer/installers": "~1.0"
  }
}
```

**Comment by alien-art** [comment]
Let it be, but require this section must be taken and you can register at https://packagist.org/

{
  "name": "kevinchappell/formBuilder",
  "type": "library",
  "description": "jQuery formBuilder",
  "keywords": [
    "form",
    "builder",
    "formbuilder",
    "form builder"
  ],
  "homepage": "https://formbuilder.online",
  "license": "MIT",
  "authors": [{
    "name": "Kevin Chappell",
    "email": "kevin.b.chappell@gmail.com",
    "homepage": "https://kevin-chappell.com",
    "role": "Developer"
  }]
}
Thank you for your quick response

**Comment by alien-art** [comment]
Good day, when it is expected the appearance of composer package in the distribution?

**Comment by kevinchappell** [comment]
formBuilder is now registered as [kevinchappell/form-builder on packagist](https://packagist.org/packages/kevinchappell/form-builder)
