### ISSUE TITLE
unsaved multiple option in select element

### ISSUE THREAD

**Issue by OPADA-Eng** [kevinchappell/formBuilder#208]
First I want to thank you for this great tool, it's very useful !
But I noticed that when you save the form after you build it the element "select" that is multiple checked 
never save and when you render the form for edit you will see that the checkbox "multiple" is unchecked.
any solution for this ?

**Comment by kevinchappell** [comment]
Thanks, what version are you using? This issue should have been resolved in [v1.10.3](https://github.com/kevinchappell/formBuilder/pull/176)

Here is a [jsfiddle](https://jsfiddle.net/kevinchappell/1rzjshtL/) of multiple in action.

**Comment by jonrcable** [comment]
Confirmed, @kevinchappell rocks and already fixed this! Thanks again

**Comment by jonrcable** [comment]
For reference: https://github.com/kevinchappell/formBuilder/issues/194

**Comment by kevinchappell** [comment]
![woo hoo](http://media1.giphy.com/media/ALCI3eTii7qOk/giphy.gif)

**Comment by OPADA-Eng** [comment]
I was using version 1.9, Thanks it is working fine now after update.
