### ISSUE TITLE
Form Render Issue !

### ISSUE THREAD

**Issue by mfahad891** [kevinchappell/formBuilder#217]
When i render two forms in a page then it doesn't render the first form again or duplicate form if i use container? how to solve it

**Comment by kevinchappell** [comment]
Could you create an example jsfiddle? WIll need to see code to understand what is happening.

**Comment by mfahad891** [comment]
Solved ..... $("input[name*='"+value.col_name+"']").val(value.data); I am doing work like that that's why it's duplicating data... Thanks...
