### ISSUE TITLE
TextArea value doesn't appear when render 

### ISSUE THREAD

**Issue by iabuhilal** [kevinchappell/formBuilder#218]
when setting a TextArea value it doesn't display when it is rendered because it is added as value attribute to the TextArea

fix, form-render.js line 208
        delete fieldAttrs.value;
        fieldMarkup = fieldLabel + '<textarea ' + fieldAttrsString + '></textarea>';

fix
       // delete fieldAttrs.value;
        fieldMarkup = fieldLabel + '<textarea ' + fieldAttrsString + '>' +  fieldAttrs.value + '</textarea>';

**Comment by kevinchappell** [comment]
This was a good catch. Additionally edit fields for value were not appearing. Pushing changes shortly
