### ISSUE TITLE
Uncaught TypeError: $(...).formBuilder is not a function

### ISSUE THREAD

**Issue by snehalsabale** [kevinchappell/formBuilder#22]
I am integrating this plug in rails application.
In HTML page i used the code given at http://kevinchappell.github.io/formBuilder/ . But it always give an error for fromBuilder.
I think the sequence of requiring the javascript files is somehow wrong.

The code in application.js is:

//= require jquery
//= require form-builder
//= require jqueryui-1.10.3.min
//= require jquery_ujs
//= require jquery.turbolinks
//= require bootstrap-sprockets
//= require jquery.dataTables.min
//= require dataTables.bootstrap
//= require jquery.validate
//= require jquery.validate.additional-methods
//= require_tree .

And 
here is my HAML file code:

%link{:href => "https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.css", :media => "screen", :rel => "stylesheet", :type => "text/css"}
.demo-wrap
  / MAIN CONTENT
  #main_content_wrap.outer
    %section#main_content.inner
      .build-form
        %h2
          %strong Build The Form
        %form{:action => ""}
          %textarea#form-builder-template{:cols => "30", :name => "form-builder-template", :rows => "10"}
        %br{:style => "clear:both"}
      .render-form
        %h2
          %strong Render The Form
        %form#rendered-form
          %p.cta Add some fields to the formBuilder above and render them here.
        .render-description
          %h3 Try it out
          %button#render-form-button.btn.btn-primary Render form
      %br{:style => "clear:both"}
-#%script{:src => "https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"}
-#%script{:src => "https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"}

:javascript
  jQuery(document).ready(function($) {
    'use strict';
    var template = document.getElementById('form-builder-template'),
      formContainer = document.getElementById('rendered-form'),
      renderBtn = document.getElementById('render-form-button');
    console.log(template)
    $(template).formBuilder();
    $(renderBtn).click(function() {
      $(template).formRender({
        container: $(formContainer)
      });
    });
  });
:javascript
  (function(i, s, o, g, r, a, m) {
    i['GoogleAnalyticsObject'] = r;
    i[r] = i[r] || function() {
      (i[r].q = i[r].q || []).push(arguments)
    }, i[r].l = 1 * new Date();
    a = s.createElement(o),
      m = s.getElementsByTagName(o)[0];
    a.async = 1;
    a.src = g;
    m.parentNode.insertBefore(a, m)
  })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

  ga('create', 'UA-4784386-21', 'auto');
  ga('send', 'pageview');

How do i fix this ?

**Comment by kevinchappell** [comment]
Does your Gem file have jquery and jquery ui? Gem file should have 
```
gem 'jquery'
gem 'jquery-ui-rails'
```

and in application.js `form-builder` should be after the jquery libraries
```
//= require jquery
//= require jquery_ujs
//= require jquery-ui
//= require jquery-ui/sortable
//= require form-builder
```

Also be sure form-builder.js is in `vendor/assets/javascripts/`

Quick notes: You won't need to manually add jquery and jquery ui scripts in your HAML and the google tracking is actually for the formBuilder github pages. You'll want to change to your own Google Analytics id.

Is the project on github? If so I could take a look.

**Comment by tknazn** [comment]
I had a similar problem and by including gem 'jquery-ui-rails', it solved that. 

Note: I think you would need 
```gem 'jquery-rails'```
instead of gem 'jquery'

**Comment by snehalsabale** [comment]
@tknazn  and @kevinchappell  : Actually the sequence of requiring the javascript files in application.js that you provided, solved my problem. Also I put the plugins files to vendor/javascripts folder. Actually jquery files reloading twice. So now i called them after requiring jquery files.
Also i included the gems you suggested and finally the solution is working.

**So thanks you guys. Awesome job. Keep rocking..!!**

###### application.js
```javascript
//= require jquery
//= require jquery_ujs
//= require jquery-ui
//= require jquery-ui/sortable
//= require jquery.turbolinks
//= require bootstrap-sprockets
//= require jquery.dataTables.min.js
//= require dataTables.bootstrap.min.js
//= require jquery.validate.js
//= require jquery.validate.additional-methods
//= require form-builder
//= require form-render.min
//= require_tree .
```

**Comment by snehalsabale** [comment]
@kevinchappell : 
I am eager to see version 2.0 which includes JSON data as default instead of XML.
Great work man..!

**Comment by kevinchappell** [comment]
@snehalsabale glad to hear you got it worked out and thanks!

**Comment by ilakkiah** [comment]
I am also facing this issue while integrating with angular2 .Can you help me out ??
