### ISSUE TITLE
RequireJS  Race Condition ?

### ISSUE THREAD

**Issue by cmagnusItOptics** [kevinchappell/formBuilder#222]
Hi, 

I'm trying to implements formBuilder into an Tapestry ( java ) but I encounter some issues with js libs. 
are you aware of Race Condition with some libs ? In my mind it's RequireJS.js , prototype.js. 

edit 1 :
The issues is line 1449 : 

code : 
 $sortableFields.sortable({
      cursor: 'move',
      opacity: 0.9,
      revert: 150,
      beforeStop: _helpers.beforeStop,
      start: _helpers.startMoving,
      stop: _helpers.stopMoving,
      cancel: 'input, select, .disabled, .form-group, .btn',
      placeholder: 'frmb-placeholder'
    });

log : 
TypeError : $sortableFields.sortable is not a function 

with requireJS sortable seems not correctly working  

Best regards, 

Clint,

**Comment by kevinchappell** [comment]
this sounds like a missing dependency to me. formBuilder requires jquery and jquery-ui sortable.

**Comment by cmagnusItOptics** [comment]
You are right, jquery-ui is missing, this is due to RequireJS manager dependency ... i'm stil looking, thanks for reply

**Comment by kevinchappell** [comment]
How did you make out on this? Alright to close this issue?
