### ISSUE TITLE
Reordering Fields is not working in Bootstrap

### ISSUE THREAD

**Issue by ujwalpaladugu** [kevinchappell/formBuilder#226]
Hey Kevin,

Reordering Fields is not working for BootStrap Theme. No errors recorded in console.

When i'm trying to move the cursor, it is just selecting the content. Can you please help me in debugging this issue.

I'm using latest version.

Thanks,
Ujwal P

**Comment by kevinchappell** [comment]
could you put together a jsfiddle to demonstrate the problem? I'm not able to replicate

**Comment by ujwalpaladugu** [comment]
Sure Kevin.

**Comment by ujwalpaladugu** [comment]
Hey Kevin, 

It works as desired. There was miss configuration at my end...

https://jsfiddle.net/yqfxc2fg/

Thanks,
Ujwal P
