### ISSUE TITLE
How to add number field ?

### ISSUE THREAD

**Issue by dennyjohnk** [kevinchappell/formBuilder#229]
Can you help me add digits only field.

**Comment by kevinchappell** [comment]
There is already a number field that is disabled by default using the `disableFields` option. However, as I was setting up a demo I found a bug that causes `disableFields` to not work properly. A demo currently exists for this feature [here](http://formbuilder.readthedocs.io/en/latest/formBuilder/options/disableFields/), you can use this setting while I work out the bug.

**Comment by dennyjohnk** [comment]
Thanx @kevinchappell :)
