### ISSUE TITLE
Add new element and Modify existing one 

### ISSUE THREAD

**Issue by tknazn** [kevinchappell/formBuilder#23]
Hi Kevin,

I'm trying to make changes to some existing form elements. For example: instead of checkbox, I want to make it like a True & False toggle. 
I am kinda lost when going thu your code. Wonder if you can shed some lights on how to either add new element or modify existing one. 

Thanks,
Trong

**Comment by kevinchappell** [comment]
Hey Trong,
Adding it to the editor itself is a bit tricky as you would need to make the changes in a few places. If the toggle is meant to completely replace the `checkbox` you could update the markup for the checkbox field template [here](https://github.com/kevinchappell/formBuilder/blob/master/src/js/form-builder.js#L776).

If you only need the toggle at render you can use something like [this](http://kevinchappell.github.io/kcToggle/) and call it after `formRender()`. To use it with the checkbox rendered by `formRender()` you would need to call it like `$('input[type="checkbox"]', document.getElementById('rendered-form')).kcToggle()`

I made a quick [jsFiddle example](https://jsfiddle.net/kevinchappell/0s6982on/)

**Comment by kevinchappell** [comment]
Hi Trong,
This [pull-request](https://github.com/kevinchappell/formBuilder/pull/24) may be of interest to you.

**Comment by tknazn** [comment]
Having option to change from checkbox to toggle would work in some scenarios. I'm looking for a clean way to replace checkbox entirely with toggle. 

Besides, another part of my question is how we can add an entirely new element? Besides the ones you have, I really need to create the star-rating element (value: 0-5).

**Comment by kevinchappell** [comment]
Star rating is a good idea. There are plans to add new inputs, star rating could certainly be one of them. In the meantime you could use the radio group to accomplish a star rating with some css. [Here is one example](https://www.everythingfrontend.com/posts/star-rating-input-pure-css.html)

**Comment by tknazn** [comment]
Thank you Kevin! I was able to leverage the css you shared.

**Comment by kevinchappell** [comment]
Excellent!
