### ISSUE TITLE
formBuilder and jsfiddle: Refuse to execute script

### ISSUE THREAD

**Issue by maasha** [kevinchappell/formBuilder#230]
jsfiddle refuses to run formBuilder:

> Refused to execute script from 'https://github.com/kevinchappell/formBuilder/blob/master/dist/form-builder.min.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

https://jsfiddle.net/9eLjjcsp/4/

How to fix?

**Comment by kevinchappell** [comment]
Github cannot be used as a CDN like that, you'll need to serve the file from your own server or use the file the demos use https://formbuilder.online/assets/js/form-builder.min.js

**Comment by maasha** [comment]
Thanks, would be good with links in the docs to these files. Or even to a jsfiddle demo.
