### ISSUE TITLE
formRender() on a single form renders all forms.

### ISSUE THREAD

**Issue by maasha** [kevinchappell/formBuilder#232]
I don't understand why both forms are being rendered in this example? I was expecting only `form1`
 to be rendered. Can this be done on a page with multiple forms?

```
<body>
  <section id="section1">
  </section>
  <section id="section2">
  </section>
</body>
```

```
  $(function() {
    var form1 = $('<textarea/>').attr('id', 'form1').appendTo($('#section1'))
    var form2 = $('<textarea/>').attr('id', 'form2').appendTo($('#section2'))
    var formData = '<form-template><fields><field class="form-control" label="Full Name" name="text-input-1459436848806" type="text" subtype="text"></field><field class="form-control" label="Select" name="select-1459436851691" type="select"><option value="option-1">Option 1</option><option value="option-2">Option 2</option></field><field class="form-control" label="Your Message" name="textarea-1459436854560" type="textarea"></field></fields></form-template>'

    $(formData).appendTo(form1)
    $(formData).appendTo(form2)

    $(form1).formRender()
  });
```

https://jsfiddle.net/mwuh6gxe/10/

**Comment by maasha** [comment]
Right, so this works as expected:

```
  $(function() {
    var form1 = $('<textarea/>').attr('id', 'form1').appendTo($('#section1'))
    var form2 = $('<textarea/>').attr('id', 'form2').appendTo($('#section2'))
    var formData = '<form-template><fields><field class="form-control" label="Full Name" name="text-input-1459436848806" type="text" subtype="text"></field><field class="form-control" label="Select" name="select-1459436851691" type="select"><option value="option-1">Option 1</option><option value="option-2">Option 2</option></field><field class="form-control" label="Your Message" name="textarea-1459436854560" type="textarea"></field></fields></form-template>'

		var opts = {
       formData: formData
    }

    $(form1).formRender(opts)
  });
```


https://jsfiddle.net/1koL4bm0/1/

**Comment by maasha** [comment]
After having a look at the code there seem to be an issue with the selector on line 425 in `master/dist/form-render.js`:

`fields = $('field', formData);`

When `formData` is null then all `fields` are selected - including fields from other textarea elements and even fields that has nothing to do with formRender!!!

**Comment by maasha** [comment]
Also, if `opts.formData` is not valid XML `jQuery.parseXML()` will return `null` and formBuilder will revert to the `'field` selection. A warning would be lovely ...

**Comment by kevinchappell** [comment]
These are great finds I plan to address today. I was able to replicate everything but haven't had a chance to get in the code to make the fix. 

There is a work around for the original issue though that I'll post but for sure the selector issue  needs to be addressed.

**Comment by kevinchappell** [comment]
Marking resolved as I am no longer able to reproduce since #243

**Comment by kevinchappell** [comment]
@bhavna11patidar this is unrelated to the original issue but subtypes need to be registered in formBuilder options on initialization. 

for example: 
```javascript
$('.form-editor').formBuilder({subtypes: {
  text: ['time']
}})
```

**Comment by bhavna11patidar** [comment]
Thank you for the solution but I want to create a input with type='time'
is it possible......

**Comment by bhavna11patidar** [comment]
How to Add multiple templates in Form Builder options...

**Comment by bhavna11patidar** [comment]
Hello Kalvin,
How can I reinitialize the Formbuilder without reloading the page
