### ISSUE TITLE
Capturing the user inputs from form-render view

### ISSUE THREAD

**Issue by tssutha** [kevinchappell/formBuilder#238]
Hi, 
Is there any inbuilt method to capture the user inputs from form-render view? I would prefer to store the user inputs in XML/JSON format, so that I could use  that to render the filled form when user tries to edit or provide Save and Submit Later Functionality. Is it possible to achieve with this plug in ? Is there any hack to do that? It will be really helpful.

**Comment by kevinchappell** [comment]
There is nothing built-in that handles this but its certainly doable and sounds similar to [this demo](http://codepen.io/kevinchappell/pen/kkYwyb) I just made. It would take a bit of work to setup the different input types like checkbox, textarea, select and text but this could be a nice feature for future versions.

**Comment by tssutha** [comment]
Thanks For you suggestion Kevin, We too had similar idea if it doesn't have in-build methods or else get the all form input field values during the form-submit event, save it as separate data file.

**Comment by tssutha** [comment]
this might be helpful for others as well, I am saving form filled data in a JSON file separately and Load it back when user try to edit the form again. 

//Save to JSON 
```
$('.rendered-form').submit(function (event) {
                var o = {};
                var a = $(".rendered-form :input").serializeArray();
                console.log(a);
                $.each(a, function () {
                    if (o[this.name] !== undefined) {
                        if (!o[this.name].push) {
                            o[this.name] = [o[this.name]];
                        }
                        o[this.name].push(this.value || '');
                    } else {
                        o[this.name] = this.value || '';
                    }
                });
                console.log(JSON.stringify(o));               
                event.preventDefault();
            });
```

//Load from JSON 
 ```
var frm = $('.rendered-form');          
            $.each(JsonData, function (key, value) {
                console.log('[name=' + key + ']');
                var $ctrl = $('[name=' + key + ']', frm);
                switch ($ctrl.attr("type")) {
                    case "text":
                    case "hidden":
                        $ctrl.val(value);
                        break;
                    case "radio":
                        $ctrl.each(function () {
                            if ($(this).attr('value') == value) {
                                $(this).attr("checked", value);
                            }
                        });
                        break;
                    case "checkbox":
                        for (var i = 0; i < value.length; i++) {
                            $ctrl.each(function () {
                                if ($(this).attr('value') == value[i]) {
                                    $(this).attr("checked", value[i]);
                                }
                            });
                        }
                        break;
                       
                    default:
                        $ctrl.val(value);
                }
            }); 
```

**Comment by kevinchappell** [comment]
@tssutha Great work, I could see this being very helpful to a lot of people. I made a quick jsfiddle using your code. https://jsfiddle.net/kevinchappell/4m64h0r6/

**Comment by petrakid** [comment]
Could someone provide an example of how to save user data from the rendered forms, via ajax, to a php form processor script?  I took the JSON example above and modified a bit, thinking that it would work, but it's not.  When I press the Submit button I added to the form, there is no response at all (no error in the browser console either)

`$('.rendered-form').submit(function(event) {
     var o = {};
     var formdata = $(".rendered-form :input").serializeArray();
     alert(formdata); // temporary to see if anythings happening
     // this is where I went from the JSON stuff to an ajax submit     
     $.ajax({
          url: 'thiswouldbemyurltoajaxscript',
          type: "POST",
          data: {
               'sform_id': thisidcomesfromaphpvariable,
               'sformdata': formdata
          },
          dataType: "HTML",
          async: false,
          success: function(data) {
               $('#submit_form').modal('show');
               $('#form_submit_modal_body').html(data);
          }
     });              
     event.preventDefault();
});`

Since I'm using Bootstrap 3, I want a modal to popup telling the user that their form was submitted.

**Comment by petrakid** [comment]
Answered my own question.  This will allow for using ajax to handle the form submission.  The actual php script for handling the submission is up to the user, I guess.  If there's an easier way to do this, I'm all ears, but this works fine and fast.

First I used the following to get the rendered form:
```
<script>
jQuery(document).ready(function($) {
  var fbRender = document.getElementById('fb-render'),
    formData = window.sessionStorage.getItem('contFormData');
  var formRenderOpts = {
    formData: formData
  };
  $(fbRender).formRender(formRenderOpts);
});
</script>
<form class="fb-render" id="fb-render"></form>
```
Then when the user clicks the Submit button in the form, the following is triggered:
```
$('.fb-render').submit(function(event) {
     var o = {};
     var a = $(".fb-render :input").serializeArray();
     $.each(a, function () {
          if(o[this.name] !== undefined) {
              if(!o[this.name].push) {
                  o[this.name] = [o[this.name]];
              }
              o[this.name].push(this.value || '');
          } else {
              o[this.name] = this.value || '';
          }
     });
     $.ajax({          
          url: '<?php echo $_SESSION['sitevars']['site_url'] ?>/plg/contactform/ajax.php',
          type: "POST",
          data: {
               'sform_id': '<?php echo $grmd['f_id'] ?>',
               'sformdata': JSON.stringify(o)
          },
          dataType: "HTML",
          async: false,
          success: function(data) {
               $('#submit_form').modal('show');
               $('#form_submit_modal_body').html(data);
          }
     });
     event.preventDefault();
});
```

**Comment by olaboyesherif** [comment]
Could someone provide an example of how to save user data from the rendered forms via c#

**Comment by Jojoshua** [comment]
Review https://github.com/kevinchappell/formBuilder/pull/749

**Comment by kevinchappell** [comment]
Closing since #750 was merged
