### ISSUE TITLE
Render form using json formData

### ISSUE THREAD

**Issue by markhorsman** [kevinchappell/formBuilder#243]
Hello,

I'm wondering if it is possible to render an HTML form using existing formData in JSON format.

I have stored the JSON representation of a form in my database and I can easily edit the form by passing it to a formBuilder instance using the formData option. 

But if I want to render the actual  form using the formRender method I need to pass in the formData. But all I have is JSON data.

How can I render the form using JSON only?

Below a code snippet:

`$fbEditor = $('.build-form').formBuilder({
                formData    : JSON.stringify(myJSONData),
                dataType    : 'json'
  });
var formData = $fbEditor.data('formBuilder').formData;

var $formPreviewModal = $('#form-preview-modal');
var formContainer = $formPreviewModal.find('.preview-container');
var formRenderOpts = {
            container: formContainer,
            formData: formData
 };

formContainer.formRender(formRenderOpts);
`

Thanks in advance.

Mark

**Comment by kevinchappell** [comment]
You'll need to set `dataType` to 'json' in formRender options, also you don't need `container` option when formRender is called on the container.

**Comment by llvasconcellos** [comment]
I had the same issue. Maybe this should be included in the docs.
