### ISSUE TITLE
Changing the types of fields available

### ISSUE THREAD

**Issue by ajberry** [kevinchappell/formBuilder#251]
Hi, 

I am looking to create  custom "form builder", where the items, instead of being forms are objects with properties that generate xml, sort of a workflow designer that exports xml. 

I am looking to use this as the base but extend it somewhat. Has anyone else done anything like this with this plugin? Or is the plugin not really suitedfor this sort of thing? 

Appreciate any advice as I am aware that it's not what the plugin was designed for.

**Comment by kevinchappell** [comment]
Hi there,
formBuilder is meant primarily to be a form creator/editor. While it is technically possible, the amount of effort to customize formBuilder to be a general purpose workflow editor would be large and it would probably be more efficient to just write one from scratch. There are a couple of decent open source workflow editors out there but unfortunately I can't think of their names at the moment.

Best of luck in your search and feel free to share your findings.  :)
