### ISSUE TITLE
formBuilder element sorting in bootstrap modal issue

### ISSUE THREAD

**Issue by herzcthu** [kevinchappell/formBuilder#259]
I'm trying to us formBuilder in bootstrap modal popup.
I've attached formBuilder to bootstrap modal's shown.bs.modal event.
Form shown correctly and working fine except sorting.
I've tried to add 
`$('.ui-sortable').sortable()`

but still not work. Am I doing wrong?

`$('#myModal').on('shown.bs.modal', function(event) {
var fbEditor = $(document.getElementById('fb-editor'));
var formBuilder = fbEditor.formBuilder().data('formBuilder');
})`

**Comment by kevinchappell** [comment]
@herzcthu Could you do something like this?  https://jsfiddle.net/kevinchappell/hpwt329e/

**Comment by herzcthu** [comment]
I'm sure that jquery-ui sortable is in place. Because sorting work if I use outside of modal in the same page.

**Comment by kevinchappell** [comment]
can you post a fiddle replicating the problem?

**Comment by herzcthu** [comment]
@kevinchappell  
Thanks for very quick reply. Now I found the problem. see this fiddle https://jsfiddle.net/herzcthu/voo8rdo5/1/

I've wrapped formBuilder into form-group div. When I remove that form-group class, sorting work perfectly.
