### ISSUE TITLE
Radio and checkbox group other option not working in form render

### ISSUE THREAD

**Issue by arunap** [kevinchappell/formBuilder#261]
When we click "other" in checkbox group or radio group, it showed text box beside that option. In latest plugin it is not functioning.

**Comment by kevinchappell** [comment]
Hello,
Can you provide steps to reproduce the issue? I did not encounter the issue on the demo site, see video: https://www.youtube.com/watch?v=S2H7YuzZfrE

**Comment by arunap** [comment]
Great.. I was doing exactly same steps that mentioned in your video. But the url was 
[http://formbuilder.readthedocs.io/en/latest/formBuilder/demos/toggle-builder/](url) 

It seems in https://formbuilder.online/ works as expected.

**Comment by kevinchappell** [comment]
The difference was formbuilder.online uses `dataType: json` and the demo still uses the xml version. The difference between the 2 dataTypes is that when parsed, xml class is `class` and json uses `className`. I forget the reason it was handled that way but i added a data sanitizer to formRender which solves the problem for now.
