### ISSUE TITLE
2 Drop Containers with single Controls

### ISSUE THREAD

**Issue by SainathBommisetty** [kevinchappell/formBuilder#265]
Hi Team,
I am new to this, Can any one help me in creating 2 drop containers with single controls window as show in the attachment? And users should be able to exchange the controls from drop container 1 to drop container 2.
![sample](https://cloud.githubusercontent.com/assets/17314739/19105982/9df1efba-8b02-11e6-9a7c-8a5849719d23.PNG)

Appreciate your help!

**Comment by kevinchappell** [comment]
Sounds like an interesting feature but would also require modifying or extending the current data structure of formBuilder. formRender would need to be updated as well to handle the new properties or structure and I'm unclear how the rendered form should look. What is the use case for multiple drop containers?

**Comment by SainathBommisetty** [comment]
This is how my requirement/use case is. I wanted to save space and want to have some sort of WYSIWYG form builder with some auto alignment/snapping feature. With current implementation when there are 10s of fields, we end up getting one form with a big vertical scroll bar. Instead, if we can effectively utilize the vertical space (in most of the cases we see forms in 2 columns based) and lay out the fields efficiently, that would be a perfect solution.

Pictorial representation below :

![current form builder renderer](https://cloud.githubusercontent.com/assets/17314739/19380473/1376c76a-9215-11e6-8027-628254e8268c.PNG)
![required form builder](https://cloud.githubusercontent.com/assets/17314739/19380486/1be7861e-9215-11e6-93d4-4f2891076663.PNG)
![required form renderer](https://cloud.githubusercontent.com/assets/17314739/19380490/20ca1b60-9215-11e6-85aa-d2f75da97204.PNG)

**Comment by kevinchappell** [comment]
Thanks for the explanation. I think to do this properly would require a major refactor to formBuilder's data structure and there is already a project that uses this new structure underway.

[![screenshot from 2016-10-14 12-13-42](https://cloud.githubusercontent.com/assets/1457540/19385664/b1180afa-9207-11e6-90db-1dc30ca7dc41.png)](https://www.youtube.com/watch?v=JZpLMGT1kRU)

This feature may eventually come to formBuilder but for now I simply to don't have the bandwidth to implement it. If someone would like to take the reigns on getting column support in formBuilder I'd be happy to provide guidance but for now I'd like to focus on only small features for formBuilder and getting Formeo to a point where it can be a full replacement.

**Comment by emailfourm450** [comment]
I have the same issue. Could you please explain to me how you fix it?
