### ISSUE TITLE
$(...).formBuilder is not a function in angularjs 

### ISSUE THREAD

**Issue by dennyjohnk** [kevinchappell/formBuilder#266]
Hi am trying to use this plugin with angulajrs 1.3 but this is giving me $(...).formBuilder is not a function error.Can you help me to solve this

**Comment by kevinchappell** [comment]
Can you confirm the dependencies are loaded?

This fiddle shows what you need.

https://jsfiddle.net/kevinchappell/nap5qcL4/

**Comment by dennyjohnk** [comment]
can you please show me a sample working example with angularjs 1.3.Am having some trouble setting it up.

**Comment by kevinchappell** [comment]
The example [here](https://jsfiddle.net/kevinchappell/nap5qcL4/) is using Angular 1.3.
