### ISSUE TITLE
Change defaultFields after form has been loaded

### ISSUE THREAD

**Issue by dinevillar** [kevinchappell/formBuilder#267]
Hello, thanks for this awesome plugin. I just wanted to know if there's a way to change the defaultFields after it has been set. I am binding the form builder to a drop down field and the form shown depends what value is set on the drop down field.

**Comment by dinevillar** [comment]
Nvm. I found the solution myself. I add a new action function (setData) for formBuilder. I wanted to put it to the _helpers object to follow your code strucuture but I found no reference to loadFields function there so I just hardcoded the function.

`// Make actions accessible
    formBuilder.actions = {
      clearFields: _helpers.removeAllfields,
      showData: _helpers.showData,
      save: _helpers.save,
      setData: function setData(data) {
        _helpers.removeAllfields();
        opts.defaultFields = data;
        formBuilder.formData = [];
        loadFields();
      }
    };`

**Comment by kevinchappell** [comment]
I have been thinking of adding a new option to prevent editing of default fields but in the meantime you can accomplish the same effect with something like [this](http://codepen.io/kevinchappell/pen/wzyvEz).
