### ISSUE TITLE
append field (json string) from database to current formBuilder formData

### ISSUE THREAD

**Issue by mcbmcb0** [kevinchappell/formBuilder#269]
I'm building forms where the user can also include questions already saved in a database as json strings (from jQuery formBuilder). I'm trying to append these db based json strings into the existing formData. 

I've experimented with concatenating the existing formBuilder.formData json string with the additional dbField json string, then deleting the existing instance of formBuilder and starting a new one (using the new concatenated formData string). this kind of works in an ugly way. 

I can see methods in form-builder.js that append new fields but they are not exposed for external use. is there a way to access these, or another way to push new fields into the existing formData?

and BTW formBuilder is a very impressive project - thanks for your work on it.

**Comment by kevinchappell** [comment]
That would be a good feature. I will add an `addField` method to Actions that takes 2 arguments, first betting the field config and optional second argument for index to insert it to.

**Comment by mcbmcb0** [comment]
that would be awesome.... looking forward to it
thanks

**Comment by Mohini9557** [comment]
hii , Kevinchappel  My question is when i used this code  to show my form it append form builder to show json form
setform: () => {
    const Option = {
      // dataType: 'json',
      formData: '[{"type":"file","required":false,"label":"File Upload","className":"form-control","name":"file-1653970324087-0", "access": false, "subtype": "file", "multiple": false }, { "type": "text", "required": false, "label": "Text Field", "className": "form-control", "name": "text-1653970327364-0", "access": false, "subtype": "text", "readonly": false }, { "type": "button", "label": "Button", "subtype": "button", "className": "btn-default btn", "name": "button-1653970332064-0", "access": false, "style": "default" } ]'
    }
    $('.build-wrap').formBuilder(Option)
  },
