### ISSUE TITLE
Add Tables element in formBuilder

### ISSUE THREAD

**Issue by farhansalam** [kevinchappell/formBuilder#270]
According our discussion on [Gitter](https://gitter.im/kevinchappell/formBuilder?at=57f7a3494fde7203141926ea). 
A `Table` elements needs to be added to our loved formBuilder.

We still have to decide between the `json` output of it.
**Option 1:**

``` JSON
{
    "type": "table",
    "value": [{
      "row": {
        "type": "tr",
        "columns": [{}, {}, ]
      }
    }]
  }
```

**Option 2:**

``` JSON
{
    "rows": {
      "rowIdOne": {
        "columns": [
          "columnIdOne"
        ]
      }
    },
    "columns": {
      "columnIdOne": {...}
    }
}

```

**Comment by kevinchappell** [comment]
This is a tough one and looking at it now I realize another difficulty will be the table content. Creating the table is one thing, but we'll then need a way to put content like fields and html in the cells. Considering how much work it will be, I think I'd rather add the feature to Formeo instead. Reasons being that it will be less work to create the editing UI, data structure is already the format we need and there is an unknown/ potentially low demand for the feature.

If others could weigh in on this it could give us a better idea if there is a strong need for this feature in formBuilder.

**Comment by egeersoz** [comment]
I'm looking for a WYSIWYG form builder, and the ability to handle tables is a big one. It will be used to add line items to purchase orders, invoices, etc.

**Comment by kevinchappell** [comment]
I'm happy to accept a PR that accomplishes this but for now I think this feature should be shelved. There are other editors than do similar things but currently formBuilder's data structure just isnt ready for drag and drops
