### ISSUE TITLE
Update for jQuery 3.1.1?

### ISSUE THREAD

**Issue by sandro-pasquali** [kevinchappell/formBuilder#271]
This is a great tool. However it seems to break if `jquery-3.1.1` is used: `TypeError: $sortableFields.sortable is not a function`

Any plans to update support for newer jquery libs?

**Comment by kevinchappell** [comment]
That error should only appear if jquery ui sortable is missing. I'll make sure the plug-in is jquery 3.0 company though.

**Comment by sandro-pasquali** [comment]
Ah, missed that jqui sortable in the bundle. That must be it. Thanks.
