### ISSUE TITLE
radio/checkbox group editor bug

### ISSUE THREAD

**Issue by sandro-pasquali** [kevinchappell/formBuilder#273]
It seems there's a bug in the edit mode for checkbox/radio groups.

In the demo I might add a checkbox group:

![screen shot 2016-10-07 at 1 02 50 pm](https://cloud.githubusercontent.com/assets/657552/19199168/b8027c00-8c90-11e6-82d0-e7c88c0a2550.png)

Two things: 

1. It seems that I can only remove (click the 'X') on the last item in the group. I would expect that I can 'roll over' or otherwise select *any* item in the group for removal.
2. Once I remove that last item via the 'X', the 'X' does not show up again on the remaining members of the group:

![screen shot 2016-10-07 at 1 03 05 pm](https://cloud.githubusercontent.com/assets/657552/19199214/f03ce52e-8c90-11e6-866d-fd492b335a04.png)

Also: If I start reordering the remaining items the 'X' magically appears again on the last item, but being in a drag/drop mode it can't click it, obviously.

I may just be missing something :) But it seems like a bug.

Thanks

**Comment by kevinchappell** [comment]
Thanks for reporting this however its technically a feature. In the early days of formBuilder like (3 -  4 years ago) there was an issue where users were able to remove all fields and save. It was eventually decided that checkbox and radio groups should not contain less than 2 options. Hiding the remove button on the first 2 options and adding a warning when form is saved and groups have less than 2 options was the solution.

**Comment by sandro-pasquali** [comment]
A for real "feature not bug" case!

Thanks. That makes sense. Adding more fields removes the "bug". And yeah, it seems there should be at least 2 in a group, so...
