### ISSUE TITLE
hide field options & set default values

### ISSUE THREAD

**Issue by bokodi-dev** [kevinchappell/formBuilder#275]
There is no way to remove field options (e.g. button name or button type).
Set default values to these options would be also good, e.g. the button default style could be primary.

**Comment by kevinchappell** [comment]
There is no api for removing fields but `userTypeAttrs` option should let you set default values. It may be tricky for button style though. 

Also may be time to extend `userTypeAttrs` to allow disabling attributes. Will look into it.

**Comment by PirunSeng** [comment]
@phiterf have you had any solutions to work around with your case yet? I'm on the way to approach like yours. What I've been trying so far is to get input text in the `option-label` to fill in `option-value` automatically. However, I cannot get the text from new added option of the `Add Option +` button.

@kevinchappell is there an event fired when the `Add Option +` is clicked, and that we can get the new added element? I cannot find in the docs as there is only `onclick` event of `max` of `date` field. Anyway, I have tried adding a `click` event of `'.add-opt'` to get the list elements which should be 4 including the new added one, but it shows only the previous 3 default list elements.
```
$('.add-opt').click ->
  console.log $('.sortable-options li').length # 3
```

**Comment by phiterf** [comment]
@PirunSeng my solution was to hide the value inputs and fill their values in the back-end of my application :'(

**Comment by PirunSeng** [comment]
@phiterf that's a way for now, anyway.

**Comment by fireHedgehog** [comment]
@phiterf hi, sir , could you tell me how do you hide the option-value input ? I cannot find any method to hide this. the only thing I can do is hide the entire options  thank you so much :)

**Comment by phiterf** [comment]
I did this using CSS if I'm not wrong.
