### ISSUE TITLE
Rows Attribute for TextArea

### ISSUE THREAD

**Issue by JyeGoodlet** [kevinchappell/formBuilder#280]
@kevinchappell 
I've added a rows attribute to textarea, just wondering if this something you want contributed. If so whats the process.

**Comment by kevinchappell** [comment]
Yeah that sounds pretty good and I'd be happy to take a look. Typically a pull request is opened against maser branch, reviewed then merged into master. The process for opening a PR is documented [here](https://help.github.com/articles/creating-a-pull-request/) but let me know if you have any questions.

**Comment by JyeGoodlet** [comment]
I've added a pull request. Its not much but does what i need. let me know if there is anything else you need.
#282

**Comment by kevinchappell** [comment]
Thanks for that. It's merged to master.
