### ISSUE TITLE
Can we add region as item in control-box as text area,text field etc...

### ISSUE THREAD

**Issue by itsmartyexpert** [kevinchappell/formBuilder#283]
Hello Kevin,

Can we add region as item in control-box section as text area,text field etc..., When we drag that region into drop area(i.e on left side) so all item should be drag inside in regions only not out side region.
Can we implement this.

Below is sample example in left side area :
**Region 1 (Personal Info)**
	Text field - Name
	Date field - BOD 
	Checkbox - Gender
**Region 2 (Address)**
        Text field - Address1
	Text field - Address2
	Text field - Address3
	Text field - City
	Select - Country	
        
Can you please suggest me how I can implement this.

Thanks in advanced.
Jack R.

**Comment by kevinchappell** [comment]
Another great potential feature and after looking at the code I don't think it should be too difficult to implement. I would start by refactoring `loadFields()` in src/form-builder.js so formData/defaultFields is looped once, then test call `prepFieldVars()` on either `formData[i]` or an input set as defined in the options. The `inputSet` option should be used to extend the controls as well.

**Comment by itsmartyexpert** [comment]
Thanks Kevin for quick reply,if you don't mind then please give me some code because I am newbie for this so it will be helpful to me,

Thanks once again.
Jack R.

**Comment by kevinchappell** [comment]
I'll have to get back to you on that but this is a good feature to be included in core so will definitely post some code when I get the chance.

**Comment by itsmartyexpert** [comment]
Thanks Kevin for this,Please let me know once you implement this.

**Comment by kevinchappell** [comment]
@itsmartyexpert [Feature implemented](https://github.com/kevinchappell/formBuilder/pull/285)

**Comment by itsmartyexpert** [comment]
Thanks Kevin,

But my requirement is different I want to drag and drop any number of items(dynamic) in side my Region/Container(Input set item).For example 
On Control Box : We have item name "Region"
Which we can drag into drop-able area, and after that we can drag any items like text field,hidden field,text area.... into region. 

Thanks and Regards,
Jack R.

**Comment by kevinchappell** [comment]
Hi Jack, I think I understand now. This sounds similar to columns and other nested field feature request like #265. Currently formBuilder doesn't support this and to implement correctly would require a lot of refactoring. For this reason I created a new form editing plugin called Formeo however its still a WIP.

formBuilder may eventually have this feature but for now I would like to focus on maintenance and finishing Formeo. It would be great if someone else added the feature to formBuilder but my bandwidth is currently too thin for any major feature development on formBuilder. 

Best of luck.

**Comment by Xsmael** [comment]
@kevinchappell why do you maintain two different project for almost the samething ? isn't that more work ?
and what's the difference between formBuilder and formeo?  wich one is more advanced ?
