### ISSUE TITLE
Rendering Select not loading the default selected value

### ISSUE THREAD

**Issue by kiranmai28mv** [kevinchappell/formBuilder#288]
Hello Kevin,
Thanks for the plugin.

I am storing the form data to mysql database. The selected option is stored properly in db as follows.
**<form-template>
	<fields>
		<field type="select" required="true" label="Select" placeholder="Select an option" class="form-control" name="persons" values="undefined">
			<option label="One" value="one" selected="true">One</option>
			<option label="Two" value="two" selected="false">Two</option>
		</field>
	</fields>
</form-template>**

but when I render this, the last option value(**Two**) is getting selected by default. Please help me in fixing the issue, Thanks in advance.

**Comment by kiranmai28mv** [comment]
the value stored in db is not displayed properly.
`<form-template>
	<fields>
		<field type="text" subtype="email" required="true" label="Username" placeholder="Enter your username" class="form-control" name="username"></field>
		<field type="text" required="true" label="Password" subtype="text" placeholder="Enter your password" class="form-control" name="password"></field>
		<field type="select" required="true" label="Select" placeholder="Select an option" class="form-control" name="persons" values="undefined">
			<option label="One" value="one" selected="true">One</option>
			<option label="Two" value="two" selected="false">Two</option>
			<option label="Three" value="three" selected="false">Three</option>
			<option label="Four" value="four" selected="false">Four</option>
		</field>
		<field type="button" subtype="submit" label="Login" class="button-input btn btn-default" name="submit" style="default"></field>
	</fields>
</form-template>`

**Comment by kevinchappell** [comment]
What version of formBuilder is this happening in?

**Comment by kiranmai28mv** [comment]
Version: 1.23.0

**Comment by kiranmai28mv** [comment]
I am facing the same issue for checkbox group and radio buttons also.
