### ISSUE TITLE
fieldRemoveWarn: true - error and won't remove field on 'yes'

### ISSUE THREAD

**Issue by mcbmcb0** [kevinchappell/formBuilder#290]
hello. 
with v1.21.3, when i set fieldRemoveWarn: true, then click 'yes' i get an error. firebug says:
`TypeError: can't convert undefined to object` at this line: `var o=[].slice.call().map(function(e){return e....`
which appears to be line 1285 of the non-minified version:
      `var availableIds = [].slice.call().map(function (field) {`

this happens on my development site and on the `http://formbuilder.readthedocs.io` at 'Docs » formBuilder Options » fieldRemoveWarn' here:
[(http://formbuilder.readthedocs.io/en/latest/formBuilder/options/fieldRemoveWarn/)]

i think its a bug, but maybe not? not sure how to proceed on this one.
thanks
Mike

**Comment by kevinchappell** [comment]
Sounds like a regression issue. I'll check it out today and fix.
