### ISSUE TITLE
Issue in defaultFields: []

### ISSUE THREAD

**Issue by Shivakrishnat** [kevinchappell/formBuilder#294]
When I pass multiple fields into defaultFields: []
the name is set correctly only for the 1st field as passed into defaultFields: [],
But, from 2nd field onwards name is set to default (like text-1476797123312)
Same in case of class, My classes will appear only for 1st field passed into defaultFields: [].
label and placeholder and others are working fine.

Please check

**Comment by kevinchappell** [comment]
Resolved in #294
