### ISSUE TITLE
How to get form items to store in mysql

### ISSUE THREAD

**Issue by q2amarket** [kevinchappell/formBuilder#30]
I am trying to get json formate of formBuilder and want to store into mysql database. Is there any way to do? There is no enough information on your docs. Thanks a lot

**Comment by Goddard** [comment]
+1 

would be great if I could add this to my php web app.  

I could store it as XML I suppose, but not as simple to deal with as maybe json.

**Comment by ivuorinen** [comment]
+1 from me too.

JSON format could also fix #112 and #111.

**Comment by demitrol** [comment]
+1

**Comment by dmitri-wm** [comment]
+1

**Comment by dsignr** [comment]
+1

**Comment by Amin-M** [comment]
I'm parsing the XML with PHP and storing it in MySQL. I use the following code:

`
        $form_data = $_POST['form_data'];
        $xml = simplexml_load_string($form_data);
        $result = [];
        if (isset($xml->fields) and isset($xml->fields->field)) {
            foreach ($xml->fields->field as $record) {
                $array = (array)$record;
                $record = current($array);
                $record['options'] = next($array); //additional options, needed for radio buttons, select lists...etc

                $result[] = $record;
            }
        }
        return $result;
`

**Comment by TeqExperts** [comment]
Nice solution @AminMkh , but i can't get option values ?

**Comment by AminMkh** [comment]
@TeqExperts  the plugin doesn't seem to support that, you can only save the options keys. It doesn't support a few other things like text fields default value, Just place holders for now.

**Comment by AminMkh** [comment]
@TeqExperts  actually I just checked the XML, it is there, it seems lost when im parsing it. I'll update my code, thanks a lot !

**Comment by TeqExperts** [comment]
That's great. ;) just share the code for me after updating, thank you !

**Comment by TeqExperts** [comment]
@AminMkh  I tried to get values but i can't, how did you do it?

**Comment by AminMkh** [comment]
@TeqExperts  I couldn't parse it either, whenever I use
```
simplexml_load_string($form_data);
```
The option values are lost, I will try to find another PHP parser. I'll keep you posted.

**Comment by dmitri-wm** [comment]
Sorry, don't know if it's ok to past link for ext project. But I've spent the whole day to find pretty formbuilder which works out of the box and provides json data (I'm using postgres json). http://dobtco.github.io/formbuilder/ , could not find repo with project so copied all files from this sample.

**Comment by bluespore** [comment]
+1

Much like @dmitri-wm I also discovered https://github.com/dobtco/formbuilder/ but it looks to be abandoned, so I have a preference to invest in a repo that is more actively developed, like yours @kevinchappell, but the JSON export is crucial for me.

**Comment by ameeradnan** [comment]
@AminMkh do let us know if you updated the parser...i'm kinda lost looking for this solution

thanks in advance

**Comment by screets** [comment]
Hey guys, we created a quick function for it 😌

	function fn_parse_form_data( $xml ) {
		$fields = array();
		$xml = simplexml_load_string( $xml );
		$xml = $xml->fields;
		
		if( isset( $xml->field ) ) {
			foreach( $xml->children() as $field ) {
				$name = (string) $field['name'];
				$fields[$name] = array();

				foreach( $field->attributes() as $k => $v ) {
					$fields[$name][$k] = (string) $v;
				}
			}
		}
		return $fields;
	}

Example usage:

	fn_parse_form_data( '<form-template><fields><field class="form-control text-input" label="Your name" name="text-1462909445840" placeholder="Your name" type="text" subtype="text"></field><field class="form-control text-area" label="Your message" name="textarea-1462882789673" placeholder="Enter your message" type="textarea"></field></fields></form-template>'  );


It should return:

    Array
    (
        [text-1462909445840] => Array
            (
                [class] => form-control text-input
                [label] => Your name
                [name] => text-1462909445840
                [placeholder] => Your name
                [type] => text
                [subtype] => text
            )

        [textarea-1462882789673] => Array
            (
                [class] => form-control text-area
                [label] => Your message
                [name] => textarea-1462882789673
                [placeholder] => Enter your message
                [type] => textarea
            )

    )

Best 😉

**Comment by him-developer** [comment]
I have tried all the PHP functions mentioned above to parse XML to JSON but none of them turned out a success. 
As most of above PHP code uses simplexml_load_string which returns a set of XML objects which is not very easy to parse and it become worse when you need to parse options of radios, select and checkbox. print_r and var_dump do not give full picture of the object  tree you got from simplexml_load_string.
Finally I have decide to convert XML to JSON on client side and then simply post the JSON only.
I have used below library from @abdmob for conversion to json.
https://github.com/abdmob/x2js

    var x2js = new X2JS();
    var xml_str = fbTemplate.value;
    var form_json =  x2js.xml_str2json(xml_str); 
    form_json = JSON.stringify(form_json["form-template"]["fields"]["field"]);

**Comment by kevinchappell** [comment]
There are a number of ways to accomplish data prep for your backend, which one depends on your specific app or website. I'm closing this issue as the discussion has strayed too far from topic and the topic is outside of formBuilder's scope.
