### ISSUE TITLE
name attribute stripping out underscores

### ISSUE THREAD

**Issue by jbyington** [kevinchappell/formBuilder#300]
```
  /**
   * Make strings safe to be used as classes
   *
   * @param  {string} str string to be converted
   * @return {string}     converter string
   */
  _helpers.safename = function(str) {
    return str.replace(/\s/g, '-').replace(/[^a-zA-Z0-9\-]/g, '').toLowerCase();
  };
```

safename helper is stripping out the underscores from my name attributes. first_name becomes firstname. the replaceing regex simply needs to account for the _, which it currently doesn't

**Comment by bluegaurav** [comment]
Please replace safename function with following code .
`/**
   * Make strings safe to be used as classes
   *
   * @param  {string} str string to be converted
   * @return {string}     converter string
   */
  _helpers.safename = function(str) {
    return e.replace(/\s/g, "-").replace(/[^a-zA-Z0-9\_-]/g, "").toLowerCase()
  };`
