### ISSUE TITLE
Changes in bower.json break bower install

### ISSUE THREAD

**Issue by herzcthu** [kevinchappell/formBuilder#304]
I found that you've added "jQuery UI Sortable" dependencies in bower.json starting from version 1.21.1.
It breaks bower install command because there is no package with such name in bower registry.
Correct name should be "jquery-ui-sortable".
To reproduce this issue, simply download version 1.21.1 and above version. Extract and CD to directory and run "bower install". command stop with the message
"bower ENOTFOUND     Package jQuery UI Sortable=jquery-ui-sortable not found".

If I change bower.json line number 28 to     "jquery-ui-sortable": "jquery-ui-sortable#*", command work perfectly.

**Comment by darkwisperer** [comment]
I also can confirm this issue.

**Comment by behram** [comment]
i confirm this issue too. `ENOTFOUND Package jQuery UI Sortable=jquery-ui-sortable not found` same exception

**Comment by kevinchappell** [comment]
Already fixed in the upcoming 1.25.0. Will reference issue in the pull-request that fixes.
