### ISSUE TITLE
Field Remove Warn z-index on Docs / Codepen

### ISSUE THREAD

**Issue by llvasconcellos** [kevinchappell/formBuilder#309]
The balloon / tooltip is hidden on the docs:
http://formbuilder.readthedocs.io/en/latest/formBuilder/options/fieldRemoveWarn/

![formbuilder](https://cloud.githubusercontent.com/assets/1710823/19832801/2bc239d2-9e0c-11e6-8174-2f3fad95d95c.png)

**Comment by kevinchappell** [comment]
warning should be smart enough to display in view. until that is fixed I have added a padding to the top of this demo.
