### ISSUE TITLE
Bower old version

### ISSUE THREAD

**Issue by alexbarnsley** [kevinchappell/formBuilder#31]
Was trying to install the most recent version of this from GitHub through Bower. The only options I was getting was 1.2 and 1.3. Resorted to Downloading a zip version but may be useful to others.

**Comment by alexbarnsley** [comment]
For reference, 1.5.3 is the most recent in bower.json

**Comment by kevinchappell** [comment]
my bad, should be fixed now. Also registered formBuilder as [bower module](http://bower.io/search/?q=jquery-formbuilder) so should have proper tag now.

**Comment by alexbarnsley** [comment]
Fantastic, thank you
