### ISSUE TITLE
showActionButtons, typeUserAttrs and typeUserEvents not on Overview

### ISSUE THREAD

**Issue by llvasconcellos** [kevinchappell/formBuilder#311]
The following defaults are not in the Docs forBuilder Options [overview page](http://formbuilder.readthedocs.io/en/latest/formBuilder/options/)

``` javascript
showActionButtons: true,
typeUserAttrs: {},
typeUserEvents: {},
```

**Comment by PirunSeng** [comment]
+1 If I'm not wrong, this open issue is similar to mine.
In my case, typeUserAttrs cannot be fully customized. I cannot find a way to hide or disable some attributes.

**Comment by kevinchappell** [comment]
@PirunSeng There is now a `disableAttrs` and `typeUserDisableAttrs`.
Overview page will be removed, it just repeats whats in the left menu anyways and is cumbersome to manually keep in sync.

**Comment by PirunSeng** [comment]
@kevinchappell sounds good. I'll give it a try once I need to upgrade the version. Thanks for your hard work.
