### ISSUE TITLE
Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by llvasconcellos** [kevinchappell/formBuilder#312]
for sortable controls:

``` javascript
$cbUL.children().each(function (index, element) {
    fieldOrder[index] = $(element).data('attrs').type;
});
```

form-builder.js:1192 Uncaught TypeError: Cannot read property 'type' of undefined

**Comment by kevinchappell** [comment]
These are fantastic. Thank you. I will try to get all these fixes in the next release.

**Comment by kevinchappell** [comment]
BTW how did you encounter this error?

**Comment by llvasconcellos** [comment]
http://formbuilder.readthedocs.io/en/latest/formBuilder/options/sortableControls/

just change the order of the controls to see.

**Comment by kevinchappell** [comment]
This appears resolved in current version.
