### ISSUE TITLE
TypeUserEvents Demo seems broken

### ISSUE THREAD

**Issue by llvasconcellos** [kevinchappell/formBuilder#313]
http://formbuilder.readthedocs.io/en/latest/formBuilder/options/typeUserEvents/

![formbuilder](https://cloud.githubusercontent.com/assets/1710823/19832997/5e14f370-9e11-11e6-96b3-5a989a7fb0e4.png)

**Comment by bkovacev** [comment]
@llvasconcellos No it's not - you have to select the password option first.

**Comment by llvasconcellos** [comment]
@bkovacev If it's not broken it's wrong. The label should be hidden as well.

**Comment by kevinchappell** [comment]
It is actually wrong. The demo was updated for 1.25.0, I'll change it back until release

**Comment by kevinchappell** [comment]
Fixed
