### ISSUE TITLE
[Request] Add custom buttons

### ISSUE THREAD

**Issue by llvasconcellos** [kevinchappell/formBuilder#314]
I would like a convenient way for me to add a "Cancel" button next to Save so I can close the form builder.
I'll do some jQuery magic for the time being.

**Comment by llvasconcellos** [comment]
It could also feature a way to disable some buttons like the view data button and not all of them.

**Comment by kevinchappell** [comment]
I was actually planning to do this. Primarily because the data button is not necessary in most use case. Looks like now is the time.

**Comment by kevinchappell** [comment]
This is doable now using `actionButtons` option, check out the [demo](https://kevinchappell.github.io/formBuilder/) and [docs](https://formbuilder.readthedocs.io/en/latest/formBuilder/options/actionButtons/) for more info
