### ISSUE TITLE
[Request] get data as javascript object

### ISSUE THREAD

**Issue by llvasconcellos** [kevinchappell/formBuilder#318]
formData is xml or json String but I really needed the javascript object itself. I'm using node.js / mongodb and stringfy / parse the json data string is pointless.
My advise for the next version is add getters and setters for all data in the object / class / component.
For now I altered form-builder.js and added a getData action:

``` javascript
// Make actions accessible
    formBuilder.actions = {
      clearFields: _helpers.removeAllfields,
      showData: _helpers.showData,
      save: _helpers.save,
      addField: function addField(field, index) {
        _helpers.stopIndex = $sortableFields[0].children.length ? index : undefined;
        prepFieldVars(field);
        document.dispatchEvent(formBuilder.events.fieldAdded);
      },
      removeField: _helpers.removeField,
      setData: function setData(formData) {
        _helpers.removeAllfields();
        _helpers.getData(formData);
        loadFields();
      },
///////////  RETURN DATA AS JAVASCRIPT OBJECT ////////////////
      getData: function(){
        return _helpers.prepData(document.getElementById(opts.formID))
      } 
    };
```

**Comment by kevinchappell** [comment]
Internally formBuilder uses an array of objects as the formData. You can get access to this from jQuery's `data`.

```
const formBuilder = $('.editor').formBuilder().data('formBuilder');

console.log(formBuilder.formData);
```

**Comment by llvasconcellos** [comment]
@kevinchappell formData is not an Array of objects. It's a String representation of this array. That's the point I'm talking about. I should be able to get this array and not the String. You should at least have both. Something like getData() and getJsonData().

**Comment by kevinchappell** [comment]
How about `getData(type)`? Where type is either xml, json, or js.

**Comment by llvasconcellos** [comment]
@kevinchappell That's great! Maybe let default to js since it's is the only that you don't need to apply any transformation to the data. Like:
```javascript
getData()  => js array of objects
getData('xml') => xml
getData('json') => json
```

**Comment by nareshananthoju** [comment]
I downloaded j query form builder project.In this i am getting code xml format .but i need code in html format .i replaced xml to html.but getting below error.What i have to do? can u solve fast?

Uncaught TypeError: fb.actions.html is not a function
    at Object.getData (demo.js:184)

**Comment by llvasconcellos** [comment]
@nareshananthoju if you want HTML can't you just do getElementById('something').innerHTML?
