### ISSUE TITLE
[BUG] Update after save form not working

### ISSUE THREAD

**Issue by aanandshekharroy** [kevinchappell/formBuilder#322]
Great library, only problem that I am facing is in updating the form after saving. Steps to reproduce:
1. Save the form in database using ajax.
2. Access the saved form (fetched from database)
3. Add another question to form
4. On clicking the new question, the dialog box of first question opens because the new question's id is similar to the saved form's first question

**Comment by kevinchappell** [comment]
Looking into this. It sounds like the ID isn't incrementing.

**Comment by kevinchappell** [comment]
I was not able to reproduce the issue. This demo [here](https://kevinchappell.github.io/formBuilder/) mimics saving the data to database.

1. add fields
2. click save
3. refresh
4. add another field of same type
5. toggle edit panel / dialog box

The above steps should be the same as yours but I am not seeing the issue. Could you create a jsfiddle illustrating the problem?
