### ISSUE TITLE
Request add FormData after formbuilder

### ISSUE THREAD

**Issue by anagas** [kevinchappell/formBuilder#323]
Hello,

is it possible that you add a function where it is possible to add the formData after the creation of the formBuilder?

Thanks.

**Comment by kevinchappell** [comment]
These features already exist but documentation for them will be coming in the next release.

-  actions
 - [`setData`](http://codepen.io/kevinchappell/pen/ozagKr)
 - [`addField`](http://codepen.io/kevinchappell/pen/LRAYyj)
 - [`removeField`](http://codepen.io/kevinchappell/pen/ozybgr)
 - [`clearFields`](http://codepen.io/kevinchappell/pen/LbYQoM?editors=0010)

**Comment by anagas** [comment]
Thanks, I am very excited about the new version:)
