### ISSUE TITLE
How to Save the form in database using ajax??

### ISSUE THREAD

**Issue by whymandip** [kevinchappell/formBuilder#324]

**Comment by nishamolcyriac** [comment]
In demo.js file, do the following steps
var data1=formBuilder.formData;
 $.ajax({
        url : 'saveForm.php',
         data :{test: data1},
        type: 'POST',
        success: function(response){
			alert('Successfully Inserted');
            },

In saveForm.php,
<?
include "connection.php";
$data=$_POST['test'];
 $addObj['content']=$data;
$saved = addRecord('exceed_formbuild', $addObj);
?>

**Comment by pavee92** [comment]
Hi could someone explain in step how to save the form in database using ajax and retrieve the saved form in a page ? Thanks
