### ISSUE TITLE
[IE Browser] Auto add "?XML:NAMESPACE" tag into string formbuilder

### ISSUE THREAD

**Issue by tritrumkt** [kevinchappell/formBuilder#327]
Hi ,
please  help me to solve error as the below 
HTML  
 <textarea name="fb-template" id="fb-template">
 </textarea>

I use XmlDocument  to read value of fb-template ,it "OK" on FF,Chrome.
But on IE , $(fb-template).val() have "<?XML:NAMESPACE PREFIX = "PUBLIC" NS = "URN:COMPONENT" />" string ,which auto adding.
So , XMLDocument cannot load it .
Please introduce me to remove the above string in $(fb-template).val()  .
Thanks.

**Comment by kevinchappell** [comment]
It sounds like IE may be adding that attribute but there are better ways to get the data now. http://formbuilder.readthedocs.io/en/latest/formBuilder/demos/data/

**Comment by tritrumkt** [comment]
Hi kevinchappell ,
Thank you for your comment.
I've seen the link but not solved my problem.
The result:
![2016-11-21_103434](https://cloud.githubusercontent.com/assets/23494434/20469896/24157e16-afd6-11e6-963f-bbb1dd892bd6.png)

Please help me to solve it.
Thanks.

**Comment by priyesh875** [comment]
Hi @tritrumkt,

i had the same issue and i have resolved this issue by adding below line in form.builder.js.
Line 2406  xmlField = _helpers.markup('field', fieldContent, xmlAttrs);
add below line, it will resolve this.
Line 2407  xmlField.getElementsByTagName("field");

Review below link for your reference.
http://jsfiddle.net/K72vD/

**Comment by kevinchappell** [comment]
resolved in v2.2.2
