### ISSUE TITLE
How to save rendered form with values

### ISSUE THREAD

**Issue by saranvarma** [kevinchappell/formBuilder#328]
Hi

I want to render the form , after that if user fills the form with some data , i want to save that data along with each field labels. Please let me know how can it be achieved for all field types of that form.

**Comment by almantasr** [comment]
Interested too. Is it possible to pass data object so saved field values would be displayed and edited?

**Comment by dukechem** [comment]
I'm trying to figure out something similar... based on answers to various form questions, I'd like to display a few lines of plain text that could be copy/pasted into a conf file (namely smartd.conf)... 
With a simple html form, you can display submitted values as show by example here:
[http://stackoverflow.com/questions/15447889/display-html-form-values-in-same-page-after-submit](http://stackoverflow.com/questions/15447889/display-html-form-values-in-same-page-after-submit)

**Comment by kevinchappell** [comment]
Saving data is a little outside the scope of formBuilder however this can be accomplished using FormData Object. See: https://developer.mozilla.org/en/docs/Web/API/FormData
