### ISSUE TITLE
SyntaxError: missing ; before statement

### ISSUE THREAD

**Issue by tknazn** [kevinchappell/formBuilder#33]
The formbuilder works fine locally. However when I tried to push it to prod, I encountered a Syntax issue in the form-builder.js
How do I solve this issue? 

 ```javascript
 238        if (fieldClass.match(/(select|checkbox-group|radio-group)/)) {
 239          previewData.values = [];
 240  
 241          $('.sortable-options li', field).each(function() {
 242            let option = {};
      ==============^
      SyntaxError: missing ; before statement
 243            option.selected = $('.select-option', $(this)).is(':checked');
 244            option.value = $('.option-value', $(this)).val();
 245            option.label = $('.option-label', $(this)).val();
 246  
 247            previewData.values.push(option);
 248          });
 249        }
```

**Comment by kevinchappell** [comment]
The presence of that `let` makes me think this may be a source file. Can you confirm you're uploading the files from /dist of the project?

**Comment by tknazn** [comment]
I believe so.

**Comment by tknazn** [comment]
Looks like you have changed to ```var``` in the latest version

**Comment by kevinchappell** [comment]
Babel should have transpiled to `var`, all the files in /dist are generated from the build process.

**Comment by tknazn** [comment]
It worked! Thank you Kevin.

**Comment by tknazn** [comment]
Happy New Year to you as well!

**Comment by kevinchappell** [comment]
Sweet! Happy new year :tada:
