### ISSUE TITLE
Checkbox doesn't change value

### ISSUE THREAD

**Issue by anagas** [kevinchappell/formBuilder#330]
Hello

i think i found a bug. I added a checkbox to my formbuilder and tried to change the value but it is has always the same result:

value{
0: "on"
}

**Comment by dukechem** [comment]
I think I see what anagas is getting at... in my tests, a check-mark causes "On" (not "on"). 
Anyways, the "On" value can be changed in formbuilder gui...
(Perhaps as a temporary work-around)  you can remove or change the "On" value like so:
1. Click on "Pencil/edit" icon 
2. In the "Value" field at bottom, select "On" and delete it. This should leave a grayed-out "value" entry. Then hit "Save" button.
And at this point the {} code button should no longer have the line -->  `"value": "On"`  
In my tests there is also no check in the box at this point.  

But adding "On" back in step 2 does not always make the check-mark appear on the form... I cannot figure out how to make the check-mark appear on the form, in the case we want the check-mark displayed as the default value. That is, the default value (On) would be used unless the end-user un-checked the box . 

Maybe I'm confusing the formbuilder-editor-display with the "live" preview that appears after I hit save?
But this behavior seems different than the Checkbox group...
For the "Checkbox Group", selecting any option correctly adds code `"selected": true` 
And as any option is de-selected, that line of code disappears for that option.

I'm assuming the single "Checkbox" should behave the same, but the check-mark is not always displayed if value is  "on" (or maybe vice versa?)  What does value mean, and what does "On" mean? That the box should display a check-mark as the default value?  With value "On" I do not always see a check-mark in the box. Maybe display of check-mark is not tied to the "on" value?

**Comment by kevinchappell** [comment]
This should be resolved now with current version (v2.2.2). Feel free to reopen if issue persists.
