### ISSUE TITLE
Editing the field attributes available in a input

### ISSUE THREAD

**Issue by NishadAhsan** [kevinchappell/formBuilder#333]
Hi,
How can I reduce the attributes available when building the form. For example, I don't want the user(who will build/edit the form) to edit the class attribute or maybe the max attribute. How can I achieve this?

Can I do this without editing the **from-builder.js**? 
If not, how should I modify it?

JS Skill: Still in learning phase.

Thanks.

**Comment by herzcthu** [comment]
`typeUserEvents: {
          text: {
            onadd: function (fld) {
              $('.name-wrap', fld).remove();
              $('.required-wrap', fld).remove();
              $('.access-wrap', fld).remove();
            }
          }
        },`

**Comment by kevinchappell** [comment]
Version 2 introduces [disabledAttrs](http://formbuilder.readthedocs.io/en/latest/formBuilder/options/disabledAttrs/) and [typeUserDisabledAttrs](http://formbuilder.readthedocs.io/en/latest/formBuilder/options/typeUserDisabledAttrs/)
