### ISSUE TITLE
How to add <img> tag at the form builder

### ISSUE THREAD

**Issue by arabica-enrique** [kevinchappell/formBuilder#338]
Hi. I wanna add the img tag to the form builder plugin. How to add custom controls at plugin source?
Best regards please.
Thanks

**Comment by nk-nareshkumar** [comment]
@simplyrichard can you please more explain or create a example.thankyou

**Comment by kevinchappell** [comment]
This is not supported out of the box but [Controls API](http://formbuilder.readthedocs.io/en/latest/formBuilder/overview/) makes adding it possible.
