### ISSUE TITLE
Number or Date is not Working on IE and Firefox

### ISSUE THREAD

**Issue by anagas** [kevinchappell/formBuilder#341]
Hello,

when i add a number in my formula i have no validation on it. I can write characters etc in number.  And when i add a number i have no datepicker in firefox.

I think that this is a bug and not my fault.

**Comment by ivuorinen** [comment]
This could be because of these (see Known issues):

- http://caniuse.com/#feat=input-number
- http://caniuse.com/#feat=input-datetime

**Comment by klevismino** [comment]
Hi @anagas 
Polyfills can solve this. E.g for the date: https://github.com/chemerisuk/better-dateinput-polyfill
