### ISSUE TITLE
Paragraph and Header are hard to re-order.

### ISSUE THREAD

**Issue by mstojanovv** [kevinchappell/formBuilder#347]
When place an paragraph or header its very hard to re-order i need to click a lot times to get the correct position so the li item to start dragging.

When the EDIT area is opened the field can be ordered like the rest ones easily.
I checked on the demo its the same too.

Any suggestions for this?

Thanks.

**Comment by mcbmcb0** [comment]
yes I've recently noticed this too... looking forward to a fix
thanks
