### ISSUE TITLE
set data 

### ISSUE THREAD

**Issue by jvm985** [kevinchappell/formBuilder#348]
Hi all,
I am saving many form-layouts in a database. When a user selects a form from a list, that form is loaded in formbuilder. When he clicks on the save button, the formdata is saved in the DB.

I can get all the indivdual parts to work fine, but when I put them together things start to fail.

My code is like this:
`
$(function() {
        var $fbEditor = $(document.getElementById('fb-editor'));
        var formBuilder = $fbEditor.formBuilder().data('formBuilder');

        $( document ).on( 'click', '.form-builder-save', function() {
            var formData = $('#frmType').serialize(); // some extras
            formData += '&layout=' + formBuilder.formData;
            $.ajax({
                url:'/dossiertypes.update',
                type:'post',
                processData: false,
                data:formData
            });
        });

       function load_dossier_type(id) {
            $.ajax({
                    type: "GET",
                    url: "/dossiertypes.ajax_type/"+id,
                    success: function(data){
                        var layout = $.parseJSON(data);
                        var options = { formData: layout[0].layout};
                        formBuilder = $fbEditor.formBuilder(options);
                    }
                });
          }
`
function load_dossier_type is called when a form in the list is selected by the user.

I am facing two problems: when loading a new form, a new formbuilder component is added to the existing one(s). I know about empty() and remove() but simply if(formBuilder) formBuilder.empty() doesn't work.
The second problem is that when saving the formdata, the value I need formBuilder.formData is undefined.

I tried many different ways and went through all the docs I could find, but to no avail. I always end up with some trouble.

So I was wondering if anybody could give me a hint in the right direction (js/jquery and formbuilder-wise). How would one generally do this (user selects form, forms get loaded and, on button click, saved)?

Thanks,

**Comment by kevinchappell** [comment]
Sorry just seeing this now. There is a setData function that may help: http://codepen.io/kevinchappell/pen/ozagKr
