### ISSUE TITLE
This is not a issue but a suggestion

### ISSUE THREAD

**Issue by onigetoc** [kevinchappell/formBuilder#35]
1- Add a placeholder text option for text field input.

2 - Is this compatible with Bootstrap?

Great plugin by the way

**Comment by kevinchappell** [comment]
1. Great suggestion. Next full release will include placeholder attribute and allow adding custom attributes. 

2. Yes.

**Comment by onigetoc** [comment]
@kevinchappell 
Great! Thank you

**Comment by onigetoc** [comment]
Another suggestion, 
the possibility to add button.
like a submit button, cancel button ect..

**Comment by kevinchappell** [comment]
Both suggestions have been implemented.
