### ISSUE TITLE
see: Field Types in Docs May Be Inactive

### ISSUE THREAD

**Issue by walkerdigital** [kevinchappell/formBuilder#353]
First off - this plugin is the bees-knees.  Thank you for that.

While trolling the documentation I was looking to see if there were any field types not available in the demo's and I see a link "see: Field Types" throughout the docs but it points towards the introduction page:  http://formbuilder.readthedocs.io/en/latest/

I just thought I would share in case this is an issue.  Perhaps you intended to demonstrate field types right there in the codepen?  

Thank You!

**Comment by kevinchappell** [comment]
Good catch. Will be removed in the next release, types are pretty self-explanatory. Thanks!
