### ISSUE TITLE
inputSets class and name attributes not loading

### ISSUE THREAD

**Issue by walkerdigital** [kevinchappell/formBuilder#355]
When an inputSet is specified are name and class supposed to be overwritten?

For instance in my input set json I've got the following:

          {
            type: 'text',
            name: 'partner-start-date',
            className: 'datepicker partner-start-date',
            label: 'Event Start Date',
          },

But the name and className attributes are ignored being replaced by 
class: form-control and name=text-######...

This seems to work on headings but not on select & text which I'm using.

Is this a bug or did I miss something in the documentation about how this works?

Thank You

**Comment by iCountSystems** [comment]
+1
We have the same issue.

**Comment by iCountSystems** [comment]
Any chance this will be sorted out soon?

**Comment by kevinchappell** [comment]
@iCountSystems working on this now.
