### ISSUE TITLE
Devide form builder container area in parts

### ISSUE THREAD

**Issue by mepawan** [kevinchappell/formBuilder#358]
Hi,
I want to divide form builder area into parts. Suppose I want to add two text box in same row. so I can create a row with two column and can add text boxes in both column. 

Is there anything possible like this ?

**Comment by ivuorinen** [comment]
Currently there are no ways to split single row into columns, but [Formeo](https://github.com/Draggable/formeo) (also by Kevin) answers this feature request.

Might be what you are looking for.

**Comment by galczo5** [comment]
Is there any ETA?

**Comment by brentkelly** [comment]
Not for formbuilder that I am aware of. As @ivuorinen points out - Formeo has a nice implementation of multiple columns although it is still under dev afaik.
