### ISSUE TITLE
How to get user id who  answer on questions generate by formbuilder

### ISSUE THREAD

**Issue by piyusharc** [kevinchappell/formBuilder#359]
Hello sir

i' ve developed a form using form builder in .net mvc. I'm a college student and developing a Survey based project for my final year.
The issue i'm getting that i have developed a form and make 10 questions with different different answer options [radio, multiple choice, selection from list etc..] using form builder. Now i wan every student to login and answer those 10 question and store it in mssql but unable to do it.
As i'm having student id but not having individual question id and with only formId . its not possible to track  what answer has been given by students.

please help me how to store form value dynamically, i 'm ready to host the code and give access.

**Comment by ivuorinen** [comment]
Hi there!

As formBuilder needs `<form>` element around it, you can add your own hidden field before your render target, for example like this

```html
<form method="post" action="/your/controller/method">
  <input type="hidden" name="student_id" value="[the student id]">
  <div id="render-target"></div>
</form>
```

And target the element like this:

```javascript
jQuery(document).ready(function($) {
  var fbTemplate = document.getElementById('fb-template');
  $('#render-target').formRender({formData: fbTemplate.value});
});
```

Please refer to [Basic formRender usage](http://formbuilder.readthedocs.io/en/latest/formRender/demos/basic/) in the docs.

Good luck with your studies!

**Comment by piyusharc** [comment]
Hello Sir 
Thank you so much for your previous response. I've a another query if u can help.

I'm using form builder for a college project, everything is working superb. I just want to know how to disabled or hide "Help text, Label and class" field while edit the radio ot checkbox button after Drag them to canvas.

please help

**Comment by ivuorinen** [comment]
You could use CSS rules to hide them. I don't think there's currently other ways to hide elements.

**Comment by piyusharc** [comment]
Thank you sir

will check and do it. 
By the way is there any way to restrict a single input type as a time.

Ex If i typed a question and drag a radio button, and now i'm trying any thing [like list, checkbox etc...] except radio button it occur an error .

So for a question a single input type gt fixed is it possible??
thanx in advance

**Comment by ivuorinen** [comment]
Currently no, as far as I know, but there should be one type for time as there is for date.

@kevinchappell Would it be possible to add it? I can look at making a PR if you are too busy.

**Comment by kevinchappell** [comment]
@ivuorinen that would be great if you could do that. I think it could be added as a subtype for date

**Comment by piyusharc** [comment]
Hello Sir

Can we do it now i mean can we disabled or restrict input types to one at a time .
