### ISSUE TITLE
Unable to Save from the downloaded sample

### ISSUE THREAD

**Issue by visitphanikumar** [kevinchappell/formBuilder#362]
Hi Team,
I have downloaded your plugin but there is no button to cpy the html of the controls, can you please help me with this I am stuck

**Comment by ivuorinen** [comment]
Do you mean like this?
http://formbuilder.readthedocs.io/en/latest/formBuilder/demos/data/

**Comment by kevinchappell** [comment]
@visitphanikumar also have a look at source code for the [website](https://formbuilder.online). If you just need a copy html button there is one there that could work as an example.
