### ISSUE TITLE
Read render values with internet explorer

### ISSUE THREAD

**Issue by anagas** [kevinchappell/formBuilder#365]
Hello,

I tired to run my application with IE but it fails when i render a form. The reason for that is that the formBuilder use a feature which IE doesn't support yet(Enhanced Object Literals). 

![image](https://cloud.githubusercontent.com/assets/12841639/22380305/48f54042-e4bd-11e6-83f4-9591c7adef98.png)

I get the error message here:

`      formData.forEach(function (value, key) {
                setValue(key, formData.getAll(key));
            });
`

Internet Explorer expects an Array but formData is a Object with a function forEach.

This is the function that make problems:
`fbUtils.forEach = function (array, callback, scope) {
  for (var i = 0; i < array.length; i++) {
    callback.call(scope, i, array[i]); // passes back stuff we need
  }
};
`

Do you have a fix for this issue or a workaround?

Regards

**Comment by ivuorinen** [comment]
Few background questions for testing: 
What version of Internet Explorer and formBuilder you are using?

In my implementation I'm not seeing this problem, but I'm running the code through webpack which could fix it for me.

**Comment by anagas** [comment]
Hello,

IE 11 Builder: 1.24.1
