### ISSUE TITLE
IE11/Edge multiple issues?

### ISSUE THREAD

**Issue by martijn189** [kevinchappell/formBuilder#369]
Can anyone confirm that IE11/Edge have issues with rendering the demo page? I have a project that uses this great looking form-builder v1.24.2, it works on Chrome and Firefox, but IE and Edge browser have two issues:

1) When rendering the form, in console it says: "Unable to get property 'length' of undefined or null reference. File: form-render.min.js (6,5314)". The textarea is shown and not replaced with form fields.

2) If i alter the code in form-render.min.js with: "(a[i].children || []).length" it can render, but only normal text fields are shown, no radio buttons.

Can anyone check if IE is working with the demo page (render form)

**Comment by kevinchappell** [comment]
Is there specific formData we can test with? I was working on some IE issues last night and would like to add yours to the list of IE fixes next release.

**Comment by martijn189** [comment]
Thanks for reply. I have testet this and i think i found a solution.

IE seems to use another DOM engine then for example Chrome and Firefox. The XML perser does not include any "children" objects. I have a proposed fix, it works for me, but i would like to know if it is correct, could you test verify?

**utils.js**
`
// OLD-CODE
// if (fields[i].children && fields[i].children.length) {
//	fieldData.values = fbUtils.parseOptions(fields[i]);
// }

// NEW-CODE
if (fields[i].childNodes && fields[i].childNodes.length && fields[i].nodeType == 1) {
	fieldData.values = fbUtils.parseOptions(fields[i]);
}

**Comment by martijn189** [comment]
It seems that even with above the IE 11 browser still has issues. Is there someone with better understanding of this code that can help resolve IE issues?

**Comment by martijn189** [comment]
In version v1.24.5 and using IE11, the radio/checkboxes are still not working. Could you please check if .children is supportet in IE or consider using .childnodes

**Comment by kevinchappell** [comment]
childNodes will include text as separate nodes. 

I've pushed a possible fix in #373. If the issue persists can you create a jsfiddle i can test on ie?

**Comment by ebredy** [comment]
Hi HiI need MI in timeind mind​you I'ma m
