### ISSUE TITLE
FormData with Required false

### ISSUE THREAD

**Issue by abugim** [kevinchappell/formBuilder#370]
When loading a data with a JSON that contains the required option set to false it loads de field but check the required option but not shows de red asterisc.

**Comment by kevinchappell** [comment]
Could you include a sample of the JSON formData? It sounds like it is functioning as intended. Required would need to be true to show the asterisk.

**Comment by abugim** [comment]
Here's the JSON:
```
[
   {
      "type":"checkbox",
      "required":false,
      "label":"Caixa de seleção",
      "className":"check-box id-276"
   },
   {
      "type":"checkbox-group",
      "required":false,
      "label":"Grupo de caixas de seleção",
      "className":"checkbox-group id-277",
      "values":[
         {
            "label":"Opção 1",
            "value":"id-278"
         },
         {
            "label":"Opção 2",
            "value":"id-279"
         },
         {
            "label":"Opção 3",
            "value":"id-280"
         }
      ]
   },
   {
      "type":"date",
      "required":false,
      "label":"Campo de data",
      "className":"calendar id-281"
   }
]
```
And here the form generated:
<a href="http://imgur.com/Sbm4eWG"><img src="http://i.imgur.com/Sbm4eWG.png" title="source: imgur.com" /></a>

Here the form have the Required option marked, when it should not:
<a href="http://imgur.com/c64mEMt"><img src="http://i.imgur.com/c64mEMt.png" title="source: imgur.com" /></a>

If the option is unchecked:
<a href="http://imgur.com/MkdJuwI"><img src="http://i.imgur.com/MkdJuwI.png" title="source: imgur.com" /></a>

**Comment by kevinchappell** [comment]
Is the formData being being edited outside of formBuilder? false property values should be stripped by formBuilder. In any case this is a bug.

**Comment by abugim** [comment]
It happens when I fetch the json for the form from the backend.

**Comment by nitrag** [comment]
Experienced this myself. I'm using previous saved `formData` and initializing formBuilder with `formData` on page load.

This is the line the breaks https://github.com/kevinchappell/formBuilder/blob/master/src/js/form-builder.js#L1039

```
if (!noMake.some(elem => elem === true)){
```
gets translated to 
```
if (!noMake.some(function (elem) {
        return elem === true;
      })) 
```
which returns true when it should not. 

I have modified it to be: (working)
```
if (values.required && values.required === true) {
```
Why not just simply the above? I don't understand what the `noMake` is trying to accomplish?

**Comment by abugim** [comment]
I keep experiencing the same problem.

**Comment by kevinchappell** [comment]
Actually going to leave this close, I am not longer able to reproduce the issue. @abugim What version formBuilder are you using?
https://jsfiddle.net/kevinchappell/v8mhwwaz/

**Comment by abugim** [comment]
I isolated the problem at the defualtFields. When loading with defaultFields it happens.

**Comment by kevinchappell** [comment]
@abugim im still not able to reproduce even with `defaultFields`

https://jsfiddle.net/kevinchappell/01k4fdwm/

**Comment by abugim** [comment]
O this example, when you open the Not Required field, the Required checkbox is selected

**Comment by kevinchappell** [comment]
ok i see what you mean, in the edit panel required is checked but shouldnt be. reopening...
