### ISSUE TITLE
How to remove/hide the attribute for each field

### ISSUE THREAD

**Issue by nk-nareshkumar** [kevinchappell/formBuilder#374]
Hi, i am looking for option from where i can remove/hide the attributes for each field.
like class, Value, Required, Toggle etc.. i want to remove the class first.

please see screen shot.
 http://www.awesomescreenshot.com/image/2214890/f3a500093ecdc334f08376295f324941

**Comment by nolantait** [comment]
#366 Is the current answer to the issue, use CSS until the API includes the feature.
