### ISSUE TITLE
Issue in add radio button in typeUserAttrs

### ISSUE THREAD

**Issue by bluegaurav** [kevinchappell/formBuilder#375]
Hello, I want to add a radio button group in form-builder. I have tried to assign a radio button object to "typeUserAttrs" but it just creates an input box

I have refer [http://formbuilder.readthedocs.io/en/latest/formBuilder/options/typeUserAttrs/](http://formbuilder.readthedocs.io/en/latest/formBuilder/options/typeUserAttrs) i have add drop down successfully but unable to create radio button

**Comment by kevinchappell** [comment]
I believe only <select> and input fields are supported with `typeUserAttrs`. A select field functions similarly to a radio group, would that be an option?

**Comment by kevinchappell** [comment]
just following up on this. I did try it out however radio groups are not yet available in `typeUserAttrs`. The api for `typeUserAttrs` would have to be expanded to allow assigning specific field type rather than parsing data types.
