### ISSUE TITLE
Charge select options with json

### ISSUE THREAD

**Issue by eder-toledo** [kevinchappell/formBuilder#377]
How to load the options of a select based on catalogs, example: show the option to load a select with countries or states, the user selects one of these and the select loads the options based on the corresponding json.

**Comment by kevinchappell** [comment]
This is possible with `typeUserAttrs` and `typeUserEvents`. Could you provide some sample JSON data?

**Comment by eder-toledo** [comment]
Thanks @kevinchappell, I have read the documentation, and thinking of solving your advice.
Think in simple options starting with uuid and name properties, attach json example.

[json.txt](https://github.com/kevinchappell/formBuilder/files/845004/json.txt)
