### ISSUE TITLE
IE Rendering Issue

### ISSUE THREAD

**Issue by bnordstrom** [kevinchappell/formBuilder#38]
In IE the logic in form-render.js for the radio group and select controls are generating labels with undefined as the label contents.  This is happening due to an issue in IE when you try to access innerHTML on the dynamically generated elements.  http://stackoverflow.com/questions/8999998/javascript-innerhtml-is-not-working-for-ie

Fix on my end was to change:
```
optionsMarkup += '<option ' + optionAttrsString + '>' + el.innerHTML + '</option>';
```
to
```
optionsMarkup += '<option ' + optionAttrsString + '>' + optionAttrs.value + '</option>';
```

And:
```
optionsMarkup += '<input ' + optionAttrsString + ' /> <label for="' + optionAttrs.id + '">' + el.innerHTML + '</label><br>';
```
to:
```
optionsMarkup += '<input ' + optionAttrsString + ' /> <label for="' + optionAttrs.id + '">' + fieldAttrs.value + '</label><br>';
```

Thanks for the library its been quite useful.

Brian

**Comment by kevinchappell** [comment]
@bnordstrom Thanks for finding that. Updating now.
