### ISSUE TITLE
How to know drag event fired or firing

### ISSUE THREAD

**Issue by nk-nareshkumar** [kevinchappell/formBuilder#382]
Is there any way or method which can tell that a drag event fired or firing.
What i want to do : I want to add a background color option in button element. 
so when the drag event fire i will add my jquery in the button attributes to show there color picker..so when button dropped in form area then it will have a color picker there.. 
So i can select my own button color instead of pre defined booststrap classes..

What you say ?

**Comment by wizaerd** [comment]
I too would be interested in seeing some events exposed... Using the afore mentioned drag event, we can tell if the form area is "dirty", thereby enabling/disabling certain buttons in the UI.

**Comment by wizaerd** [comment]
@nk-nareshkumar 
I dug through the code a bit and it looks like there are some events you can use... Not the dragend event, but there is a field added event, which you can subscribe too...

var event = new Event('fieldAdded');
document.addEventListener('fieldAdded', function(e) { alert("FieldAdded"); });

This gets me what I need, in terms of determining if the builder form is dirty or not...

**Comment by nk-nareshkumar** [comment]
thank you.. you are right.. i also checked the code .. 

Anyway what is your means about form dirty or not ?not getting your whole purpose :)

**Comment by wizaerd** [comment]
From a programmatic perspective, a form is "dirty" if the user has added data to it.  I have a menu bar with different functions that are enabled or disabled based on whether the user has in fact dropped a field onto the form, thus starting the form building process.  The Save, Clear, and Preview buttons are disabled if there is nothing in the "form", whereas once a user has dropped a new form field onto the form, these menu buttons get enabled.  It's not a technical term, but is an industry accepted term for knowing when the user has modified something.

**Comment by tacman** [comment]
On a related note, I'd like to intercept the event before the field is added and prompt for a field name, validate that it doesn't already exist, etc.  I can do this by adding a listener to onadd in typeUserEvents, but that requires having a separate listener for each type.  Is there a way to listen for any add event?  I'd also like to be able to grab the field and change the name and text.

```javascript
            typeUserEvents: {
                text: {
                    onadd: function(fld) {
                        var name = prompt('Field name');
                        console.log(fld);
```

**Comment by lucasnetau** [comment]
Attach to the * all control type selector
  ```js
            typeUserEvents: {
                '*': {
                     onadd: function(fld) {
                         var name = prompt('Field name');
                         console.log(fld);
 ```

**Comment by lucasnetau** [comment]
You can detect a control being dragged over with

`$( ".cb-wrap" ).on( "sortstart", function( event, ui ) { console.log(event) } )`

You can detect when a field is added to the stage or it is reordered via dragging with

`$( ".stage-wrap" ).on( "sortupdate", function( event, ui ) { console.log(event) } ) `
