### ISSUE TITLE
Generate form vertically using this form builder

### ISSUE THREAD

**Issue by nk-nareshkumar** [kevinchappell/formBuilder#383]
Hi,
this form builder is only generating form horizontally..
when vertically form will come  ?

**Comment by nk-nareshkumar** [comment]
@kevinchappell can we get a option to generate vertical form this form builder ?

**Comment by kevinchappell** [comment]
I think this would be a great feature for someone to implement as long as it doesn't break compatibility however this is not a feature I will be adding to formBuilder. Please see my [reason 1 from my comment on why](https://github.com/kevinchappell/formBuilder/issues/391#issuecomment-285820203).
