### ISSUE TITLE
How to save and render multiple forms?

### ISSUE THREAD

**Issue by jsghines** [kevinchappell/formBuilder#385]
If you follow the[ demo on adding new pages](http://formbuilder.readthedocs.io/en/latest/formBuilder/demos/tabs/), how could I save and render all of them.

**Comment by ankurk91** [comment]
@jsghines 
Did you checked JS code on that example -
```js
$(document.getElementById('save-all')).click(function() {
    var allEditorValues = $('.fb-editor').map(function() {
      return $(this).data('formBuilder').formData
    });
   // Do ajax here 
    console.log(allEditorValues);
  });
```
That example have a 'Save All' button on bottom. 
It is up to you how you store and render the form.
All you need to do is loop through all **pages** and collect the form data from there.

**Comment by jsghines** [comment]
I did, and I should have removed the saving line because I had figured that much out, but the question was more asking if there was a way to render the pages.

**Comment by kevinchappell** [comment]
you would have to call multiple instances of formRender, one for each formData.
