### ISSUE TITLE
Nonrelated textbox changes when using formBuilder

### ISSUE THREAD

**Issue by wizaerd** [kevinchappell/formBuilder#386]
So I have a weird thing happening that I cannot quite figure out why. I start with a basic form, I have a div with two textboxes for form meta data that initially do not have any data values in them.  When I drag a new textbox over onto the screen/canvas/form area, and select the password type, one of those afore mentioned fields, which should not be tied to this form, changes to a yellow textbox populated with my username. Whaaa...?

![start](https://cloud.githubusercontent.com/assets/2036918/23675564/fcd9d450-0336-11e7-8213-10b1a7eb19b2.png)
![afterpassword](https://cloud.githubusercontent.com/assets/2036918/23675569/01223ade-0337-11e7-8d33-c963360186a6.png)

I'm not really doing anything via javascript yet, don;t even have the form saving methods hooked up yet.

Any ideas?

**Comment by wizaerd** [comment]
For the record, I am able to duplicate it with the most basic of HTML pages...

`<html>

<head>
	<script src="modernizr-2.6.2.js"></script>
	<script src="jquery-3.0.0.js"></script>
	<script src="jquery-ui.js"></script>
	<script src="form-builder.js"></script>
	<link href="form-builder.css" rel="stylesheet" />

	<title>jQuery formBuilder/formRender Demo</title>
</head>

<body>
  
  <input type="text" id="test"/>
  <div id="fb-editor"></div>
 
 <script type="text/javascript">
	var $fbEditor = undefined;
    var formBuilder = undefined;

	$(document).ready(function () {
        $fbEditor = $(document.getElementById('fb-editor'));
		formBuilder = $fbEditor.formBuilder().data('formBuilder');
	});
  </script>
</body>

</html>
`

**Comment by wizaerd** [comment]
More information.  I wish I could solve this myself, but alas, it's a little bit out of my league... I'm usually a C# developer...
Anyways, when the text field in the formBuilder gets set to a password type, it seems to automagically set the value to my actual password, probably via the Chrome password keeping and/or logging functionality...  I don't know why that resets the non-related form to my username automagically either.
But in either case, I'm not sure anything can be done about it, but if not, I may just have to remove the password type from the available formfields, which I don;t really want to do, or there needs to be some way it can create a password text field without it actually containing the users password, as well as altering other non-related form fields.

**Comment by kevinchappell** [comment]
This is related to Chrome autofill. Chrome attempts to fill in commonly used form fields with data it thinks should be there. You can create a chrome extension (one may already exist) to prevent this from happening on specific domains. In your case you want to stop autofill on localhost. Have a look [here](http://superuser.com/questions/523877/can-i-disable-google-chrome-autofill-only-for-localhost) for more info. 

Closing for now though as it is not related to formBuilder.

**Comment by wizaerd** [comment]
I agree, it's not a formBuilder issue, however because it does happen, may I request a new exposed option for the formBuilder options to selectively disable certain subtypes? Right now I took the password option out of the subtype array in the code, but if I update obviously I'll have to re-comment it out, or perjhaps set it as a formBuilder option?

**Comment by kevinchappell** [comment]
Absolutely, in fact next version has custom subtypes as option. There you would be able to define your own, excluding the `password` in your list. 

This issue did shed light on what i would consider a user experience though. When setting password subtype the value input should change to type of password. There is a codepen demo showing how to do this via `typeUserAttrs` option but this is something that should be built-in.
