### ISSUE TITLE
How can I change the formData dynamically?

### ISSUE THREAD

**Issue by wizaerd** [kevinchappell/formBuilder#388]
When my page loads, I have the formBuilder visible via the normal methods, but initially it's empy, as desired.  I also have a series of links to the left of the screen that the user can click on, which should load the saved form data into the formbuilder.  If the user selects a different one, the previous entries should be cleared out and new formData loaded.  Right now I'm doing this by clearing out the contents of the fb-editor div, and then reinstantiating it with a new options array containing the form data:

`function pbSelect(e) {
	var dataItem = this.dataItem(e.item);

	// if the id is not the topmost "guid"
	if (dataItem.id !== "@TopicStudioItem.ACTIVE_GUID" && dataItem.id !== "@TopicStudioItem.INACTIVE_GUID") {
		formBuilder.actions.clearFields();

		$("#topicTitle").val(dataItem.Title);
		$("#topicDescription").val(dataItem.Description);

		options = {
			dataType: "json",
			editOnAdd: true,
			disableFields: [
				'autocomplete',
				'file'
			],
			controlOrder: [
				'text',
				'textarea'
			],
			sortableControls: false,
			stickyControls: true,
			showActionButtons: false,
			formData: dataItem.FormData
		};

		$("#fb-editor").html("");
		formBuilder = $fbEditor.formBuilder(options).data('formBuilder');

		if (dataItem.FormData) {
			ToggleMenus(true);
		}
	}
}`

This doesn;t seem very efficient to me, and want to just change the loaded formData itself.  Is there a better way? I initially tried just writing the new formData to formBuilder.formData, but that did nothing.

**Comment by kevinchappell** [comment]
Surprised I missed this issue. You can load new data with `actions.setData(formData)` http://codepen.io/kevinchappell/pen/ozagKr
