### ISSUE TITLE
Paragraph style with embedded HTML

### ISSUE THREAD

**Issue by wizaerd** [kevinchappell/formBuilder#389]
Assume I have a paragraph element in the formBuilder, and assume I have embedded HTML in it.  When I close the component options screen, the embedded HTML text shows appropriately rendered.  However, when I preview the form, I just see the embedded HTML as text instead of being rendered.  For my preview function, I am using the preview method as outlined in the documentation for the formBuilder:

http://formbuilder.readthedocs.io/en/latest/formRender/demos/preview-popup/

For the embedded HTML, to test I merely added a span tag, with a style to change the text within red.  As I said, in the formBuilder it shows, but when I preview or show my actual form, it is not rendered.

**Comment by musla** [comment]
Got the same need. It would be fine to have the option to insert HTML element type. Perhaps to add another "Paragraph" element type span or div that would allow to insert any HTML?

I certainly need to be able to insert at least line breaks into the Paragraph element. Bold would be fine as well. 

Any option to do it in current version?

**Comment by nitrag** [comment]
Ditto, on the line breaks in paragraph! Following.

**Comment by nitrag** [comment]
I'm not git savvy with all the rebasing so I think the existing #246 PR isn't compatible? I made my own off master:

https://github.com/nitrag/formBuilder/tree/nitrag-html-fields

Let me know if you want me to submit a separate PR.
