### ISSUE TITLE
Checkbox in rendered screen incorrectly placed

### ISSUE THREAD

**Issue by wizaerd** [kevinchappell/formBuilder#390]
Using the same preview code as what is in the docs, when previewing my form, on single checkboxes, the label is on the next line below the actual checkbox, and if there's a form field control after it, it is on the same line as the checkbox label.  See image:

![checkbox](https://cloud.githubusercontent.com/assets/2036918/23812950/d265b4b8-0599-11e7-9beb-e621ebab8898.png)

**Comment by wizaerd** [comment]
In case you want to see that actual javascript... As I said, it's pretty much torn from the example shown in the documentation:

`function showPreview() {
	var formRenderOpts = {
		dataType: "json",
		formData: formBuilder.formData,
		render: false
	};

	var renderedForm = new FormRenderFn(formRenderOpts).markup;
	var theHtml = getPreviewHtml().replace("{RENDEREDFORM}", renderedForm);
	var formPreviewWindow = PopupCenter("", "formPreview", 640, 480, { toolbar:0, resizable: 1, location: 0, menubar: 0, scrollbars: 1});
	formPreviewWindow.document.write(theHtml);

	var style = document.createElement("link");
	style.appendChild(document.createTextNode(""));
	style.setAttribute("href", "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css");
	style.setAttribute("rel", "stylesheet");
	style.setAttribute("type", "text/css");
	formPreviewWindow.document.head.appendChild(style);
}

// opens a new browser window center screen regardless of which 
// monitor (dual monitors) is the active monitor
function PopupCenter(url, title, w, h, opts) {
	var _innerOpts = '';
	if (opts !== null && typeof opts === 'object') {
		for (var p in opts) {
			if (opts.hasOwnProperty(p)) {
				_innerOpts += p + '=' + opts[p] + ',';
			}
		}
	}
	// Fixes dual-screen position, Most browsers, Firefox
	var dualScreenLeft = window.screenLeft != undefined ? window.screenLeft : screen.left;
	var dualScreenTop = window.screenTop != undefined ? window.screenTop : screen.top;

	var width = window.innerWidth ? window.innerWidth : document.documentElement.clientWidth ? document.documentElement.clientWidth : screen.width;
	var height = window.innerHeight ? window.innerHeight : document.documentElement.clientHeight ? document.documentElement.clientHeight : screen.height;

	var left = ((width / 2) - (w / 2)) + dualScreenLeft;
	var top = ((height / 2) - (h / 2)) + dualScreenTop;
	return window.open(url, title, _innerOpts + ' width=' + w + ', height=' + h + ', top=' + top + ', left=' + left);
}

// this is outside of the minified script because the HTML tags caused issues with the minification
function getPreviewHtml() {return "<!doctype html><title>Form Preview</title><body class='container'><h1>Preview</h1><hr>{RENDEREDFORM}</body></html>";}
`

**Comment by wizaerd** [comment]
Sorry for the horrible code formatting... the code tags here just don;t want to cooperate...

**Comment by kevinchappell** [comment]
@wizaerd thanks for the excellent write-up. This looks like a css conflict. Can you share the link of the demo you mentioned? I was not able to reproduce on the website.

**Comment by wizaerd** [comment]
Sure thing @kevinchappell The preview code I'm using is from the documentation shown at http://formbuilder.readthedocs.io/en/latest/formRender/demos/preview-popup/

The only styles applied to the preview form are the same ones from the preview demo mentioned above...  I'll try it without the styles and see if it makes a difference.

**Comment by wizaerd** [comment]
Removing the stylesheets from the preview does correct it, however another issue popped up because of it... two checkbox elements in the form builder, 2 separate checkboxes mind you not the checkbox group, come out on the same line when there are no styles applied.

![checkbox_2](https://cloud.githubusercontent.com/assets/2036918/23813525/7da1dbfc-059c-11e7-8990-c80048976c99.png)

**Comment by kevinchappell** [comment]
After some review i see this is for sure a formRender bug. The label should wrap the input and the form-group is missing the 'checkbox' class.
