### ISSUE TITLE
sitckyControls act a bit wonky

### ISSUE THREAD

**Issue by wizaerd** [kevinchappell/formBuilder#392]
I'm truly sorry for bothering you yet once more today...  But now I'm having an issue with stickyControls really behaving badly.  Now granted, I am embedding the formBuilder inside of another client side component, from Telerik, the Splitter.  The formBuilder UI is inside of a div which is inside of the splitter.  Eventually as I add more and more formfields, eventually the control palette jumps completely out of the splitter panel and the div. 

![stickycontrols](https://cloud.githubusercontent.com/assets/2036918/23816911/b2093ce0-05ac-11e7-9d50-fa8d7362428d.png)

I don't really think it has anything to do with the splitter, and unfortunately I need to keep using it in order to build this thing out the way my users want it.

**Comment by kevinchappell** [comment]
This is one of the "nuuumerous bugfixes" mentioned in my reply to #391. The fix may not directly address your issue but it does provide an option where instead of just setting `stickyControls` to `true` you can provide an object for positioning ie:
```
stickyControls: {
  enable: true,
  offset: {
    top: 120
  }
}
```

**Comment by wizaerd** [comment]
I don't know if it's too late to suggest this, but I'd like to suggest it anyways.... The canvas area be scrollable while the control palette remain stationary so instead of scrolling the whole thing, only the area where controls are being dropped scrolls.

**Comment by kevinchappell** [comment]
@wizaerd this is a good idea but would have to be an option since not many fields will be visible at a time.
