### ISSUE TITLE
inputSet not working only IE11

### ISSUE THREAD

**Issue by sumandey121** [kevinchappell/formBuilder#393]
it shows me undefined 

  if (inputSet.showHeader) {
          var header = {
            type: 'header',
            subtype: 'h2',
            id: inputSet.name,
            label: inputSet.label
          };
          prepFieldVars(header, true);
        }
        inputSet.fields.forEach(function (field) {
          prepFieldVars(field, true);
        });

![untitled](https://cloud.githubusercontent.com/assets/7975413/23833621/68d49736-076e-11e7-93bf-030d9eab7873.png)

**Comment by ankurk91** [comment]
@sumandey121 
Can you make a [JSFiddle](https://jsfiddle.net/) or [plunker](https://plnkr.co/) to demonstrate your issue ?
