### ISSUE TITLE
Modify existing field type

### ISSUE THREAD

**Issue by ontop17** [kevinchappell/formBuilder#394]
Is there a way to modify a existing field type? For example I want to deactivate the "option-value" and deactivate the Access.

**Comment by ankurk91** [comment]
I did it using css
```css

/* Hide roles select box */
[id^=frmb-][id$='-form-wrap'] .frmb .form-field .form-group.access-wrap {
  display: none !important;
}

``

**Comment by ontop17** [comment]
Hi ankurk91, 
thank you for answer. I do not want to do this with CSS. Is there no way with javascript to do this?

**Comment by ankurk91** [comment]
I could not find any option to do that on official docs.
http://formbuilder.readthedocs.io/en/latest/
