### ISSUE TITLE
how to change json data's field(key) ?

### ISSUE THREAD

**Issue by abiaoLHB** [kevinchappell/formBuilder#395]
![github answer](https://cloud.githubusercontent.com/assets/11990911/23985553/b5ef4252-0a5a-11e7-8fe5-278f9eece327.png)

**Comment by abiaoLHB** [comment]
Is anybody there?

**Comment by abiaoLHB** [comment]
i want change the field in sourceCode.Don‘t use    for(var i=0;i<xxx;i++)

**Comment by kevinchappell** [comment]
formBuilder needs that property to know which field to create/render. Why does it need to change?

**Comment by ankurk91** [comment]
Why would some do that ?
