### ISSUE TITLE
how to use formBuilder in Angular2

### ISSUE THREAD

**Issue by terenceung** [kevinchappell/formBuilder#396]
I am new to Angular2, typescript, webpack.
I install the formBuilder through `npm install formBuilder`
when I use this in typescript `import 'formBuilder';`
the browser has error with `$sortableFields.sortable is not a function`
however, there is no index.d.ts or @types/formBuilder which support Angular2.
Is there any support or tutorial which I can follow to make the pure js works in my Angular2 project.

**Comment by ankurk91** [comment]
@terenceung 
form-builder require [jQuery-ui](https://www.npmjs.com/package/jquery-ui) to be pre-loaded.
You no need to load whole jQuery ui. Only following modules should be sufficient.

```js
require('jquery-ui/ui/widget.js');
require('jquery-ui/ui/data.js');
require('jquery-ui/ui/scroll-parent.js');
require('jquery-ui/ui/widgets/mouse.js');
require('jquery-ui/ui/widgets/sortable.js');
```
[Customize](https://jqueryui.com/download/#!version=1.12.1&components=101000000100000010000000010000000000000000000000) jQuery-UI
