### ISSUE TITLE
Can I get the result of the form in XML?

### ISSUE THREAD

**Issue by bhaidar** [kevinchappell/formBuilder#397]
Hi,
I need to design a form and then collect all information about the form fields and store them in my own database. Something like Form 1 has field 1, field 2, etc.

does the plugin allow me to know details about the form and fields added so that I can take this info and save in db?

Thanks

**Comment by kevinchappell** [comment]
formBuilder is a front-end tool. it will produce xml and json data of form templates. saving user entered data from the form generated by formBuilder is up to the developer.

**Comment by bhaidar** [comment]
Great news!
