### ISSUE TITLE
How to encapsulate formbuilder in Angular 1.x Directive?

### ISSUE THREAD

**Issue by bhaidar** [kevinchappell/formBuilder#399]
Hi,
How to use this formbuilder when the application I am developing is pure Angular? Is there a directive for this plugin?

If not, any guidelines on how to do so or integrate with it?

Thanks

**Comment by kevinchappell** [comment]
I know some have done it, however I only have this basic example: https://jsfiddle.net/kevinchappell/nap5qcL4/

**Comment by bhaidar** [comment]
Thats a good start.

In the documentation, where does it show how to handle saving the form definition? Maybe I extend this directive to also handle saving output and other stuff. Thanks a lot.

**Comment by kevinchappell** [comment]
docs should show how to get the formData, outside of that saving is dependent on your app.
