### ISSUE TITLE
Question : Regarding form Builder 2.0 ?

### ISSUE THREAD

**Issue by Yatoo1992** [kevinchappell/formBuilder#40]
Hello kevin,
I need to add form builder in my website in a week or two.
can you please inform me about the release date for Form Builder 2.0 as i am planning to use a from builder with html 5 elements.

By the way very nice plugin!

**Comment by kevinchappell** [comment]
@Yatoo1992 Thanks for the kind words. I'm looking to have 2.0 released Feb 8th. What fields are you needing?

**Comment by Yatoo1992** [comment]
Currently only field that i am missing is **img control  with preview**.
Also I am very thankful to you if you (get some extra time to) add following functionality in it:
1) Multi language support
2) Documentation for adding custom fields for developers, or at least explain an example with code for adding a field like check box or input.(this is very important)

**Issues**:
i am using *formbuilder.js* not the *min* file , it is giving error in firefox for using **let** instead of **var** and IE is giving error for using  **` (grave accent)** for example in (preview = **`**<${attrs.type} class="no-drag">${options}</${attrs.type}>**`**;)

for **let** i used **var** but dont know how to solve **` (grave accent)** issue
very thankful if yo help

**Comment by kevinchappell** [comment]
It sounds like I need to get on some documentation. formBuilder is multi language ready but does not come with with translations. To add your own translations formBuilder can be initialized with options containing the translated strings. [Example](http://codepen.io/kevinchappell/pen/BjxNKZ)

Regarding the issues, it sounds like your'e using the files from `/src` instead of `/dist`. There should be no `let` or literal template strings in the compiled version.

**Comment by Yatoo1992** [comment]
Oops my mistake i am using the file from `/src`,  files in `/dist` folders are perfectly fine.
again thanks for the help.

**Comment by Yatoo1992** [comment]
@kevinchappell  have you any thoughts about using two / three column layout?

**Comment by ricardovigatti** [comment]
@kevinchappell, i saw your example and i can translate the fields names. On the stage-wrap there's a message "Drag a field from the right to this area". How can i translate this and the title "Form Elements" just above the fields ?

**Comment by kevinchappell** [comment]
@ricardovigatti [This demo](http://formbuilder.readthedocs.org/en/latest/demos/translation/) has an example of how to translated messages.

@Yatoo1992 Columns are definitely coming in future version

**Comment by Yatoo1992** [comment]
Thanks @kevinchappell 
very much appreciated..!!!
