### ISSUE TITLE
Cannot disable multiple on a select field.

### ISSUE THREAD

**Issue by phiterf** [kevinchappell/formBuilder#401]
Hi, I'm trying to add a select, but it's always turning into a multiple select even if it's not what I want.

Pen: http://codepen.io/phiter/pen/PpyNyb

Used JSON for formData:

```
[
	{
		"type": "select",
		"required": true,
		"label": "Pick one!",
		"className": "form-control",
		"name": "select-1490713532332",
		"multiple": false,
		"values": [
				{
					"label": "ONE",
					"value": "op-1",
	        "selected" : true
				},
				{
					"label": "TWO",
					"value": "op-2"
				},
				{
					"label": "THREE",
					"value": "op-3"
				},
				{
					"label": "FOUR",
					"value": "op-4"
				}
			    ]
		}
]
```

**Comment by kevinchappell** [comment]
It should be a single select if you omit the `multiple` property

**Comment by phiterf** [comment]
I tried omitting it and it indeed became a single select, but the generated json is creating the multiple anyways, even if with a null or false value. What can I tweak in order to make `multiple : false` work?

**Comment by kevinchappell** [comment]
What version of the plugin are you using? The multiple property should not be generated if its not checked. Tested on the website: https://formbuilder.online/
![2017-03-28-172116_1026x598_scrot](https://cloud.githubusercontent.com/assets/1457540/24415943/fe4da65e-13da-11e7-969b-9b924cdd78eb.png)

**Comment by phiterf** [comment]
I turned the generated json into a C# class and I generate it by serializing the Object, and it sends back every option, even if null.

**Comment by kevinchappell** [comment]
how are you reading the formData? Can you share the code that leads to this? The `multiple` property should not be included in formData.

**Comment by phiterf** [comment]
Kevin, I picked up the json and created a C# class with all possible options, as follows:

![image](https://cloud.githubusercontent.com/assets/12252332/24416325/c7c377aa-13ba-11e7-9bb5-466d461661c5.png)

When I serialize this class using `JsonConvert.SerializeObject`, it outputs this result:

![capturar](https://cloud.githubusercontent.com/assets/12252332/24416376/f2368f7c-13ba-11e7-9a33-1b5e693d5c98.PNG)

It creates all properties, even if they are null. What I could do is to remove all properties with a null value from my object, but I think the plugin should recognize this.

**Comment by kevinchappell** [comment]
the plugin reads `null` values because some attributes like `multiple` and `disabled` function as flags. reading null properties allows it to generate markup like `<select name="skjdlkajd" multiple disabled>`. For this reason nulls are purposely removed from the output data using `trimObj` function:

```
  /**
   * Remove null or undefined values
   * @param  {Object} attrs {attrName: attrValue}
   * @return {Object}       Object trimmed of null or undefined values
   */
  utils.trimObj = function(attrs) {
    let xmlRemove = [
      null,
      undefined,
      '',
      false,
      'false'
    ];
    for (let attr in attrs) {
      if (utils.inArray(attrs[attr], xmlRemove)) {
        delete attrs[attr];
      } else if (Array.isArray(attrs[attr])) {
        if (!attrs[attr].length) {
          delete attrs[attr];
        }
      }
    }

    return attrs;
  };
```

It would be great to remove this since its using a bunch of slow deletes and is generally not pretty

**Comment by phiterf** [comment]
Well, I just found out that I can [filter out the nulls when I serialize the object](http://stackoverflow.com/a/6507965).


But it's still weird that `multiple : false` is interpreted as `multiple : true`.

**Comment by kevinchappell** [comment]
@phiterf totally agree.
