### ISSUE TITLE
 Can stage be Separate?

### ISSUE THREAD

**Issue by wslpdgg** [kevinchappell/formBuilder#403]
thanks give this form design tool.
i have a question,  Does stage where drag the form fields can be separated to custom number of cells ? like microsoft excel（row,column）， one row can have more than one cell for drag form fields , and merge cell  let one row only have one form field .
 in this case, i can use it to build form  for my web ,not only for app

like this:

![tim 20170401172214](https://cloud.githubusercontent.com/assets/7911356/24577499/812ac330-1701-11e7-9d9a-f58161f4c857.jpg)

thanks

**Comment by kevinchappell** [comment]
Unfortunately no, this is not supported.
