### ISSUE TITLE
Language conversion issue

### ISSUE THREAD

**Issue by Carnia** [kevinchappell/formBuilder#404]
issues Demo url: 
[http://formbuilder.readthedocs.io/en/latest/formBuilder/demos/translation/#translation](http://formbuilder.readthedocs.io/en/latest/formBuilder/demos/translation/#translation)
or
[http://codepen.io/Carnia/pen/wJbKaO](http://codepen.io/Carnia/pen/wJbKaO
)

Hi kevin,
    When I click "**繁體中文(Traditional Chinese)**-->**button/TextField** " ,  the "button" and "textfield" 's type options are invalid ,  and render like this **_"<選項 1 type="選項 1" class="button-input btn-default btn" name="button-1491385687232-preview" style="default" id="button-1491385687232-preview">按鈕"_**

and i think I know the reason , the demo.js replaces the language pack ， But it should not add the extra option **_"subtypes"_** ； like this :
```
jQuery(document).ready(function($) {
  var language = {
      pt: {
        button: 'Botão',
        text: 'Texto',
         ...
         ...
      },
      zhtw: {
         ...
        subtype: '格式',
        //subtypes: {        【★★★★★】====== maybe this option is not allowed ======【★★★★★】
        //  text: ['text', 'password', 'email', 'color'],
        //  button: ['button', 'submit']
        //},
        text: '文字欄位',
        textArea: '文字區塊',
        toggle: '彈出提示',
        warning: '警告!',
        viewXML: '&lt;/&gt;',
        yes: '是'
      }
    },
    $fbTemplate = $(document.getElementById('fb-editor'));
  $fbTemplate.formBuilder();

  $('.language-selector li').click(function() {
    var lang = this.id;

    $fbTemplate.empty().formBuilder({
      messages: language[lang] || {}
    });
  });

});
```
Because the following code is used in **_'form-builder.js'_**？

```
    defaults.messages.subtypes = function () {
      var subtypeDefault = function subtypeDefault(subtype) {
        return {
          label: subtype,
          value: subtype
        };
      };

      return {
        text: ['text', 'password', 'email', 'color', 'tel'].map(subtypeDefault),
        header: ['h1', 'h2', 'h3'].map(subtypeDefault),
        button: ['button', 'submit', 'reset'].map(subtypeDefault),
        paragraph: ['p', 'address', 'blockquote', 'canvas', 'output'].map(subtypeDefault)
      };
    }();
```

**Comment by Carnia** [comment]
Demo->bug not fixed:
[http://codepen.io/Carnia/pen/wJbKaO](http://codepen.io/Carnia/pen/wJbKaO)
Demo->bug fixed:
[http://codepen.io/Carnia/pen/vxwNER](http://codepen.io/Carnia/pen/vxwNER)

**Comment by kevinchappell** [comment]
This is related to subtypes being part of `messages` which its not in the next version. will keep this open until next version is released.
