### ISSUE TITLE
Suggestion of star ratings input

### ISSUE THREAD

**Issue by epigos** [kevinchappell/formBuilder#409]
This plugin is really great and has helped me a lot.

There is one suggestion, I realized star ratings is a major input field in creating a survey or review forms. It will be awesome if this plugin has star ratings input field.

Would you mind investigating this plugin? 

http://www.jqueryscript.net/other/Minimal-Emoji-Rating-Plugin-With-jQuery-Emoji-Ratings.html

Its a lightweight jQuery star rating plugin that uses emoji unicode characters for rating symbols.

Thanks!

**Comment by kevinchappell** [comment]
Star rating would be a good feature, I'll check out the plugin.
