### ISSUE TITLE
Making field required causes HTML 5 validation and doesn't let form to save the JSON data into database.

### ISSUE THREAD

**Issue by rajeev07cha** [kevinchappell/formBuilder#415]
I have added formBuilder to a form where I am storing its JSON formData in a form attribute, when I add a text input through formBuilder and make it required, it doesnt let the form data to be saved as it throws HTML 5 required validation error on formBuilder input field, where I just need to store its JSON.

**Comment by kevinchappell** [comment]
@rajeev07cha use [novalidate](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Form_validation#Example_using_the_constraint_validation_API)
