### ISSUE TITLE
Cannot edit the text area value

### ISSUE THREAD

**Issue by abugim** [kevinchappell/formBuilder#417]
When try to select a text area to change it's value the input don't get selected and it's not possible to edit it.

**Comment by kevinchappell** [comment]
What version are you seeing this?

**Comment by abugim** [comment]
2.0.0

**Comment by kevinchappell** [comment]
Ok, will look into this.

**Comment by ankurk91** [comment]
Yes, i can reproduce this as well. Text area is not focusable in form-builder, however right click on textarea did the trick.
