### ISSUE TITLE
Unable to provide nested name, like: parent[child]

### ISSUE THREAD

**Issue by rajeev07cha** [kevinchappell/formBuilder#418]

**Comment by ankurk91** [comment]
@rajeev07cha 
Do you think one can help you without explaining anything ?

**Comment by kevinchappell** [comment]
@ankurk91 actually I know what this is. I'll release a fix today with the updated docs. There is a function that removes invalid characters from name attribute, brackets need to be added to the valid character regex.

**Comment by rajeev07cha** [comment]
@ankurk91 never mind, @kevinchappell got my concern.

**Comment by kevinchappell** [comment]
@rajeev07cha, @ankurk91 has a point though. it did take me a minute to figure out. A more descriptive issue will help others help you faster.
