### ISSUE TITLE
[2.4.1] i18n: override a single string

### ISSUE THREAD

**Issue by ankurk91** [kevinchappell/formBuilder#421]
Hi, kevin
I was trying the all new **i18n** option, i want to change a string, see example -
```js
 var formBuilderOptions = {
 i18n: {
      locale: 'en-US',
      preloaded: {
        'en-US': {
          label: 'Question',
          value: 'Default value'
        }
      }
    }
};
var $editor = $(window.document.querySelector('#form-builder-editor'));
var builder = $editor.formBuilder(formBuilderOptions);
```
But i ended up with messing formBuilder UI, see screenshot.
![screenshot from 2017-04-20 09-55-41](https://cloud.githubusercontent.com/assets/6111524/25213629/88c0aaf8-25af-11e7-8fac-4a4632677413.png)

How do i change a single string form 'en-US' ? Please help.

PS. Updated to v2.4.1 but still have same issue

**Comment by kevinchappell** [comment]
Saw this bug last night but was too late fix. Will work on it today.

**Comment by ofauno** [comment]
also on values on other langs f. i. ('es-ES')

![screen shot 2017-04-20 at 12 30 31](https://cloud.githubusercontent.com/assets/1057021/25243944/7cf30120-25c4-11e7-9202-82c84e367f3a.png)

cool work @kevinchappell  🤘🏽

**Comment by ankurk91** [comment]
Any update on this ?

**Comment by kevinchappell** [comment]
@ankurk91 none yet, but its next on the list.

**Comment by KuenzelIT** [comment]
Hey,

I'm using the german translation and some label seem to be empty, like "class" or "value". The input field is there with its content, but the label is empty. Doesn't happen if I use the english version.

Is this the same bug?

Thanks!
