### ISSUE TITLE
Add new elements

### ISSUE THREAD

**Issue by eder-toledo** [kevinchappell/formBuilder#423]
How could you modify the core to add new elements ?, for example a geographic point.
And if I succeed in creating them, I can share them with the project.

**Comment by kevinchappell** [comment]
No Longer necessary. v2.1 introduced custom elements and v2.2 expanded greatly on that with full class inheritance for custom elements.

### Docs
[Overview](https://github.com/kevinchappell/formBuilder/blob/master/src/js/README.md)
[Controls](https://github.com/kevinchappell/formBuilder/blob/master/src/js/control/README.md)
[Plugins](https://github.com/kevinchappell/formBuilder/blob/master/src/js/control_plugins/README.md)
