### ISSUE TITLE
[2.1.1] .input-group-addon class conflict with bootstrap css 

### ISSUE THREAD

**Issue by ankurk91** [kevinchappell/formBuilder#424]
Hi, kevin
Today i noticed that some of my bootstrap form inputs not looking as they were before v2.x.
See - https://plnkr.co/edit/qR2JNWzWBPRVeE7soudD?p=preview

![screenshot from 2017-04-21 09-42-49](https://cloud.githubusercontent.com/assets/6111524/25262669/23817a32-2677-11e7-8e46-b0b89b1c6371.png)

As you can see this is the border radius issue. I compared with v1.x and it was not there.

**Comment by kevinchappell** [comment]
Fixed in v2.2.1
https://plnkr.co/edit/C1vxt07D7q1u0cZ4HkiS?p=preview
