### ISSUE TITLE
latest release stopped working on IE11

### ISSUE THREAD

**Issue by PDLDYNAMICS** [kevinchappell/formBuilder#425]
the latest release nolonger works in IE 11

**Comment by kevinchappell** [comment]
@PDLDYNAMICS Can you share the error from console?

**Comment by PDLDYNAMICS** [comment]
@kevinchappell  I have added the console messages and screen shot of the debugger 

![capture](https://cloud.githubusercontent.com/assets/1996879/25280735/dd943718-26a2-11e7-9253-e6f37070eb2c.PNG)

DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
www.google.co.uk
HTML1300: Navigation occurred.
formbuilder.online
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
www.google.co.uk
SCRIPT445: Object doesn't support this action
vendor.min.js (18,26107)
SCRIPT438: Object doesn't support property or method 'formBuilder'
site.min.js (7,1498)

**Comment by kevinchappell** [comment]
Thanks, this gives me a good starting point.
