### ISSUE TITLE
No buttons to copy code

### ISSUE THREAD

**Issue by Edgars7q** [kevinchappell/formBuilder#429]
Hello. When i am viewing form code i cant see it all because its sticking out of screen  - im making large forms. Cant copy code this way. You should make copy button. Check screenshot.
Thank You.
![capture](https://cloud.githubusercontent.com/assets/26358393/25342328/ae928ac4-2903-11e7-9403-31f0804a27a8.JPG)

**Comment by vikramjb** [comment]
@Edgars7q Goto form-builder.js and proceed to line 5960. And do a console.log on  formData. You should have the json code being generated. You can use this workaround till and if the feature gets implemented. Better yet, now that you know where to find the code, you can use clipboard js to copy the json using a different a button action and submit a PR to Kevin

**Comment by kevinchappell** [comment]
You can grab the formData using `actions` API. [Example](http://formbuilder.readthedocs.io/en/latest/formBuilder/actions/getData/)
