### ISSUE TITLE
Adding Headers

### ISSUE THREAD

**Issue by Morne-W** [kevinchappell/formBuilder#43]
IS there a way to maybe add headers, like h1, h2 and h3 to the menu and drag them onto the form?

**Comment by Yatoo1992** [comment]
@Morne-W  Well there is no built in method in this plugin to add custom fields, but you can modify the formbuilder.js to add your custom fields.

**Comment by Morne-W** [comment]
Any idea on how to go to work on that? or any pointers?

**Comment by Yatoo1992** [comment]
1) Add new field in **frmbFields** like `{
      label: "Custom_button",
      attrs: {
        type: 'Custom_button',
        className: 'button',
        name: 'button'
      }
    }`

2) Add ` Custom_button :appendInput` in **appendFieldType ** object.

3) Add `case 'Custom_button':
          preview = '<button type="button">Custom Button</button>';
          break;`  in **fieldPreview** function
![1](https://cloud.githubusercontent.com/assets/16875461/12641584/1edf9290-c5d2-11e5-857a-4cd361638f8f.JPG)
![3](https://cloud.githubusercontent.com/assets/16875461/12641599/2f40aebc-c5d2-11e5-9f7d-5b4fac8e6cf4.JPG)
![2](https://cloud.githubusercontent.com/assets/16875461/12641600/2f461d7a-c5d2-11e5-8bc4-d9c8f1f17d90.JPG)

**Comment by Morne-W** [comment]
Thanx for the help. Will try it out

**Comment by Morne-W** [comment]
One last thing, where will i add runat="server" tags in the .JS file to add it to the actual element

**Comment by Yatoo1992** [comment]
@Morne-W  I guess you can do something like this `<input type="button" runat="server" id="btnTest" />`

**Comment by Morne-W** [comment]
Already tried that and also adding it as an attribute but with no success

**Comment by Yatoo1992** [comment]
why do you need runat ="server"?

**Comment by Morne-W** [comment]
I am using it in a ASP.net web application where on one page the admin creates a form and the html of the form gets saved in the database. On another page a user chooses a form out of a list and has to proceed to populate the form. I got everything working up to that point. 

This is the part where I'm stuck:
When the user clicks submit I have to go through each element on the form to find the id, the type and the value that the user entered. In order for me to access the controls on the form each control needs a runat server tag which makes it visible for my back end code. 

Maybe there is another solution that I am not aware of.

**Comment by Yatoo1992** [comment]
Can't help there my scenario is totally different using html.
its better to ask this question here [https://gitter.im/kevinchappell/formBuilder]

**Comment by kevinchappell** [comment]
@Morne-W  - @Yatoo1992 is on the right track with adding new fields. 

If the fields did not need to be sorted there are `disabledFields` that could be added to beginning and end of the form like [this](http://codepen.io/kevinchappell/pen/XXYdvv)

`defaultFields` will allow you to populate the form with existing fields but currently you'll have to edit the plugin to add new markup.

**Comment by Morne-W** [comment]
I changed a bit of the stuff around like the autocomplete, I replaced that with a file upload. Stil working on adding headers to the form but it can wait

**Comment by kevinchappell** [comment]
Nice! If there is anything you think should be in the plug-in feel free to submit a pull request.

**Comment by fnwc** [comment]
Regarding populating the form with existing fields, you can instantiate like so: 

`$(function () {
				'use strict';
				$('#form-builder-template').formBuilder({ defaultFields: [{ label: 'First Name', name: 'first-name', required: 'true', description: 'Your first name', type: 'text' }] });
			});`

It would be nice to be able to use the saved form HTML that the form builder generates using formRender() to fill the default fields.

I'm trying to allow the user to later modify the form after it's been saved to the database, but I'm having issues trying to populate a new form builder with the existing HTML generated earlier.

**Comment by kevinchappell** [comment]
@fnwc I think the best approach for this would be to populate formBuilder using the saved XML. This [codepen](http://codepen.io/kevinchappell/pen/Vedrqr) has an example of this method.

**Comment by fnwc** [comment]
@kevinchappell Ok, thanks.
