### ISSUE TITLE
Cannot create PDF of FormBuilder or FormRender output using WkHtmlToPdf CLI tool

### ISSUE THREAD

**Issue by atljoseph** [kevinchappell/formBuilder#430]
@kevinchappell - Maybe you will be able to shed some light on this or provide a workaround! :) 

I don't know why this combo would not work because I haven't found any big issue reported between WkHtmlToPdf and jQuery-UI.

EXAMPLE INFO:

URL Target: https://formbuilder.online/
Description: Form Builder area (near top of page) doesn't even appear in pdf output. Also, Render Area will not display properly.
Script: (from windows batch file)

@echo on
set "inputUrl=https://formbuilder.online/"
set "inputDir=%cd:=/%"
set "outputFile=%inputDir%/temp.pdf"
set "exePath=C:\Program^ Files\wkhtmltopdf\bin"
set "exeFile=wkhtmltopdf.exe"
set "options=--enable-javascript --javascript-delay 10000 --no-stop-slow-scripts"
cd %exePath%
%exeFile% %options% %inputUrl% %outputFile%
pause

System: Win 10 - Surface 4
Goals: PDF-ize forms rendered with form-render.js

**Comment by kevinchappell** [comment]
Going to close this. Discussion can be carried over to [wkhtmltopdf issue](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3445)
