### ISSUE TITLE
Checkbox/Radio Group vs. Checkbox/Radio inconsistency

### ISSUE THREAD

**Issue by atljoseph** [kevinchappell/formBuilder#432]
No plain jane Checkbox or Radio exists, which is fine and dandy, so...

I assume that the Checkbox and radio Groups are intended to be used when a single checkbox or radio button is needed.

but (for example) ...

If I add a Checkbox Group, it originally is assigned one option by default.
If I add an option, everything works as it should.
If I attempt to delete the next to last option (going from 2 options back to 1), I get a console message saying that the control "requires a minimum of 2 options".
This doesn't make sense because the control was initialized with 1 option, thus it should be compatible with one option.
I think the validation that goes on when options are added/removed just hasn't been updated for this scenario and version.

**Comment by kevinchappell** [comment]
The checkbox issue is resolved in v2.2 but there should not exists a single radio
