### ISSUE TITLE
Removing value="" from select lists disables html5 required functionality

### ISSUE THREAD

**Issue by boonep** [kevinchappell/formBuilder#434]
Select lists with value='' have their value attribute removed, which prevents some browsers from recognizing that select option as an empty value, and requiring a different selection.

i.e.

```
  {
        'name': 'select-gender',
        'type': 'select',
        'label': 'Gender',
        'required': True,
        'values': [
            {'label': '------------', 'value': "", 'selected': True},
            {'label': 'Female', 'value': 'female',},
            {'label': 'Male', 'value': 'male'}
        ],
        'className': 'form-control',
    }
```

renders as:
```
<div class="fb-select form-group field-select-gender">
  <label class="fb-select-label">Gender<span class="fb-required"> *</span></label>
   <select name="select-gender" label="Gender" required="true" class="form-control">
      <option id="select-gender-0">------------</option>
      <option value="female" id="select-gender-1">Female</option>
      <option value="male" id="select-gender-2">Male</option>
   </select>
</div>
```
***Note: since first option has no value, it isn't seen as empty, and chrome (possibly others) allows submission even if the blank option '-----------------' is selected**

This options is being trimmed out here:
https://github.com/kevinchappell/formBuilder/blob/master/src/js/utils.js#L38

I'm more than happy to submit a PR to fix, but not sure the architectural reasons for removing null attributes, so not sure of the best way to resolve.  

Let me know your thoughts and I can assist.  Thanks!

**Comment by Jojoshua** [comment]
Feel free to reopen if this is still an issue.
