### ISSUE TITLE
How to remove control from the list which is already dragged

### ISSUE THREAD

**Issue by developervishaldhawan** [kevinchappell/formBuilder#435]
Hi,

I want to **remove control items** which are **already dragged** from the **control list** (on the right side). 
For this i was debugging code and found that  the item is removing from the list while rendering control on the left side draggable area. But after some processing and rendering, the item is appending to the Control list.

Has anyone did this kind of implementation or any idea how can i achieve this functionality.  

Thanks in advance... :)

**Comment by kevinchappell** [comment]
There is nothing like that build into formBuilder though it may be a nice feature in the future. Currently you can accomplish this with a little extra JS. In the demo below, The file field is limited to 1. If there is a File field on the stage the control is hidden from the list.
http://codepen.io/kevinchappell/pen/eZReEB
