### ISSUE TITLE
Required (*) UI issue when there is no Label for input

### ISSUE THREAD

**Issue by nk-nareshkumar** [kevinchappell/formBuilder#437]
See the UI when there is no  Label of input , same issue with helptext if there is no  Label for input

![See here](https://cloud.githubusercontent.com/assets/2937132/25552885/ca3b8664-2cc2-11e7-947f-b3d55d8e4eaa.png)

**Comment by kevinchappell** [comment]
Not sure if this is a bug, what is the expected result? I would like to keep the indicator uniform, that is it looks the same whether there is a label or not. This would be kind of a big change though and I'd like to see some discussion about it. 

Maybe we could do something more minimal like [this demo](http://codepen.io/kevinchappell/pen/waVeoE)

**Comment by nk-nareshkumar** [comment]
Kevin. thanks for reply.
But what if there is no label for input. the formbuilder bind with the condition that there should be label for input. but what if we dont want label and label text in placeholder. ?

**Comment by kevinchappell** [comment]
The link i share addresses that scenario, making required indicator attached to field instead of label.

**Comment by brentkelly** [comment]
@nk-nareshkumar if you are using the latest formbuilder, you can pass override layout templates as an option which will give you full control to represent 'required' however you like: https://github.com/kevinchappell/formBuilder/tree/master/src/js#layouts
