### ISSUE TITLE
inputSets have issue with placeholder when there is no type ='text' 

### ISSUE THREAD

**Issue by nk-nareshkumar** [kevinchappell/formBuilder#438]
inputSets have issue with placeholder when there is no type ='text' .

For the all other email,number .... etc its not showing placeholder..only showing when there is text type in inputSets 

formBuilder: options -> inputSets http://codepen.io/anon/pen/MmpLga

**Comment by kevinchappell** [comment]
Is this that the correct codepen link? The inputSets option is not set and neither is placeholder properties.
