### ISSUE TITLE
Multi language

### ISSUE THREAD

**Issue by Yatoo1992** [kevinchappell/formBuilder#44]
I was able to change the language of form during initialization e.g as explain in [this](http://codepen.io/anon/pen/eJrGOj) example provided by **Kevin chappel** . But what if i want to change the language in the middle of form creation or user want to save a form with English and a french version.
Do i have to re initialize the form with new language messages on language change event??

**Comment by kevinchappell** [comment]
Currently this is not possible and there would need to be some work done to to provide a `reInit()` function.

A future version may have some 2-way data binding similar to [ngI18n](http://kevinchappell.github.io/ng-i18n/) but currently I would recommend a page refresh.

**Comment by kevinchappell** [comment]
@Yatoo1992 #62 should allow you to reinitialize formBuilder on the fly with options as they are needed. Note this will not change some items on the stage as these are considered saved values. Example if you change the default label for the Text input but already have text inputs on the stage their label will not change. However other, non-editable labels like "Help Text" or "Subtype" will update with the new values.
