### ISSUE TITLE
Question: Multiple columns

### ISSUE THREAD

**Issue by sheibeck** [kevinchappell/formBuilder#45]
Hey Kevin,
  I wasn't sure the best way to ask the question, so posting it as an issue. Does formBuilder support multiple columns. Or, maybe I need a different to think about it, but the goal woud be to have the possibililty of fields being side-by-side on the form instead only one field per row. Sorry if you already answered a similar question.
  
Thanks.

**Comment by kevinchappell** [comment]
Currently formBuilder does not support multiple columns though this could be easily remedied with css. Will follow-up with example.

**Comment by sheibeck** [comment]
Thank you!

**Comment by kevinchappell** [comment]
@sheibeck #46 should help you with columns. I created a demo here: http://codepen.io/kevinchappell/pen/MKXybG

**Comment by sheibeck** [comment]
Kevin, that is perfect! Thanks. I run http://www.theprocurator.com and I'm planning on doing some heavy duty upgrades. Right now, I have a form building engine that is home grown and just completely in sufficient for what my goal is for the site. 

I found your engine and I was hoping to use it to make my UI a lot more user friendly for people who want to build their own sheets in my app. This will help a lot, and I'm looking forward to 2.0!

Thanks again.

**Comment by kevinchappell** [comment]
Wicked! Glad you're finding it useful. Best of luck.
