### ISSUE TITLE
Radio Group 2nd option not deleting 

### ISSUE THREAD

**Issue by nk-nareshkumar** [kevinchappell/formBuilder#452]
Produce : Drag the Radio Group and open edit then delete the 3rd option and then try to delete the 2nd option. then 2nd option will not delete

![formbuilder v2 0](https://cloud.githubusercontent.com/assets/2937132/26051798/f2c5cf0c-3980-11e7-88e5-a69c2b6204c6.png)

**Comment by kevinchappell** [comment]
This should be resolved now in v2.2

**Comment by mourareaupro** [comment]
The problem seems to be still here. i also tried on the demo version https://formbuilder.online/, that's impossible to remove the second option. please let me know if there is a way to fix it.
