### ISSUE TITLE
Get data

### ISSUE THREAD

**Issue by eder-toledo** [kevinchappell/formBuilder#458]
Hi.
I use the formbuilder Version: 1.24.7.
The method getData generate the error: TypeError: Cannot read property 'getData' of undefined

My code is: 
    var editor = document.getElementById('ficha');
    window.formBuilder = $(editor).formBuilder(options);
    formBuilder.actions.getData('json')

**Comment by kevinchappell** [comment]
`getData` doesnt exist immediately. This is resolved in v2.2 with a [`promise` property](http://codepen.io/kevinchappell/pen/ybgqLK) Is it possible to call `getData` later? Worst case scenario you could do setTimeout
