### ISSUE TITLE
not support in mobile, tablet?

### ISSUE THREAD

**Issue by hungthai1401** [kevinchappell/formBuilder#461]
Hello,
How can use formBuilder in mobile, tablet? It is available in laptop, desktop.
Thanks

**Comment by kevinchappell** [comment]
Is there a specific issue you are facing with mobile/tablet use? Be sure to include [jQuery touch punch](http://touchpunch.furf.com/)

**Comment by ankurk91** [comment]
@hungthai1401 
formBuilder UI is responsive, see screenshot
![screenshot from 2017-05-17 18-29-17](https://cloud.githubusercontent.com/assets/6111524/26154854/d0fe57a4-3b2e-11e7-9faf-4e2e42967089.png)

**Comment by kevinchappell** [comment]
Action buttons could benefit from improved styling though.

**Comment by hungthai1401** [comment]
@kevinchappell  thank. it is helpful.
