### ISSUE TITLE
[2.2.2] css files are missing from npm package

### ISSUE THREAD

**Issue by ankurk91** [kevinchappell/formBuilder#465]
Hi, Kevin

Just installed v2.2.2 today through npm
```
npm install formBuilder@2.2.2 --save
```
and found that css files were not published on npm. 
See screenshot
![screenshot from 2017-05-17 18-10-40](https://cloud.githubusercontent.com/assets/6111524/26154187/2966693e-3b2c-11e7-8c6c-d1bb224627e2.png)

Please publish a new version, thanks.

**Comment by kevinchappell** [comment]
CSS is now bundled with the plugin. Need need for separate include.

**Comment by ankurk91** [comment]
Oh, should we also mention this in change log ? My build system was broke due this, because it could not find the css file.

**Comment by kevinchappell** [comment]
Yes I am updating documentation now but CHANGELOG is a good spot for now.
