### ISSUE TITLE
Windows  github running issue

### ISSUE THREAD

**Issue by bajinaji** [kevinchappell/formBuilder#472]
Pardon me if I'm being "noob crap", but I've clone from git, and run npm start (after yarn install).

I'm running on a windows machine,and initially I received many errors regarding CRLF issues with gulp.
I updated the settings for gulp to include "linebreak-style": 0.

Now the local server starts correctly on port 8080, but when I navigate there, I am finding that the drop and drop is not functioning.
It does from the demo site.
I am unable to drag the elements from the right toolbar selection area to the form area.

Cheers,

Rob

**Comment by brentkelly** [comment]
I don't think it is a windows specific issue. This is happening for me to with the latest version of master. `npm start` loads the webserver, the formBuilder page loads fine, when you hover over the controls the cursor switches to a drag icon, but you can't drag. No errors in console - its like the `draggable` call isn't happening or something.

**Comment by kevinchappell** [comment]
vendor files may have been blocked. I'll change how they are loaded.
