### ISSUE TITLE
Add input to option

### ISSUE THREAD

**Issue by eder-toledo** [kevinchappell/formBuilder#474]
Hi.
I need to add another input to the options

![image](https://cloud.githubusercontent.com/assets/2104229/26257420/33bdcb56-3c86-11e7-9f30-b2683b4f483b.png)

To get the json:

 {
		"type": "checkbox-group",
		"required": true,
		"label": "Checkbox Group",
		"name": "checkbox-group-1495033544998",
		"other": true,
		"odktype": "select_multiple",
		"values": [
			{
				"label": "Option 1",
				"value": "option-1",
				"selected": true,
                                "myCustomProperty": "value"
			}
		]
	}

Thanks.

**Comment by kevinchappell** [comment]
Where would your custom property be output in the html?

**Comment by eder-toledo** [comment]
I think of something like this

![image](https://cloud.githubusercontent.com/assets/2104229/26323792/dd05e7ea-3ef5-11e7-8266-cd6e4beab066.png)

**Comment by kevinchappell** [comment]
I get that part, but how does the value get output in the generated HTML? For example in a select field the output is currently `<option value="${value}>${label}<option>`. Where would ${myCustomProperty} be output?

**Comment by eder-toledo** [comment]
The HTML similar to: <option ${myCustomProperty}="${myCustomPropertyValue}" value="${value}>${label}<option>

**Comment by kevinchappell** [comment]
I'm not opposed to adding this feature but there are a few issues that would need to be addressed:

1. Extending option data and parsing custom properties
2. Finding room in the UI: how would custom property input be added, what is the limit of custom properties, how does it scale down for mobile displays etc.
3. Will it be valid HTML? [Only a few attributes are valid](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option) on the <option> tag, some browsers may ignore additional attributes.

### Implementation criteria:

- Preserve current functionality. 
- Minimal UI changes

**Comment by craigpotter** [comment]
What would be a real life case for this ? 

Only thing I can think of is maybe using data- attributes but not sure someone using a form generator would need too? 

In this case, would a text area be acceptable to input all other attributes ? 
`data-test="case" data-case="test"`

Could be one input for these? Would be easier on the UI for sure?

**Comment by eder-toledo** [comment]
Hi @craigpotter 
I need add input to option to make it an attibute, to create extended functionality for example: dependent selects or related te option to custom image.

Same as it is possible to solve it with a custom element following  the documentation.

Or any other possibility.

**Comment by avinashi37** [comment]
hey @eder-toledo ,
Have you resolved it? I also have the same requirement in my project and wants to implement option like this. Can you please share the detail ?

**Comment by eder-toledo** [comment]
Hi @avinashi37 
I needed add images to options, in this case I create other page for add the images to the options.

In the formbuilder element add a button with redirect to the page for add images.

![imagen](https://user-images.githubusercontent.com/2104229/31694178-60cb4a02-b368-11e7-8393-e43e65d897af.png)

**Comment by Jojoshua** [comment]
Looks like this got resolved
