### ISSUE TITLE
Setting the default class and html output

### ISSUE THREAD

**Issue by danshimmert** [kevinchappell/formBuilder#476]
Hi Kevin

Thanks for a great tool.

I realised that as I was typing this, I found the reason why and how to fix it.

It's appears the docs need tweaking though?

http://formbuilder.readthedocs.io/en/latest/formBuilder/options/defaultFields/

has 

{
        class: "form-control",
        label: "First Name",
        placeholder: "Enter your first name",
        name: "first-name",
        required: true,
        type: "text"
      },

but requires **className**, as I spotted here : http://codepen.io/kevinchappell/pen/ozagKr

Thanks
.ds.

**Comment by kevinchappell** [comment]
Good catch. Should be resolved with #469
