### ISSUE TITLE
Webpack needs to wrap output min files in an IIFE

### ISSUE THREAD

**Issue by brentkelly** [kevinchappell/formBuilder#479]
Current dist files aren't completely wrapped in an IIFE. Ideally webpack should be wrapping all output files (including control plugins) in an IIFE (plugin currently conflicts with other libraries such as prototype.js).

Previous config with the gulp-iife plugin was working well.

**Comment by kevinchappell** [comment]
Is the conflict the $? If so could we change something in the plugin to resolve the issue? Alternatively we could use something like a [wrapper plugin](https://github.com/levp/wrapper-webpack-plugin) for webpack but it feels an antipattern to me.

**Comment by Jojoshua** [comment]
Looks like this was resolved
