### ISSUE TITLE
Remove "Access" and roles 

### ISSUE THREAD

**Issue by craigpotter** [kevinchappell/formBuilder#489]
Is it possible to remove the access control from FormBuilder ? 

I want to remove Access/Roles all together? Didn't see anything in the documentation to easily do this?

**Comment by craigpotter** [comment]
Never mind, I'm an idiot!!!

```javascript
jQuery(function($) {
  var fbEditor = document.getElementById("build-wrap"),
    options = {
      disabledAttrs: ["access"]
    };
  $(fbEditor).formBuilder(options);
});
```

**Comment by kevinchappell** [comment]
No, it's not immediately obvious how its done. Now that that documentation has grown to be quite large I think the entry page for formBuilder Docs should have a Common tasks or FAQ with links to answers. disabledAttrs could be right at the top of the list since it is an almost daily request.

**Comment by craigpotter** [comment]
FAQ's could be handy. 

There are a few that springs to mind. Spotted a couple of bits where it would be handy to list possible values as well. 
e.g 
disabledActionButtons

Would be handy to list `["save", "data", "clear"]`
