### ISSUE TITLE
Trigger 'change' event when text area is updated

### ISSUE THREAD

**Issue by ghostfreak3000** [kevinchappell/formBuilder#49]
I'm trying implement an auto-update feature...
instead of having to run a `setinterval()` to track the change, would it be possible to just trigger a change event when the text area is updated and i listen to that change?

for a quick fix.. just show me the area of the code to implement the change and I make a quick fork of the project.

**Comment by kevinchappell** [comment]
is this in formRender or formBuilder?

**Comment by ghostfreak3000** [comment]
formBuilder

**Comment by kevinchappell** [comment]
Oh I see what you mean. So when the hidden textarea changes you want to run some code?

**Comment by ghostfreak3000** [comment]
yup.. want to get the xml

**Comment by kevinchappell** [comment]
got it. I'll whip up a codepen example now.

**Comment by ghostfreak3000** [comment]
cool

**Comment by ghostfreak3000** [comment]
Thanks!

**Comment by kevinchappell** [comment]
:+1:  You can do something like this now: http://codepen.io/kevinchappell/pen/ZQqwLp
