### ISSUE TITLE
gulp font-save issue

### ISSUE THREAD

**Issue by craigpotter** [kevinchappell/formBuilder#503]
### Description:
```shell
$ gulp font-save
[16:05:03] Requiring external module babel-register
[16:05:05] Using gulpfile C:\Git\formBuilder\gulpfile.babel.js
[16:05:05] Starting 'font-save'...
[16:05:05] Finished 'font-save' after 6.74 ms

{ Error: Command failed: if test ! $(which unzip); then echo "Unzip is installed"; exit 128; fi
 rm -rf .fontello.src .fontello.zip
 curl --silent --show-error --fail --output .fontello.zip http://fontello.com/$(cat .fontello)/get
 unzip .fontello.zip -d .fontello.src
 rm -rf src/fonts/fontello
 mv $(find ./.fontello.src -maxdepth 1 -name 'fontello-*') src/fonts/fontello
 rm -rf .fontello.src .fontello.zip
! was unexpected at this time.

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'if test ! $(which unzip); then echo "Unzip is installed"; exit 128; fi \n rm -rf .fontello.src .fontello.zip \n curl --silent --show-error --fail --output .fontello.zip http://fontello.com/$(cat .fontello)/get \n unzip .fontello.zip -d .fontello.src \n rm -rf src/fonts/fontello \n mv $(find ./.fontello.src -maxdepth 1 -name \'fontello-*\') src/fonts/fontello \n rm -rf .fontello.src .fontello.zip' } '! was unexpected at this time.\r\n'



```
### Environment Details:

 - formBuilder Version: 2.3.4
 - Browser: 
 - OS: Windows 10 (Will test in Ubuntu shortly)

### Expected Behavior
Font should save 
### Actual Behavior
Error message above

**Comment by kevinchappell** [comment]
This is most likely the unzip utility missing from Windows powershell and cmd. Could you test Ubuntu bash on Windows? `font-save` should be refactored out of gulp anyways​ and in the process we can switch to a js module for cross platform unzipping.

**Comment by craigpotter** [comment]
I'm using the Git Bash on my windows machine as the moment 
Unzip is loaded in the Bash as well

```shell 
$ unzip
UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send
bug reports using http://www.info-zip.org/zip-bug.html; see README for details.


```

**Comment by kevinchappell** [comment]
Could you test the other utilities in that command? Maybe it's curl

**Comment by kevinchappell** [comment]
Actually that should be loaded too. I'll test this on Windows

**Comment by craigpotter** [comment]
hmm I think it might be something with this set up 

```shell 
$ gulp
[16:50:25] Requiring external module babel-register
[16:50:27] Using gulpfile C:\Git\formBuilder\gulpfile.babel.js
[16:50:27] Starting 'devJS'...
[16:50:30] Finished 'devJS' after 3.7 s
[16:50:30] Starting 'devCss'...
[16:50:34] Finished 'devCss' after 4.14 s
[16:50:34] Starting 'watch'...
[16:50:35] Finished 'watch' after 405 ms
[16:50:35] Starting 'serve'...
[16:50:35] Finished 'serve' after 165 ms
[16:50:35] Starting 'default'...
[16:50:35] Finished 'default' after 2.33 μs

events.js:160
      throw er; // Unhandled 'error' event
      ^
SyntaxError: Unexpected character '@'

```

**Comment by kevinchappell** [comment]
Ok that makes more sense. That error usually happens from running es6+ without babel-node. I havent used font-save in a while and some changes have been made to the build scripts since then.

Just tested Windows myself and having trouble with both gulp font-edit and font-save. Ubuntu and OSX seem to still work fine but Windows gulp tasks need work.

**Comment by craigpotter** [comment]
I got a error the first time I used font-edit however it was an internal server error on Fontello. 

Edit has worked fine since. 

I'll give it a go on Ubuntu over the weekend.

**Comment by kevinchappell** [comment]
@craigpotter I got that one too on the first try from Ubuntu but on Windows it didn't even open the browser.

**Comment by craigpotter** [comment]
@kevinchappell maybe Fontello are having some issues as well if we both got internal server errors. 

Weird your Windows browser didn't open at all. Bank Holiday weekend over in the UK so I will try to spend some time and investigate.

**Comment by craigpotter** [comment]
Hey @kevinchappell 
Did you ever look at this issue?

**Comment by craigpotter** [comment]
I managed to narrow the issue down to browserify.
In src/js/form-builder.js , you are using `import '../sass/form-builder.scss'; `

Browserify sees the first line and sees `@import` and falls over ... Not sure the solution however!

**Comment by kevinchappell** [comment]
sorry i forgot to update this issue... but its solved now.
Gulp is no longer used and font scripts use only node modules.
