### ISSUE TITLE
Form Builder within a form - Required Field stop submission

### ISSUE THREAD

**Issue by craigpotter** [kevinchappell/formBuilder#504]
### Description:
If form builder is used within a form and you mark any fields as required, it stops the parent form from being submitted. 

Version 2.3.4 

### Expected Behavior
Should allow parent form 
### Actual Behavior
HTML5 Validation kicks in and stops the form from being submitted 

### Steps to Reproduce

https://codepen.io/anon/pen/BRbbjW

**Comment by ankurk91** [comment]
This is the normal behaviour

**Comment by craigpotter** [comment]
In my case, I have the form builder on a page within a form. On submitting the form, it uses the getData() function to assign the form builder data to a hidden field. 

I guess I could try and move the form builder outside the form but seems like this could be the common path users might take. 

Maybe it just needs to be documented? Any thoughts @kevinchappell

**Comment by kevinchappell** [comment]
I could see where this is a bug as formbuilder is sometimes used inside a form submitted the normal submit way. I found a solution but probably can't get to it until Monday.
