### ISSUE TITLE
Template for all defaultFields option types.

### ISSUE THREAD

**Issue by ghostfreak3000** [kevinchappell/formBuilder#51]
To reload fields in the formBuilder i have to enter their structure in the defaultFields option...
currently the only type whose template i found was 'text'..

I specifically want to know how to add the options for select list and checkbox group types...

**Comment by kevinchappell** [comment]
Reloading saved fields should really be done using the `textarea` value. Here are some examples on how to do it both ways though.
defaultFields: http://codepen.io/kevinchappell/pen/pgxYEW
textarea value: http://codepen.io/kevinchappell/pen/MKXybG

**Comment by ghostfreak3000** [comment]
Just between you and me.. I hate working with XML, that's why when i saw the default fields takes json, it did me solid.

Thanks for the code pen.. saved me.

**Comment by kevinchappell** [comment]
I'm not a fan either but it was a technical requirement of version 1. The new formBuilder will have full JSON support.
