### ISSUE TITLE
disabledAttrs not removing all fields

### ISSUE THREAD

**Issue by dylanvdmerwe** [kevinchappell/formBuilder#511]
## Description:
I am trying to remove attribute fields that I do not need. 

 - Help Text
 - Class
 - Text Area Type

I cannot disable these fields. 

### Environment Details:

 - formBuilder Version: 2.4.1
 - Browser: Chrome
 - OS: Mac

### Sample Code
```
                                var options = {
                                    disableFields: ['autocomplete', 'button', 'checkbox-group', 'header', 'hidden', 'paragraph', 'radio-group', 'select'],
                                    disabledAttrs: ['placeholder', 'helptext', 'required', 'name', 'access', 'max', 'class', 'rows', 'value', 'type'],
                                    disabledActionButtons: ['data', 'clear', 'save']
                                }
                                $(document.getElementById('fb-editor')).formBuilder(options);
```

### Expected Behavior
Help Text, Class and any other fields should be removed from the list. When removed, should be set to their default values. 

### Actual Behavior
The fields in the designer are not removed.

**Comment by kevinchappell** [comment]
I think [some tweaks to your config](https://jsfiddle.net/v8mhwwaz/) could hide the rest of the attributes. The problem here is we need better documentation on what the field and attribute ids are.

**Comment by dylanvdmerwe** [comment]
Ah your example worked. Yes, I was looking through the source where all the attributes were defined but couldn't find. Documenting these would be a great idea.
