### ISSUE TITLE
Unique ID field generated per field

### ISSUE THREAD

**Issue by dylanvdmerwe** [kevinchappell/formBuilder#512]
### Description:
Each field should have a hidden `Id` (not shown in the attributes). I know there is a `Name` field with the time appended, but this is not good enough unfortunately if a user quickly adds two fields onto the form. 

### Environment Details:

 - formBuilder Version: 2.4.1
 - Browser: Chrome
 - OS: Mac

### Expected Behavior
 - When a control is dragged onto the builder, create a _hidden_ `Id` element
 - This `Id` is a randomly generated number or Guid.
 - When accessing `formData`, this `Id` field should be present. 
 - This `Id` field should not be a viewable attribute on the UI
 - When populating `formData` from the server, set the `Id` if present. If no `Id` is given, randomly generate one for use going forward.

### Actual Behavior
There is no `Id` generated for each field to properly identify each field. This is problematic when using a form builder as a template generator which can then be applied to other instances. 

Also, in my specific case I don't want the end user to see the `Id`.

**Comment by kevinchappell** [comment]
I've had some time to think about this and unfortunately it's not possible without some refactoring of core plugin. 

Ideally the formData would be refactored to be something similar to [formeo](https://draggable.github.io/formeo/), where its possible to have both uuid and id attribute for fields. Ex:
```
...
	"fields": {
		"59b704e6-d185-4fa8-b8c2-7bcd40e4337e": {
			"tag": "input",
			"attrs": {
				"type": "text",
				"id": "my-id"
			},
			"config": {
				"label": "Text"
			},
			"meta": {
				"group": "common",
				"icon": "text-input",
				"id": "text-input"
			},
			"id": "59b704e6-d185-4fa8-b8c2-7bcd40e4337e"
		}
	}
...
```
 In formBuilder's data structure this could be accomplished by either:

1. modifying formData structure which would be a breaking change for a lot of apps
2. or adding a special attribute which would need special processing, something like a `uuid` attribute.

There may be some other options I'm missing.

**Comment by lucasnetau** [comment]
@kevinchappell Pretty sure this one can be closed. Id is set to value of Name and we guarantee that it is unique using the timestamp+counter method
