### ISSUE TITLE
How to disable to add default class for label tag?

### ISSUE THREAD

**Issue by gotounix** [kevinchappell/formBuilder#514]
### Description:
`
<label for="date-1496234746595" class="fb-date-label">
`

Can I disabled automatically generating class for label?

`
<label for="date-1496234746595" class="">
`

### Environment Details:

 - formBuilder Version: 2.3.5
 - Browser: Chrome 58.0.3029.110
 - OS: Windows 10

**Comment by kevinchappell** [comment]
Currently there is no api for that but you could do it with some extra javascript that runs after render.

**Comment by Jojoshua** [comment]
Closing since this is a very old version issue
