### ISSUE TITLE
NoConflict() compatibility

### ISSUE THREAD

**Issue by jordan314** [kevinchappell/formBuilder#518]
Thanks for making this project!
Could you wrap your whole code in 
`jQuery( document ).ready(function( $ ) {
  // Code that uses jQuery's $ can follow here.
});`
to enable noConflict() compatibility? When I include jQuery and then formBuilder, I get a "$ is not defined" error because I am in a noConflict() environment.

**Comment by brentkelly** [comment]
There has been some discussion on this issue (my project requires prototype & jQuery to run at the same time *shudder*). Wrapping it in an IIFE seems to be the generally accepted best practice for jQuery plugins.

```
(function($) {
  // jQuery code
}(jQuery);)
```

**Comment by ankurk91** [comment]
[gulp-insert](https://www.npmjs.com/package/gulp-insert#wrap) may help here
This is how i do -
```js
const gulp = require('gulp');
const insert = require("gulp-insert");
 const uglify = require("gulp-uglify");

gulp.task('js',function() {

return gulp.src('js/**/*.js')
// Add a new pipe before uglify
.pipe(insert.wrap('(function(window,document,jQuery){', '})(window,document,jQuery);'))
.pipe(uglify())
.pipe(gulp.dest('dist/app.js'))
})


```

**Comment by brentkelly** [comment]
yeah - `gulp-iife` also did the trick. Alas we have moved away from gulp and are using webpack now.

**Comment by jordan314** [comment]
Is there any disadvantage to putting the source in an IIFE as opposed to using an external tool?

**Comment by brentkelly** [comment]
Yes - the source is contained in many files which are joined together by webpack & minified. Putting every piece of code in its own IIFE would be both cumbersome & cause problems with namespaces / scoping.

**Comment by kevinchappell** [comment]
plugin output is now wrapper in an iife as of 2.10.4
