### ISSUE TITLE
Re-render XML after sorting elements

### ISSUE THREAD

**Issue by ghostfreak3000** [kevinchappell/formBuilder#52]
Hey.. I feel bad that i've opened so many issues on day-1 with the formBuilder.
But I think that proves it's an amazing plugin... and i'm already a dependent

So, when i finish sorting the elements on the form, the xml isn't re-rendered unless something else is done to trigger the render( like adding a new element, or editing an attribute of an existing one)..

Any way to trigger a re-render of the XML for the new sorted order.. after a sort?

**Comment by kevinchappell** [comment]
Thats a bug I've been meaning to get to. Fixed in #55

**Comment by ghostfreak3000** [comment]
Thanks!
