### ISSUE TITLE
Why I can't get value from autocomplete field?

### ISSUE THREAD

**Issue by gotounix** [kevinchappell/formBuilder#520]
### Description:

I can't get value from autocomplete field.

### Environment Details:

 - formBuilder Version: 2.3.5/2.5.1
 - Browser: Chrome 58.0.3029.110
 - OS: Windows 10

### Screenshot - *(optional)*

![Config](https://cloud.githubusercontent.com/assets/18606632/26769855/c9bdc064-49e4-11e7-94f2-853e6386e736.png)
![Test submit](https://cloud.githubusercontent.com/assets/18606632/26769859/cdca99fc-49e4-11e7-9596-2745d0a2280b.png)

**Comment by kevinchappell** [comment]
This should be fixed now in #521
