### ISSUE TITLE
Getting the Values of all pages.

### ISSUE THREAD

**Issue by littletias** [kevinchappell/formBuilder#523]
### Description:
When ever i try to save the  "formBuilder.actions.getData('json', true)" it only serves me the first page(when editor contains more pages than 1). 
Is there a way that i can get all the pages and not just the first?

### Environment Details:

 - formBuilder Version: v2.5.1
 - Browser: Chrome
 - OS: Windows.

### Expected Behavior
returns json formatted result for everypage in the editor.
### Actual Behavior
returns only the first page in the editor and leaves out the rest.

**Comment by brentkelly** [comment]
@littletias can you please provide further explanation. Formbuilder doesn't support "pages" ... so I am not sure you have you multiple. Perhaps this is something specific to how it has been implemented in your application?

**Comment by littletias** [comment]
Hi Brent, 
ive been following some of the documentation and what ive implemented is something like this: http://formbuilder.readthedocs.io/en/latest/formBuilder/demos/tabs/
this is what i mean when i say " multiple pages" :-)

**Comment by brentkelly** [comment]
Ahhh I see. My bad :). I didn't notice the tabs feature. :). I've never used it so can't be too much help unfortunately.

**Comment by kevinchappell** [comment]
I've updated the demo to show how to grab value from all editors.

https://codepen.io/kevinchappell/pen/BKYPRp

**Comment by littletias** [comment]
i salute you sir (y)
