### ISSUE TITLE
Unhandled promise rejection Error: Zone.js has detected that ZoneAwarePromise

### ISSUE THREAD

**Issue by anikets43** [kevinchappell/formBuilder#524]
I have imported FormBuilder in Angular 4 project and using as a wrapper. I'm able to generate the form template, but the having issue with trying to render the form. Adding [https://formbuilder.online/assets/js/form-render.min.js](url) to angular-cli throws following error.

`VM405:6 Unhandled promise rejection Error: Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.
Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)
    at Function.Zone.assertZonePatched (zone.js:39) [<root>]
    at new NgZone (core.es5.js:3973) [<root>]
    at PlatformRef_._bootstrapModuleFactoryWithZone (core.es5.js:4767) [<root>]
    at :4200/vendor.bundle.js:5417:59 [<root>]
    at eval (eval at webpackJsonp.53.module.exports (scripts.bundle.js:1), <anonymous>:6:142326) [<root>]
    at eval (eval at webpackJsonp.53.module.exports (scripts.bundle.js:1), <anonymous>:6:142435) [<root>]
    at MutationObserver.s (eval at webpackJsonp.53.module.exports (scripts.bundle.js:1), <anonymous>:6:81210) [<root>]
    at Zone.runGuarded (zone.js:138) [<root> => <root>]
    at MutationObserver.<anonymous> (zone.js:116) [<root>]`

Code 
` ngAfterViewInit() {
    const formData = this.template;
    const formRenderOpts = {
      formData,
      dataType: 'json'
    };
    const fbEditor = document.getElementById('emp-form');
    this.form = $(fbEditor).formRender(formRenderOpts);
  }`

Thanks in advance,
Aniket

**Comment by littletias** [comment]
did you try what the error message states?
##############
Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)

**Comment by KhaledSMQ** [comment]
@anikets43  have you manage to solve this problem , I have exact same issue trying to use formbuilder with Angular 4

**Comment by kevinchappell** [comment]
@KhaledSMQ Did you ever get this sorted out? The latest version has a lot of improvements regarding polyfills, namely that browser support has changed so it should no longer be loaded. Can someone verify if this is still an issue?

**Comment by kevinchappell** [comment]
Excellent, thanks for making that demo!

**Comment by KhaledSMQ** [comment]
by the way, in the website 
https://formbuilder.readthedocs.io/en/latest/getting-started/

please update the document 
```
  <script src="http://formbuilder.online/assets/js/form-builder.min.js"></script>
```
to use  **https** since chrome and other browsers didn't allow mixed content if you are trying to load http and https 
```
<!DOCTYPE html>
<html>
<head>
    <title>Example formBuilder</title>
</head>
<body>
  <div id="fb-editor"></div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
  <script src="https://formbuilder.online/assets/js/form-builder.min.js"></script>
  <script>
  jQuery(function($) {
    $(document.getElementById('fb-editor')).formBuilder();
  });
  </script>
</body>
</html>
```

**Comment by kevinchappell** [comment]
oh good, thanks for letting me know. i'll change it now.
