### ISSUE TITLE
JSON data source for Autocomplete and select components 

### ISSUE THREAD

**Issue by syedhasanabbaszaidi** [kevinchappell/formBuilder#526]
### Description:
Requirement of functionality where autocomplete or select components needs to populate data with json data source. This can be a url json request but in offline form view remote data source cannot be loaded, hence if a feature comes to load data from a local json file (may be a flat json file not hierarchical ) than its great for dynamic real time application.
### Environment Details:

 - formBuilder Version: 
 - Browser: 
 - OS:

**Comment by foaadnami** [comment]
+1

**Comment by cipu** [comment]
+1

**Comment by jseger** [comment]
+10

**Comment by kevinchappell** [comment]
At the moment there are no plans to add this natively. To make this work properly you wold have to also define a mapping so the received data matches formBuilder's expected schema. Considering that its only another step to just have a custom control that handles it entirely. Have a look at the autocomplete control, you can make your own files based on it that populates the options from a datasource.

Even easier would to use `replaceFields` and add the datasource on init but for more dynamic forms like selecting auto make and models you could use `typeUserEvents`
