### ISSUE TITLE
Custom Controls Appear On All Instances of FormBuilder

### ISSUE THREAD

**Issue by starlightknight** [kevinchappell/formBuilder#528]
### Description:

Hi,
Thanks providing this cool tool to the community!. I have been playing with FormBuilder within an SPA (in this case, within Angular2). 

Let's say I have some custom controls defined, and I have FormBuilder appear within two different components in the app. On one component, custom controls are added in addition to what is provided with formbuilder. On component 2, only the standard controls are configured. Because the custom controls are registered statically, the custom controls appear on any future formbuilders within the app once they are encountered, even if I pass in an empty array/object for fields and templates to instances that should not receive them. 

From what I can tell, there does not seem to be a sanctioned way to clear the custom controls list, or deregister a custom control. 

While I could hide them with disableFields, that requires each component to be aware of all possible custom types that other components might provide, and which ones they should not use, which is cumbersome. It would be great if these were either not static (and associated only with the current instance), or could be easily cleared or reset with a new instance of the form builder.

### Environment Details:

 - formBuilder Version: 2.5.3
 - Browser: Firefox/Chrome
 - OS: Linux

### Expected Behavior

Custom controls should only appear on form builder instances that have them configured

### Actual Behavior

Custom controls appear on all future form builder instances, whether they were configured for that instance or not.

### Steps to Reproduce

Within an SPA, place formbuilder on two components. Add a custom control to formbuilder on component 1. Navigate to component 2. Component 2's formbuilder will also have the custom control, even if none were configured.

**Comment by mikevoets** [comment]
Got the same problem here.

**Comment by jakovac** [comment]
Yea, me 2, got same problem.

**Comment by kevinchappell** [comment]
@jakovac can you test this with the latest version? custom control registration should now be scoped instead of global. Please reopen if the issue persists

**Comment by tnguyenxuan** [comment]
@kevinchappell I'm using v3.1.2 right now, seem likes this bug still be existed. All of my instances (after initializing an instance with customs controls) will be affected. Any solutions for working around? Thanks you :).

**Comment by kevinchappell** [comment]
@tnguyenxuan Not that I know of other than removing the control after initialization with extra js. I'll take another look at this. re-opening.

**Comment by kevinchappell** [comment]
custom controls have been refactored to display on individual instances, if this is still an issue please reopen with a codepen demonstrating the error
