### ISSUE TITLE
FormBuilder: Label Fields Glitch When Enter Is Pressed

### ISSUE THREAD

**Issue by starlightknight** [kevinchappell/formBuilder#532]
### Description:
Label fields start creating visual glitches if the user presses enter while one is selected. It seems to accept multiline input, even though the box is presented as a single line control. FormBuilder will start inserting ```<br>``` tags in the background. First press will glitch the cursor. Further presses will start inserting line breaks between elements within the FormBuilder

### Environment Details:

 - formBuilder Version: 2.5.3
 - Browser: Firefox/Chrome
 - OS: Linux

### Expected Behavior
If label is a single line control, it should ignore the enter key (the other single line fields do).

### Actual Behavior
Various display glitches happen

### Steps to Reproduce

1) Create any element
2) Start to fill out a label
3) Press enter one or more times while the label field is in focus.

### Screenshot - *(optional)*

http://www.mediafire.com/view/z2n9e1k20ylfdw0/Form+Builder+Label+Field+Enter+Bug.png

**Comment by cklone** [comment]
Verified this is still happening in v2.9.8, although now the `<br>` tag is wrapped in a `<div>`.

**Comment by faizu88** [comment]
.label-wrap .fld-label{
     height: auto !important;
}

**Comment by kevinchappell** [comment]
This is fixed now in 2.10.3 using @faizu88 code 👍
