### ISSUE TITLE
[PROPOSAL] Add Explicit Support of Grid System

### ISSUE THREAD

**Issue by meysampg** [kevinchappell/formBuilder#534]
### Description:
In some situations (actually in many situations) you need to put some elements in a row. For example you wanna generate a form that the username and password fields are in a row. This can be done with a grid system.

### Possible Solution
It can be done with adding custom CSS style to `Class` attribute of a field. As showed in this picture:
![with-col-md](https://user-images.githubusercontent.com/1416085/27418584-405f634a-5731-11e7-9207-b59df3d4e918.png)

### Expected Behavior
It's a good idea if we have an extra attribute which just with clicking on its options, we be able to select a grid and the selected value be added on a extra field of `json` (or `xml`) output. For example something like this:
![with-grid-buttons](https://user-images.githubusercontent.com/1416085/27418594-4b8c37e8-5731-11e7-9331-b29b86e89cd8.jpg)

will produce an output like this:
```json

[
	{
		"type": "text",
		"label": "Username",
		"className": "form-control",
                "grid": "50",
		"name": "username",
		"subtype": "text"
	},
	{
		"type": "text",
		"subtype": "password",
		"label": "Password",
		"className": "form-control",
                "grid": "50",
		"name": "password"
	}
]
``` 
With this feature programmers will be able to choose a correct grid option based on their front-end system (for above example, they can choose `col-md-6` on `bootstrap` or `large-6` on `foundation`, in fact they will be free on choice!).

**Comment by Jojoshua** [comment]
> ### Description:
> In some situations (actually in many situations) you need to put some elements in a row. For example you wanna generate a form that the username and password fields are in a row. This can be done with a grid system.
> 
> ### Possible Solution
> It can be done with adding custom CSS style to `Class` attribute of a field. As showed in this picture:
> ![with-col-md](https://user-images.githubusercontent.com/1416085/27418584-405f634a-5731-11e7-9207-b59df3d4e918.png)
> 
> 
> ### Expected Behavior
> It's a good idea if we have an extra attribute which just with clicking on its options, we be able to select a grid and the selected value be added on a extra field of `json` (or `xml`) output. For example something like this:
> ![with-grid-buttons](https://user-images.githubusercontent.com/1416085/27418594-4b8c37e8-5731-11e7-9331-b29b86e89cd8.jpg)
> 
> 
> will produce an output like this:
> ```json
> 
> [
> 	{
> 		"type": "text",
> 		"label": "Username",
> 		"className": "form-control",
>                 "grid": "50",
> 		"name": "username",
> 		"subtype": "text"
> 	},
> 	{
> 		"type": "text",
> 		"subtype": "password",
> 		"label": "Password",
> 		"className": "form-control",
>                 "grid": "50",
> 		"name": "password"
> 	}
> ]
> ``` 
> With this feature programmers will be able to choose a correct grid option based on their front-end system (for above example, they can choose `col-md-6` on `bootstrap` or `large-6` on `foundation`, in fact they will be free on choice!).

You can add a custom grid property yourself but I don't see how that would help. You or the library would have to translate that back to the specific grid system.

**Comment by Jojoshua** [comment]
It's a neat idea but I dont think it would work well in practice. The library would never know how to interpret this so that means it would need to expose a function for your custom logic...in that case you might as well just add the appropriate class onto the field to control this.
