### ISSUE TITLE
FormRender Required Validation

### ISSUE THREAD

**Issue by 26nmedia** [kevinchappell/formBuilder#538]

**Comment by brentkelly** [comment]
Hi @26nmedia. This falls under a bit of a debate as to how far this project should go with regard to the functionality offered by formRender. Should it just render the form controls into the page & leave validation, using & processing the final users input data to your implementation.

Or should we offer methods for retrieving values, validation etc. The historic thinking has been the former approach, hence why there is no functionality in formRender in this area.

I have outlined an implementation approach in a Google doc here: https://goo.gl/HMDFTC which would provide the functionality you've requested here.

@kevinchappell IMO this falls into the same category of functionality as providing the ability for formRender to extract values from the output controls.

**Comment by Jojoshua** [comment]
Feel free to reopen if this is still an issue.
