### ISSUE TITLE
override default templates

### ISSUE THREAD

**Issue by roger-castaldo** [kevinchappell/formBuilder#539]
### Description:
Unable to override templates for the existing items when not specifying custom fields.

### Environment Details:

 - formBuilder Version: 2.5.3
 - Browser: Firefox, Chrome
 - OS: Windows 10

### Expected Behavior
By passing in a new object in the templates option into formbuilder I can override the existing autocomplete and build it in a way where I limit it to a given set of possible urls to use in a callback as well as customize the autocomplete, which also requires disabling the options field.  With the code below I should see log messages in the console but I see none.  I believe the issue is form form-builder.js lines 46-48 where it checks to see if the fields has a value or not.  The documentation, however, indicates that you can override templates for existing items.

### Actual Behavior
The builder errors out the moment I drag a new autocomplete object onto the form builder.

### Steps to Reproduce
create a test web page with the following code inside

```
<!DOCTYPE html>
<html>
<head>
    <title>Example formBuilder</title>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
  <script src="http://formbuilder.online/assets/js/form-builder.min.js"></script>
  <script>
  function start(){
	  jQuery(function($) {
		var options = {
			disabledAttrs: ['access'],
			fields:[],
			templates:{
				autocomplete:function(fieldData){
					console.log('creating autocomplete');
					return {
						field: '<input id="'+fieldData.name+'" type="text">',
						onRender: function() {
							console.log('autocomplete rendered');
							return false;
						},
						build:function(){
							console.log('build called');
						}
					};
				}
			},
			typeUserDisabledAttrs:{
				autocomplete:['options']
			},
			typeUserAttrs:{
				autocomplete:{
					search_url:{
						label:'Search URL',
						options:{
							'/autocomplete/groupswldap':'Groups',
							'/autocomplete/roles':'Roles',
							'/autocomplete/users':'Users'
						}
					}
				}
			}
		};
		window.builder = $(document.getElementById('fb-editor')).formBuilder(options);
	  });
  }
  </script>
</head>
<body onload="start();">
  <div id="fb-editor"></div>
</body>
</html>
```

### Screenshot - *(optional)*
![image](https://user-images.githubusercontent.com/11507328/27558846-7ce4aa88-5a8c-11e7-9a49-f4a6f2e20b6e.png)

**Comment by brentkelly** [comment]
As a workaround you could create a control plugin instead. That definitely lets you override the default behavior. http://formbuilder.readthedocs.io/en/latest/formBuilder/control-plugins/ (the transpiling bit in the docs is deprecated - you can now just use `npm run-scripts build:plugins` to transpile the plugins.

**Comment by roger-castaldo** [comment]
Attached the patch generated from the fix into form-render and form-builder so that it matches the description on the templates page in the documentation that states that existing elements can have their templates  overridden.

[patch.txt](https://github.com/kevinchappell/formBuilder/files/1105678/patch.txt)

**Comment by ThuThuong234** [comment]
Hi Kevin,
I have seen in formbuilder method "disable the attribute type", but I cannot find the method to delete/disable one or more default types in formbuilder (autocomplete, fileupload,..)
Is there any way to delete/disable it
Please help me.
Thanks,
Thuong
