### ISSUE TITLE
Missing css in /dist is breaking build process

### ISSUE THREAD

**Issue by sjordan1975** [kevinchappell/formBuilder#540]
### Description:
Looks like the latest build no longer contains css in dist, so my webpack build process is breaking.

Module not found: Error: Can't resolve 'formBuilder/dist/form-builder.min.css'

### Environment Details:

 - formBuilder Version: 2.5.3
 - Browser: Chrome
 - OS: OSX

### Expected Behavior
Build process should complete without error.

### Actual Behavior
Module not found: Error: Can't resolve 'formBuilder/dist/form-builder.min.css'

### Steps to Reproduce
Reference "formBuilder/dist/form-builder.min.css" in src file

Run webpack build with similar rule:
rules: [
            {      
                test: /\.css$/,
                loader: 'style-loader!css-loader'    
            }
        ]

**Comment by kevinchappell** [comment]
css is no longer a separate file but injected from js.
