### ISSUE TITLE
Reset FormBuilder and ReInitialized without page reload

### ISSUE THREAD

**Issue by Procaseycash** [kevinchappell/formBuilder#541]
How can I achieve formBuilder re-initialization without reloading the page or destroy the formBuilder and re-initialize

**Comment by brentkelly** [comment]
Is this what you're after?
http://formbuilder.readthedocs.io/en/latest/formBuilder/actions/clearFields/

**Comment by Procaseycash** [comment]
No, the issue I am facing is that i have a custom select field created, once i initialize formBuilder on first request, it render fine but when i close the formBuilder dialog and re-initialize formBuilder, it keeps repeating the custom field for every clicked i made on the intialization because i wasn't doing page reload whenever i am re-initializing it. keep a note on the Banks field on first intialization and notice it on second intialization. 
![first intialization](https://user-images.githubusercontent.com/19539984/27681704-066b9a46-5cb8-11e7-96e4-f02e765cd0c8.png)
![second intialization](https://user-images.githubusercontent.com/19539984/27681723-0f342968-5cb8-11e7-9d0d-98bd5266da03.png)

**Comment by kevinchappell** [comment]
@Procaseycash Can you post the code for your custom control?

**Comment by Procaseycash** [comment]
import { Component, OnInit } from '@angular/core';
import {FormGroup, FormBuilder, AbstractControl, Validators, FormControl} from '@angular/forms';
import {CopingsService} from '../../../../shared/services/copings.service';
import {UserService} from '../../../../shared/services/user.service';
import {NotificationService} from '../../../../shared/services/notification.service';
import {BillerFormsService} from '../../../../shared/services/biller-forms.service';
import {ActivatedRoute} from '@angular/router';
import {ValidationErrorService} from '../../../../shared/services/validation-error.service';
import {BillerEndpointsService} from '../../../../shared/services/biller-endpoints.service';
import {Cache} from '../../../../shared/util/cache';
declare const jQuery: any;
@Component({
  selector: 'app-forms-actions',
  templateUrl: './forms-actions.component.html',
  styleUrls: ['./forms-actions.component.css']
})
export class FormsActionsComponent implements OnInit {
  public listFormActions:  Array<any> = [];
  public microServices:  Object = {};
  public listEndpoints:  Array<any> = [];
  public createFormActions: FormGroup;
  public createHeader = 'Register New Form Action';
  public formID: any;
  public billerFormObj: any;
  private authUser: any;
  viewFormAction: any;
  booleanVar = {
    loading: true,
    adder: false,
    view: false,
    edit: false,
    react: false,
    validate: false,
    endpoint: null,
    endpointLoader: false,
    exist: 0,
    message: 'Registering, please wait...'
  };

  public alert = {
    visible: false
  };

  private stepsObj = {
    name: '',
    formId: 0,
    payloads: ''
  };

  private  templates = {
    country_list: (fieldData) => {
      return {
        field: '<span id="' + fieldData.name + '">',
        onRender: function() {
        }
      }
    },
    state_list: (fieldData) => {
      return {
        field: '<span id="' + fieldData.name + '">',
        onRender: function() {
        }
      }
    }
  };
  private fields = [
    {
      type: 'country_list',
      icon: '<i class="fa fa-list"></i>',
      label: 'Country List',
      name: 'country_list',
      className: 'form-control',
    },
    {
    type: 'select',
    icon: '<i class="fa fa-bank"></i>',
    label: 'Banks',
    name: 'bank_list',
    className: 'form-control',
    values: [
      {
        label: 'Access Bank',
        value: '044',
        selected: false
      },
      {
        label: 'Citibank',
        value: '023',
        selected: false
      },
      {
        label: 'Diamond Bank',
        value: '063',
        selected: false
      },
      {
        label: 'Ecobank',
        value: '050',
        selected: false
      },
      {
        label: 'Fidelity Bank',
        value: '070',
        selected: false
      },
      {
        label: 'First Bank',
        value: '011',
        selected: false
      },
      {
        label: 'First City Monument Bank',
        value: '214',
        selected: false
      },
      {
        label: 'Guaranty Trust Bank',
        value: '058',
        selected: false
      },
      {
        label: 'Keystone Bank',
        value: '082',
        selected: false
      },
      {
        label: 'Mainstreet Bank',
        value: '014',
        selected: false
      },
      {
        label: 'Skye Bank',
        value: '076',
        selected: false
      },
      {
        label: 'Stanbic IBTC Bank',
        value: '221',
        selected: false
      },
      {
        label: 'Standard Chartered Bank',
        value: '068',
        selected: false
      },
      {
        label: 'Sterling Bank',
        value: '232',
        selected: false
      },
      {
        label: 'Union Bank',
        value: '032',
        selected: false
      },
      {
        label: 'United Bank for Africa',
        value: '033',
        selected: false
      },
      {
        label: 'Unity Bank',
        value: '215',
        selected: false
      },
      {
        label: 'Wema Bank',
        value: '035',
        selected: false
      },
      {
        label: 'Zenith Bank',
        value: '057',
        selected: false
      },
      {
        label: 'Spring Bank',
        value: '084',
        selected: false
      }
    ]
  },
    {
      type: 'state_list',
      icon: '<i class="fa fa-list"></i>',
      label: 'State List',
      name: 'state_list',
      className: 'form-control',
    }];
  private types = ['date', 'select', 'text', 'textarea', 'number', 'country_list', 'state_list'];
  private globalTypeUserDisabledAttrs = ['access'];
  private  globalTypeUserAttrs = {
  disabled: {
    label: 'Disabled',
    type: 'checkbox'
  },
  readonly: {
    label: 'Readonly',
    type: 'checkbox'
  },
  hidden: {
    label: 'Hidden',
    type: 'checkbox'
  }
};

  private fbOptions = {
    onSave: (e, formData) => {
      this.saveFormSteps(formData);
    },
    stickyControls: {
      enable: true
    },
    sortableControls: true,
    disableFields: [
      'autocomplete',
      'file',
      'button',
      'paragraph',
      'header',
      'checkbox-group',
      'radio-group',
      'hidden',
    ]
  };

  constructor(
    private fb: FormBuilder,
    private copings: CopingsService,
    private userService: UserService,
    private Alert: NotificationService,
    private billerFormsService: BillerFormsService,
    private billerEndpointsService: BillerEndpointsService,
    private activatedRoute: ActivatedRoute,
    private validationError: ValidationErrorService
  ) {
    this.authUser = this.userService.getAuthUser();
    this.createFormActions = this.resetBillerFormObj();
  }

  /**
   * This is used to get to disable or assign field attributes
   * @param type
   * @param values
   * @returns {{}}
   */
  getTypeAttrs = (type, values) => {
    const x = {};
    if (Array.isArray(type)) {
      for (let i = 0; i < type.length; i++) {
        x[type[i]] = values;
      }
    }  else {
      x[type] = values;
    }

    return x;
  };


  resetStepsObj() {
    this.stepsObj = {
      name: '',
      formId: 0,
      payloads: ''
    }
  };

  /**
   * Used to display Error message
   * @param data
   */
  showError(data) {
    if (data.status_code === 1400) {
      this.alert = this.Alert.warning((this.validationError.message(data.validation)));
    } else {
      this.alert = this.Alert.warning(data.message);
    }
  }


  /**
   * This is used to reset the create user form field
   */
  resetBillerFormObj(): any {
    return {
      name: ['', Validators.required]
    };
  };

  /**
   * This is used to add controls endpoint based on selected endpoint type
   * @param type
   */
  addEndpointControls(type) {
    this.createFormActions.addControl('method', new FormControl('', Validators.required)); // method required is validation is needed
    if (type) {
      this.booleanVar.endpoint = type;
      this.createFormActions.addControl('biller_endpoint_id', new FormControl('', Validators.required));
      this.createFormActions.removeControl('micro_service_id');
      this.getListBillerEndpoints();
    } else if (type === false) {
      this.booleanVar.endpoint = type;
      this.createFormActions.addControl('micro_service_id', new FormControl('', Validators.required));
      this.createFormActions.removeControl('biller_endpoint_id');

      this.getMicroServices();
    } else {
      this.alert = this.Alert.warning('No Option Selected');
    }
  };

  /**
   * This is used to remove form controls if no validation is required for step during creation
   */
  removeControls() {
    this.booleanVar.validate = false;
    this.booleanVar.endpoint = null;
    this.createFormActions.removeControl('biller_endpoint_id');
    this.createFormActions.removeControl('micro_service_id');
    this.createFormActions.removeControl('method');
    this.resetStepsObj();
  };

  /**
   * This is used to load available micro-services
   */
  getMicroServices() {
    console.log(Cache.get('listMicroServices'));
    if (Cache.get('listMicroServices') !== null) {
      this.booleanVar.exist = 2;
      this.microServices = Cache.get('listMicroServices');
      this.createFormActions.controls['micro_service_id'].setValue(this.microServices['id']);
      return null ;
    }
    this.booleanVar.endpointLoader = true;
    this.booleanVar.message = 'loading micro services, please wait';
    this.billerFormsService.listMicroServices().subscribe(
      data => {
        if (data !== undefined && data !== null && data.status) {
          if (Object.keys(data.data).length !== 0) {
            this.microServices = data.data;
            this.booleanVar.exist = (Object.keys(this.microServices).length > 0) ? 2 : 4;
            Cache.set('listMicroServices', this.microServices);
            this.createFormActions.controls['micro_service_id'].setValue(this.microServices['id']);
            // this.alert = this.Alert.success('Biller form actions fetched successfully');
          } else {
            this.booleanVar.exist = 4;
          }
        } else {
          this.showError(data);
          this.booleanVar.exist = 4;
        }
        this.booleanVar.endpointLoader = false;
        console.log('dataListMicro =>', data);
      },
      err => {
        this.booleanVar.endpointLoader = false;
        this.alert = this.Alert.error(err.message || 'An error was encountered, please contact admin.');
        console.log('Err response', err);
      }
    );
  };

  /**
   * This is used to load available endpoints
   */
  getListBillerEndpoints() {
    if (Cache.get('listEndpoints') !== null) {
      this.booleanVar.exist = 1;
      this.listEndpoints = Cache.get('listEndpoints');
      return null ;
    }
    this.booleanVar.endpointLoader = true;
    this.billerEndpointsService.listEndpointsByTypeLight('validation').subscribe(
      data => {
        console.log('listEndpoints =>', data);
        if (data !== undefined && data !== null && data.status) {
          if (data.data.list.length !== 0) {
            this.listEndpoints = data.data.list;
            this.booleanVar.exist = (this.listEndpoints.length > 0) ? 1 : 3;
            Cache.set('listEndpoints', this.listEndpoints);
          } else {
            this.booleanVar.exist = 3;
          }
         // this.alert = this.Alert.success('Biller form actions fetched successfully');
        } else {
          this.showError(data);
          this.booleanVar.exist = 3;
        }
        this.booleanVar.endpointLoader = false;
      },
      err => {
        this.booleanVar.endpointLoader = false;
        this.alert = this.Alert.error(err.message || 'An error was encountered, please contact admin.');
        console.log('Err response', err);
      }
    );
  };

  /**
   * Retrieves the list of available Form steps for Biller
   */
  getListFormActions() {
    this.booleanVar.message = 'Loading form actions, please wait...';
    this.billerFormsService.listFormActions(this.formID).subscribe(
      data => {
        if (data !== undefined && data !== null && data.status) {
          this.listFormActions = data.data;
          this.alert = this.Alert.success('Form steps fetched successfully');
        } else {
          this.showError(data);
        }
        this.booleanVar.loading = false;
        console.log('dataList =>', data);
      },
      err => {
        this.booleanVar.loading = false;
        this.alert = this.Alert.error(err.message || 'An error was encountered, please contact admin.');
        console.log('Err response', err);
      }
    );
  }


  /**
   * This used to view user in overlap
   */
  OpenViewFormActions(action) {
    this.viewFormAction = this.copings.deepCopy(action);
    this.booleanVar.view = true;
  }


  /**
   * This is used to open overlap for edit or create.
   * @param type
   * @param form
   */
  createFormActionsOverlap(type, form?: any) {
    console.log('actions= ', form);
    this.booleanVar.adder = true;
    if (type === 'edit') {
      this.booleanVar.validate = true;
      this.booleanVar.edit = true;
      this.billerFormObj = this.copings.deepCopy(form);
      console.log('form=', this.billerFormObj);
      this.billerFormObj.payloads = [this.billerFormObj.payloads];
      this.createFormActions = this.fb.group(this.billerFormObj);

      if (this.billerFormObj.endpoint_type === 'App\\BillerEndpoint')  {
        this.addEndpointControls(true);
        this.createFormActions.controls['biller_endpoint_id'].setValue(this.billerFormObj.endpoint.id);
        this.createFormActions.controls['method'].setValue(this.billerFormObj.method);
        this.getListBillerEndpoints();
        this.booleanVar.endpoint = true;
      }

      if (this.billerFormObj.endpoint_type === 'App\\MicroService')  {
        this.addEndpointControls(false);
        this.createFormActions.controls['micro_service_id'].setValue(this.billerFormObj.endpoint.id);
        this.createFormActions.controls['method'].setValue(this.billerFormObj.method);
        this.getMicroServices();
        this.booleanVar.endpoint = false;
      }

      this.createHeader = 'Update Form Steps Information.';
      console.log('edit pages=', this.createFormActions.value);
      this.resetStepsObj();
    } else {
      this.booleanVar.edit = false;
      this.createHeader = 'Register New Form Steps';
      this.billerFormObj = this.resetBillerFormObj();
      this.createFormActions = this.fb.group(this.billerFormObj);
    }
    // load form builder or re-render existing forms in form builder
    this.runFormBuilder();
  };

  /**
   * This is used to validate form steps during creation
   * @returns {boolean}
   */
  checkFormValues() {
    console.log('subjects=', this.stepsObj);
    let returnType = false;
    let val = null;
  Object.keys(this.stepsObj).forEach((key) => {
     if (key === 'payloads') {
       val = JSON.parse(this.stepsObj[key]);
       if (val.length === 0) {
         this.alert = this.Alert.error(`Please Drag and Drop a field to create Payloads`);
         return returnType = true;
       }
     }
      if (!this.stepsObj[key]) {
       key = (key === 'micro_service_id' || key === 'biller_endpoint_id') ? 'Endpoint' : key ;
        this.alert = this.Alert.error(`${key} is required`);
        return returnType = true;
      }
  });

  return returnType;
  }

  /**
   * This is used to save form steps
   * @param formData
   */
  saveFormSteps = (formData) => {
    this.stepsObj.name = this.createFormActions.value.name;
    this.stepsObj.payloads = formData;
    this.stepsObj.formId = this.formID;
    if (this.booleanVar.endpoint) {
        this.stepsObj['biller_endpoint_id'] = this.createFormActions.value.biller_endpoint_id;
        this.stepsObj['method'] = this.createFormActions.value.method;
    } else if (this.booleanVar.endpoint === false) {
      this.stepsObj['micro_service_id'] = this.createFormActions.value.micro_service_id;
      this.stepsObj['method'] = this.createFormActions.value.method;
    }
    console.log('this.createFormActions.value=', this.createFormActions.value);
    if (this.checkFormValues()) { return null; }
    console.log('formSteps=', this.stepsObj);
    this.booleanVar.react = true;
    this.booleanVar.message = 'Creating form steps, please wait...';
    if (this.booleanVar.edit) {
      this.stepsObj['id'] = this.createFormActions.value.id;
    }
    this.billerFormsService.createOrUpdateFormActions(this.booleanVar.edit, this.stepsObj).subscribe(
      data => {
        console.log(data);
        if (data !== undefined && data !== null && data.status) {
          if (this.booleanVar.edit) {
              this.booleanVar.adder = false;
              this.listFormActions.forEach((step, i) => {
                console.log(i + '=ids=', this.stepsObj['id'], step['id']);
                if (step['id'] === this.stepsObj['id']) {
                  console.log('passedFormData= ', formData);
                  this.listFormActions[i]['payloads'] = this.copings.deepCopy(JSON.parse(formData));
                }
              });
          } else {
            this.booleanVar.adder = false;
            this.listFormActions.push(data.data);
            this.alert = this.Alert.success('Form Steps Created successfully');
          }
          this.resetStepsObj(); // reset step object
        } else {
          this.showError(data);
        }
        this.booleanVar.react = false;
      },
      err => {
        this.Alert.error(err.message || 'An error was encountered, please contact admin.');
      }
    );
  };


  /**
   * This is used to render form builder
   */
  runFormBuilder() {
    // render form builder
    this.booleanVar.endpoint = null ;
    this.booleanVar.validate = false;
    const checkFieldExistence = this.fbOptions['fields'];
    console.log('checkExist= ', checkFieldExistence);
    const typeUserDisabledAttrs = this.getTypeAttrs(this.types, this.globalTypeUserDisabledAttrs);
    typeUserDisabledAttrs['country_list'] = ['placeholder', 'access', 'value'];
    typeUserDisabledAttrs['state_list'] = ['placeholder', 'access', 'value'];
    this.fbOptions['typeUserDisabledAttrs'] = typeUserDisabledAttrs;
    this.fbOptions['typeUserAttrs'] = this.getTypeAttrs(this.types, this.globalTypeUserAttrs);
    this.fbOptions['fields'] = this.fields;
    this.fbOptions['templates'] = this.templates;
    if (this.booleanVar.edit) {
        this.fbOptions['formData'] = JSON.stringify(this.billerFormObj['payloads'][0]);
    }

    jQuery($ => {
      $('.fb-form-steps').formBuilder(this.fbOptions);
    });
  }


  /**
   * This is used to delete form steps under a biller
   * @param id
   */
  deleteFormAction(id) {
    /*if (!confirm('Are you sure you want to delete this form step?')) {
      return;
    }*/
    this.booleanVar.message = 'Deleting step, please wait...';
    this.booleanVar.react = true;
    this.billerFormsService.deleteFormAction(id).subscribe(
      data => {
        if (data !== undefined && data !== null && data.status) {
          this.listFormActions = this.copings.deepCopy(this.listFormActions.filter(step => step.id !== id));
          this.alert = this.Alert.success('Step deleted successfully.');
          this.booleanVar.adder = false;
        } else {
          this.showError(data);
        }
        this.booleanVar.react = false;
        console.log('deleted step', data);
      },
      err => {
        this.booleanVar.react = false;
        this.alert = this.Alert.error(err.message || 'An error was encountered, please contact admin.');
        console.log('err response', err);
      }
    );
  }

  ngOnInit() {
    this.formID = parseInt(this.activatedRoute.snapshot.params['formID']);
    console.log(this.formID);
    this.getListFormActions();
   }

}

**Comment by starlightknight** [comment]
I believe you're hitting #528 - the custom fields are initialized statically, so they end up global instead of associated with a single instance of formbuilder.

**Comment by mikevoets** [comment]
Got the same problem here!

**Comment by Procaseycash** [comment]
@mikevoets , have u gotten any solution to that?

**Comment by mikevoets** [comment]
No. The problem seems to lie in the `control` and `controlCustom` class which don't seem to get initiated upon initiating a form builder. There does not seem to be an straight forward way to refresh the list of registered custom fields.

**Comment by Procaseycash** [comment]
Ok cool, hoping they resolve the issue anyway...

**Comment by GzimH** [comment]
Same issue here. Is there any solution to this yet?

**Comment by bhavna11patidar** [comment]
Same issue... I just want to edit the previously submitted form...

**Comment by jakovac** [comment]
Same issue here. When I return to form keep getting duplicates.

**Comment by jokamax** [comment]
Ahhhh Horrible... The same here.
Impossible to destroy the formbuilder without reloading the page...

**Comment by jokamax** [comment]
@kevinchappell is it possible to rise the priority of this bug ?
I know you are very busy but this is a critical bug : formBuilder can only be use in a static way with force page reloading... No ajax, no live reloading that drive to menu duplication.
Note : Formeo has the same Bug or nearly then I can't use in production formBuilder or formeo :'( : https://github.com/Draggable/formeo/issues/93

**Comment by kevinchappell** [comment]
@jokamax could you try the release/2.10.0 branch? I'm not able to test now but will later this evening. The 2.10.0 branch has numerous fixes and I'm 95% sure this issue is solved already. Documentation for the new features is about complete so I should have it released later this week. If you don't want to pull the branch, `yarn add formBuilder@next` should have the fix too.

**Comment by jokamax** [comment]
@kevinchappell Ahhhh, I've just decommissioned the code for a production release... I'll will retry with the branch (or the final 2.10) on the end of october ! Bug a very big thanks for the answer and the support

**Comment by jokamax** [comment]
Hi @kevinchappell , excuse me to disturb : is there a release dated for 2.10 ? 
Thanks a lot

**Comment by jokamax** [comment]
@kevinchappell I confirm : bug closed (I use the last version and no problem anymore)

**Comment by kevinchappell** [comment]
@jokamax thanks for the confirmation. :+1:
