### ISSUE TITLE
Other text Input hides on click it

### ISSUE THREAD

**Issue by tarasromil** [kevinchappell/formBuilder#545]
### Environment Details:

 - formBuilder Version: 2.1.2
 - Browser: Safari
 - OS: MacOS

### Expected Behavior
When click on other "text input" it hides
### Actual Behavior
Input shouldn't hides
### Steps to Reproduce
- Create Checkbox group with "other" input.
- Click on "text input"

Should add option to "form render" for disabling show/hide effect.
It should also move "other text input" outside the label block

**Comment by etyp** [comment]
@kevinchappell Hey Kevin, we're running into some issues on this one and are unsure how to proceed. Any ideas?

**Comment by kevinchappell** [comment]
This is a bug with the double click to edit feature.

We need to increase specificity on the selector [here](https://github.com/kevinchappell/formBuilder/blob/master/src/js/form-builder.js#L1217) so that it excludes `.form-elements`

**Comment by kevinchappell** [comment]
This should be resolved as of `v2.9.0`
