### ISSUE TITLE
Data load from XML on IE with checkbox, radio and select fields

### ISSUE THREAD

**Issue by felipestroff** [kevinchappell/formBuilder#546]
### Description:

Hello,
I recently encountered a bug when I load the saved data from XML to page. This happens only in the Internet Explorer / Edge browser on **checkbox**, **radio** and **select** types, these fields are not selected/checked.

### Environment Details:

 - formBuilder Version: 2.5.3
 - Browser: Internet Explorer 11 / Edge
 - OS: Windows 10

### Expected Behavior

Load data saved by XML into the **checkbox**, **radio** and **select** fields with selected/checked attributes in the Internet Explorer browser.

### Actual Behavior

Attributes of the **checkbox**, **radio**, and **select** fields are not selected/checked in the Internet Explorer browser.

### Steps to Reproduce

In the Internet Explorer or Edge browser, create a form with **checkbox**, **radio** or **select** field types, change values and save.

### Screenshot - *(optional)*

![formbuilderbug](https://user-images.githubusercontent.com/12732152/28081328-42ffbb7c-6645-11e7-9c6b-a35fef5c2ed9.jpg)
![formbuilderbugsaved](https://user-images.githubusercontent.com/12732152/28081367-67bdccd8-6645-11e7-8ae3-fa73bd233c55.jpg)

**Comment by kevinchappell** [comment]
xml handling much improved in 2.10.x, this is now resolved
