### ISSUE TITLE
Tabbed/Multi-Page Forms - Rendering

### ISSUE THREAD

**Issue by smartens80** [kevinchappell/formBuilder#548]
First of all, nice work!

I have implemented the Tabbed/Multi-Page Forms (http://formbuilder.readthedocs.io/en/latest/formBuilder/demos/tabs/) - issue is how to render multi pages using formRender (http://formbuilder.readthedocs.io/en/latest/formRender/options/formData/)? 

I'm having issues getting the below JSON to render - is this supported for multi page forms?

Example JSON Data:
[[{"type":"button","label":"Button","subtype":"button","className":"btn-default btn","name":"button-1499226556011","style":"default"}],[{"type":"button","label":"Button","subtype":"button","className":"btn-default btn","name":"button-1499226578866","style":"default"}]]

Error: 
Uncaught TypeError: t.values.map is not a function
    at t.santizeField (form-render.min.js:6)
    at t.render (form-render.min.js:6)
    at HTMLFormElement.<anonymous> (form-render.min.js:6)
    at Function.each (jquery.js:374)
    at n.fn.init.each (jquery.js:139)
    at n.fn.init.t.fn.formRender (form-render.min.js:6)
    at HTMLDocument.<anonymous> (formrender.php:31)
    at j (jquery.js:3099)
    at Object.fireWith [as resolveWith] (jquery.js:3211)
    at Function.ready (jquery.js:3417)

Any help would be greatly appreciated.

Cheers
Scott

**Comment by mdelahig** [comment]
Hello, did you solve this problem, I have the same issue when trying to render a form with checcbox group.

Thanks in advance

**Comment by omvirala** [comment]
Hi , how can you solve this?

**Comment by Amitguptas** [comment]
I am creating custom form multiple tabs through form builder. The form is being saved in json format, I want to show the form on one edit page and do some improvements but the form is not showing in multiple tabs. please give me a good suggestion that i can show the form and improve it

**Comment by Amitguptas** [comment]
[jQuery(($) => {
  "use strict";
  var $fbPages = $(document.getElementById("form-builder-pages"));
  var addPageTab = document.getElementById("add-page-tab");
  var fbInstances = [];

  $fbPages.tabs({
    beforeActivate: function (event, ui) {
      if (ui.newPanel.selector === "#new-page") {
        return false;
      }
    }
  });

  addPageTab.addEventListener(
    "click",
    (click) => {
      const tabCount = document.getElementById("tabs").children.length;
      const tabId = "page-" + tabCount.toString();
      const $newPageTemplate = document.getElementById("new-page");
      const $newTabTemplate = document.getElementById("add-page-tab");
      const $newPage = $newPageTemplate.cloneNode(true);
      $newPage.setAttribute("id", tabId);
      $newPage.classList.add("fb-editor");
      const $newTab = $newTabTemplate.cloneNode(true);
      $newTab.removeAttribute("id");
      const $tabLink = $newTab.querySelector("a");
      $tabLink.setAttribute("href", "#" + tabId);
      $tabLink.innerText = "Page " + tabCount;

      $newPageTemplate.parentElement.insertBefore($newPage, $newPageTemplate);
      $newTabTemplate.parentElement.insertBefore($newTab, $newTabTemplate);
      $fbPages.tabs("refresh");
      $fbPages.tabs("option", "active", tabCount - 1);
      fbInstances.push($($newPage).formBuilder());
    },
    false
  );

  fbInstances.push($(".fb-editor").formBuilder());

  $(document.getElementById("save-all")).click(function () {
    const allData = fbInstances.map((fb) => {
      console.log(fb.actions.getData());
      return fb.formData;
    });
    console.log(allData);
  });


   // form show 
   var formData = '<?php echo strip_tags($exam['json_question']) ?>';
                    setTimeout(function(){ 
                        formBuilder.actions.setData(formData); 
                    }, 500);
});](url)
