### ISSUE TITLE
paragraph data update issue

### ISSUE THREAD

**Issue by nenya1840** [kevinchappell/formBuilder#551]
### Description:

paragraph data updating has some problem.

### Environment Details:

 - formBuilder Version: 
 - Browser: 
 - OS: 

### Expected Behavior
data should get updated after editing in the paragraph
### Actual Behavior
data not get updated until add another field
### Steps to Reproduce
In the demo
drag a paragraph
edit paragraph
type some context in replace of default text 'Paragraph'
then check the data

**Comment by kevinchappell** [comment]
This is now fixed in 2.10.0
