### ISSUE TITLE
custom radio button in template with add new option 

### ISSUE THREAD

**Issue by MaryamHemati** [kevinchappell/formBuilder#552]
### Environment Details:

 - formBuilder Version: 2.5.3
 - Browser: 
 - OS: 

### Screenshot - *(optional)*
  typeUserAttrs: {
      time: {
            required: {
                type: 'checkbox',
                label: 'فیلد اجباری است؟',
            },
            Label: share.Label,
            Group: share.Group,
            Tip: share.Tip,
            DefaultValue: share.DefaultValue,
            Placeholder: share.Placeholder,
            Value: share.Value,
            State: {
                'type': 'checkbox-group',
                label: "فرمت نمایش",
                'className': 'form-control',
                 values: [
                        {
                            "label": "Option 1",
                            "value": "AM 01:30:24",
                            "selected": true,
                        },
                        {
                            "label": "Option 2",
                            "value": "'AM 01:30'",
                            "selected": false,
                        },
                        {
                            "label": "Option 3",
                            "value": "13:20",
                            "selected": false,
                        },
                        {
                            "label": "Option 4",
                            "value": "ب.ض 01:30:24",
                            "selected": false,
                        },
                        {
                            "label": "Option 5",
                            "value": "ب.ض 01:30",
                            "selected": false,
                        },
                        {
                            "label": "Option 6",
                            "value": "01:30:24",
                            "selected": false,
                        }
                    ]
            }

        },
    }

**Comment by kevinchappell** [comment]
Sorry but I'm unclear on what this issue is about. Is this a bug or feature request? Could you explain more?
