### ISSUE TITLE
how I can make it on diffrenet layout ?

### ISSUE THREAD

**Issue by emailfourm450** [kevinchappell/formBuilder#553]
I have layout contains more than div. I want drag and drop  the HTML  controls of formBulider in each div 

I have a layout with 2 divs (right div and left div ) I want to make formBulider work on them without repeating the Html controls for each div on the right of the page. and when I drag and drop the controls they drop on the specific div

 - formBuilder Version: 
 - Browser: all browsers
 - OS: win

![image](https://user-images.githubusercontent.com/7602376/28023445-3975d54e-658e-11e7-8a8a-b2fb544ca691.png)

**Comment by wallyWang5966** [comment]
Hello, I have encountered the same change formbuilder layout problem as you, I would like to consult you, how do you solve this problem? Thanks 642744345 @qq.com

**Comment by kevinchappell** [comment]
currently not possible but you could possibly have 2 instances of formBuilder and hide one control set
