### ISSUE TITLE
Error: formBuilder.actions.setData is not a function

### ISSUE THREAD

**Issue by gordon-matt** [kevinchappell/formBuilder#559]
I am getting this error:

**formBuilder.actions.setData is not a function**

I believe it's because I am trying to use setData immediately and not with a button click as your demo shows. For example, go here:

[https://codepen.io/kevinchappell/pen/ozagKr](https://codepen.io/kevinchappell/pen/ozagKr)

Change the last part of the JS so that the setData function gets called on load instead of on button click. You will get the same error as I mentioned above (see the console).

To be 100% clear on this, here's the full JS:

```
jQuery(function($) {
  var fbEditor = document.getElementById('build-wrap');
  var formBuilder = $(fbEditor).formBuilder();
  var formData = '[{"type":"text","label":"Full Name","subtype":"text","className":"form-control","name":"text-1476748004559"},{"type":"select","label":"Occupation","className":"form-control","name":"select-1476748006618","values":[{"label":"Street Sweeper","value":"option-1","selected":true},{"label":"Moth Man","value":"option-2"},{"label":"Chemist","value":"option-3"}]},{"type":"textarea","label":"Short Bio","rows":"5","className":"form-control","name":"textarea-1476748007461"}]';

  formBuilder.actions.setData(formData);
});
```

I am assuming this is because the form builder is not ready by the time setData is being called. Can this be easily fixed?

**Comment by gordon-matt** [comment]
Quick update - I just tried to use a timeout and that does the trick. Example:

`setTimeout(function(){ formBuilder.actions.setData(formData); }, 500);`

However, this feels a bit "hacky" and could possibly still fail sometimes. A proper fix would be great, but this is a workaround for anyone who may face the same issue.

**Comment by kevinchappell** [comment]
@gordon-matt Your assumption is correct, formBuilder is not ready at the time you call setData. You can use [fromBuilder.promise](http://formbuilder.readthedocs.io/en/latest/formBuilder/promise/) call `setData` when formBuilder is ready.

**Comment by mrsaifullah52** [comment]
@ousid I tried your method and it worked for me
