### ISSUE TITLE
defaultFields equivalent in formRender

### ISSUE THREAD

**Issue by ghostfreak3000** [kevinchappell/formBuilder#56]
Is there a defaultFields equivalent in formRender.. or something that can help me sink in the field data

**Comment by kevinchappell** [comment]
formRender is still pretty new and unfortunately only takes the textarea value. This will be changing in the next week though.

**Comment by ghostfreak3000** [comment]
From what i can see.. fastest option is to make a hidden div.. put the text area there, sink in my data using formbuilder, then point the form render to that textarea.. and the container where i want it to be
