### ISSUE TITLE
Building a custom control with JQuery Formbuilder

### ISSUE THREAD

**Issue by utpalmaity** [kevinchappell/formBuilder#561]
I want to add a custom control of button type with all the default properties of button and an additional dropdown property named **Function** and the value of which I want to populate using an ajax call.I can add a control of custom type using this code but how a add a property of dropdown type in that control

**Comment by kevinchappell** [comment]
Please see `typeUserAttrs` option. It can be used in conjunction with `fields` or custom controls api

**Comment by 6developer3i** [comment]
how can I build a custom menu for like Polaris button, TextField?

I want to add my Custom field to the design form in Polaris.

![tool](https://user-images.githubusercontent.com/69382500/100217444-76573480-2f39-11eb-986d-dec71fa0b0cb.jpg)

**Comment by 6developer3i** [comment]
> how can I build a custom menu for like Polaris button, TextField?
> 
> I want to add my Custom field to the design form in Polaris.
> 
> ![tool](https://user-images.githubusercontent.com/69382500/100217444-76573480-2f39-11eb-986d-dec71fa0b0cb.jpg)

Please Reply if anyone can know about this.
