### ISSUE TITLE
Reduce name long

### ISSUE THREAD

**Issue by eder-toledo** [kevinchappell/formBuilder#562]
### Description:
It´s possible reduce the element name long?

### Environment Details:

 - formBuilder Version: V 2

### Screenshot - *(optional)*
![image](https://user-images.githubusercontent.com/2104229/28339557-0f54bdb2-6bd2-11e7-8c0e-8eaee6c98a5a.png)

**Comment by brentkelly** [comment]
why?

**Comment by kevinchappell** [comment]
Currently no but happy to consider a PR that implements such a feature.
