### ISSUE TITLE
Bootstrap class conflicts

### ISSUE THREAD

**Issue by eradin** [kevinchappell/formBuilder#564]
V2.5.3

I have a button bootstrap button bar at the top of my page (3 buttons evenly spaced).  When I include formBuilder, the buttons are all crunched up in the corner.  Button bar html is:

		<div class="btn-group btn-group-justified" role="group">
			<a class="btn btn-default active" href="evalSetup.php">Setup</a>
			<a class="btn btn-default" href="report1.php">Report 1</a>
			<a class="btn btn-default" href="report2.php">Report 2</a>
		</div>

Seems the formbuilder css conflicts with bootstrap.

**Comment by kainpl** [comment]
I noticed the same behavior yesterday. 
Problem in formBuilder-injected-style. Class names in injected-style same as in Bootstrap.
Problem with btn-group i almost fix by changing sting '.btn-group>.btn{position:relative;float:left}' to '.btn-group>.btn{position:relative;}' in form-builder.min.js
But this is not a normal solution. I believe that styles and fonts need to be removed from the js file and placed in the css or even removed, since this is a Bootstrap.

**Comment by eradin** [comment]
I see the problem and I also found a workaround.  It's still a bug and should be fixed.

The problem is formbuilder overrides this style  .btn-group > .btn with a float:left.  Class btn-group-justified originally sets float:none so the buttons get jammed to the left.  

The work around is to restore bootstrap by adding a style="float:none;" to each of the 'a' tags.  It's kludgy and not very maintainable but it works for now.

I agree that encapsulating the css into the js is not a good idea.  In version 1 I could always override the class again in my styles.css.  I guess I can still do that but I would have to load my styles after the js files but that is very unorthodox and causes other potential issues.

**Comment by mikevoets** [comment]
Encapsulating the css into the js is really bad practice.

**Comment by craigpotter** [comment]
@eradin Couldn't you just have a custom build of the formbuilder and edit the styles?

**Comment by eradin** [comment]
@craigpotter Sure but kind of defeats the purpose of having formbulder in the first place as a drop in plugin.  A custom build also breaks the upgrade process as we would have to make a custom build each time and test again.  That's not optimal.

A separate css file was the standard in version 1 and worked great.  I don't understand why the developers went against best practices in V2 but it should be a separate file and any custom styles should have a separate name space and not conflict with other frameworks it may be used in.

**Comment by kevinchappell** [comment]
This should be fixed now in `v2.9.1`
