### ISSUE TITLE
Change Control Name

### ISSUE THREAD

**Issue by craigpotter** [kevinchappell/formBuilder#566]
Is it possible to change a control label without building a custom control. 

I have a request to rename 

> Checkbox Group

 to 

> Tickbox Group

**Comment by kevinchappell** [comment]
Easiest way would be to replace the field like so: https://codepen.io/kevinchappell/pen/RZWyKz

**Comment by siripragada** [comment]
what is the type of icon used to place in icon section in jquery.  i want to place barcode icon
