### ISSUE TITLE
Converting special characters when generating json formdata

### ISSUE THREAD

**Issue by Slim-dev** [kevinchappell/formBuilder#568]
### Description:
when i drag a control and add "&" in the label field, when i save i get "&amp;" in the json generated

### Environment Details:

 - formBuilder Version: 1.24.2
 - Browser: chrome
 - OS: windows 10

### Expected Behavior
when i add a special character in a control label field e.g "&" i should get "&" in the json generated

### Actual Behavior
when i add a special character in a control label field, i get "&amp;" in the json generated

### Steps to Reproduce
drag a textfield control, change the label to "T&c". save add see the json formData generated

### Screenshot - *(optional)*
<img width="736" alt="formbuilder issue" src="https://user-images.githubusercontent.com/29542493/28718219-e976b0a0-739c-11e7-9f39-867f1fede2fd.PNG">

**Comment by Slim-dev** [comment]
solved my issue

**Comment by sxndy1** [comment]
> solved my issue

and how? .. -.-
