### ISSUE TITLE
Tag <br> in every label with added space

### ISSUE THREAD

**Issue by kubco2** [kevinchappell/formBuilder#569]
### Description:
Tag br is inserted at the end of label if label is edited with space.

### Environment Details:

 - formBuilder Version: 2.5.3
 - Browser: Firefox
 - OS: Linux

### Expected Behavior
No br tag

### Actual Behavior
br tag is added

### Steps to Reproduce
On live demo:
1. add text field
2. show data(all is OK here)
3. edit text field label append " something", space is crucial here
4. save form, edit form, show data
5. br is there

**Comment by kevinchappell** [comment]
2 options, you can use [disableHTMLLabels](http://formbuilder.online/docs/formBuilder/options/disableHTMLLabels/) or `typeUserEvents` to remove trailing spaces.
