### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by lukepolo** [kevinchappell/formBuilder#57]
Even though you have the bower file did you actually register it yet?

**Comment by kevinchappell** [comment]
I thought I had... but not seeing it in registry.

**Comment by kevinchappell** [comment]
`bower info formBuilder` note the cameCase name

**Comment by kevinchappell** [comment]
![image](https://cloud.githubusercontent.com/assets/1457540/12893804/39cee616-ce8b-11e5-88b0-31dcf36b0a7f.png)
