### ISSUE TITLE
"Y.sortable is not a function" formBuilder 2.5.3 via NPM, running on Laravel 5.4

### ISSUE THREAD

**Issue by barnonahill** [kevinchappell/formBuilder#570]
I'm trying to run formBuilder in a Laravel 5.4 project that uses Bootstrap 3.3.7 and jQuery 3.2.1 on the front-end. I installed the formBuilder package via NPM and built it into a JS file using webpack in Laravel.

When I try to run formBuilder on a div I get the following error in Chrome:

TypeError: Y.sortable is not a function
    at new A (formBuilder.js:86)
    at HTMLDivElement.<anonymous> (formBuilder.js:86)
    at Function.each (jquery.min.js:2)
    at n.fn.init.each (jquery.min.js:2)
    at formBuilder.js:86
    at <anonymous>

Do I need to add jQuery UI as its own dependency to solve this? I'm going to attempt this, but I figured I would make an issue report in case
a) it doesn't work
b) others run across this in the future

Thanks.

**Comment by barnonahill** [comment]
I was having an issue with how I imported jquery into webpack. Apparently the jquery-ui npm package doesn't come pre-built, so jquery-ui-dist has to be used and aliased as jquery-ui.

**Comment by kevinchappell** [comment]
Thanks for looking into that. I know jQuery and jQuery UI do not have good npm support but was not aware of that issue.
