### ISSUE TITLE
typeUserAttrs, doesn't render checkbox checked property correctly

### ISSUE THREAD

**Issue by joerou** [kevinchappell/formBuilder#571]
### Description:
Perhaps I am missing something but if I create a new custom attribute using typeUserAttr of type checkbox, when I render the form with existing data the checkbox is not checked if the value is true. This seems to work correctly for the required field.

### Environment Details:

 - formBuilder Version: 
 - Browser: Chrome
 - OS: 

### Expected Behavior
Inserting formData for custom attributed will correctly check checkboxes.

### Actual Behavior
The value attribute of the custom field is set to true but the box is not checked

### Steps to Reproduce
```
jQuery(function($) {
  var fbTemplate = document.getElementById('build-wrap');
var options = {
      disabledActionButtons: [
        'data',
        'clear'
      ],
      disableFields: [
        'button',
        'autocomplete',
        'hidden',
        'file',
        'date',
        'header',
        'number'
      ],
      disabledAttrs: [
        'access',
        'multiple',
        'toggle',
        'placeholder',
        'className',
        'inline',
        'other',
        'subtype',
        'description',
        'maxlength',
        'rows'
      ],
      typeUserAttrs: {
        'radio-group': {
          randomize: {
            label: 'Randomize',
            type: 'checkbox'
          },
          feedback: {
            label: 'Feedback',
            type: 'text',
            placeholder: 'Insert feedback for this question here'
          }
        },
        'textarea': {},
        'checkbox-group': {
          randomize: {
            label: 'Randomize',
            type:"checkbox"
          },
          feedback: {
            label: 'Feedback',
            type: 'text',
            placeholder: 'Insert feedback for this question here'
          }
        },
        'select': {
          randomize: {
            label: 'Randomize',
            type: 'checkbox'
          },
          feedback: {
            label: 'Feedback',
            type: 'text',
            placeholder: 'Insert feedback for this question here'
          }
        },
        'text': {
          content: {
            label: 'Content',
            type: 'textArea',
            placeholder: 'Insert feedback for this question here'
          },
          feedback: {
            label: 'Feedback',
            type: 'text',
            placeholder: 'Insert feedback for this question here'
          }
        },
        'paragraph': {
          name: {
            label: 'Name',
            type: 'text'
          }
        }
      },
      formData: '[{"type":"checkbox-group","label":"Checkbox Group","name":"checkbox-group-1501853553952","feedback":"","randomize":true,"values":[{"label":"Option 1","value":"option-1","selected":true}]}]',
      dataType: 'json',
      layoutTemplates: {
        label: function (label, data) {
          return $('<label class="bright"/>')
            .attr('for', data.id)
            .append(label);
        }
      }
    };

  $(fbTemplate).formBuilder(options);
});
```

The value of the field randomize is set to true, but the box is not checked on load

### Screenshot - *(optional)*
<img width="853" alt="screen shot 2017-08-04 at 5 23 10 pm" src="https://user-images.githubusercontent.com/16531276/28975245-a65a4794-7939-11e7-9f71-af092c9b8985.png">

**Comment by jjleavitt** [comment]
I didn't even know you could add a checkbox with typeUserAttr, so thank you, will help me on my project.

if you add a 'checked' prop with any value it looks like it will default as checked ie:

```
'select': {
          randomize: {
            label: 'Randomize',
            type: 'checkbox',
            checked: ''  /*<-----  here*/
          },
          feedback: {
            label: 'Feedback',
            type: 'text',
            placeholder: 'Insert feedback for this question here'
          }
        }
```

**Comment by joerou** [comment]
Yep that works! Thanks!

**Comment by jjleavitt** [comment]
yeah...  for now the workaround will be if you want it to be defaulted true, add the checked prop.  If you want to be defaulted false, leave checked prop out.

In the form data, when the box is checked the randomize property will be there.  If you don't have it checked, it will be removed.

Looks like missing logic in the inputUserAttrs function, to check the value prop for true or false on non type='text' inputs to set checked.

Also in the utils.trimObj function it looks like **if a value is bool or string false, it gets removed** which is why the prop disappears.  I can understand on null or undefined, but anyone know if that's intentional?

```
  /**
   * Remove null or undefined values
   * @param  {Object} attrs {attrName: attrValue}
   * @return {Object}       Object trimmed of null or undefined values
   */
  utils.trimObj = function(attrs) {
    let xmlRemove = [
      null,
      undefined,
      '',
      false,    //JL: intentional?
      'false'   //JL: intentional?
    ];
    for (let attr in attrs) {
      if (utils.inArray(attrs[attr], xmlRemove)) {
        delete attrs[attr];
      } else if (Array.isArray(attrs[attr])) {
        if (!attrs[attr].length) {
          delete attrs[attr];
        }
      }
    }

    return attrs;
  };
```

**Comment by joerou** [comment]
The current use case for the project at hand is that it should default to false and when building the form builder with data from the database, (basically edit mode for a previously created form) then it should render already checked if that was what it was in the database. So I am not sure that solution will work for my use case, for now I added a function that will add the checked property to the element based on the "value" being true or false and then added this function to the onAdd hook for the limited elements that I am using that require a randomize answer property.

In the coming month, perhaps I will have a bit more time to also look into this further, but for now this will be my solution.

Thanks for all the additional information btw and the prompt responses!

**Comment by AvKhushbu** [comment]
@joerou can you please share your logic to set checkbox property using a function? I am facing the same issue

**Comment by joerou** [comment]
@AvKhushbu of course!

First I added the attributes to the type as below:
```javascript
typeUserAttrs: {
  'radio-group': {
    randomize_values: {
      label: 'Randomize',
      type: 'checkbox'
    },
    always_correct: {
      label: 'Always correct',
      type: 'checkbox'
    },
  }
}
```

Then I created a function to check what the property was equal to and add the checked property accordingly
```javascript
function fixCheckedProps(fld) {
    var randomizeField = $(fld).find('input.fld-randomize_values');

    // Also if the value is not set, because I wanted checked by default as well
    if ($(randomizeField).val() === 'on' || $(randomizeField).val() === ''){
      $(randomizeField).attr('checked', true);
    } else {
      $(randomizeField).attr('checked', false);
    }

    var alwaysCorrectField = $(fld).find('input.fld-always_correct');

    if ($(alwaysCorrectField).val() === 'on'){
      $(alwaysCorrectField).attr('checked', true);
    } else {
      $(alwaysCorrectField).attr('checked', false);
    }
  }
```

Then I added the function to the onAdd event
```javascript
typeUserEvents: {
  'radio-group': {
    onadd: function (fld) {
      fixCheckedProps(fld);
    }
  },
}
```

**Comment by AvKhushbu** [comment]
@joerou thanks a lot, buddy! your example is very clear and it works perfectly fine in my code. Once again thank you so much!

**Comment by alexsergeibichy** [comment]
Dear @joerou, I am gonna add color picker in typeuserattr by using the text, but I can't get info about this, so if you have a solution, I hope your help.

**Comment by joerou** [comment]
@alexsergeibichy  I'm not exactly sure what you mean, and I haven't used this package in a while. I'm happy to try to help, but maybe you can give an example of the code you already wrote with an explanation of what you are trying to do and what is not working?

**Comment by kevinchappell** [comment]
@alexsergeibichy you can use the same pattern but need to add a `value` to the color picker config.
example: https://codepen.io/kevinchappell/pen/yaJbZZ

**Comment by kevinchappell** [comment]
Also, I just reviewed the original issue. There was a bug in how the checked value for was interpretted. The order of precedence for how custom checkbox attributes value is resolved is now:
```
formData[fieldData][attributeName] > typeUserAttr[attributeName].value || typeUserAttr[attributeName].checked > false
```

**Comment by sarika624** [comment]
I want to add a custom dropdown attribute and bind dropdown options with the help of database
please help me to find out solution

**Comment by sid046** [comment]
how to customize the sequence of attributes

**Comment by vividansari** [comment]
@kevinchappell I have to add a new radio button with images and need to add an option to add more options is it possible?
