### ISSUE TITLE
Attributes values of custom templates 

### ISSUE THREAD

**Issue by dema121** [kevinchappell/formBuilder#574]
### Description:
With version 2.1.2 I declared a custom field/template like this:
```
fields: {
    label: 'My custom label',
    attrs: {
        type: 'mytype',
        required: true
    },
    icon: 'P'
},
templates: {
   mytype: function (fieldData) {
        return {
            field: '<span ...>...',
            onRender: function () {
                ...
            }
        };
    },
}
```
With this method I was able to set field attributes like required, description, className, etc.

Now I update to version 2.5.3 and so edited a bit my configurations:
```
fields: {
    label: 'My custom label',
    type: 'mytype',
    required: true,
    icon: 'P'
},
templates: {
   mytype: function (fieldData) {
        return {
            field: '<span ...>...',
            onRender: function () {
                ...
            }
        };
    },
}
```
But now I'm not able to set attributes (like required, description, etc.) of custom templates.
What am I missing?
### Environment Details:

 - formBuilder Version: 2.53
 - Browser: Chrome
 - OS: Ubuntu 17.04

### Expected Behavior
Setting attributes values of custom templates. 

### Actual Behavior
Attributes values of custom templates aren't set.

**Comment by kevinchappell** [comment]
Could you create a jsfiddle demonstrating the issue? `fields` should be an array but you have it as an object in both examples.

**Comment by dema121** [comment]
Sorry, my fault in writing the example. `fields` is an array with that object.
https://codepen.io/anon/pen/KvaraW
Here you can see the issue. I forked your starRating example in the templates documentation and adapted to include required and description attributes.
The email 'alias' (using existing types and subtypes) works great, and also required and description attributes are inserted correctly.
However `starRating` field hasn't all the desidered attributes.

**Comment by kevinchappell** [comment]
Custom fields work a bit different now and something like starRating might not be able to hold `required` attribute unless the plugin has its own setting for it. Will need further investigation

**Comment by dema121** [comment]
So at the moment, is there a method to do this or a possible workaround?

**Comment by kevinchappell** [comment]
With custom control class you can add your own validation including required. In this PR you can see an input was added, using that you could add or remove `required` on the input and html5 constraint api will be able to use it.
