### ISSUE TITLE
Empty Data after changing language

### ISSUE THREAD

**Issue by pufich** [kevinchappell/formBuilder#575]
There is an empty Data bug after language change:
- open demo page "formBuilder/demo/index.html";
- change language to "Deutsch";
- add some fields to the area;
- click the "Get XML Data" button (or "Get JSON Data", or "Show Data").

![formbuilder_bug](https://user-images.githubusercontent.com/20898590/29206856-711dabfe-7e8c-11e7-94ee-9ac229cf5ab3.png)
The same happends if I set custom translation.

The other strange behaviour:
- open demo page "formBuilder/demo/index.html";
- add some fields to the area;
- change language to "Deutsch" (then elements area crears);
- click the "Get XML Data" button (or "Get JSON Data", or "Show Data").
In this case I get Data, but the area is empty.

![formbuilder_bug1](https://user-images.githubusercontent.com/20898590/29207345-850fdc16-7e8e-11e7-8a5d-23bfce5e36ee.png)

**Comment by kevinchappell** [comment]
I'm having trouble reproducing the issue: https://youtu.be/dosLyCBHsBg

Can you provide more info?
