### ISSUE TITLE
Delete input groups at one time

### ISSUE THREAD

**Issue by roshanjha12** [kevinchappell/formBuilder#576]
### Description:
Hi,
I want to delete inputsets at one not each input one by one. any method ?
### Environment Details:

 - formBuilder Version: 
 - Browser: 
 - OS:

**Comment by kevinchappell** [comment]
This would be a good feature but would require significant refactoring. Adding to backlog

**Comment by lucasnetau** [comment]
Adding as duplicate of #627, deletion of input sets would require some form of grouping
