### ISSUE TITLE
setData for Checkbox Group

### ISSUE THREAD

**Issue by eder-toledo** [kevinchappell/formBuilder#578]
### Description:
What is the correct json for setData and include text in the other option for a Checkbox Group
### Environment Details:

 - formBuilder Version: V 2.5
 - Browser: Chrome and Firefox
 - OS: Windows

### Screenshot - *(optional)*
![image](https://user-images.githubusercontent.com/2104229/29336297-f439e22a-81d2-11e7-83c3-d5c68d716ed3.png)

**Comment by kevinchappell** [comment]
The `other` option is meant for user input only. There currently is not a default value for this option.

**Comment by eder-toledo** [comment]
any idea to rebuild the form so that the user can edit that value?

**Comment by adteague** [comment]
@kevinchappell What is the JSON data structure for having 'Other' checked and text within the input?

**Comment by flaiming** [comment]
@kevinchappell I have same issue here as @adteague - how should be JSON structured to fill "Other" input value?
