### ISSUE TITLE
Angular 4 version

### ISSUE THREAD

**Issue by KhaledSMQ** [kevinchappell/formBuilder#582]
Hi, Thank you for your efforts working on Form Builder, I have uploaded TypeScript version  working perfectly with angular 4, please feel free to take a look 

https://github.com/KhaledSMQ/Ng2FormBuilder

**Comment by kevinchappell** [comment]
Incredible work you've done there. I'm really looking forward to getting into it further.

**Comment by kevinchappell** [comment]
Link to your project added to formBuilder README.

**Comment by KhaledSMQ** [comment]
Thank you @kevinchappell,
That will be great if you don't mind to come up with new version written in typescript from scratch that will fit all javascript frameworks. i am ready to involve and i can set one or two hours daily.

**Comment by kevinchappell** [comment]
@KhaledSMQ I started something similar with Formeo but its pure JS instead of typescript. Currently formBuilder relies on jQuery UI Sortable, if we remove that dependency it should be much easier to make formBuilder available to all apps and frameworks.

**Comment by pankaj-git** [comment]
@khaledSMQ can we maintain the sessionState in formbuilder Angular 4 app demo you shared. Like after putting some element refresh the page and it maintain the state of form field added.

**Comment by KhaledSMQ** [comment]
Hi @pankaj-git 
Sorry for late reply.
In my project I manage that by using angular dynamic forms, to build for me the form and design elements of the form i used  formBuilder the one i shared.

https://angular.io/guide/dynamic-form
https://github.com/KhaledSMQ/Ng2FormBuilder

**Comment by nishant-varshney** [comment]
Is angular 6/7 version available??

**Comment by harshalyelpale** [comment]
@KhaledSMQ This is very useful. Can we have an Angular 8 version? It would be great if we have step by step formBuilder integration doc.

**Comment by KhaledSMQ** [comment]
@harshalyelpale you can check out this #925 
you don't need angular version 4 anymore
here is example how to build with angular 6+ https://stackblitz.com/edit/angular-ngformbuilder
