### ISSUE TITLE
paragraph TinyMCE

### ISSUE THREAD

**Issue by renmlp** [kevinchappell/formBuilder#583]
Hello is it possible in the paragraph to get an TinyMCE?

**Comment by kevinchappell** [comment]
I think it would be better to use the `textarea` field with tinyMCE subtype. You can replace it like this: https://codepen.io/kevinchappell/pen/qXMoqR

Try the bottom control labeled "Paragraph"

**Comment by renmlp** [comment]
i want in the edit mode an tinyMCE to edit the Paragraph text

that i could use the HTML Features.

**Comment by kevinchappell** [comment]
I think I see what you mean now. It's not built-in can do this using the [`typeUserEvents`](http://formbuilder.readthedocs.io/en/latest/formBuilder/options/typeUserEvents/) option. [Here](https://codepen.io/kevinchappell/pen/rzqYRe) is an example to get you started, however you will still need to save the data form tinyMCE back to formBuilder

**Comment by renmlp** [comment]
Hello kevin,
there is another Problem too... if i put an text into the tinyMCE will the text in content div not update.

**Comment by kevinchappell** [comment]
> however you will still need to save the data form tinyMCE back to formBuilder
Meaning this is not built-in you will need to use the formBuilder and tinyMCE API to complete the feature.

**Comment by renmlp** [comment]
Oh okay is there an documentation?

**Comment by kevinchappell** [comment]
This is not a supported feature so there is no documentation

**Comment by renmlp** [comment]
Thank you very well :)
