### ISSUE TITLE
formRender getData function

### ISSUE THREAD

**Issue by haisol** [kevinchappell/formBuilder#586]

**Comment by kevinchappell** [comment]
This has been the most requested feature in the last month. The biggest hurdle is that `formData` doesn't *directly* map between formRender and formBuilder because of things like the `other` option for checkbox and radio groups but this should resolvable. 

Will look into it this weekend.

**Comment by haisol** [comment]
Cool, thanks.
An idea on this..
When setting data it would be nice to include a callback function that could be used to set data on custom form controls where handling is unknown.  Example formRenderSetData(thisData, unknownControlCallback).  I'm not sure of all the callback attributes but perhaps field type, name, values... Example in use $(.form-render).formRenderSetData(thisData, function(fieldType, fieldName, fieldValues){
.....};  that way end users can handle setting content for custom controls.  Perhaps just sending back all the field data for that object would work too.

There could also be a custom function as well for getting data on custom controls.  Example:  formRenderGetData(callback).  Not sure what would be here except maybe the dom object so the user can parse it for the values needed.

Thanks again.

**Comment by amiqat** [comment]
Hello, 
when this resolve?

**Comment by haisol** [comment]
Any update on the getdata and setdata functions for form render?

Thanks

**Comment by grierson** [comment]
Reference: #320
Duplicate question: #609

This is how I'm currently doing it.

```javascript
function form_to_object(form) {
    return [...form].reduce((current, [key, value]) => {
        if (current.hasOwnProperty(key)) {
            return Object.assign(current, { [key]: [...[current[key]], value].join() });
        } else {
            return Object.assign(current, { [key]: value });
        }
    }, {});
}

const form = form_to_object(new FormData(document.getElementById('fb-render')));
console.log(JSON.stringify(form));
```

**Comment by Jojoshua** [comment]
This is the only hole in this solution. Would really like to see it completed.

**Comment by Jojoshua** [comment]
Review https://github.com/kevinchappell/formBuilder/pull/749

**Comment by kevinchappell** [comment]
https://formbuilder.readthedocs.io/en/latest/formRender/actions/userData/
