### ISSUE TITLE
How to persist and update form fields in database?

### ISSUE THREAD

**Issue by shibli786** [kevinchappell/formBuilder#587]
### Description:
This might be very basic question but i am facing problem for the bellow points because it is nowhere mention in the Documentation.
 We can generate the form and will save its json in form table (mysql).
query 1)
Do we have to save whole json of form for each and every user independently.?
Query 2)
Suppose if we have 1 thousand user record of the form in database and then admin changes some field how will we manage this? how we will update all the form as we have 1000 instance of form in db saperately?
query 3) what will be the basic database structure to save the users  profile saved whose form is built with formbuilder ?
 

### Environment Details:

 - formBuilder Version:  latest
 - Browser: any
 - OS: any

**Comment by wnoveno** [comment]
I had the same issue as well. What I did was save the user's "answers" separately from the form.

**Comment by kevinchappell** [comment]
database interactions are far outside the scope of formBuilder but it provides data in a variety of different formats you should be able to save to the backend of your choice.

**Comment by shibli786** [comment]
Ye you are right that we can save the date in different formats but i am asking 
for 10000 form entry we will have 10000 independent form in database and admin changes some field in form then how we can reflect these changes on all the separate form instances in db.?
