### ISSUE TITLE
Gridsystem

### ISSUE THREAD

**Issue by renmlp** [kevinchappell/formBuilder#588]
### Description:
Hello is it possible to get multiple Columns in the formbuilder eventually with gridstack.js?
 `https://troolee.github.io/gridstack.js/`

**Comment by crattat** [comment]
I would love to have this. Even better would be individual decision if an item stays is the same or next row and if it was full width or limited.

Any idea what would be a proper approach for this? I'm looking into the code currently. It would be cool if the form-group would be a container also in the form builder and have an editor. With that, attributes for form-group could be set to align in the same or new row easily. This would not spoil the current strategy imho and also it would become possible to remove form-groups completely as they were inserted.

**Comment by kevinchappell** [comment]
Sorry but there are no plans to add grid system support to formBuilder. I would be happy to review a PR that adds one but cannot allocate resources to this feature.
