### ISSUE TITLE
I got an error in IE - 'Promise' is undefined

### ISSUE THREAD

**Issue by Amy518** [kevinchappell/formBuilder#592]
### Description:
Got an error in IE to build Form Builder using Visual Studio 2015
### Environment Details:

 - formBuilder Version: 2.5.3
 - Browser: IE
 - OS: Windows 7 Enterprise

### Actual Behavior
![ieerror](https://user-images.githubusercontent.com/29471405/29826366-0d94430a-8ca5-11e7-8f99-8c76226be7a6.JPG)

### Screenshot - *(optional)*
![image](https://user-images.githubusercontent.com/29471405/29826229-c0265b76-8ca4-11e7-8190-2bc5c48dd659.png)

**Comment by Amy518** [comment]
I went to the document site and it looks like there are no controls displayed in CodePen in Internet Explorer.
![image](https://user-images.githubusercontent.com/29471405/29838677-de27b780-8cc9-11e7-87eb-7215a1538cbb.png)

**Comment by Amy518** [comment]
I figured out the issue. The solution is including the js

<script>
        if (typeof Object.assign != 'function') {
            Object.assign = function (target) {
                'use strict';
                if (target == null) {
                    throw new TypeError('Cannot convert undefined or null to object');
                }

                target = Object(target);
                for (var index = 1; index < arguments.length; index++) {
                    var source = arguments[index];
                    if (source != null) {
                        for (var key in source) {
                            if (Object.prototype.hasOwnProperty.call(source, key)) {
                                target[key] = source[key];
                            }
                        }
                    }
                }
                return target;
            };
        }
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.4/bluebird.min.js"></script>

**Comment by kevinchappell** [comment]
@Amy518 I'm glad you found the solution. What version IE did you encounter this issue? I have expanded the polyfills to include IE10 now, so Promise should now be available, would you be able to test this for me?

**Comment by Amy518** [comment]
I am using IE version 11.0.9600
It's still not showing up the form controls on the CodePen section on the page with the link http://formbuilder.readthedocs.io/en/latest/formBuilder/actions/getData/getData - formBuilder
  
|  
|   |  
getData - formBuilder
   |  |

  |

 

Thanks for looking into it.

**Comment by Amy518** [comment]
Another one I found an issue in IE 11... The append method is not supporting in DOM in IE 11. So, I have to replace DOM object to JQuery object in the library. 
Using $(t).append instead of t.append...This issue is only happening in IE 11. You can update this in the next version.

**Comment by Amy518** [comment]
Never mind the issue of append method.. I tested online in the version of v2.9.0 and it works perfect.
