### ISSUE TITLE
formBuilder seems to be too liberal in re-styling basic types

### ISSUE THREAD

**Issue by jhwinters** [kevinchappell/formBuilder#594]
### Description:
Simply including the formbuilder.min.js file in your web page, without even invoking it, is enough to get extra stylesheets injected into your page, re-defining your layout.

The particular problem which I hit is that it re-styles "select" elements to have a margin-bottom of 0px, over-riding a setting which I made earlier in my style definitions.

Surely the selector which it uses should be more selective - it should affect only such elements within formBuilder forms - not everywhere in the application?

### Environment Details:

 - formBuilder Version: 2.5.3-4
 - Browser: Chrome
 - OS: Linux

### Expected Behavior
formBuilder's styles should be sufficiently specific that they affect only its own elements.

### Actual Behavior
Currently, they affect the whole application.

### Steps to Reproduce
As above.

### Screenshot - *(optional)*

![screenshot from 2017-08-30 10-00-54](https://user-images.githubusercontent.com/345516/29864337-40f9c2ae-8d6a-11e7-8cfc-34ca8b2cdcf2.png)

Note how the drop-downs have been squished together.  The Chrome debugger indicates that the change has been imposed by formBuilder's injected CSS, even though this isn't a formBuilder form.  The effect is achieved simply by including formBuilder's js file, without invoking it in any way.

**Comment by wnoveno** [comment]
I've had the same problem as well. 
A suggestion to the maintainers is to create a separate CSS file, it would also have the added benefit of custom styling.

**Comment by jhwinters** [comment]
I agree with the idea of having a separate, explicitly included, CSS file.  It may seem superficially attractive to have the JS code inject its own embedded stylesheet, thus meaning that the package can be distributed as a single file, but it's not standard behaviour and it will inevitably lead to problems like this.

Possible fixes:

1. Make the CSS styles more specific, so they affect only elements within a formBuilder parent element (this should be done regardless).

2. Don't inject the stylesheet unless and until formBuilder code is invoked.  It thus won't do any damage on other pages of an application.  Not really a proper fix, but possibly easier to do quickly.

3. Remove the stylesheet from the JS file entirely, and put it where it should be - in a CSS file.  This then means that end users can tweak it if necessary.

**Comment by sophanox** [comment]
#602 is still causing me issues. In my case it's overriding the bootstrap classes:

![image](https://user-images.githubusercontent.com/19409202/40984025-d48cf1ea-68d8-11e8-8afd-b7a949ed81b6.png)

As you can see, the inline style makes the form group a block, which breaks the form-group row flex wrapping.

**Comment by kevinchappell** [comment]
@sophanox Thanks for the extra info. formBuilder shouldn't be overwriting basic types so I'll see what is happening. Do you have a jsfiddle or codepen that can replicate this problem? 

Do you have insight on what needs to be changed in formBuilder? From looking [here](https://github.com/kevinchappell/formBuilder/blob/master/src/sass/form-builder.scss) it seems like formBuilder should affect any bootstrap definitions outside of `.form-wrap.form-builder`

**Comment by sophanox** [comment]
hey @kevinchappell thanks for getting back to me.

Isn't the problem that the the .form-wrap.form-builder is closed off prior to the form-group declaration below? 

 `.form-wrap.form-builder {
  @import 'base/bs';
  @import 'base/animation';
  @import 'controls';
  @import 'stage';
  @import 'kc-toggle';
  position: relative;

  &::after {
    content: '';
    display: table;
    clear: both;
  }
}`

Cheers

**Comment by AdamJAKing** [comment]
This is a long shot but is there any update regarding this? Would love to see a separate CSS file to resolve this issue

**Comment by Furburger** [comment]
It would be nice to have these issues fixed because it is a very nice plug in.

I notice that **var options = {  disableInjectedStyle: true};** doesn't seem to work.

The main issue I had with the injected CSS is that it was changing the **.row** class to _display:block_ which is a problem if you are using Bootstrap 4 because it uses flexbox for its rows and columns

I put this in my CSS:

```
.row {
    display: flex !important;
}
```

and it resolved a lot of the layout issues in the other parts of the program.

**Comment by Furburger** [comment]
I wrote:

> I notice that var options = { disableInjectedStyle: true}; doesn't seem to work.

It does "work" but not how I expected. It simply removed the CSS from the FormBuilder component - it does not remove the injected CSS from the body which is a pity.

**Comment by Furburger** [comment]
Latest update:

This solution proved a bit too permanent - e.g. it didn't allow display:none to be added to a row (to hide a row, for example) because **display: flex !important;** was forcing it to be displayed

```
.row {
    display: flex !important;
}
```

So what I did was include the (more gentle) override in the body of the document _after form-builder.min.js_. Like this...

```
    <script src="https://cloudfront.net/js/form-builder.min.js" defer></script>

    <!-- Adjustments for Form Builder -->
    <style type="text/css">
        .row { display: flex; }
    </style>

```

Hope this helps...it seems to be working much better now.

**Comment by Jojoshua** [comment]
Try this
 https://formbuilder.online/docs/formBuilder/options/disableInjectedStyle/

**Comment by lucasnetau** [comment]
Reopening, as I see no fix, disabling injected styles is not a fix
