### ISSUE TITLE
How can i re-init form builder through Ajax?

### ISSUE THREAD

**Issue by ajaykr089** [kevinchappell/formBuilder#60]
Hey Guys,

I am trying to update default fields through ajax. but not able to do that. When i tried to do that with new set of default fields, it did nothing...

Can you guys please suggest me, How to do it?

Thanks.

**Comment by kevinchappell** [comment]
@ajaykr089 #62 resolves #60. This can be tested in the console on the [demo page](http://kevinchappell.github.io/formBuilder/).
