### ISSUE TITLE
formBuilder.actions.getData('json', true) does not show disabledFieldButtons

### ISSUE THREAD

**Issue by foaadnami** [kevinchappell/formBuilder#600]
It looks like formBuilder.actions.getData('json', true) does not show the newly [implemented ](https://github.com/kevinchappell/formBuilder/pull/550) field attribute disabledFieldButtons

So if I use disabledFieldButtons in either fields or defaultFields, then try to get the data for a DB save then later retrieve it from the DB, the version I get will be without disabledFieldButtons

**Comment by kevinchappell** [comment]
I have been thinking this option should not be in formData after-all, I'd like to move `disabledFieldButtons` to form options. This wouldn't directly solve your issue but if you are already storing form options in DB you can simply load `disabledFieldButtons` with the rest of your form options. wdyt?

**Comment by foaadnami** [comment]
Yes, that should work. I will also look at extending the logic to perhaps have a field option to limit a field from being added more than once

**Comment by kevinchappell** [comment]
Lets discuss that in #606

**Comment by foaadnami** [comment]
@kevinchappell  appreciate your super busy but wondering if this is on the decks for getting fixed ?

**Comment by foaadnami** [comment]
@kevinchallell Label as bug ?

**Comment by kevinchappell** [comment]
I think the API for this has changed. in the upcoming 2.10.0 `disabledFieldsButtons` is defined in the options passed on initialization of formBuilder. Since this is an editor feature it shouldn't be present in formData.

Have a look at the latest `2.10.0`, you can grab it from the next tag on npm or yarn `yarn add formBuilder@next`
