### ISSUE TITLE
Change the checkbox input tags (input inside label)

### ISSUE THREAD

**Issue by rssluca** [kevinchappell/formBuilder#608]
Hi all,

I have tried to add a template, but I am not sure it solves my problem. How can I change the checkbox fields withing a checkbox-group? In the specific I need to insert the input field inside the label field and also add the checkbox class to the label.

Thank you and advance for your help and your great work.

Luca

**Comment by kevinchappell** [comment]
You can do something like this to change the output of chekcbox-group and other types: https://codepen.io/kevinchappell/pen/WZXNKr
