### ISSUE TITLE
How can I get form JSON object to save in database?

### ISSUE THREAD

**Issue by avinashi37** [kevinchappell/formBuilder#609]
I have successfully integrated "kevinchappell/formBuilder" in my project and it is working good. The next requirement is to save form object in database. But I don't know how to get JSON object of the form. Can anyone please help me!

I have tried below code, but it returns all input fields of the form- 

`$('#my-form').on('submit', function (e) {
            e.preventDefault();
            // Collect form data
            var formData = $(this).serialize();
            // Send data to server
            $.post('/categoryForm', formData)
                    .done(function (response) {
                        console.log('form saved')
                    }).fail(function (jqXHR) {
                        console.log('form was not saved')
                    });
            // Prevent form submission
            return false;
        });`
### Environment Details:
 - formBuilder Version: latest 
 - Browser: chrome, mozilla

**Comment by craigpotter** [comment]
http://formbuilder.readthedocs.io/en/latest/formBuilder/actions/getData/
