### ISSUE TITLE
how to add conmmon attribute into each field?

### ISSUE THREAD

**Issue by baoyadong** [kevinchappell/formBuilder#611]
As the title said,I want to add common attribute into each field.In my program ,I want to add a 
select label into all the fields,how can it easily add?
   for example ,I want to add 'groupSort' a select label,how can I add  in all the fields?
code ie:
groupSort:{
        label:'组排序',
        type:'select',
        options:[
        {'label': '1'},
        {'label': '2'},
        {'label': '3'},
        {'label': '4'}
          ]
        }
    },

**Comment by bstaniszczak** [comment]
I need this feature to.

**Comment by baoyadong** [comment]
I also find that I cannot add the attribute of select label to the field very well ,it cannot show the content of option ,the browse shows code like this : 
<select id="groupSort-frmb-1505288748534-fld-1" title="组别" name="groupSort" class="fld-groupSort form-control">
    <option value="0" selected="null"></option>         
    <option value="1"></option>
    <option value="2"></option>
    <option value="3"></option>
</select>
I don't know why.Can you help me solve this problem as soon as possible?

**Comment by bstaniszczak** [comment]
I do it like this:
Define array with types:

var available_types = [{type:'text'},{type:'button'},{type:'select'},{type:'button'},{type:'checkbox-group'},{type:'date'},{type:'file'},{type:'header'},{type:'hidden'},{type:'paragraph'},{type:'number'},{type:'radio-group'},{type:'select'},{type:'text'},{type:'starRating'},{type:'autocomplete'},{type:'textarea'}];

and in loop build user type attrs:

  var typeUserAttrs = {};
  for(e in available_types){
	  typeUserAttrs[available_types[e].type]={parentClass: {label: 'Kolumny',options: {'col-md-3': '1/4','col-md-6': '1/2','col-md-9': '3/4','col-md-12': '1',}}};
  }

not nice but work for me.

**Comment by baoyadong** [comment]
OK,I tried ,and it worked .Thank you very much! @bstaniszczak

**Comment by bstaniszczak** [comment]
no problem, it would be nice to get list of all types from app.

**Comment by baoyadong** [comment]
Yes ,I think it's a good idea!

**Comment by kevinchappell** [comment]
Will add a `userAttrs` option which applies the attributes to all fields and an action/method for registered controls

**Comment by rachelSwimmer** [comment]
Hi,
if I want to create a typeuserattrs with my html,
can I do something like that?

**Comment by sivashree** [comment]
Hi @kevinchappell , Is there any progress on this feature?

**Comment by lucasnetau** [comment]
@kevinchappell what do you think of a typeUserAttrs[*] and typeUserEvents[*] (Using the * selector like CSS) to allow setting a user attribute and hooking into a user event? Simple to configure for users and small code change to support

**Comment by lucasnetau** [comment]
Closed by #1447
