### ISSUE TITLE
Disable or remove edit, copy and delete button

### ISSUE THREAD

**Issue by cipu** [kevinchappell/formBuilder#615]
Is it possible disable or remove edit, copy and delete button for each field which has a certain attribute (ex. className) ?

**Comment by kevinchappell** [comment]
This can be done using the `typeUserEvents` option. Add listener to className attribute, if it matches a specific pattern remove the desired button.

**Comment by Adam-78** [comment]
How can you achieve this when reloading a saved form via setData or directly passing a saved json string to formData as no typeUserEvent is taking place?

**Comment by toine2one** [comment]
i have the same question as Adam-78 .

**Comment by masoodw1** [comment]
same here too, these buttons just don't go away :(

**Comment by spassvogel** [comment]
I also have this use case.

**Comment by divyangpatel0778** [comment]
### 

> [`_****_`](url)
