### ISSUE TITLE
Form Render throws an error

### ISSUE THREAD

**Issue by tarasromil** [kevinchappell/formBuilder#616]
### Environment Details:

 - formBuilder Version: 2.1.2
 - Browser: Chrome 49
 - OS: OSX 10_8_5

### Actual Behavior
Browser throws an error `Error: TypeError: t.append is not a function`
### Screenshot - *(optional)*
<img width="435" alt="screen shot 2017-09-18 at 2 39 52 pm" src="https://user-images.githubusercontent.com/16254098/30692343-ccc88e12-9ed3-11e7-963d-54acb292ec02.png">

**Comment by kevinchappell** [comment]
Verison 2.1.2 is quite old and I'm pretty sure this was resolved since then. Can you test if this is still an issue? If so feel free to reopen the issue.
