### ISSUE TITLE
new icons and setting default value

### ISSUE THREAD

**Issue by siripragada** [kevinchappell/formBuilder#618]
I am using form-builder.min.js file in my project. I some how registered url as new type. i nedd to add icon for it. but i am unable to add the icon gor the new type. is there any way to add new icons in the file. and i want to set textfield default type to email. how can i do these @kevinchappell

**Comment by siripragada** [comment]
i saw the video to upload new icons but was unable to do that. can you please help me to sort this out

**Comment by kevinchappell** [comment]
sorry im only just seeing this now
icons can be added using custom control architecture or via options for custom fields.

in control class `definition` https://github.com/kevinchappell/formBuilder/blob/master/src/js/control_plugins/starRating.js#L19

as option https://github.com/kevinchappell/formBuilder/blob/master/src/demo/js/demo.js#L45
