### ISSUE TITLE
formRender not working: TypeError: $(...).formRender is not a function

### ISSUE THREAD

**Issue by shabaz-ejaz** [kevinchappell/formBuilder#623]
### Description:

I am trying to render a form from some existing json that was saved from the formBuilder.
When I try to call the `formRender` method I get the following error:
> Uncaught TypeError: $(...).formRender is not a function

Here is my code:

```
 const formRenderOpts = {
      formData: scheme.default_data_format,
      dataType: 'json',
 };

$('#fb-preview').formRender(formRenderOpts);


<div id="fb-preview" />
```

Not sure why this is happening. Any ideas?

### Environment Details:
 - formBuilder Version: 2.9.6
 - Browser: Chrome
 - OS: Windows

### Screenshot - *(optional)*

![2017-09-27_16h06_27](https://user-images.githubusercontent.com/29374282/30921370-4780d4a6-a39e-11e7-9327-af7b021fb89d.png)

**Comment by kevinchappell** [comment]
afaik this only happens when formRender is not included, can you check that form-render.js is included in your app?
