### ISSUE TITLE
Add "other" as a checkbox option rather than just an attribute

### ISSUE THREAD

**Issue by rssluca** [kevinchappell/formBuilder#635]
Is this possible without having to intercept the formData and adding it manually? I am saving the form in a rails json column and rendering it via rails (not using form-render) and was looking for a clue in either form-builder.js or select.js control to add it myself and repackage.

For now I am manually adding the option when i save the form and removing it when i load it in form-builder.

Cheers

**Comment by kevinchappell** [comment]
fixed 
![image](https://user-images.githubusercontent.com/1457540/47823896-8e8f0200-dd27-11e8-99c1-faefa7288226.png)
