### ISSUE TITLE
Check group markup doesn't seem correct

### ISSUE THREAD

**Issue by eradin** [kevinchappell/formBuilder#637]
Version 2.9.8

There is something wrong with the checkbox markup on both the builder and renderer.  

On renderer, there are 2 nested checkbox classes.

<div class="checkbox">
    <div class="checkbox">
   </div>
</div>

I suspect the outer one should be checkbox-group?  

Also, there appears to be errant <br> tags before the required asterisks which forces the asterisk to the next line.

I am trying to create a section of the form called Acknowledgments which a series of checkboxes.  I have made Acknowledgement a header and forced the checkbox group label to blank.  It just renders sloppily.

Screen shots attached.

![screenshot-2017-10-10 teamscoring com](https://user-images.githubusercontent.com/3924103/31416053-8fbb6e92-addb-11e7-84c2-1db70cc906c0.png)
![screenshot-2017-10-10 teamscoring com 1](https://user-images.githubusercontent.com/3924103/31416054-8fdbc39a-addb-11e7-8c3f-d684f4f1e15d.png)

**Comment by kevinchappell** [comment]
fixed 
![image](https://user-images.githubusercontent.com/1457540/47823864-699a8f00-dd27-11e8-919e-582ab905687e.png)
