### ISSUE TITLE
Hi, There is any documentation about how to handle file field inputs? I can't find the way to get the uploaded file when building a form... Thanks!

### ISSUE THREAD

**Issue by arp690** [kevinchappell/formBuilder#639]
### Environment Details:

 - formBuilder Version:  1.24
 - Browser: 
 - OS:

**Comment by SHKEd** [comment]
` <form  enctype='multipart/form-data' ....>`
PHP $_FILES['name_input_file']

**Comment by arp690** [comment]
Hi SHKEd, thanks for your answer... sounds beautiful but no... I can not file any $_FILES post when pressing the button "SAVE" of the form builder

**Comment by kevinchappell** [comment]
backend handling of files is outside of formBuilder's scope, hope you found your solution.

**Comment by harsh-dev007** [comment]
if any one have solution about back end storing with sql for N number of Filds ..please let me know :) <3 thaxx for oowwwsome builder  @kevinchappell   <3 love from indian dev's
