### ISSUE TITLE
How to implement a new custom "access (roles)" typeUserAttrs

### ISSUE THREAD

**Issue by sdkcarlos** [kevinchappell/formBuilder#642]
### Description:

 With the current `typeUserAttrs` in the builder options for any kind of Input, you can add simple fields like checkbox, single selects. However when it comes to create a "complex field", like the roles, I don't know if it's possible to create a similar field to the roles.

 I expect to create something similar to:

![image](https://user-images.githubusercontent.com/11634719/31709759-42505be0-b3f3-11e7-91dd-5ffef3f2ed75.png)

Is this possible using the typeUserAttrs?

**Comment by kevinchappell** [comment]
currently no but `typeUserAttrs` will have some improvements in the future. For now you could use a multiple select: https://codepen.io/kevinchappell/pen/EOxOXe
