### ISSUE TITLE
Field Name Attribute is forced into lowercase?

### ISSUE THREAD

**Issue by Adam-78** [kevinchappell/formBuilder#643]
Hi,

I note Field Name attribute is forced into lowercase. How can I force it to retain whatever case (title, pascal, camel) I choose to use?

**Comment by qualitycode** [comment]
This should be fixed. It seems to be a quick and dirty trick to make it easier to do something like compare. It would be nice to fork the code to fix this. I looked into fixing this, but I am hesitant and don't want to break the code. Maybe make a simple map of the name values before they are mangled by the library, then restore them once the library is finished.

**Comment by kevinchappell** [comment]
this is fixed in latest version
