### ISSUE TITLE
Can I convert or download the rendered form to HTML or PDF ?

### ISSUE THREAD

**Issue by jiyanibharat303** [kevinchappell/formBuilder#645]
Hello,
How can I download the form as HTML and PDF once its rendered.
I cannot use the form render functionality everywhere, hence I need forms stored in HTML or PDF.

**Comment by Jordy-A** [comment]
You can get the html by reading the html content with jquery (`.html()`)?

**Comment by kevinchappell** [comment]
Since 2.10.0 there is also a new formRender method called `html` http://formbuilder.online/docs/formRender/actions/html/

You'll need a 3rd party lib for generating a pdf
