### ISSUE TITLE
There is no date picker displaying on the Date Field in IE 11

### ISSUE THREAD

**Issue by Amy518** [kevinchappell/formBuilder#648]
### Environment Details: IE 11

 - formBuilder Version: 2.5.3
 - Browser: IE 11
 - OS: Windows 8

**Comment by Amy518** [comment]
![image](https://user-images.githubusercontent.com/29471405/31832391-d3c3a86e-b594-11e7-9396-9d798a4ecc66.png)

**Comment by kevinchappell** [comment]
formBuilder had at one point a polyfill for this but it was removed because it added too much to filesize. Anyone that still needs this can use jquery ui datepicker or similar

```
$( 'input[type="date"]' ).datepicker();
```
