### ISSUE TITLE
events.fieldRemoved fired outside slideUp

### ISSUE THREAD

**Issue by arielmorry** [kevinchappell/formBuilder#650]
### Description:
Assuming 1 field in stage >> click remove button:
"fieldRemoved" Event is fired outside $field.slideUp thus the when the event is fired the builder data is not up to date, tying to check number of fields show in correct number as the field is still there.

### Environment Details:

 - formBuilder Version: 2.9.8
 - Browser: Chrome 61
 - OS: Windows 10

### Expected Behavior
    $(document).on('fieldRemoved', function (e) {
        console.log(formBuilderData.actions.getData().length); // output 0
    });
### Actual Behavior
    $(document).on('fieldRemoved', function (e) {
        console.log(formBuilderData.actions.getData().length); // output 1
    });
### Steps to Reproduce
See https://jsfiddle.net/0poojyny/ (Add a Field and then Remove it)

**Comment by MartyvdB** [comment]
Experiencing this too. Is there any update on this?

**Comment by kevinchappell** [comment]
This race condition is fixed in 2.10.0
