### ISSUE TITLE
How to add Line Break in Fields menu

### ISSUE THREAD

**Issue by jiyanibharat303** [kevinchappell/formBuilder#651]
Hello,
How shall I add Line Break as an option to the Fields.
Following is not working.
  var fields = [
    {
      type: 'break tag here not working',
      label: 'Line Break',
    },
  ];

**Comment by kevinchappell** [comment]
Since this is a new field type you'll need to also define a template. https://codepen.io/kevinchappell/pen/wrbVvy

You may also want to disable the edit buttons and add your own styles.

**Comment by jiyanibharat303** [comment]
WOW Thank You So Much :)

**Comment by mrityunjoy88** [comment]
Thanks for the help. 
It is showing an error while trying to preview/render the screen.
_**Invalid control type. (Type: break, Subtype: undefined). Please ensure you have registered it, and imported it correctly.**_

Please help!!
