### ISSUE TITLE
error when using formBuilder.formData

### ISSUE THREAD

**Issue by ayman-aljullaq** [kevinchappell/formBuilder#652]
TypeError: l.actions.getData is not a function[Weitere Informationen]  form-builder.min.js:6:44393

**Comment by kevinchappell** [comment]
Can you provide an example of the error?

http://formbuilder.readthedocs.io/en/latest/formBuilder/promise/

**Comment by kevinchappell** [comment]
There are some async calls when formBuilder first loads for languages so `formBuilder.formData` is not ready when your alert is called. You can use the promise function i linked above or call `.formData` later. Also there would be no formData when the editor first loads anyways, I'm not sure I understand the use case for this.

**Comment by ayman-aljullaq** [comment]
Thank you very much :+1:

**Comment by gohelradheshyam** [comment]
Uncaught ReferenceError: jQuery is not defined
    at Object.153 (form-builder.min.js:6)
    at e (form-builder.min.js:6)
    at 111 (form-builder.min.js:6)
    at form-builder.min.js:6

**Comment by gohelradheshyam** [comment]
Please solve above error

**Comment by gohelradheshyam** [comment]
i declare already jquery and ui jquery  in my form builder  and it work complete but console log show this error
