### ISSUE TITLE
Save Button Rename & Form values empty Issue

### ISSUE THREAD

**Issue by jiyanibharat303** [kevinchappell/formBuilder#653]
Hello,
How to place the Save Button at the Top instead of Bottom.
Also want to rename it to Preview.
I saved the form structure in database. Then on the second module I show the form here I only want to show the form no buttons or side menu hence on load I trigger -
	$(".save-template").trigger('click');
But here when form loads and I fill in the data I don't get the values it goes empty.
Please let know on this

**Comment by kevinchappell** [comment]
It will probably be easier to set [showActionButtons](https://formbuilder.readthedocs.io/en/latest/formBuilder/options/showActionButtons/) to false and create your own button that uses formBuilder actions to save and render the form
