### ISSUE TITLE
Form-Render Custom Control?

### ISSUE THREAD

**Issue by Adam-78** [kevinchappell/formBuilder#655]
I've created a new custom control which renders correctly in form-builder. However it doesn't render in form-render when I click the save button. Is there something I'm missing, do I need to tell form-render to use this control, If so what is the syntax?

      var options = {
        onSave: function (e, formData) {
           toggleEdit();
            $('.render-wrapper').formRender({
                formData: formData,
                control: ['file.dropzone']
             });
        },            
     };

My control saved in control_plugins:

    // configure the class for runtime loading
    if (!window.fbControls) window.fbControls = [];

    window.fbControls.push(function (controlClass, allControlClasses) {

       let controlText = allControlClasses.text;
  
       class controlDropzone extends controlClass {

       static get definition() {
          return {
            i18n: {
              default: 'Dropzone'
            }
         };
       }

      configure() {}

      build() {
     
          let innerWrapper = '<div class="dz-default dz-message"><span><i class="fa fa-paperclip" aria-hidden="true"></i>Drag and drop files or click to upload</span></div>';

          this.wrapper = this.markup('div', innerWrapper, { id: 'my-cool-dropzone', class: 'dropzone' });
          return [this.wrapper];
     }

     onRender(evt) {
              $("div#my-cool-dropzone").dropzone({ url: "/file/post" });
     }
    }

      controlText.register('file', controlText, 'file');
      controlText.register('dropzone', controlDropzone, 'file');
       return controlDropzone;
    });

**Comment by kevinchappell** [comment]
hmm im not sure about this. As long as the custom control is registered it should be available to both formBuilder and formRender.

Closing as this is quite old but feel free to open if its still an issue.
