### ISSUE TITLE
 disabledFieldButtons not working when reloading a saved form?

### ISSUE THREAD

**Issue by Adam-78** [kevinchappell/formBuilder#657]
I have a form with some default fields which users should not be able to remove. I can manage this by using the disabledFieldButton property as follows when creating a form:

        var defaultFields = [
            {
                "type": "text",
                "required": true,
                "label": "Subject",
                "className": "form-control",
                "name": "Subject",
                "subtype": "text",
                "maxlength": "255",
                "disabledFieldButtons": ['remove', 'copy']
           },

When you save the form the disabledFieldButtons property does not get saved. So when you reload the form to edit by passing in the json string to formdata, the field buttons reappear meaning users can now delete them. 

Is there any way we can ensure that mandator field are not removed whether creating or when editing?

**Comment by foaadnami** [comment]
Looks the same as https://github.com/kevinchappell/formBuilder/issues/600 ?
