### ISSUE TITLE
Disable auto-alignment / introduce custom positions

### ISSUE THREAD

**Issue by AydinChavez** [kevinchappell/formBuilder#658]
Hi,

first of all, great piece of code.

Is it possible to stop the auto positioning / auto alignment so the added form elements stay on their (custom) positions when dragged and do not snap back?

**Comment by kevinchappell** [comment]
Is this for controls on for fields dragged to the stage? There is a new option called [`allowStageSort`](https://formbuilder.readthedocs.io/en/latest/formBuilder/options/allowStageSort/)

Setting this to false will disable sorting on the stage.
