### ISSUE TITLE
File field name change  with multiple attribute.

### ISSUE THREAD

**Issue by durgadutt87** [kevinchappell/formBuilder#659]
While enabling multiple option for file field I need to add square brackets to the field name. It has been already working for checkbox and multi dropdown. However it is not working for File field. So I added following code in text.js:

> build() {
>     if (this.config.multiple && this.config.type === 'file') {
>       this.config.name= this.config.name + '[]';
>     }
>     return this.markup('input', null, this.config);
>   }

It works fine in preview mode. However while rendering the HTML of the form, It does not show those square brackets with field name. Please advise. 

### Environment Details:

 - formBuilder Version: 2.9.8
 - Browser: Opera
 - OS: MAC

**Comment by kevinchappell** [comment]
This is fixed now in 2.10.3 
![image](https://user-images.githubusercontent.com/1457540/47959027-acae6980-df96-11e8-9fab-cafa06a4163e.png)
