### ISSUE TITLE
field disspaer

### ISSUE THREAD

**Issue by karthikn7** [kevinchappell/formBuilder#660]

**Comment by karthikn7** [comment]
Hi kevin,

Your form builder is working Awesome, Thanks for it

I need some customization in form builder , I am going to use form fields instead of fields

For Eg:

I going to remove all the right side fields, and use first name , last name, sex, age, gender etc.. and once i drag and drop the first name means it should disappear, pls help me to do this

**Comment by kevinchappell** [comment]
@karthikn7 you should be able to do this with a little extra code. Example: https://codepen.io/kevinchappell/pen/eZReEB
