### ISSUE TITLE
Value Attribute on Save Mode

### ISSUE THREAD

**Issue by jiyanibharat303** [kevinchappell/formBuilder#662]
Hello,
When the form is in edit mode and I trigger -
alert(formBuilder.actions.getData('json', true));
I get the value attribute but when I load the same form from the database and show it in saved mode, in saved mode because I dont want to edit the structure but I can change the value of fields and then save back as HTML.
In this case I dont get the value attribute on 
alert(formBuilder.actions.getData('json', true));
Let know if anything added needed when form is loaded in saved mode.

**Comment by foaadnami** [comment]
Looks the same as https://github.com/kevinchappell/formBuilder/issues/600 ?

**Comment by jiyanibharat303** [comment]
No its not the same basically all I am saying the while I enter the value while building the form and click getdata it shows the value. But once I save it and store in database. Then because at the other user I dont want them to edit structure but only allow them to fill the values for the form is created from backend. Hence at that point I load from db and rendered it with save button already clicked. This time the getdata to only shows the previous recorded values and not the updated ones.
I managed to get it done with the -
for(var pair of formData.entries()) {
           console.log(pair[0]+ ': '+ pair[1]);
 }
On TestSubmit provided.
