### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by RenvanHeerden** [kevinchappell/formBuilder#664]
### Description: Not really an issue, I'm busy trying to use pagination so that my form doesn't really grow too much and automatically page after a set amount of controls; anybody that could point me in the right directions?

I don't want to use tabs as that is multiple forms, I want one forms with pagination.

Another thing that would be nice is progress completion view.

Still I find this the most easiest Form build to implement into our system.
Thanks to the amazing team and contributors!

**Comment by kevinchappell** [comment]
Thanks for the kind words. Its possible to use tabs to design a single form but you would need a little extra code to chunk the generated formData for pagination.

Then you would be able to call formRender on the chunked data, one formRender for each chunk
