### ISSUE TITLE
babel-polyfill is not meant to be included in libraries

### ISSUE THREAD

**Issue by combs** [kevinchappell/formBuilder#666]
### Description:

The inclusion of babel-polyfill fails in environments that already include it, such as a WordPress instance running recent versions of https://github.com/Yoast/wordpress-seo

Per babel-polyfill docs,

> This will emulate a full ES2015+ environment and is intended to be used in an application rather than a library/tool. 

### Environment Details:

 - formBuilder Version: 2.9.8
 - Browser: Chrome
 - OS: OS X 10.11

### Expected Behavior

Not included in pages

### Actual Behavior

```

formrender.js:4590 Uncaught Error: only one instance of babel-polyfill is allowed

```

### Steps to Reproduce

Install WordPress
Install Yoast SEO
Attempt to use formBuilder

**Comment by kevinchappell** [comment]
babel-polyfill has been removed form the project, thank for reporting this.

**Comment by combs** [comment]
Thank you @kevinchappell !
