### ISSUE TITLE
Assumes that jQuery is at '$' ?

### ISSUE THREAD

**Issue by combs** [kevinchappell/formBuilder#667]
### Description:

https://github.com/kevinchappell/formBuilder/blob/master/src/js/form-render.js#L56

It looks like you are assuming jQuery is available at `$` but our environment uses `jQuery`

```
Uncaught TypeError: Cannot read property 'extend' of undefined
    at new e (formrender.js:6)
    at a.fn.init.e.fn.formRender (formrender.js:6)
    at loadFormScripts (VM991 v3.js?1511217161:209)
    at VM991 v3.js?1511217161:201
    at d (VM1024 raven.min.js:2)
```

### Environment Details:

 - formBuilder Version: 2.9.8
 - Browser: Chrome
 - OS: OS X 10.11

### Expected Behavior

Use of `jQuery` is ok

### Actual Behavior

Dies with undefined `$`

### Steps to Reproduce

Unset your `$` and watch the fireworks

**Comment by stutteringp0et** [comment]
same issue here

**Comment by kevinchappell** [comment]
formBuilder now only uses `$` inside of 
```javascript
;(function($) {
// init plugin
})(jQuery)
```

Can you confirm if this is still an issue?
