### ISSUE TITLE
Can i add my own options to the form which show up when i click on edit?

### ISSUE THREAD

**Issue by PradeepKeshavprakash** [kevinchappell/formBuilder#669]
### Description:
I want to have a functionality where i should able to define actions on button click or attach model data etc to the element. Is there a way to do that?
### Environment Details:
AngularJS v1
 - formBuilder Version: 
 - Browser: 
Chrome
 - OS: 
Windows

**Comment by kevinchappell** [comment]
[typeUserEvents](https://formbuilder.readthedocs.io/en/latest/formBuilder/options/typeUserEvents/) may help but if this is for the generated form you may need some additional code
