### ISSUE TITLE
Getting formBuilder to work with React

### ISSUE THREAD

**Issue by hhtech1** [kevinchappell/formBuilder#670]
Hi, I've been trying to get formBuilder to work in a React app.

Steps to reproduce are:

1)
Create an empty React app with these (reference: https://reactjs.org/tutorial/tutorial.html):
npm install -g create-react-app
create-react-app my-app

2)
Install latest versions of  jquery, jquery-ui and formBuilder to the React app with:
npm install jquery --save
npm install jquery-ui --save
npm install formBuilder --save
So in package.json these are then added:
"jquery": "^3.2.1",
"jquery-ui": "^1.12.1",
"formBuilder": "^2.9.8"

3)
In app.js top of file add:
import $ from 'jquery';
window.jQuery = $;
window.$ = $;
require('jquery-ui');
require('formBuilder');
I came to use the above lines after first seeing various errors like "$ is undefiend", "jQuery is undefined" etc.
With the above lines, I am sure that jquery, jquery-ui and formBuilder are all loaded into my bundle.js (I verified by looking into bundle.js code).

4)
In app.js, inside render method, add these 2 elements:
  ```
      <input type="button" value="Load Editor" onClick={this.loadEditor} />
        <div id="editor">Editor goes here...</div>        

```
5)
In app.js, inside App component, add these 2 methods:

  ```
// Tries to load editor on after component load
  componentDidMount() {
    let ed = $("#editor");
    ed.formBuilder();
  }
```
```

  // Tries to load editor on button click {
  loadEditor() {
    let ed = $("#editor");
    ed.formBuilder();
  }
```

6)
Run app with:
npm start
Open F12 console, you can see this error:
index.js:2177 TypeError: N.sortable is not a function
    at new A (form-builder.min.js:6)
    at HTMLDivElement.<anonymous> (form-builder.min.js:6)
    at Function.each (jquery.js:362)
    at jQuery.fn.init.each (jquery.js:157)
    at form-builder.min.js:6
    at <anonymous>

7)
Click Load Editor button.
In F12 console, you can see it also gives the same error as in step 6.

8)
Try editing package.json to load the exact same jquery and jquery-ui versions as referenced in Basic Example in http://formbuilder.readthedocs.io/en/latest/getting-started/:
    "jquery": "2.1.4",
    "jquery-ui": "1.11.4",
    "formBuilder": "^2.9.8"

The same error still occurs.

Any pointers? We would very much like to use this plugin as we haven't found a WYSIWYG type of form builder for React.

The two edited files are in the attached zip, all other files are unedited (they remain as they were created by create-react-app in step 1.
[files.zip](https://github.com/kevinchappell/formBuilder/files/1505429/files.zip)

**Comment by hhtech1** [comment]
In case someone else has the same problem, I got this to work as follows in a basic React app (created with create-react-app):

package.json:

    "jquery": "^3.1.1",
    "jquery-ui-sortable": "*",
    "formBuilder": "^2.9.8"

app.js:

    import $ from 'jquery';
    window.jQuery = $;
    window.$ = $;
    require('jquery-ui-sortable');
    require('formBuilder');

And the same in a React with TypeScript app created with the Visual Studio 2017 React template:

app.js:

    import * as $ from 'jquery';
    (window as any).jQuery = $;
    (window as any).$ = $;
    require('jquery-ui-sortable');
    require('formBuilder');


The Basic Example at http://formbuilder.readthedocs.io/en/latest/getting-started/  should be updated, it no longer works as such.

**Comment by jjleavitt** [comment]
Thank you for this @hhtech1

**Comment by BrianHVB** [comment]
Here is a simple working React template
https://codesandbox.io/s/6zl7o2jynn

**Comment by angelrethinam** [comment]
Hi, i use this code it is working nice, but save button is not working,
