### ISSUE TITLE
Single checkbox field

### ISSUE THREAD

**Issue by rssluca** [kevinchappell/formBuilder#672]
Hi, 

I am trying to implement a single checkbox agreement field that instead of a label shows a paragraph . Is it possible to lock a single option and also giving it a name/value?

Creating a custom control is out of my depth I am afraid..

**Comment by ochiengolanga** [comment]
Duplicate of #783

**Comment by kevinchappell** [comment]
@rssluca There isnt a built-in way to lock into a single checkbox but you could do it by hiding or removing the options in the edit panel using a `typeUserEvents` callback.
