### ISSUE TITLE
I want to add options dynamically from table to the checkbox, radio and select option

### ISSUE THREAD

**Issue by CSK888** [kevinchappell/formBuilder#673]
### Description:
We can add options to the checkbox, radio button, and select by manually entering values and labels under option. But I want to add options to this fields by selecting fields from tables. If the user selects any table and checks the fields which he wants to use as the options. How to do it

### Environment Details:

 - formBuilder Version: 
 - Browser: 
 - OS:

**Comment by mudassarhanifchohan** [comment]
same question

**Comment by Harry97** [comment]
That's what [typeUserEvents](http://formbuilder.readthedocs.io/en/latest/formBuilder/options/typeUserEvents/) designed for.
