### ISSUE TITLE
Not rendering form with json from database

### ISSUE THREAD

**Issue by apmyp1990** [kevinchappell/formBuilder#674]
### Description:
I am trying to render a form with formRender(...). Previously I have stored the generated json in a MariaDB database in a json-field. Now I am retrieving the json from the database and insert it into the formRender function, but it does not work.

I made a console.log before I am sending it to database, and one before pushing it to the renderForm function - it looks same.

### Environment Details:

 - formBuilder Version: latest
 - Browser: Chrome
 - OS: Windows 10

### Expected Behavior
It should render the form from json.

### Actual Behavior
It does nothing.

### Steps to Reproduce
See above.

**Comment by gustavo43t** [comment]
Working fine for me.

```
var eleRender = $(#id_form_to_place_fields)
eleRender.formRender({
  dataType: 'json',
  formData: this.group.fields,
  render: true
});

Note: The formData is a string, not json object!
```
