### ISSUE TITLE
Notify object in options doesn't seem to do anything

### ISSUE THREAD

**Issue by stutteringp0et** [kevinchappell/formBuilder#675]
### Description:
View the "Notify" demo - 
If you know how to view the console of a specific frame, this will do:
http://formbuilder.readthedocs.io/en/latest/formBuilder/options/notify/

Otherwise, you can view the codepen directly here:
https://codepen.io/kevinchappell/pen/xVrOVr

### Environment Details:

 - formBuilder Version: whatever is hosted from formbuilder.online
 - Browser: Chrome
 - OS: Linux

### Expected Behavior

events are logged

### Actual Behavior

nothing happens

### Steps to Reproduce

See above

**Comment by sergioralmeida** [comment]
Same thing here, using any browser from Windows or Chrome/Safari in Mac.
Nothing happens.

**Comment by shoe5454** [comment]
Same issue here, Chrome on Windows.

**Comment by kevinchappell** [comment]
notify is only used for a few actions like clearAllFields.
@stutteringp0et  The below screenshot taken from the demo you linked, can you confirm if this is still a problem?
![image](https://user-images.githubusercontent.com/1457540/47823594-33a8db00-dd26-11e8-92df-579b268b35fc.png)
