### ISSUE TITLE
quill editor looks wrong 

### ISSUE THREAD

**Issue by mlingureanu** [kevinchappell/formBuilder#677]
### Description:
probably some css it's missing ?

### Environment Details:

 - formBuilder Version: 
 - Browser: 
 - OS: 

### Steps to Reproduce
1. add a textarea and select type quill
2. add more than one rows of text

### Screenshot - *(optional)*
![quill](https://user-images.githubusercontent.com/18526392/33984676-29624d32-e0c1-11e7-96cd-3ce214dbf11a.PNG)

**Comment by kamranajabbar** [comment]
yes i have also observed same issue. Kindly share solution if possible.

**Comment by nbelyh** [comment]
Try removing the bootstrap "form-control" class from the editor. Should do the trick.

**Comment by kevinchappell** [comment]
indeed form-control a the problem. maybe we should have the class be removed when the type is changed.

marking this as a bug because there are multiple issues going on here
