### ISSUE TITLE
Disable Item Same Label

### ISSUE THREAD

**Issue by ratshrdina** [kevinchappell/formBuilder#679]
### Description:
There is some way to block two labels from having the same value?

<img width="877" alt="captura de pantalla 2017-12-19 a la s 19 03 48" src="https://user-images.githubusercontent.com/29409459/34181001-6074a176-e4ef-11e7-824d-9bf4ec15f775.png">

**Comment by xhava** [comment]
have you find something to solve this?

**Comment by kevinchappell** [comment]
This can be done with `typeUserEvents`
