### ISSUE TITLE
Getting "Uncaught TypeError: $(...).formBuilder is not a function" Error with Tabbed/Multi-Page Forms 

### ISSUE THREAD

**Issue by DevrajKapdi** [kevinchappell/formBuilder#681]
@kevinchappell 
### Description:

Uncaught TypeError: $(...).formBuilder is not a function
    at HTMLDocument.<anonymous> (Contact:95)
    at c (jquery-1.10.2.min.js:21)
    at Object.fireWith [as resolveWith] (jquery-1.10.2.min.js:21)
    at Function.ready (jquery-1.10.2.min.js:21)
    at HTMLDocument.q (jquery-1.10.2.min.js:21)

### Below is my code, please let me know what i am missing here,

===================================================

`<style type="text/css">`
 ```
   body {
        padding: 0;
        margin: 10px 0;
        background: #f2f2f2 url('http://formbuilder.readthedocs.io/en/latest/img/noise.png');
    }
```

    .save-all-wrap {
        text-align: center;
        padding: 20px;
    }
</style>

`<div id="form-builder-pages">`
  `  <ul id="tabs">`
       ` <li><a href="#page-1">Page 1</a></li>`
       ` <li id="add-page-tab"><a href="#new-page">+ Page</a></li>`
   ` </ul>`
  `  <div id="page-1" class="fb-editor"></div>`
    `<div id="new-page"></div>`

`</div>`
`<div class="save-all-wrap"><button id="save-all" type="button">Save All</button></div>`

`<link href="~/Theme/css/jquery-ui.css" rel="stylesheet" />`

```
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery-ui.min.js"></script>
<script src="~/Theme/vendor/javascripts/form-builder.min.js"></script>
<script src="~/Theme/vendor/javascripts/form-render.min.js"></script>
```

```
<script type="text/javascript">
    $(function () {
        "use strict";
        var $fbPages = $(document.getElementById("form-builder-pages"));
        var addPageTab = document.getElementById("add-page-tab");
        var fbInstances = [];

        $fbPages.tabs({
            beforeActivate: function (event, ui) {
                if (ui.newPanel.selector === "#new-page") {
                    return false;
                }
            }
        });

        addPageTab.onclick = function () {
            var tabCount = document.getElementById("tabs").children.length,
              tabId = "page-" + tabCount.toString(),
              $newPageTemplate = $(document.getElementById("new-page")),
              $newPage = $newPageTemplate
                .clone()
                .attr("id", tabId)
                .addClass("fb-editor"),
              $newTab = $(this).clone().removeAttr("id"),
              $tabLink = $("a", $newTab)
                .attr("href", "#" + tabId)
                .text("Page " + tabCount);

            $newPage.insertBefore($newPageTemplate);
            $newTab.insertBefore(this);
            $fbPages.tabs("refresh");
            $fbPages.tabs("option", "active", tabCount - 1);
            fbInstances.push($newPage.formBuilder());
        };

        fbInstances.push($(".fb-editor").formBuilder());

        $(document.getElementById("save-all")).click(function () {
            var allData = fbInstances.map(function (fb) {
                return fb.formData;
            });
            console.log(allData);
        });
    });

</script>
```

=========================================================

### Environment Details:

 - formBuilder Version: 
 - Browser:  Crome
 - OS: Windows 10

### Actual Behavior 
Its not working as shown in example  http://formbuilder.readthedocs.io/en/stable/formBuilder/demos/tabs/

**Comment by coolternet** [comment]
soo ? it was ?
