### ISSUE TITLE
replaceFields duplicates fields in multi-page form

### ISSUE THREAD

**Issue by rssluca** [kevinchappell/formBuilder#682]
Hi all,

I need to use replaceFields with multi-page forms but it seems the fields are duplicated each time I add a tab. I replicated the issue by adding my options to the Codepen snippet from the documentation page.

https://codepen.io/anon/pen/QaKrXy

Cheers,

Luca

**Comment by rssluca** [comment]
Solved this morning, I am passing the replaceFields hash only to the first tab.

`// Add replaceFields if first tab only (otherwise it will add it once more for each tab)
    if ( tabId == 1 ) {
      // console.log($.extend({}, options, { 'replaceFields': replaceFields}))
      var setOptions = $.extend({}, options, { 'replaceFields': replaceFields});
    } else {
      var setOptions = options;
    }

    // Add form builder instance to the new tab
    fbInstances[tabId] = $("#page-" + tabId).formBuilder(setOptions);`

Cheers

**Comment by rssluca** [comment]
Hello, its been a while.

This is still not working fine with Turbolinks. I am setting options to null and rebuilding every time but replaceFields still duplicates.

Cheers

**Comment by kevinchappell** [comment]
@rssluca 
hey sorry for the incredible delay on this. This should be fixed now in 2.10.0, I just tested with your codepen- thanks for creating that.

**Comment by Ravi-kavya01** [comment]
I am getting the last tab data for each one.

You can check this URL. It have the same issue
https://codepen.io/anon/pen/QaKrXy

Thanks

**Comment by Ravi-kavya01** [comment]
Any update on this
