### ISSUE TITLE
How to add columns ?

### ISSUE THREAD

**Issue by gauravgoyal5** [kevinchappell/formBuilder#684]
It is very good tool. Thanks for providing us good tool.
I am trying to add 2 column but I am not able to find any way to add columns in which I can add controls i.e.

First Name : ___________________________    Last Name :______________________________________

Can you please let me know how to add columns?

Thanks & Regards
Gaurav

**Comment by MahdiRadcom** [comment]
If you haven't start your development, you can take a look at [Formeo ](https://draggable.github.io/formeo/) instead of FormBuilder. As I know, FormBuilder doesn't provide such feature.

**Comment by bdkoder** [comment]
> It is very good tool. Thanks for providing us good tool. I am trying to add 2 column but I am not able to find any way to add columns in which I can add controls i.e.
> 
> First Name : ___________________________ Last Name :______________________________________
> 
> Can you please let me know how to add columns?
> 
> Thanks & Regards Gaurav

Columns works well - https://codepen.io/bdkoder/pen/eYrGXKG
