### ISSUE TITLE
Menu is not working properly

### ISSUE THREAD

**Issue by MahdiRadcom** [kevinchappell/formBuilder#685]
The menu -even the online version- is not working properly when the controls added are longer than the height of the menu. It shows up when I start scrolling. I have tested this issue by different browsers. Sometimes menu gets invisible and sometimes moves to an inappropriate place.
This is what I get:
![formbuilder](https://user-images.githubusercontent.com/30586571/34665361-221c46dc-f475-11e7-9735-a27745f43a34.png)

**Comment by kevinchappell** [comment]
thanks for reporting.

fixed in 2.20.0
