### ISSUE TITLE
Adding option to options attribute problem in other languages than English

### ISSUE THREAD

**Issue by MahdiRadcom** [kevinchappell/formBuilder#688]
When adding option to currently added options field in languages such as Persian, "Label" and "Value" placeholders are not shown.
![placeholder](https://user-images.githubusercontent.com/30586571/34709301-f10195e0-f52b-11e7-88ee-e34a287122af.png)

**Comment by kevinchappell** [comment]
New option values are normally blank but there should be a placeholder for those fields. Its likely the translation is missing for those: would you mind adding here? https://github.com/kevinchappell/formBuilder-languages
