### ISSUE TITLE
Proposal: change disabledFields option

### ISSUE THREAD

**Issue by kevinchappell** [kevinchappell/formBuilder#69]
A common question is how to disable specific fields in formBuilder like Autocomplete. The simplest way to accomplish this is to hide it from the user with css like this:
```
.frmb-control .icon-autocomplete {
    display: none;
}
```

There are use cases however where the field type should not exist in DOM at all. For this I propose changing the current `disabledFields` option to accept an array of field types that should **not** be rendered. Initializing formBuilder with this option would look like this:
```
var fbTemplate = document.getElementById('fb-template'),
    options = {
      disabledFields: ['autocomplete']
    };
$(fbTemplate).formBuilder(options);
```

The only catch is that `disabledFields` is already an option used to prepend and append uneditable fields/html to the beginning and end of the form. For this reason the second part of this proposal is to reassign that functionality to new options called `prepend` and `append` respectively.

Please use the comments here to vote up or down and make suggestions related to this proposal.

Voting ends Feb, 26 2016

**Comment by kevinchappell** [comment]
Looks like there were no objections. Expect this change in the next week or so.

**Comment by wudoz** [comment]
It's a good idea to disable form elements .
