### ISSUE TITLE
customized block with multiple inputs

### ISSUE THREAD

**Issue by henriquehf** [kevinchappell/formBuilder#690]
Not an issue per say, as I don´t even know if this plugin was supposed to be able to do this, but I want to create custom form "blocks" (like the star rating one they use as n example), but I want to make blocks that have multiple inputs.
Is that even possible? if so, how do?
Thanks!

**Comment by kevinchappell** [comment]
Absolutely, this can be done using [custom controls](https://formbuilder.readthedocs.io/en/latest/formBuilder/control-plugins/)
