### ISSUE TITLE
Escape characters replacing ampersand again and again

### ISSUE THREAD

**Issue by prageethindika** [kevinchappell/formBuilder#691]
### Description:
I'm saving the formdata on database and after for the edit, I'm loading the formdata to formbuilder.
When formdata load to the form builder, & (ampersand) load as "\&amp;\" in the label field. And if I save it again, it loaded "\&amp;amp\";
All the time & symbol replace with "\&amp;\" 
This happens for all ",&,<,> symbols 

### Environment Details:
 - formBuilder Version: 1.24.2
 - Browser: Chorme
 - OS: Windows 10

### Expected Behavior
& (ampersand) symbol should replace with "\&amp;\" but should not replace the &amp; code 

### Actual Behavior
When formdata load to the form builder, & (ampersand) load as &amp; in the label field. And if I save it again it loaded as "&amp;amp";

### Steps to Reproduce
Save the formdata on db and load it to formbuilder and repeat it again and again.

**Comment by kevinchappell** [comment]
resolved in 2.10.0
