### ISSUE TITLE
Is there any way in which conditional inputs can be added via the formbuilder? 

### ISSUE THREAD

**Issue by ondemandnathan** [kevinchappell/formBuilder#692]
### Description:

Is there any way in which conditional inputs can be added via the formbuilder? 

For instance:

If there was a select box with the text "Did you enjoy your holiday?" and the options "YES" and "NO", if the user was to select "NO" could a text area then be displayed asking why they selected no? 

Thanks in advance for any help on this.

**Comment by kevinchappell** [comment]
Conditionals are not built-in but this can be accomplished by creating custom controls using the control architecture: https://formbuilder.readthedocs.io/en/latest/formBuilder/controls/
