### ISSUE TITLE
how to create Multiple column  

### ISSUE THREAD

**Issue by santosh-k1** [kevinchappell/formBuilder#697]
@kevinchappell as per your form builder documentation we can not create  Multiple column by using formBuilder. instead of formBuilder you have introduce Formeo but documentation is not available. so its make difficulty to use the framework. so please suggest !!!

**Comment by kevinchappell** [comment]
sorry but multiple columns are not supported by formBuilder and formeo is still a work in progress. Documentation will come as soon as formeo is finalized.

**Comment by Epandudev** [comment]
> sorry but multiple columns are not supported by formBuilder and formeo is still a work in progress. Documentation will come as soon as formeo is finalized.

Hi kevinchappell ,
The form builder is a great idea and the developed application is awesome. Can you please share updated and resizable columns(Multiple columns) link.
