### ISSUE TITLE
Value attribute for TextArea control is a input[type=text] and not textarea/div[contenteditable] leading to removal of new lines

### ISSUE THREAD

**Issue by sergioralmeida** [kevinchappell/formBuilder#699]
We can write new lines (hit the "enter" button) on the textarea, but it doesn't save them.
You can try this on the demo page.
1 - https://formbuilder.online/
2 - Add a textarea
3 - Write something with multiple lines
4 - Save
5 - Weep

![image](https://user-images.githubusercontent.com/5584428/35748192-0bd22d5e-0845-11e8-9302-a3ee379eea5f.png)

Value is saved with all lines together, not even a tiny space between characters.

![image](https://user-images.githubusercontent.com/5584428/35748215-20c83050-0845-11e8-9fc4-53026f3e3c08.png)

Any ideas to fix this are highly appreciated. Cheers.

**Comment by YaroslavPetryk** [comment]
you need at first before sending to encodeURIcomponent(message), then when you recieve the message decodeURIComponent(message); then message.replace(/%0A/g, "<br>");

**Comment by Jojoshua** [comment]
Is this still an issue?

**Comment by lucasnetau** [comment]
The value field is a a input[type=text] element which can only take single line text. So when we sync the value of the preview textarea to the value field the \n newlines are removed.

https://github.com/kevinchappell/formBuilder/blob/58baf4e4de05f98406ea7050a12ae87cef5a1140/src/js/form-builder.js#L1717

**Comment by temamagic** [comment]
Also in edit mode, we have single line input instead textarea
<img width="231" alt="image" src="https://github.com/kevinchappell/formBuilder/assets/15264697/f3f862ba-6823-4be1-811f-d2f0b960bf35">
