### ISSUE TITLE
disabledActionButtons does not disable buttons

### ISSUE THREAD

**Issue by Davidslv** [kevinchappell/formBuilder#700]
### Description:

I'm only interested in Header, paragraph and text field, so I want to disable all the other buttons,
I've used `disabledActionButtons` and I expected the buttons added in that array to not show, but they all show up in the form.

### Environment Details:

 - formBuilder Version: 2.9.8
 - Browser: Chrome Version 63.0.3239.132 (Official Build) (64-bit)
 - OS: OSX Sierra 10.12.4

### Expected Behavior

I expect that when I add button names to `disabledActionButtons` that they do not show.

### Actual Behavior

When I add button names to `disabledActionButtons` they still show.

### Steps to Reproduce

```javascript

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
<script src="http://formbuilder.online/assets/js/form-builder.min.js"></script>
<script>

jQuery(function($) {
  var options = {
    controlOrder: [
      'header',
      'text',
      'paragraph'
    ],
    disabledActionButtons: [
      'autocomplete',
      'button',
      'checkbox-group',
      'radio-group',
      'select',
      'file',
      'date',
      'number',
      'textarea'
    ],
  };

  var container = $(document.getElementById('fb-editor'));
  $(container).formBuilder(options);
});
```

### Screenshot - *(optional)*
<img width="1246" alt="screen shot 2018-02-03 at 11 07 03" src="https://user-images.githubusercontent.com/136777/35766554-90db2982-08d2-11e8-8862-ea56a61da8c5.png">

**Comment by rakeshghasadiya** [comment]
Try this.
var options = {
    controlOrder: [
     'header',
      'text',
      'paragraph'
    ],
    disableFields: [
     'autocomplete',
      'button',
      'checkbox-group',
      'radio-group',
      'select',
      'file',
      'date',
      'number',
      'textarea'
    ],
  };

**Comment by kevinchappell** [comment]
@Davidslv I think you need `disableFields` as @rakeshghasadiya pointed out.
