### ISSUE TITLE
Unable to edit form . Once i created a form and saved , Then i need to edit the same for but unable to render the form. How can i render the form ?

### ISSUE THREAD

**Issue by DineeshDS** [kevinchappell/formBuilder#702]
### Environment Details:

 - formBuilder Version: 
 - Browser: 
 - OS:

**Comment by sharmaanand086** [comment]
am not able to edit my rendered form database in JSON format with formbuilder is it possible to do
when i am clicking on edit form it again showing me new formbuider not that which i want to edit from my database.
<?php
$servername = "localhost";
$username = "root";
$password = "";
$dbname = "forms";
$conn = new mysqli($servername,$username,$password,$dbname);
if($conn->connect_error){
echo $conn->connect_error;
}
$id= $_GET["id"];
// echo $id;
$sql = "SELECT id, fdata FROM form_element where id='$id' ";
$result = mysqli_query($conn, $sql);
$formfile;
if ($result->num_rows > 0) {
// output data of each row
while($row = $result->fetch_assoc()) {
$formfile = preg_replace('!\r?\n!', "", $row["fdata"]);
// echo $formfile;
}

} else {
echo "0 results";
}

?>

<div id="form-render-wrap" ></div>
<button id="edit-form">Edit Form</button>
<script type="text/javascript">

formData ='<?php echo $formfile; ?>';
$('#form-render-wrap').formRender({
formData: formData,
dataType: 'json'

  });   
</script>
![image](https://user-images.githubusercontent.com/38725515/43317090-230c01f4-91b9-11e8-982f-dec64e3e9060.png)
