### ISSUE TITLE
setData "label":"" results in placing the word undefined

### ISSUE THREAD

**Issue by ThomasWiens** [kevinchappell/formBuilder#703]
### Description:
If you use the function setData and you give an empty String for label it results in setting the word undefined instead. The preview still has the default value for that widget.
A quick test showed that other field aren't affected by that behaviour.

### Environment Details:

 - formBuilder Version: 2.9.8
 - Browser: Chrome
 - OS: Windows 10

### Expected Behavior
The label value reflects the data provided by the data given - even when it is empty.

### Actual Behavior
it does not

### Steps to Reproduce
1. go to https://codepen.io/kevinchappell/pen/ozagKr
2. replace "Full Name" with "" on the label of the textfield in the JS section
3. let codepen refresh
4. in the preview activate the button "set Data"
5. open the first widget via edit button
6. confirm that there is the text "undefined"
7. profit

**Comment by kevinchappell** [comment]
Can you confirm this is still an issue? I am seeing the fallback label now.
