### ISSUE TITLE
How can I translate my custom control?

### ISSUE THREAD

**Issue by AndriyYushko** [kevinchappell/formBuilder#704]

**Comment by kevinchappell** [comment]
Could you provide an example of your custom control? You should be able to add translations through your custom control definiton

```javascript
controlCustom.def = {
        i18n: {
          'pt-br': {...},
          'zh-cn': {...}
        }
      };
```

**Comment by AndriyYushko** [comment]
class controlVideoFile extends controlClass {

    static get definition() {
        return {
            icon : '📹',
            class: 'fa-camera',
            i18n : {
                default: 'Attach video'
            }
        }
    };

    build() {
        let controlTpl = new controlTemplate();
        let attrs = Object.assign(this.config);
        let name = attrs.name || '';
        let id = this.id;
        this.field = controlTpl.getInputTpl(name, 'video/*', '',
'camcorder', id);

        return this.markup('div', [this.field]);
    }
}



2018-02-07 14:17 GMT+02:00 Kevin Chappell <notifications@github.com>:

**Comment by AndriyYushko** [comment]
I tried this method controlCustom.def = {
        i18n: {
          'pt-br': {...},
          'zh-cn': {...}
        }
      };
but it not work

**Comment by kevinchappell** [comment]
This is covered in Control Definitions section of the docs: http://formbuilder.readthedocs.io/en/latest/formBuilder/overview/#control-definitions

**Comment by AndriyYushko** [comment]
Thank you I'll try

**Comment by AndriyYushko** [comment]
Very very Thank you all work

**Comment by kevinchappell** [comment]
great, I'm happy to hear that.
