### ISSUE TITLE
How to create user attribute for custom control?

### ISSUE THREAD

**Issue by AndriyYushko** [kevinchappell/formBuilder#707]
It is possible in new control class?
I mean... Like this 
![image](https://user-images.githubusercontent.com/35810665/36160215-4f2eda50-10e9-11e8-8b7b-80b1c8096cf9.png)

**Comment by sheikmohamed90** [comment]
yes using typeUserAttrs

**Comment by sheikmohamed90** [comment]
var typeUserAttrs = {
        text: {
            className: {
                label: 'Class',
              option:{
'form-control': 'form-control',
'class2':'classname2',
'class3':'className3'
}
            }
}
