### ISSUE TITLE
Request: typeUserEvents onremove and onedit

### ISSUE THREAD

**Issue by ThomasWiens** [kevinchappell/formBuilder#709]
### Description:
you can add functions for onclone and onadd via the typeUserEvents Options. I need an aditional onremove and onedit for a project i am working on.

If all of those function would return the affected control that would be awesome as well.

**Comment by AndriyYushko** [comment]
I have some problem

**Comment by kevinchappell** [comment]
I've added `onremove` but when specifically would `onedit` be triggered?

**Comment by kevinchappell** [comment]
I think we can rely on events for `onedit`

**Comment by aloncarmel** [comment]
Is this something that has been added? I couldn't find any onedit anywhere or onremove.

**Comment by Jojoshua** [comment]
> `onremove`

Yes it's there as a userEvent, similar to onadd but onremove isn't documented yet https://formbuilder.online/docs/formBuilder/options/typeUserEvents/
