### ISSUE TITLE
setLang removes every control (and creates internally a new formBuilder i believe)

### ISSUE THREAD

**Issue by ThomasWiens** [kevinchappell/formBuilder#710]
### Description:
when using the function setLang on an already configure form it removes everything of it.
(I believe it does that by simply creating a new formBuilder and replacing the old one)

### Environment Details:

 - formBuilder Version: 2.9.8
 - Browser: any
 - OS: Windows 10

### Expected Behavior
The controls stay but the values resets to their defaults
(it still is the same builder)

### Actual Behavior
Remove all the things.

### Steps to Reproduce
1. go to [http://formbuilder.readthedocs.io/en/latest/formBuilder/actions/setLang/](example)
2. add something to your form
3. click on a button

**Comment by kevinchappell** [comment]
previously `setLang` would create a new instance this is now fixed in the latest version, 2.10.3 at the time of writing.
