### ISSUE TITLE
unable to chage template for text field

### ISSUE THREAD

**Issue by scrlt-speedster** [kevinchappell/formBuilder#711]
I am unable to change default template for fields like textfield and text area. But able to do so for autocomplete , checkbox-group.

the code  snipet is given below :

var templates = {
   autocomplete: function(fieldData) {
    return {
      field: '<input class="form-control" id="'+fieldData.name+'" type="text"><input type="button" value="comment" id="'+fieldData.name+'">'
    };
  },
  'checkbox-group': function(fieldData) {
   return {
     field: '<input class="form-control" id="'+fieldData.name+'" type="text"><input type="button" value="comment" id="'+fieldData.name+'">'
   };
 },
  text: function(fieldData) {
  return {
    field: '<input class="form-control" id="'+fieldData.name+'" type="text"><input type="button" value="comment" id="'+fieldData.name+'">'
  };
}
};

var formRender=$('form', formContainer).formRender({
            formData: $scope.selectedForm.formData,
            templates: templates
  });

this is how the output looks like 
![screenshot from 2018-02-16 11-58-50](https://user-images.githubusercontent.com/30341683/36295982-d3d28fbc-1310-11e8-9a92-8b1aa3a3dfcc.png)

**Comment by scrlt-speedster** [comment]
never mind i found a workaround

**Comment by MyMy1609** [comment]
@scrlt-speedster  hi,can you show me your solution please, i have same problem

**Comment by mbortonus** [comment]
@scrlt-speedster or @MyMy1609 , can you possibly share your solutions?
