### ISSUE TITLE
XML Parsing error in Firefox loading language file

### ISSUE THREAD

**Issue by davexpression** [kevinchappell/formBuilder#714]
### Description:
I see "XML Parsing Error: syntax error ... Line Number 1, Column 1:" when loading language files. It actually works and there is no problem with the functioning of the form builder yet. Researching on this I found out that it's because response type is not set correctly
### Environment Details:

 - formBuilder Version: 2.9.6
 - Browser: Firefox 58.0.2
 - OS: Windows 10

### Steps to Reproduce
`      i18n: {
        locale: ru-RU,
        location: url
        //extension: '.ext'
        //preloaded: {
        //    'en-US': {...}
        //}
      }`

**Comment by kevinchappell** [comment]
@davexpression you have `locale: ru-RU` but it should be `locale: 'ru-RU'`.  I know this is quite old but  if youre still having the issue could you test with the latest version? I was not able to reproduce the problem.
