### ISSUE TITLE
How to remove field by id?

### ISSUE THREAD

**Issue by AndriyYushko** [kevinchappell/formBuilder#716]

**Comment by denda888** [comment]
I have a same problems

**Comment by AndriyYushko** [comment]
formBuilder.removeField('your_id');

**Comment by denda888** [comment]
thank you. Do you know how to change the default name of the input. 
Like text-1519740215937-prevew => text

**Comment by AndriyYushko** [comment]
you can use jQuery

**Comment by denda888** [comment]
I do not know how to do, you please just way for me, thank you much

**Comment by AndriyYushko** [comment]
when you added new control executed method

onadd: function (fld) {

}

you mast take fld.id and find li element on formBuilder

$(`#${fld.id}`).attr('id', 'new_id')


2018-02-27 16:49 GMT+02:00 Đen đá <notifications@github.com>:

**Comment by denda888** [comment]
I understand and thank you so much
