### ISSUE TITLE
How to make Label of the control to appear on the left side  instead of at the top of the control

### ISSUE THREAD

**Issue by soumyojit** [kevinchappell/formBuilder#717]
### Description:
Hi Kevin. We want the Label of the control to appear on the left side of the control instead of the top . How can this be done ? Can you let me know step by step . I am new to javascript.

### Environment Details:

 - formBuilder Version:  Version: 2.9.8
 - Browser:  Chrome
 - OS:  Windows 10

### Expected Behavior

 We want the Label of the control to appear on the left side of the control instead of the top . 

### Actual Behavior

The Label of the control  appears on the top of the control

**Comment by soumyojit** [comment]
Please help me to close this

**Comment by kevinchappell** [comment]
There is no built-in settings but it could be done with some extra css

``
.rendered-form .form-group > label {
  display: inline-block;
  float: left;
  margin-right: 2%;
}

.rendered-form .form-group > label + div,
.rendered-form .form-group > label + input,
.rendered-form .form-group > label + textarea,
.rendered-form .form-group > label + select {
  display: inline-block;
  width: 73%;
}
```
