### ISSUE TITLE
i want to show image in form preview . but error coming when i am Rendering the form 

### ISSUE THREAD

**Issue by phpdevelopernk-git** [kevinchappell/formBuilder#718]
### Description:
I am trying to create a custom control where only a image will come OnRender in form preview

### Environment Details:

 - formBuilder Version: 
 - Browser: Firefox
 - OS: Ubuntu

### Expected Behavior
It should come track image as a form field when i am Rendering the form data with json in preview mode

### Actual Behavior
when i am tryin to render form with preview button then Error coming in console.

Error: Invalid control type. (Type: track, Subtype: undefined). Please ensure you have registered it, and imported it correctly.

Please look at my script:

https://gist.github.com/phpdevelopernk-git/18841590ac1b0e95bdd4effc32b8abdb

**Comment by tienuit** [comment]
hi @phpdevelopernk-git 
Did you solve your issue? I also got this issue, and waiting for a solution

**Comment by phpdevelopernk-git** [comment]
Unfortunately still this issue coming.

**Comment by kevinchappell** [comment]
Excellent find! I'm releasing a fix now.

Also I've updated your gist a little to avoid using jquery to lookup the field again. https://gist.github.com/kevinchappell/c5a05ea77e9e8b6b3303dd28521f7d53
