### ISSUE TITLE
how to change of remove input name ?

### ISSUE THREAD

**Issue by dv-denda** [kevinchappell/formBuilder#720]
I want to save the name of the input tag to the database but the input tag is default text-1519740731887-preview. How to delete the string behind like: text-1519740731887-preview => text

**Comment by kevinchappell** [comment]
The `-preview` is only added in the editor but the names are purposefully generated with unique IDs to prevent duplicates. To use the generated forms you should be saving the formData and doing so you'll have access to a `type` attribute on fields. In the example you gave the type would be `text`.
