### ISSUE TITLE
How to disable name field of all the element being drag dropped to create form using form builder

### ISSUE THREAD

**Issue by nono1988** [kevinchappell/formBuilder#722]
Hi kevinchappell,
This is a beautiful tool. I want to disable name property of every element for disabling users to edit name attribute of whether input types or text areas. how can i do that. I want users not to edit this field when the design a form.
![capture](https://user-images.githubusercontent.com/10363426/36933843-b8a854c8-1f05-11e8-89f1-844de9e9bd61.PNG)

**Comment by rssluca** [comment]
Hi,

If you want the name to be generated and included in the json string I would just disable it in css.

`// Remove name field in attributes
div.name-wrap, div.subtype-wrap {
  display: none!important;
}`

**Comment by kevinchappell** [comment]
There is also a `disabledAttrs` option: https://formbuilder.readthedocs.io/en/latest/formBuilder/options/disabledAttrs/
