### ISSUE TITLE
Dynamic attribute add to fields like field1 , field2 , field3

### ISSUE THREAD

**Issue by vanithaPHP** [kevinchappell/formBuilder#726]
Hi kevinchappell,
 I need to add fields with custom attribute like `<input type="text" data-attr = "field1"  id= "name" name="name"/>` how to do it?

and i need to remove field from right side panel after drag into main container please help me.

**Comment by vanithaPHP** [comment]
Hi,

After a long days i found solution for  dynamic attribute adding and on drag and drop removing adding fields in form-builder panel.

**Comment by Jojoshua** [comment]
There is now config to add custom props
