### ISSUE TITLE
Controls Not Support Internet Explorer

### ISSUE THREAD

**Issue by sheikmohamed90** [kevinchappell/formBuilder#728]
### Description:
Dear 
   i using kevinchappell/formBuilder  only working chrome not a Internet explorer please explain why not working kevinchappell/formBuilder specially not working controls[ date and numbers].i using latest version of kevinchappell/formBuilder. please explain and reply me. if possible to work
### Environment Details:

 - formBuilder Version: latest
 - Browser: internet explorer
 - OS: windows

### Expected Behavior
working All browser
### Actual Behavior
only working perfect chrome
### Steps to Reproduce
please check and reply me

**Comment by kevinchappell** [comment]
by controls do you means the ones that are part of the editor or custom controls?
![image](https://user-images.githubusercontent.com/1457540/47957307-92fa2b80-df70-11e8-8429-86fb4d040051.png)

Can you verify if this is still an issue with the latest release, 2.10.3?
