### ISSUE TITLE
How to add custom button with icon in typeUserAttrs

### ISSUE THREAD

**Issue by rafsan007** [kevinchappell/formBuilder#729]
I want to show a custom button with icon inside header details:

![screen shot 2018-03-21 at 7 52 52 pm](https://user-images.githubusercontent.com/19227159/37713621-a701762e-2d41-11e8-9a05-aaacf1e929a4.png)

I like to show a color picker icon on right side of background #field. 

This is my code:

> var typeUserAttrs = {
      header: {
        style: {
            name: 'headerColor',
            label: 'Choose a color',
            type: 'button',
            onfocus: "getColors(this)",
            onblur: "setValue(this)"
        }
    }};

is there any way i can achieve this ? need Help.

**Comment by kevinchappell** [comment]
There isnt a built-in way but maybe you could use 🎨?

**Comment by LuisAndres** [comment]
@rafsan007 do you applied the color picker on all the  labels controls(text, select etc)? how do you made that?
