### ISSUE TITLE
Is there no function to get formrender's data?

### ISSUE THREAD

**Issue by lhadmin06** [kevinchappell/formBuilder#730]
Is there no function to get formrender's data? in harry

**Comment by sangaloma** [comment]
Please if you figure it out, post it here. I think I have the same needs as you.

**Comment by denitsa-cm** [comment]
Want to do the same too :)

**Comment by wobh** [comment]
I did this by setting the `onRender` option to a function that assigned the formData value to a variable which would be available for other event callbacks.

**Comment by Jojoshua** [comment]
@wobh does your solution get the data the user entered before submit?

**Comment by SoftwarePhil** [comment]
like this
$(#class/.div where you put your form).serializeArray().map(function(v) {return {"field_name":v.name, "field_value":v.value};} )

**Comment by Jojoshua** [comment]
Say you save that into the database... How do you fill the form back with the data? Seems tricky with the different options formbuilder provides like checkbox-other

**Comment by kevinchappell** [comment]
@Jojoshua that is precisely the reason it was never implemented. However `formRender.formdata` is still something I would like to add as I have some ideas on how to handle the differences between user data and formData but unfortunately time is very limited for side projects these days.

The bottom line is the data from formBuilder and formRender are not 1:1 so there will need to be some compatibility layer. PRs welcome :)

**Comment by Jojoshua** [comment]
@kevinchappell You've done a good job with this code and I understand you have other priorities so I'll take a stab at this. If you already have some thoughts on how it might be done, please share your ideas.

**Comment by wobh** [comment]
@Jojoshua I wrote a function for it like this, although it has at least one bug in it I haven't fixed yet:

```js
let setFormData = function( formData ) {
  $.each( formData, function( _, field ) {
    if ( !!field[ "name" ] ) {
      // FIXME: check for multi-value fields (radio, checkbox, etc)
      // and store in field.values
      field.value = $( "#" + field[ "name" ] ).val();
    }
  });
}
```

**Comment by wobh** [comment]
@Jojoshua Let me know if I can help. Except for the bug, what I have mostly works.

**Comment by Jojoshua** [comment]
Ok I just sent a PR. Whoever is interested in this concept, please review for improvement and testing edge cases.  https://github.com/kevinchappell/formBuilder/pull/749

**Comment by kevinchappell** [comment]
Closing since `userData` has been in core for a while now. Great work @Jojoshua 
https://formbuilder.readthedocs.io/en/latest/formRender/actions/userData/
