### ISSUE TITLE
How to add custom property to a form field type

### ISSUE THREAD

**Issue by AmirZenhari** [kevinchappell/formBuilder#731]
Hi,
I need to add weight property to some field types such as radio and number field types. Weight is a number which will be used to calculate the overall score of a answered form (Example : survey form or quiz form) in a case that a couple of form field types are radio or number.
Is there any documentation on "how to" available or any in-progress development related to my requirement?
Regards,
A.Z

**Comment by simon-hevs** [comment]
You can do this in typeUserAttributes and set it in the options, here is an example
Remember to set typeUserAttributes = typeUserAttributes in fbOptions

```var typeUserAttrs = {
        text: {
            className: {
                label: 'Width',
                options: {
                    'form-control width-100': '100%',
                    'form-control width-50': '50%',
                    'form-control width-25': '25%'
                }
                //style: 'border: 1px solid red'
            },
            IncludeInList: {
                label: 'Include in List',
                options: {
                    'false': 'No',
                    'true': 'Yes'
                },
                style: 'width:auto;'
            }
        }
}
```

**Comment by kevinchappell** [comment]
@AmirZenhari number inputs can be generated like so:

```
typeUserAttrs: {
      text: {
        weight: {
          type: "number",
          label: "Weight",
          min: "0",
          max: "5",
          value: 0
        }
      }
    }
```
