### ISSUE TITLE
Hello Kevin, would like to thank you for this amazing plugin. Would like to ask if there is a possible way to set control attributes as required . Thanks

### ISSUE THREAD

**Issue by Ozeeee** [kevinchappell/formBuilder#733]
### Environment Details:

 - formBuilder Version: 
 - Browser: 
 - OS:

**Comment by kevinchappell** [comment]
Thanks for the kind words. You should be able to add custom attributes using the `typeUserAttrs` option.
https://formbuilder.readthedocs.io/en/latest/formBuilder/options/typeUserAttrs/
