### ISSUE TITLE
Disable "sortable"

### ISSUE THREAD

**Issue by sergioralmeida** [kevinchappell/formBuilder#734]
### Description:
Is there any option to disable the "sortable" functionality (from jQuery UI) from the forms? Couldn't find anything on the docs.

We could just call `$('.ui-sortable').sortable('destroy');` but we are using REST and it's not that simple. Also, it would be much better to just not allow the elements to be sortable instead of allowing and disallowing.

Any ideas?

### Environment Details:

 - formBuilder Version: 2.9.8
 - Browser: any
 - OS: any

### Expected Behavior
Elements not sortable.

### Actual Behavior
Elements always sortable.

### Steps to Reproduce
Open any form (for example: https://formbuilder.online/), add elements to form and drag them.

**Comment by kevinchappell** [comment]
v2.10.0 introduced a new option called `allowStageSort`. This option can be set to false to disable sorting elements on the stage.
https://formbuilder.readthedocs.io/en/latest/formBuilder/options/allowStageSort/

**Comment by SambojuShravan** [comment]
This option is also disabling the Field Sort functionality. I.e., I'm unable to drag and drop the Fields into the template. 
Any idea  on this?
