### ISSUE TITLE
the name of a multi file upload should be an array 

### ISSUE THREAD

**Issue by ArnoutCreemers** [kevinchappell/formBuilder#736]
### Description:
When creating a multi-file uploader with the formbuilder plugin, the name of the file input element is not an array. This causes issues when processing the uploaded files.

### Steps to reproduce:

1. Go to https://formbuilder.online/
2. Add a file uploader
3. Go to settings and check "Allow users to upload multiple files"
4. Save the form, copy the HTML

### Expected Behavior
The input file is generated as:
`<input type="file" class="form-control" name="file-1524506075088[]" multiple="true" id="file-1524506075088">`

Note the **[]** behind the name of the element

### Actual Behavior
The input file is generated as:
`<input type="file" class="form-control" name="file-1524506075088" multiple="true" id="file-1524506075088">`

**Comment by ArnoutCreemers** [comment]
For those with the same issue, a dirty fix is to execute following jQuery after the form is rendered:
` $('input[type="file"][multiple="true"]').each(function() {
                $(this).attr("name", $(this).attr("name") + "[]");
            });`

**Comment by sahilr2050** [comment]
@ArnoutCreemers How do I save the uploaded file from the form which is made from FormBuilder? 

> I have made the form using form builder
> I have rendered the form
> User now upload the file and click on submit. I can see the file-xxxx in the post but how can I save the file into the server and in database?

**Comment by sahilr2050** [comment]
I have latest version of Form Builder Still the if input files allow multiple files then name should be an array. Still this is simple name

**Comment by Spl4x** [comment]
> For those with the same issue, a dirty fix is to execute following jQuery after the form is rendered:
> 
> ```
> $('input[type="file"][multiple="true"]').each(function() {
>      $(this).attr("name", $(this).attr("name") + "[]");
>  });
> ```

Great, it helped me rename several fields!
