### ISSUE TITLE
Uncaught TypeError: $(...).formBuilder is not a function

### ISSUE THREAD

**Issue by DiegoSousaMg** [kevinchappell/formBuilder#737]
### Description:

I have a page with multiple "form-builders" and I wont use "Tabbed/Multi-Page Form" because I need to have some extra information in the tabs.

I was using the demo.js that comes in the download, but in it I couldn't use setData probably because I need to do it to each form-builder, so I'm trying to start the "form-builders" inside a each but when I call the function formBuilder I get this error: Uncaught TypeError: $(...).formBuilder is not a function

### Environment Details:

 - formBuilder Version: v2.9.8
 - Browser: Opera, Firefox, Chrome
 - OS: Windows

### Expected Behavior

Create all form builders with its data. The data is used when the user is editing a form. I stored it in the attr "data-form" of the element.

### Actual Behavior

Uncaught TypeError: $(...).formBuilder is not a function

### Steps to Reproduce

I have 2 or more of that in my page
`<div id="stage1" class="build-wrap" data-form="[@data_form]"></div>`

I declarate only the 
"~/Scripts/Template/plugins/form-builder/js/form-builder.js"
I dont need to render the form.

e = element
`function nova_form_build(e) {
//copied from the demo.js        
var templates = {
starRating: function (fieldData) {
                return {
                    field: '<span id="' + fieldData.name + '">',
                    onRender: function () {
                        $(document.getElementById(fieldData.name)).rateYo({ rating: 3.6 });
                    }
                };
            }
        };
        var fbOptions = {
            subtypes: {
                text: ['datetime-local']
            },
            onSave: function (e, formData) {
                toggleEdit();
                $('.render-wrap').formRender({
                    formData: formData,
                    templates: templates
                });
                window.sessionStorage.setItem('formData', JSON.stringify(formData));
            },
            stickyControls: {
                enable: true
            },
            sortableControls: true,
            templates: templates,
            disabledActionButtons: ['data', 'clear', 'save'],
            disableInjectedStyle: false,
            disableFields: ['autocomplete', 'button', 'hidden', 'paragraph', 'radio-group', 'number', 'header'],
            disabledAttrs: ['access', 'className', 'inline', 'max', 'maxlength', 'min', 'multiple', 'name', 'other', 'placeholder', 'rows', 'step', 'style', 'subtype', 'toggle', 'value'],
            disabledFieldButtons: {
                text: ['copy']
            },
            defaultFields: $(e).attr("data-form").replace(",\"values\":[]", "").replace(",]", "]").replace("},]", "]")
        };
        var formBuilder = $(e).formBuilder(fbOptions);
        //var fbPromise = formBuilder.promise;
}`

**Comment by kevinchappell** [comment]
sorry but could you create a jsfiddle or similar that replicates the problem? I'm having trouble reproducing the error.
