### ISSUE TITLE
Long json of defaultFields take longer to render in Formbuilder

### ISSUE THREAD

**Issue by shashankaugurs** [kevinchappell/formBuilder#738]
### Description:
I have long list of json as defaultFields to be loaded for form builder on edit function. Sometimes the json will have 4-5 tabs and each page has lots of fields.

So, this json took very long time to be parsed and render in the form builder area.

How can I solve this loading time issue?

**Comment by kevinchappell** [comment]
can you share an example of this long JSON? JSON parsing alone should not add much time
