### ISSUE TITLE
Disable subtypes

### ISSUE THREAD

**Issue by FabianSchmick** [kevinchappell/formBuilder#739]
Is there an oportunity to disable/remove subtypes?

For the **text** type I only need _Text Type_ and _email_.

I thought about something like this, as an opposite of the existing subtype option:

```
disableSubtypes: {
    text: ['tel', 'color', 'password']
}
```

**Comment by kevinchappell** [comment]
this is a good idea. I''l look into adding it in future version otherwise feel free to submit a PR
