### ISSUE TITLE
Proposal: multiple languages

### ISSUE THREAD

**Issue by ixlipixli** [kevinchappell/formBuilder#74]
Hi,

I was wondering if it's possible to have something like a language setting. So that I only have to create a form once (and not for every language) and I am able to name e.g. the label attributs in the different languages.

Thanks in advance!

**Comment by kevinchappell** [comment]
I would love to do this, and plan to as soon as I find translators. Will update the Readme today asking for translators.

**Comment by rogeriomarques** [comment]
I would gladly help translate to french and portuguese. Count on me.

**Comment by kevinchappell** [comment]
Excellent! I started writing a little how-to but I'd like to have this be part of v2 of the plugin instead. @rogeriomarques I'll ping you after v2 alpha is posted, it will have an example of how to translate. Thank you!
