### ISSUE TITLE
Utils.safeAttr question

### ISSUE THREAD

**Issue by smanohar** [kevinchappell/formBuilder#740]
### Description:
Line #93 in utils.js removes the first comma that is part of any value. The offending code is as follows:
valString = utils.escapeAttr(value.replace(',', ' ').trim())
This causes any comma in the values of attrs such as labels, values etc to be chopped. What is the rationale for this? Can the replace() be removed safely without any side effects?
 
### Environment Details:

 - formBuilder Version: 2.9.8 
 - Browser: all
 - OS: all

### Steps to Reproduce
call setData with a label or value attribute with a comma in its value field. The comma will be chopped.

**Comment by kevinchappell** [comment]
i don't remember the rationale for this decision. It can probably be removed
