### ISSUE TITLE
Cannot create repeatable elements in list

### ISSUE THREAD

**Issue by fedepia** [kevinchappell/formBuilder#742]
Hi guys, not sure if this is the right channel to create this ticket.

FormBuilder does not support building repeatable elements. For example, I can't build a form like this:
```
Company: "Amazon"
Locations: [ 
   { country: US, address: San Francisco }, 
   { country: ARG, address: Buenos Aires },
   { country: CR, address: San Jose }
]
```

I haven't found a way to create this very common use case. Is this supported by FormBuilder?

**Comment by kevinchappell** [comment]
This is doable via custom control architecture or `fields` option. https://formbuilder.readthedocs.io/en/latest/formBuilder/controls/
