### ISSUE TITLE
can i user JQuery 3.3 instead of JQuery 2.1.4? is there any conflict in the future.

### ISSUE THREAD

**Issue by jason-migz** [kevinchappell/formBuilder#743]
### Description:
Can i use JQuery 3.3 instead of JQuery 2.1.4? is there any conflict in the future.
### Environment Details:

 - formBuilder Version: 2.9.8
 - Browser: Chrome
 - OS: Windows 10

**Comment by kevinchappell** [comment]
Yes that should be fine. The version is updated to 3.1.1 in the next release
