### ISSUE TITLE
Add subtype for select control

### ISSUE THREAD

**Issue by ProjectMaker** [kevinchappell/formBuilder#746]
### Description:
Is possible to add on the `form-builder` methods `defaultFieldAttrs` at this line :

`select: defaultAttrs.concat(['multiple', 'options'])`
`select: defaultAttrs.concat(['multiple', 'options', 'subtype'])` ( adding 'subtype' )

Thanks

**Comment by kevinchappell** [comment]
Its possible to replace control configs or even create a custom control to do this. How would select subtype be used though?

**Comment by kevinchappell** [comment]
as far as I can see `select` tags wouldnt support subtypes. `subtypes` are like <input type=`text|number|email`/> or for header tags <`h1|h2|h3`>. I'm not sure how this would work for select.
