### ISSUE TITLE
how i can remove the edit button in every element and place it above the Save button

### ISSUE THREAD

**Issue by jason-migz** [kevinchappell/formBuilder#748]
### Description:
I want the edit button of every element place above the `save` button, and when i click to an element in stage the edit option for that element is place above the save button rather than displaying in front of element.
### Environment Details:

 - formBuilder Version: 2.9.8
 - Browser: Google Chrome
 - OS: Windows 10

**Comment by kevinchappell** [comment]
Do you mean to open all edit windows with a single button?

**Comment by jason-migz** [comment]
No. If i click the element the edit configuration of that element will be
seen. It means no edit button in each element. Its like the edit
cofiguration will automatically be seen depend what form element is
selected by cursor.

**Comment by jason-migz** [comment]
Possibly you are thinking my request is un reasonable. But i want to make
it clear. I want the edit view of each element to be remove. Instead place
it somewhere but not above of form element selected by pressing the edit
button.

**Comment by kevinchappell** [comment]
ah i see. I just finished adding feature to the next release that will enable this called `toggleFieldEdit()` I am preparing the release now but in the meantime can you have a look at the demo [here](https://github.com/kevinchappell/formBuilder/blob/release/2.10.0/demo/assets/js/demo.js#L273)?

My thinking is you could add an event listening for clicks on field `li` tags and in the handler, grab the id and call `toggleFieldEdit`. wdyt?

**Comment by kevinchappell** [comment]
oohhh. do you mean like an edit modal? so instead of sliding down it appears elsewhere on the page?

**Comment by kevinchappell** [comment]
Ah OK. I'm clear now. My striked out comment was correct. They're isn't a built-in way of doing that but I think there should be. Will have a look at adding it.

**Comment by jason-migz** [comment]
Thank you very much. Appreciated. (:
