### ISSUE TITLE
Question: Appending classes

### ISSUE THREAD

**Issue by sheibeck** [kevinchappell/formBuilder#75]
Sorry if this was answered somewhere, I couldn't find if it was. Is there a way to append additional classes to the fields? I'd like to be able to wrap the form elements with some additional CSS classes that would be in addition to the classes that are autogenerated by formBuilder.

**Comment by kevinchappell** [comment]
@sheibeck currently no but I like the idea and have added it to my ToDo list. 

In the interim you could create SASS or LESS mixins to apply specific styling or if you need the actual classes for Javascript activities you could apply the additional classes after render. For example if you needed the classes `profile-options` and `shelbeck-field` added to all `checkbox-group` field wrappers you could add them with jQuery like so: 
```
jQuery('[class^=field-checkbox-group]').addClass('profile-options shelbeck-field');
```

**Comment by sheibeck** [comment]
Thanks for the ideas. I can work with the after render for now. I'll just need a way to be able to apply different classes to the same type of field. For example, I may have a text input that I want to be 25% wide and the next one to be 75% wide. I'm assuming I can find something that will uniquely identify each field if I want to make a few small tweaks that won't affect the whole type.

**Comment by kevinchappell** [comment]
Absolutely, each field as its own unique wrapper class and you can combined different selectors to target every other, every 3rd etc field with nth selectors.

**Comment by kevinchappell** [comment]
Classes attribute added in 1.9.0

**Comment by sheibeck** [comment]
Kevin, that's awesome. I'm looking forward to your implementation of the bootstrap css.
