### ISSUE TITLE
Field label does not remove or escape non text characters copied from Ms. Office Word/PDF

### ISSUE THREAD

**Issue by PirunSeng** [kevinchappell/formBuilder#757]
### Description:
Field label does not remove or escape non text characters as how it is visible.

### Environment Details:

 - formBuilder Version: 2.9.8
 - Browser: Chrome (might be any)
 - OS: MacOS X (might be any)

### Expected Behavior
Field label should get rid off any non text characters if a user copy text from anywhere and make/paste it as label of form builder field.

### Actual Behavior
Field label stores everything of the copied text, eg. if we copy text from Ms. Office Word/PDF, etc, it will contain html, css, \n, \t, etc.

### Steps to Reproduce
When you copy text from Ms. Office Word/PDF to make it as your field label, when submitting the form, if you check the passing params (back-end / server side), you will see those html, css, \n, \t, etc, along with the field label/text you've just copied.

**Comment by mikevoets** [comment]
Is this fix currently on master?

**Comment by PirunSeng** [comment]
I guess the fix will be available in 2.10.0. Can't wait for it :)

**Comment by mikevoets** [comment]
Me neither! This will solve many problems in our app :-)
