### ISSUE TITLE
Non-input element

### ISSUE THREAD

**Issue by t-bru** [kevinchappell/formBuilder#758]
This tool is great!  Great work!  Just wondering... If i wanted to create a control for a `<hr/> `how would I do it?  I have added the following but it has the label "Separator".  HOw can I remove the label?  Or is there a better solution?

let fields = [{
		  label: 'Seperator',
		  attrs: {
			type: 'seperator',
			label: '',
		  },
		  icon: '--'
		}];
		let templates = {
		  seperator: function(fieldData) {
			return {
			  field: '<span id="'+fieldData.name+'">',
			  onRender: function() {
				$(document.getElementById(fieldData.name)).html('`<hr/>`');
			  }
			}
		  },
		}

**Comment by kevinchappell** [comment]
close, have a look at the [`controlParagraph`](https://github.com/kevinchappell/formBuilder/blob/a64bf58166891ce5726cf1e2fc7acde6086abebc/src/js/control/paragraph.js), that should set you in the right direction
