### ISSUE TITLE
Trying to Pass the Csrf token value

### ISSUE THREAD

**Issue by mbarb** [kevinchappell/formBuilder#759]
### Description:
Using Laravel I am trying to pass the csrf token during post with no luck.
the code I am using 
```
<form id="fb-render" action="{{url('/sendform')}}" method="post" >
                            {{ csrf_field() }}
</form>
```
```
  <script>
        jQuery(function($) {
            var fbRender = document.getElementById('fb-render'),
                formData = {!! $form->formcode !!};

            var formRenderOpts = {
                formData,
                dataType: 'json'
            };

            $(fbRender).formRender(formRenderOpts);
        });
    </script>
```
  
### Environment Details:
-Backend: Laravel 5.5
 - formBuilder Version:  2.9.8
 - Browser: Chrome
 - OS: Windows

### Expected Behavior
To post the formData
### Actual Behavior
It does not Post the data with Status Code: 419 unknown status cause CSRF is missing

If I except the post url ( /sendform) from the csrf validation  the post  is successful

**Comment by mbarb** [comment]
After some trial and error  this code worked.
```
<form method="POST" action="{{url('/sendform')}}">
                            <input type="hidden" name="_token" value="<?php echo csrf_token(); ?>">
                                <div id="fb-render" ></div>
                         </form>
```
This form builder is awesome.!
Thanks ;)

**Comment by kevinchappell** [comment]
Glad you got it worked out :+1:
