### ISSUE TITLE
Update compiled script in dist directory

### ISSUE THREAD

**Issue by sophanox** [kevinchappell/formBuilder#760]
Hey Kevin,

The compiled script in the dist directory is 8 months out of date and is missing a few important updates (for me it's the lack of proper CSS scoping you fixed in #602). 

Our project doesn't have a proper build process, so we can't do the build ourselves. Could you please update the compiled script in /dist/?

Thanks very much

**Comment by kevinchappell** [comment]
@sophanox Can you describe the issues #602 are causing? I am preparing a big release and if its something small could include a fix.
