### ISSUE TITLE
Help Wanted: Datetime input field

### ISSUE THREAD

**Issue by mbarb** [kevinchappell/formBuilder#761]
I need a datetime input field so I wonder from where I start.?
is there something I can do with the date  field that already exists to be able to add the time too ?

Thanks

**Comment by Jingli-lu** [comment]
Hi there, 

Have you figured out how to do it? I have the same question. 

Thanks, 
Jingli

**Comment by Jingli-lu** [comment]
I have figured it out. Just create

var fields = [
        {
            label: "DateTime",
            type: "text",
            subtype:"datetime-local",
            icon: "⏰"  
        }
    ];

and in fbOptions add 
var fbOptions = {
fields: fields
}

Hope this would help someone has the same question.

**Comment by philanz** [comment]
do you have any working plucker or fiddle ? @Jingli-lu i tried out same but seems like im only getting a regular textbox

**Comment by philanz** [comment]
datetime-local no safari support

**Comment by mbarb** [comment]
Excellent !  
Thanks @Jingli-lu
