### ISSUE TITLE
Label attribute text content overflows out of input box

### ISSUE THREAD

**Issue by wolfej1994** [kevinchappell/formBuilder#762]
### Description:

The label control attribute's text overflows out of the constraints of the box, going onto a new line. This may be due to the fact that the label attribute input, and only the label attribute input, is a <div> rather than an <input>

### Environment Details:

 - formBuilder Version: **v2.9.8**
 - Browser: **Chrome Version 67.0.3396.79 (Official Build) (64-bit)**
 - OS: **maxOS High Sierra Version 10.13.4**

### Expected Behavior

Text input to act like any regular text input within bootstrap _i.e._ truncate with '...' but allow the user to scroll through the text horizontally

### Actual Behavior

Text goes onto a new line when it reaches the right boundary.

### Steps to Reproduce

Type anything into the default label attribute editor input that exceeds the width of the box.

### Screenshot - *(optional)*

![image](https://user-images.githubusercontent.com/11985466/41241315-7f3d1fec-6d94-11e8-8696-6151aee460e6.png)

**Comment by worldtutorials** [comment]
I have a fix for this in my issue post.

**Comment by kevinchappell** [comment]
fixed in 2.10.0
![image](https://user-images.githubusercontent.com/1457540/47823119-f5122100-dd23-11e8-9d2f-0604e54cd15a.png)
