### ISSUE TITLE
moment-picker as control not working

### ISSUE THREAD

**Issue by philanz** [kevinchappell/formBuilder#764]
### Description:

Created a custom template for a time picker using moment-picker. the picker is working on same page outside the form builder. Inside the builder the control is appearing and im able to drag and drop it too. But the calendar view for the moment-picker is not appearing

PFB the code
```
fields: [{
                label: 'Time',
                attrs: {
                    type: 'customTime'
                },
                icon: '⌚'
            }],
templates: {
                customTime: (fieldData) => {
                    return {
                        field: `
                    <input id=${fieldData.name} type="text" class="form-control"
                    moment-picker="tempTime"
                    locale="en"
                    format="HH:mm" 
                    start-view="month"
                    placeholder="HH:mm"
                    ng-model="tempTime" />
                        `,
                        onRender: function () {
                        }
                    };
                }
            },
```

### Environment Details:
 - Angular: 1.6
 - webpack": 1.15.0
 - Node: 9.3.0
 - formBuilder Version: 2.9.8
 - Browser: Chrome 67.0.3396.87
 - OS: Ubuntu 16.04

**Comment by kevinchappell** [comment]
Can you create a codesandbox or codepen demonstrating? Are there any errors? could it be a z-index issue?

**Comment by kevinchappell** [comment]
unable to reproduce, feel free to reopen with more info
