### ISSUE TITLE
Help on retrieving formData field index

### ISSUE THREAD

**Issue by insoluzioni** [kevinchappell/formBuilder#765]
Is there a way to retrieve one added field index? 
I am dynamically filling options for a select, but to do that I need the right index position to get the field attribute name.

**Comment by kevinchappell** [comment]
This depends, do you need the most recently added field?
Currently there is a `fieldAdded` event you could listen for. 2.10.0 Will have a new callback option that gives the new field's id and data. Would that help?

**Comment by insoluzioni** [comment]
Thank you! I'll check that! If I manage to retrieve the field ID then I can reger to it.
