### ISSUE TITLE
Can not cancel values attr

### ISSUE THREAD

**Issue by singleseeker** [kevinchappell/formBuilder#767]
````
disabledAttrs = ['subtype', 'values' , 'access', 'value', 'options' , 'multiple', 'max', 'maxlength', 'min', 'other', 'toggle', 'inline'];
````

can not cancel "values" attr show when click "Code" in "Select" element.. Any idea?

**Comment by singleseeker** [comment]
![image](https://user-images.githubusercontent.com/520698/41837799-2568f042-7891-11e8-83e8-d890d9afe8e8.png)

**Comment by kevinchappell** [comment]
disabledAttrs is mainly for ui, why do you need it removed from data object?

Internally, if formBuilder has a select field without a `values` attribute it will add default values
