### ISSUE TITLE
minSelectionRequired render issue

### ISSUE THREAD

**Issue by oliverkuchies** [kevinchappell/formBuilder#769]
### Description:
When preloading data into the formrender form, the form is rendered in a way that assumes that the value is not meeting the requirements of the form. In this case it is minSelectionRequired in the checkbox group. Form cannot be submitted due to this 'requirement'
### Environment Details:

 - formBuilder Version: 2.9.8
 - Browser: Chrome
 - OS: Windows

### Expected Behavior
Form is submitted without any issue even when checkboxes are preloaded.
### Actual Behavior
Form cannot submit even with checkbox data given/preloaded by application. 
### Steps to Reproduce
1) Preload form with data, use jQuery function to check the box with .prop('checked', true); 
2) Load form - click 'Submit form' button in the form.
3) minSelectionRequired error for checkbox entries
See screenshot attached for result

### Screenshot - *(optional)*
![image](https://user-images.githubusercontent.com/11084292/41886015-d516b0fe-793d-11e8-989e-c0b81caf8296.png)

**Comment by kevinchappell** [comment]
This is happening because formRender is not aware of the change. Can you try triggering the change?

https://stackoverflow.com/questions/24410581/changing-prop-using-jquery-does-not-trigger-change-event

Feel free to re-open if this does not solve the problem

**Comment by sqlgreen** [comment]
Why is the validation message "minSelectionRequired"? I am having this issue as well, can't seem to work out how to get the correct text. Ideas welcome.

**Comment by kevinchappell** [comment]
@sqlgreen are you triggering the changes programmatically? Also its saying `minSelectionRequired` because the term is not added to the language files.

**Comment by sqlgreen** [comment]
Rather than hijacking this thread I have opened an issue [843](https://github.com/kevinchappell/formBuilder/issues/843)
