### ISSUE TITLE
Best practice to load data into rendered form

### ISSUE THREAD

**Issue by JohanM87** [kevinchappell/formBuilder#770]
Can someone please tell me what is the best way to load data from JSON into a rendered form?

In some JSON-schemaform setups this is called a 'model' (see for example the form at the homepage of  http://schemaform.io/ ).

**Comment by ppatilpravin** [comment]
I am not able to load data in rendered form please help

**Comment by BrianHVB** [comment]
I'm not sure I understand your question @JohanM87  and @ppatilpravin.

When you save a form as JSON, you get data that looks like this:
```json
[
{"type":"checkbox-group","label":"Checkbox Group (multiple allowed)","name":"checkbox-group-1538420974819","values":[{"label":"Bacon","value":"bacon"},
{"label":"Eggs","value":"eggs","selected":true}]},{"type":"date","label":"Date Field","className":"form-control","name":"date-1538421114160","value":"2020-10-03"},
...
]
```

If you save this data to a DB or other store, you can then use it to reload the form with the following:

```javascript
initialize() {
	this.formBuilder = this.$editor.formBuilder({
		formData: myFormData,
                // other options...
	});
}
```
