### ISSUE TITLE
Sticky toolbox broken after window resize

### ISSUE THREAD

**Issue by mgendre** [kevinchappell/formBuilder#771]
### Description:
The sticky toolbox should stay sticked to the right of the screen even after a window resize.

When the window is resized, the sticky toolbox keep the old horizontal position. So when you scroll, the toolbox comes over the form or go outside the displayed web page.

### Environment Details:

 - formBuilder Version: 2.9.8
 - Browser: IE11, Firefox, Chrome
 - OS: Linux + Windows

### Expected Behavior
The toolbox should stick to the wight of the window

### Actual Behavior
The toolbox covers the form or go outside the visible part of the web page

### Steps to Reproduce
Create a big form that requires the toolbox to scroll.
Scroll in the page, the toolbox go in sticky mode.
Now resize the browser, make it bigger.
Scroll to the top of the form then scroll to bottom.
The toolbox is over the form.

You can test that on the demo page.

### Screenshot - *(optional)*
![2018-07-02 10_56_02-jquery formbuilder _ drag drop form creation](https://user-images.githubusercontent.com/11831166/42154683-b1fa5104-7de6-11e8-86f0-72c9a1f1db74.png)

**Comment by kevinchappell** [comment]
This is now fixed in 2.10.0
