### ISSUE TITLE
No name field for header type

### ISSUE THREAD

**Issue by scrlt-speedster** [kevinchappell/formBuilder#773]
### Description:

Can you please provide a name attribute for **header** field in form builder like there is for all other fields.

**Comment by kevinchappell** [comment]
This is possible, but the name attribute was intentionally excluded for non-input fields. What is the use case? Is this just for formData or is it meant to be rendered? The name attribute is not meant to be used as a uuid, I would prefer adding a non-rendered uuid property to field data than adding a name attribute to a header tag.
