### ISSUE TITLE
How to add button in edit box for my custom control

### ISSUE THREAD

**Issue by yushko2015** [kevinchappell/formBuilder#775]
I create my custom control "Logo" and want add button upload image in edit box of created control.
How can I make it?
Control I create as described here https://formbuilder.readthedocs.io/en/latest/formBuilder/control-plugins/
Code my custom control plugin:
![image](https://user-images.githubusercontent.com/14107049/42724851-8d55746e-8782-11e8-9ba9-ef0533bf15fe.png)

**Comment by kevinchappell** [comment]
You should be able to include the Add button in the build method, but the second argument of `markup` takes an object for attributes, not an array.

Could you create a codesandbox or codepen with your code? It will be easier to see where your'e stuck.

**Comment by kevinchappell** [comment]
I'm not sure I understand what youre trying to accomplish. I forked your codepen and added a button but I doubt thats what you need. https://codepen.io/kevinchappell/pen/WaxZmr?editors=0010

I would have a look at the file.fineuploader control- it may have what you need. https://github.com/kevinchappell/formBuilder/blob/master/src/js/control/file.fineuploader.js
