### ISSUE TITLE
Element label fields

### ISSUE THREAD

**Issue by worldtutorials** [kevinchappell/formBuilder#779]
### Description:
When a user is editing an element, they can press enter to go to the next line in the 'label' field. This makes things look a little wonky and may confuse our clients.

### Fix
To combat this, in the javascript of the page using the form builder, I added some 'typeUserAttrs' and edited each elements label field by adding a maxlength to it. This seems to fix the problem, but moves the label field to the bottom of the edit element panel.
`typeUserAttrs: {
                text: {
                    label: {
                        maxlength: '100'
                    }
                }, .......`
I had to do this for every element that has a label field.
### Extra
This problem isn't urgent as I have fixed it, but I just though I would let you guys know.

**Comment by wolfej1994** [comment]
I wouldn't really call it a fix, more of a work-around as I didn't really want to add a length restriction to certain fields.
