### ISSUE TITLE
Single checkbox

### ISSUE THREAD

**Issue by eventrac** [kevinchappell/formBuilder#783]
I notice that there is no single checkbox field, instead a checkbox group.  Is the "way" to use a checkbox group and only add one option?

I find myself wanting to use a single checkbox much more frequently than a checkbox group.

I can see from the screenshot on github, there used to be a single checkbox.  Was this removed?

Thanks!

**Comment by kevinchappell** [comment]
Yes that's correct. By default Checkbox Group adds 1 checkbox. This label could maybe be updated to "Checkbox/Group" to reduce confusion, wdyt?
