### ISSUE TITLE
Capturing the user inputs from rendered form in angular 6

### ISSUE THREAD

**Issue by ppatilpravin** [kevinchappell/formBuilder#785]
### Description:I have installed formBuilder in my angular 6 project,I am able to create and render the form. Could you help me to read the user inputs
Tried this: https://jsfiddle.net/kevinchappell/64b0tqov/2/ but no luck

### Environment Details:
Angular 6
 - formBuilder Version: 
 - Browser: 
 - OS:

**Comment by kevinchappell** [comment]
Can you try this branch? https://github.com/kevinchappell/formBuilder/tree/release/2.10.0

There is a new feature called `userData` that makes it easy to read the user entered data and hydrate the template with it.
https://github.com/kevinchappell/formBuilder/blob/release/2.10.0/docs/formRender/actions/userData.md

**Comment by kevinchappell** [comment]
There is a new feature called `userData` that comes with the latest version of formRender. You should be able to capture user inputs with that.
