### ISSUE TITLE
Checkbox and radio group options

### ISSUE THREAD

**Issue by saitoreeper** [kevinchappell/formBuilder#787]
### Description: I want to display only one input to be filled in for the options instead of the side by side. ie. if one is filled in that needs to be the label and the value instead of being filled in twice.

![capture](https://user-images.githubusercontent.com/40993991/43767096-76287fe2-9a34-11e8-97bd-27a281146304.PNG)

These 2 should only be 1 input and that input should be the label and value to be set.

I would appreciate any possible assistance 

Kind regards
saitoreeper

**Comment by kevinchappell** [comment]
These seems common enough that maybe it should be a feature. Here is how it can be done with `typeUserEvents` https://codepen.io/kevinchappell/pen/oMzKRo

**Comment by simon-hevs** [comment]
I did this with jquery

**Comment by simon-hevs** [comment]
I did this as follows:

        $('.form-wrap.form-builder').on('keyup', function () {
            var target = $(event.target);
            if (target.hasClass('option-label')) {
                $(target).parent().find('.option-value').val($(target).val());
            }
        });
