### ISSUE TITLE
Hi, this formbuilder is awesome and i really want to use it for my school project. My only problem is if i can get the html code instead of the json ???? 

### ISSUE THREAD

**Issue by hanaakhoj** [kevinchappell/formBuilder#788]
### Environment Details:

 - formBuilder Version: 
 - Browser: 
 - OS:

**Comment by kevinchappell** [comment]
You can by grabbing the `outerHTML` of the rendered form. formRender also has an `render` option you should be able to set to `false` which allow you to get the html from `formRender.markup`

**Comment by hanaakhoj** [comment]
Thank you so much for your reply! but i'm so new to this and i didn't understand you well... can please show me the code where i'll change the options?
Thank you again in advance

**Comment by hanaakhoj** [comment]
Thank you so much for your reply! but i'm so new to this and i didn't
understand you well... can please show me the code where i'll change the
options?
Thank you again in advance

**Comment by kevinchappell** [comment]
@hanaakhoj https://formbuilder.readthedocs.io/en/latest/formRender/options/render/
