### ISSUE TITLE
Uncaught TypeError: $(...).formRender is not a function with vuejs component

### ISSUE THREAD

**Issue by NeerT** [kevinchappell/formBuilder#789]
### Description:
I am trying to create a component in vuejs to use formBuilder and formRender functionalities, below is the code for my component.

<script>
  window.$ = window.jQuery = require('jquery');
  require('jquery-ui-sortable')
  require('formBuilder')
  require('formRender')
  import Vue from 'vue'

  export default {
    name : 'v-form-builder',
    template : '<div><div id="form-editor"></div><div id="form-render"></div></div>',
    props : {},
    mounted : function() {
      var self = this,
      fbOptions = {
        onSave:function () {
          $('#form-render').formRender({formData:fBuilder.formData});
          self.$emit('on-save', fBuilder.formData);
        },
        disabledActionButtons: ['data']
      },
      fBuilder = $('#form-editor').formBuilder(fbOptions);
    }
  }
</script>
### Environment Details:

 - formBuilder Version: 2.9.8
 - Browser: chrome
 - OS: Mac

### Expected Behavior
clicking on save button It should render the form created
### Actual Behavior
Uncaught TypeError: $(...).formRender is not a function
    at Object.onSave (formbuilder.vue?e3a5:16)
    at Object.click (form-builder.min.js?7463:6)
    at HTMLButtonElement.eval (form-builder.min.js?7463:6)

**Comment by kevinchappell** [comment]
is formRender included in the project? can you create a codesandbox demonstrating the problem? https://codesandbox.io/s/vue

**Comment by NeerT** [comment]
is formRender a separate npm package which needs to be installed? I have created an example here https://codesandbox.io/s/1vq1o0w35j

**Comment by kevinchappell** [comment]
ah, i see the problem. it's in the same npm package but is a separate bundle in that package. im marking this as a bug since this can be improved. For now here is a workaround

https://codesandbox.io/s/n91zzl4vpp

**Comment by NeerT** [comment]
I get this now, Thanks for your quick response!
