### ISSUE TITLE
Options remove all options when remove button clicked

### ISSUE THREAD

**Issue by saitoreeper** [kevinchappell/formBuilder#791]
### Description: Clicking on the remove button in options deletes all the options instead of just the one.
Currently how I do this is via Jquery but it doesn't work correctly. Is there an alternative, maybe javasript?

`            $("body").on("click", ".remove", function () {
                $(this).closest("div").remove();
            });`

![image](https://user-images.githubusercontent.com/9712629/43822577-cc80e2c2-9aec-11e8-92b5-67d16cfcb024.png)

**Comment by kevinchappell** [comment]
With the code you provided, the closest div would be the wrapper div for all options which is why they are all removed but you shouldn't need extra code to enable those buttons. 

Does the option remove button not work? It seems ok on https://formbuilder.online

**Comment by kevinchappell** [comment]
I was never able to reproduce this. Closing until it it is reported again.
