### ISSUE TITLE
Error : Property 'formBuilder' does not exist on type JQuery<HTMLElement>

### ISSUE THREAD

**Issue by Rehum02** [kevinchappell/formBuilder#792]
### Description:
Hello  Kevin.  I want to use your great formBuilder plugin in my project.  But Since 2 days, i am unable to implement it.

### My Environment Details:
Angular 6

### These are my code
**component.ts**

` ...
import * as JQuery from 'jquery';
import 'jqueryui/jquery-ui.min.js';

import 'formBuilder/dist/form-builder.min.js';
import 'formBuilder/dist/form-render.min.js';

@Component({
...
})
export class Component implements OnInit {
...
 $('#form_building').formBuilder(options);
}
`

**component.html**

` ... <div  id="form_building"></div>..`

### Expected Behavior

I have tried several things but nothings.  I still have the same error. 
**Property 'formBuilder' does not exist on type JQuery<HTMLElement>**

So, please How to do to fix this issue ?

**Comment by kevinchappell** [comment]
I have not seen this before but I am guessing it's a race condition. Can you create a codesandbox to demonstrate the problem?

**Comment by nikitanicholas106** [comment]
Hello Kevin,
I was trying to implement FormBuilder in Angular 8. When ever i run this project it shows "ReferenceError: $ is not defined" in the console. The following is my code:

**component.ts**
`import { Component, OnInit } from '@angular/core';
declare var $;

const formData = [
  {
    type: "header",
    subtype: "h1",
    label: "formBuilder in Angular"
  },
  {
    type: "paragraph",
    label:
      "This is a demonstration of formBuilder running in an AngularJS project."
  }
];


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent  implements OnInit {


  ngOnInit(){

    $(document.getElementById("fb-editor")).formBuilder({ formData });
  }

}
`

**html**

`<div id="fb-editor"></div>`

**PS:** I also tried replacing $ with 'jQuery' and it showed the error "Property 'formBuilder' does not exist on type 'JQuery<HTMLElement>'."

It will be great if you could help me fix this issue.

**Comment by MicheKOKORA** [comment]
Hello nikitanicholas106.

1 --------------------------
Install Jquery in your project via npm
`npm i jquery    `
[Ref:  https://www.npmjs.com/package/jquery]

2- --------------------------
Import JQuery In your project
`import * as $ from 'jquery;`

3- --------------------------
It seems that formBuilder is not available via npm. 
So, i urge you to insert the formBuilder files by appending them in the dom like this

```
ngAfterContentChecked() {  
      /* You can get more info about Angular LifeCycle here   https://angular.io/guide/lifecycle-hooks */
       /** Building Script path. We assume you downloaded the files and put them in your assets folder */
        let script_1 = '<script class="script_2"  src="assets/js/formBuilder/dist/form-builder.min.js"></script>' +  '<script class="script_2"  src="assets/js/formBuilder/dist/form-render.min.js"></script>';
   /** Check if files not already inserted in the dom, Otherwise, append them  */
        $('.script_2').length != 0 ? null : $('head').append(script_1);
 }
```

I think these lines above will help you.
Please, tell me if it works.

**Comment by nikitanicholas106** [comment]
Hello @MicheKOKORA ,
Actually https://www.npmjs.com/package/angular-formio this packed helped me in achieving the same requirement.
Thank you for the reply. :)

**Comment by MicheKOKORA** [comment]
@nikitanicholas106.
Don't mention it.
Glad to hear that you achieved your goal with other library. Lot of paths in IT.
👍

**Comment by praveen-vishnu-gp** [comment]
@nikitanicholas106 

> declare var $;

Thank you,, you saved my day
