### ISSUE TITLE
How can we make a fully-editable but static Header control on each new form

### ISSUE THREAD

**Issue by Annuther** [kevinchappell/formBuilder#794]
### Description:
Firstly Kevin, thanks for this v.v Cool plugin; Bigup from the UK!!! - ok,

Is it possible to ensure each new form that user begins with has a Header field at the top which is fully editable but :

1. MUST exist when saving, hence cannot be removed (sticky,static)
2. CANNOT be dragged to a new position; It MUST remain the first control on the form

Also is it possible to Add template forms to the bottom of the controls list so that users can optionally choose a pre-made template or choose to build their own in the standard way

Cheers...

### Environment Details: Bootstrap 3,  jQuery, LESS

 - formBuilder Version: Version: 2.9.8
 - Browser:  Version 68.0.3440.106 (Official Build) (32-bit)
 - OS: Win 8.1

**Comment by kevinchappell** [comment]
Sorry but there is no built-in way to ensure field positions are not moved. In the next release it is possible to lock all fields in place but a single field is difficult and would require a lot of extra logic.
