### ISSUE TITLE
Is there a way to fill form-builder page on load with data from a database?

### ISSUE THREAD

**Issue by Tichion** [kevinchappell/formBuilder#796]
I'm trying to create an update page for a form that's been created and saved to a database beforehand. Is there a way to fill the form-builder page with desired controls on load, without clicking on the menu?

**Comment by Annuther** [comment]
Hi,
I've asked a similar question yesterday (my username is **Annuther**) -  (just below your question) and i uploaded some files for Kevin to check out. Im still waiting for a response but i believe we need to use the defaultFields option. If you can load defaultFields via jquerys' **json.get()** method then you can assign a whole form to the editor on the click of a button after a page reload! However im getting errors when i try to load the file. My main language is PHP and i struggle with client-side stuff so if you can figure out my issue looking at the uploaded files it will offer a solution for you too hopefully.

Cheers

**Comment by simon-hevs** [comment]
Yes it is possible, I have been playing with an earlier post, working with the demo to save and load the rateYo too :)

I save the form layout and the data together, so that if the form is changed, I can still reload the old version and give the user the chance to update it (which could result in the loss of data).

function submitForm(frm) {
    var o = {};
    var a = $('#' + frm + ' .formholder :input').serializeArray();
    $.each(a, function () {
        if (o[this.name] !== undefined) {
            if (!o[this.name].push) {
                o[this.name] = [o[this.name]];
            }
            o[this.name].push(this.value || '');

        } else {
            o[this.name] = this.value || '';
        }
    });
    var b = $('#' + frm + ' .fb-starRating');
    $.each(b, function () {
        var item = $(this).find('span.jq-ry-container');
        var id = item.attr('id');
        var value = $(item).rateYo("rating");
        if (o[id] !== undefined) {
            if (!o[id].push) {
                o[id] = [o[id]];
            }
            o[id].push(value || '');

        } else {
            o[id] = value || '';
        }
    });

    var json = JSON.stringify(o);
    $('#' + frm + ' .formdata #Data').val(json);
    $('#' + frm + ' .formdata .companyid').val($('#CompanyId').val());
    var frmdata = $('#' + frm + ' .formdata :input').serializeArray();
    $.ajax({
        type: 'POST',
        url: '/FormBuilder/UpdateData',
        data: frmdata,
        success: function() {
            showFeedback('success', 'Updated');
        },
        error: function() {
            showFeedback('failure', 'Update Failed');
        }
    });

}

function loadForm(form, datain) {
    var frm = $('#' + form);
    var data = JSON.parse(datain);
    $.each(data, function (key, value) {
        var $ctrl = $('[name="' + key + '"]', frm);
        switch ($ctrl.attr("type")) {
            case "text":
                $ctrl.val(value);
                break;
            case "hidden":
                if (key.indexOf('autocomplete') > -1) {
                    $ctrl.val(value);
                    $ctrl.prev('input').val(value);
                } else {
                    $ctrl.val(value);
                }
                break;
            case "radio":
                $ctrl.each(function () {
                    if ($(this).attr('value') == value) {
                        $(this).attr("checked", value);
                    }
                });
                break;
            case "checkbox":
                for (var i = 0; i < value.length; i++) {
                    $ctrl.each(function () {

                        if ($(this).attr('value') == value[i]) {
                            $(this).attr("checked", value[i]);
                        }
                    });
                }
                break;
            case "datepicker":
                $ctrl.val(value);
                break;
            default:
                if (key.indexOf('starRating') > -1) {
                    $('#' + key).rateYo();
                    $('#' + key).rateYo("rating", value);
                    break;
                } else {
                    $ctrl.val(value);
                }
                
        }
    });
}

**Comment by Tichion** [comment]
@simon-hevs @Annuther thanks for the answer, I actually managed to achieve my problem with using the "Add Field" button. I realized it was already used for exactly what I wanted to(adding fields to builder), so I json serialized my data from the back end and fed it to the addField function in the .js file.

**Comment by kevinchappell** [comment]
@Tichion you can also use `setData` or initialize with the `formData` option.
