### ISSUE TITLE
Remove div's class "checkbox" on add or edit field checkbox.

### ISSUE THREAD

**Issue by pedromjustino** [kevinchappell/formBuilder#800]
### Description:

When I add a checkbox field the plugin creates the code:

```
<div class="checkbox">
<input type="checkbox"...
</div>
```

I want just remove the div's class because it is conflicted with my default css. Someone know how can I remove it?

### Environment Details:

 - formBuilder Version: 2.9.8
 - Browser: Google Chrome
 - OS: Windows 10

### Expected Behavior
```
<div>
<input type="checkbox"...
</div>
```

### Actual Behavior
```
<div class="checkbox">
<input type="checkbox"...
</div>
```

### Steps to Reproduce
Just add a checkbox field or add a new option for this field.

### Screenshot - *(optional)*
![image](https://user-images.githubusercontent.com/26795124/44465182-33d47e00-a5f3-11e8-82f9-4cf0e677b8b1.png)

**Comment by simon-hevs** [comment]
The easiest way to do this, is after rendering the form:

    $('div.checkbox').removeClass('checkbox');
