### ISSUE TITLE
Is possible create a Checkbox in treeview?

### ISSUE THREAD

**Issue by frba** [kevinchappell/formBuilder#801]
### Description: Hello Kevin, I would like to know if it is possible to create checkbox or radio in a treeview. I put an image to turn it more clear. Is there a way to create a form like this? Thanks in advance.

![image](https://user-images.githubusercontent.com/30867168/44469019-8d897800-a5f4-11e8-95f6-cbcdeaad4c03.png)

**Comment by frba** [comment]
Thanks for you help! I could create the treeview checkboxes. I added the jstree (www.jstree.com) in the form and it works. But, now the problem that I have is related to the Edit mode. 
Every time I click in the Edit button, the tree is reload. 
I tried to save the treeData in this.treeData, but it got lost everytime I click in the Edit button. One solution that I thought was to disable the Edit button because the tree edition is made by the js itself, but I don't know how to disable it.
The other problem is related about how can I save the modifications made in the tree by the user and put it together with all the info already in the form.

The javascript code that I'm using is this here:

// configure the class for runtime loading
if (!window.fbControls) window.fbControls = new Array();
window.fbControls.push(function (controlClass) {

  /**
   * Cascade Check class
   */
  class controlTreeCheck extends controlClass {

    configure() {
      this.js = './assets/js/jstree.min.js';
      this.css = './assets/css/style.css';
	  this.treeData = [{ "id" : "ajson1", "parent" : "#", "text" : "Simple root node" }];
    }

    /**
     * build a text DOM element, supporting other jquery text form-control's
     * @return DOM Element to be injected into the form.
     */

    build() {
      console.log('build');
      console.log(this.treeData);
      this.field = this.markup('span', null, {id: this.config.name});
	  return this.field;
    }

    onRender() {
	  var that = this;
      console.log('onRender');
	  console.log(that.treeData);
      $('#'+this.config.name).jstree({
    	"checkbox" : {"keep_selected_style" : false}, //Turn in blue when the checkbox is selected
    	"plugins" : [ "checkbox", "contextmenu","dnd", "html_data"], 

		  'core' : {
			"check_callback" : true,
			"themes" : { "stripes" : true, "icons":false, "dots" : false },
		    'data' : this.treeData
		  } 
  	  }).on("changed.jstree", function (e, data) {
		  that.treeData = [
		   { "id" : "ajson1", "parent" : "#", "text" : "Simple root node" },
		   { "id" : "ajson2", "parent" : "#", "text" : "Root node 2" },
		   { "id" : "ajson3", "parent" : "ajson2", "text" : "Child 1" },
		   { "id" : "ajson4", "parent" : "ajson2", "text" : "Child 2" },
    	  ];
		  console.log('onChange'); // newly selected
          console.log(that.treeData);
      });
    }
  }

  // register this control for the following types & text subtypes
  controlClass.register(['treeCheck'], controlTreeCheck);
  return controlTreeCheck;
});

![image](https://user-images.githubusercontent.com/30867168/44797228-aeb21180-ab7c-11e8-89c4-9f4016bb9af0.png)

**Comment by kevinchappell** [comment]
@frba 
For the first issue `onRender` will be called every time the preview is rendered. I see you are storing your `treeData` in your custom control's class but its being overwritten every time onRender is called.

for saving you'll likely need a custom handler for the jstree data.
