### ISSUE TITLE
Pull form data from DB via ajax along with other response data

### ISSUE THREAD

**Issue by petrakid** [kevinchappell/formBuilder#802]
I am building a "plugin" for a custom CMS I maintain.  This plugin will utilize formBuilder and formRender, using PHP and Mysql on an Apache server.

Part of the plugin's page collects general settings that an elevated user can access. The user can enable/disable the form, set the email recipient, a CC recipient and a BCC recipient, and also choose to save the rendered form's data in the database OR email it.  They can also give the form a name, etc.

The second half of the elevated user's page is the form itself which would utilize formBuilder and be pulled as json data from mysql.

Now here's the fun part:  all of this is loaded through ajax in the success: function() {} parameter.  Now it's no problem for me to load the initial settings data and fields or to initialize the formBuilder, but how do I load the saved form data -- json saved in the database -- to the same page and below the other fields in the same ajax function?  Is this even possible?

Is my best option here to create some way for the elevated user to perform another ajax call (say press a button) to load the formdata itself?

**Comment by petrakid** [comment]
Answered my own question - gettin' tired.  Just ran a new function in success: and initialized formBuilder there.

**Comment by kevinchappell** [comment]
@petrakid Glad you got it worked out. Another method for setting form fields would be to call [`setData()`](https://formbuilder.readthedocs.io/en/latest/formBuilder/actions/setData/) on your existing formBuilder instance in your success callback but if you need to modify options then a new instance is the best way to go.
