### ISSUE TITLE
Example of Adding Element

### ISSUE THREAD

**Issue by Askarov5** [kevinchappell/formBuilder#803]
### Description:
Hello Everyone. I want to add new Element(bootstrap 3 inputs with addons) with attributes, className and setting default className, Default Value of addons that can be changed with custom field in control. Could some one help me or give a full explanation of how to add this kind of fields
Thanks

example of Input with addon: 

### Environment Details:

 - formBuilder Version: 
 - Browser: 
 - OS: 

### Screenshot - *(optional)*
![as](https://user-images.githubusercontent.com/13361800/44672265-e93d7200-a9f5-11e8-8b96-216d1be98844.jpg)

**Comment by kevinchappell** [comment]
@Askarov5 formBuilder doesn't support this directly but it can be accomplished by creating a custom component or a combination of `typeUserEvents` and `fields` options. Have a look at the custom control architecture and mentioned options here: https://formbuilder.readthedocs.io/en/latest/formBuilder/controls/
