### ISSUE TITLE
JSON data structure for having "Other" option checked and text filled within checkbox group

### ISSUE THREAD

**Issue by flaiming** [kevinchappell/formBuilder#809]
I'm trying to re-open issue from issue https://github.com/kevinchappell/formBuilder/issues/578 . 
How exactly should JSON structure look like to check "Other" option and fill related text field when using checkbox group? I didn't find any solution in docs.

**Comment by kevinchappell** [comment]
There isnt a definition but you can achieve this using `typeUserEvents`
https://codepen.io/kevinchappell/pen/EdyvYz?editors=0010
