### ISSUE TITLE
How to save multiple values of an array with typeUserAttrs?

### ISSUE THREAD

**Issue by pussifeu** [kevinchappell/formBuilder#813]
Currently I am trying this:
typeUserAttrs: text: {
 className: {
   label: 'Class',
   options: {
      'red form-control': 'Red',
      'green form-control': 'Green',
      'blue form-control': 'Blue'
   },
   style: 'border: 1px solid red',
   multiple: "true"
 }
}
My question is: 
How to save multiple values of an array cause when i try to save, the plugin saved only the first element that i have selected ?

**Comment by kevinchappell** [comment]
This is a bug with the current release but it should be resolved in release/2.10.0 branch, can you test your settings against that branch?

**Comment by pussifeu** [comment]
This branch works fine with this feature, but it creates a new bug.
In my project, i use multi-paged and my goal is to save all data on this page.
When i use master branch, all data are saved and it works fine. 
But with release/2.10.0 branch, it always puts the values in the last page in each row of the formData.
Can you help me please to fix this issue?

Thank you.

**Comment by kevinchappell** [comment]
This is fixed in 2.10.0
