### ISSUE TITLE
formBuilder-injected-style

### ISSUE THREAD

**Issue by Annuther** [kevinchappell/formBuilder#815]
Hi,
is it possible for us to prevent the two **formBuilder-injected-style** from being added to the form page?

I created my own render function so my own css styles are styling the form but i just noticed two hefty css style definitions which are now needlessly injected into the page. When i delete them temporarily using Chrome Dev Tools it makes no difference to the presentation. how do you prevent these style sheets - please??

**Comment by kevinchappell** [comment]
something like this? https://formbuilder.readthedocs.io/en/latest/formBuilder/options/disableInjectedStyle/

**Comment by Annuther** [comment]
ahh ha - saw that  a while ago and forgot that it was used for just this reason ...duh!!!
Cheers thanks for that.
