### ISSUE TITLE
Have a lot of troubles with JSON

### ISSUE THREAD

**Issue by mrhili** [kevinchappell/formBuilder#816]
This JSON is not well rendered

Uncaught SyntaxError: Unexpected token d in JSON at position 123

"[{\"type\":\"header\",\"subtype\":\"h1\",\"label\":\"La premiere entrer de Pom a la classe\"},{\"type\":\"radio-group\",\"label\":\"<span id=\\\"docs-internal-guid-8f310963-7fff-1c5d-68f1-d553d6f159d9\\\"><span style=\\\"font-size: 14pt; font-family: Arial; color: rgb(0, 0, 0); background-color: transparent; font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;\\\">Qu est-ce qu il ya dans le cartable de Pom ?<\/span><\/span>\",\"name\":\"radio-group-1537457912347\",\"values\":[{\"label\":\"Des souris\",\"value\":\"option-1\"},{\"label\":\"Des crayons\",\"value\":\"option-2\"}]},{\"type\":\"radio-group\",\"label\":\"<span id=\\\"docs-internal-guid-3bb4f9bb-7fff-da37-c75f-0fbf0d7ee0af\\\"><span style=\\\"font-size: 14pt; font-family: Arial; color: rgb(0, 0, 0); background-color: transparent; font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;\\\">Est-ce que Pom est gentiment assis sur sa place ?<\/span><\/span>\",\"name\":\"place\",\"values\":[{\"label\":\"Oui tres gentiment\",\"value\":\"option-1\"},{\"label\":\"Non il fait des betises\",\"value\":\"option-2\"}]},{\"type\":\"radio-group\",\"label\":\"<span id=\\\"docs-internal-guid-ddb4b0ce-7fff-7d80-1b32-6fa8c74780d4\\\"><span style=\\\"font-size: 14pt; font-family: Arial; color: rgb(0, 0, 0); background-color: transparent; font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;\\\">Que lui fait la maitresse ?<\/span><\/span>\",\"name\":\"maitresse\",\"values\":[{\"label\":\"Un gros bisous\",\"value\":\"option-1\"},{\"label\":\"Une punition\",\"value\":\"option-2\"}]},{\"type\":\"radio-group\",\"label\":\"<span id=\\\"docs-internal-guid-33c80b9c-7fff-4c74-db24-17f1f5318b60\\\"><span style=\\\"font-size: 14pt; font-family: Arial; color: rgb(0, 0, 0); background-color: transparent; font-weight: 700; font-variant-numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;\\\">Qu est-ce qu on fait dans la classe?<\/span><\/span>\",\"name\":\"fait\",\"values\":[{\"label\":\"Des betises\",\"value\":\"option-1\"},{\"label\":\"Des devoirs\",\"value\":\"option-2\"}]},{\"type\":\"radio-group\",\"label\":\"<span style=\\\"color: rgb(0, 0, 0); font-family: Arial; font-size: 18.6667px; font-weight: 700; white-space: pre-wrap;\\\">Qui est Pom?<\/span>\",\"name\":\"radio-group-1537458146318\",\"values\":[{\"label\":\"Une maitresse\",\"value\":\"option-1\"},{\"label\":\"Un eleve\",\"value\":\"option-2\"}]}]"

**Comment by kevinchappell** [comment]
Looks like extra style information is being pasted into the field's label and it's not being stringified correctly. I will test with release/2.10.0 branch (there was some improvement to the label for handling html) and let you know what I find.

**Comment by kevinchappell** [comment]
There was a bug but release/2.10.0 has the fix now. See https://github.com/kevinchappell/formBuilder/commit/477f6fe220830cee87de61318c5d02edc1cbb951 for more info.

Will leave this ticket open until 2.10.0 is released.

**Comment by mrhili** [comment]
Thanks for all your work
