### ISSUE TITLE
Updated json on changes of particular events

### ISSUE THREAD

**Issue by samimaktar** [kevinchappell/formBuilder#817]
Thanks for the awsome plugin.... 
I have implemented a form and storing the json in a textarea on  the event like below
document.addEventListener('fieldAdded', function()
    {
      document.getElementById('data1').value = formBuilder.formData;
      
    });

now when i am editing the form if i remove one field or edit one filed or copy one field i am unable to get the event ...so what are those events or how to get the updated json so i can show it in the textarea after anything changes in the form without any clicks ..

Thanks in advance

**Comment by ss14620** [comment]
Hello can you please tell me how you have fix this?
