### ISSUE TITLE
Custom Autocomplete and TextArea(TinyMCE) can't be disabled

### ISSUE THREAD

**Issue by ralphmallari** [kevinchappell/formBuilder#818]
### Expected Behavior
As the description said, custom autocomplete and textarea can't be disabled in the function disabledFields. But in the controlOrder those 2 input just works fine. See the screenshot below

### Screenshot - *(optional)*
![form](https://user-images.githubusercontent.com/42198726/46051034-cecbf500-c169-11e8-98d0-77619487782c.png)
![codee](https://user-images.githubusercontent.com/42198726/46051096-194d7180-c16a-11e8-903e-c747d3f50965.png)

**Comment by kevinchappell** [comment]
Custom controls require a little extra configuration to be disabled. The built-in controls have their own registered types (`datatype`) but to make registering custom fields similar to extending existing fields, the `controlCustom` class will set a `datatype` with random hash:
```javascript
// generate a random key for datatype lookup when one is not set
lookup = field.datatype ? field.datatype : `${type}-${Math.floor((Math.random() * 9000) + 1000)}`;
```
So by adding `datatype` to your custom control configuration you'll have a non-random key you can use on the `disabledFields` options.

cool background btw :sunglasses:
