### ISSUE TITLE
 two dynamic selection properties in typeUserAttrs or custom field

### ISSUE THREAD

**Issue by filipeaugustosantos** [kevinchappell/formBuilder#820]
### Description:

I would like to know if it is possible and how to set to use two select type properties on an element.
In the case I want to use formbuilder to create a custom element where the user can parameterize some fields, more specifically, properties of an Ajax request, such as method, header and form.
That is, it would need some properties like select, twice in typeUserAttrs; if possible without the radio or checkbox.
Other options such as text or select property do not work.
Thank you

### Screenshot - *(optional)*
![capturar](https://user-images.githubusercontent.com/36250590/46119261-91567e80-c1e0-11e8-9464-f652befb7cba.PNG)

**Comment by kevinchappell** [comment]
`onAdd` is the way to go. With that you have access to the element and can call api methods to do practically anything with editor like getData, setData, add/remove options etc.

I think combining a custom control, `typeUserAttrs` and `typeUserEvents` should get you to where you need. Feel free to reopen if this doesn't solve it for you.
