### ISSUE TITLE
[Question] How to add additional class btn-lg in button?

### ISSUE THREAD

**Issue by dwikip** [kevinchappell/formBuilder#826]
### Description:
Hi
How to add additional class btn-lg in button? since when im trying to class add btn-lg in button it always removed

### Environment Details:

 - formBuilder Version: v2.9.8
 - Browser: Chrome
 - OS: Windows

### Expected Behavior
Im expecting we can add class btn-lg for button

### Actual Behavior
when trying to add btn-lg as class for button, it removed

### Steps to Reproduce
Drag and drop button, klik edit, in Class input field put btn btn-default btn-lg, move to another input field, the Class input filed now become btn btn-default, no btn-lg

**Comment by osthafen** [comment]
Same problem here.
You can reproduce the bug in the demo at https://formbuilder.online/ :

1. Drag and drop button
2. click edit
3. add btn-lg in class field
4. click in any other input field
5. sometimes the class names get reordered then after another click in an input field the new class name gets removed
