### ISSUE TITLE
one more sortable-options attribute for check-box.

### ISSUE THREAD

**Issue by junathakuri** [kevinchappell/formBuilder#827]
Hey Kevin, Thank you so much for formBuilder. 
I was trying to add new sortable-options attribute for check-box field along with the existing one in one of my project. Is there any way to do so..?
Screen shot attached. I am trying to have new Options(FR).

<img width="601" alt="optionfr" src="https://user-images.githubusercontent.com/43784126/46351880-75127180-c626-11e8-918b-983350d12010.png">

**Comment by kevinchappell** [comment]
@junathakuri is the goal to have different languages for the label? Languages can be managed in different instances using the i18n option. 
https://formbuilder.readthedocs.io/en/latest/formBuilder/demos/translation/
https://formbuilder.readthedocs.io/en/latest/formBuilder/options/i18n/

If you really need an extra attribute you could add it using the `typeUserAttrs` option: https://formbuilder.readthedocs.io/en/latest/formBuilder/options/typeUserAttrs/
