### ISSUE TITLE
Disallow changing field name (via defaultFields), and provide list of allowed fields

### ISSUE THREAD

**Issue by smark111** [kevinchappell/formBuilder#83]
Hi,

Thanks again for implementing the good plugin. 

I was looking for documentation for following. Can you please let me know if following possible,

1) Is there any option to not allow user to change form "field_name". First time when creating the fields, yes we need the field name (even autogenerated field name is fine too). 

But once we start saving data into database, using the field name, and if user changing field name, it's making it tough to match the field name with data that was already saved with earlier form field name. Possible when re displaying fields (via defaultFields input element), can we can have option to not allow user to change field name.

2) For the allowed list of form fields that can be added, we want to avoid having "File Input" and "Hidden Field". Is there any option to not have these fields on right side of allowed fields.

Thanks

**Comment by kevinchappell** [comment]
@smark111 there could be a locking mechanism added but I think this functionality should be handled by the back-end since formBuilder runs entirely client side there is not way to truly prevent changing the name.


For item 2 the fields can be removed with css, javascript or a combination of both.

**CSS**:
```
.frmb-control .icon-file-input, .frmb-control .icon-hidden-input{
    display:none;
}
```

**Javascript**:
formBuilder will be getting custom events soon like `afterInitialize` (or something like that) that you could hook into to remove the field type but for now you can do it manually like so.
```
var template = document.getElementById('form-builder-template');
$(template).formBuilder();
$('li.icon-file-input, li.icon-hidden-input', '.frmb-control').remove();
```

The above is untested so let me know if that doesn't work for you.

**Comment by smark111** [comment]
Thanks Kevin for the quick response. I was thinking of following approach for disabling name change,

1) As part of values being sent to "defaultFields" input element, for each element have additional attribute, "namefixed:true"

2) At run time when providing option to edit form fields, if (namefixed == true) then make the name field either read only or hide the field.

On the server side, when XML is received if a field with earlier name is missing, then we we can prompt the user as earlier created name field is missing, and if confirm if it was their intention to remove the name field.

Since the intent of using this plugin is to keep it light weight, and not track add/delete actions using another background process, the only time server knows something changed was when XML comes back to server on clicking "save form" button. On server side, the only way it knows something changed is by processing the XML file.

Please do let me know if i am missing another approach being used, for tracking which form fields elements were added/removed, since at the end the goal is accept data from user via the form and save info to database, and keep displaying the same data for same fields. 

A novice user would not know that they should not change the name field, once they have started using the form. Any hints will be very helpful.

Thanks

**Comment by kevinchappell** [comment]
I think this might be something we can pass as an editor setting. Future versions will have `<form-settings>` in XML and `"form-settings"` in JSON that contain various settings for the builder. If we are going to do this for `name` attribute we should make it scale-able to other attributes as well. The below format can be used to pass options in addition to name fixing. Here it is fixing the `name` attribute:
```
{
  formSettings: {
    attrs: {
      name: {
        fixed: true
      }
    }
  }
}
```

This structure should give us an extensible base to add other options as needed eg. whether to hide or show the field and even custom validators.
```
{
  formSettings: {
    attrs: {
      name: {
        fixed: true,
        visible: false
      },
      className: {
        validator: validators.hyphenCase
      }
    }
  }
}
```

// then later
```
validators.hyphenCase = (str) => {
  str = str.replace(/[^\w\s\-]/gi, '');
  str = str.replace(/([A-Z])/g, function($1) {
    return '-' + $1.toLowerCase();
  });

  return str.replace(/\s/g, '-').replace(/^-+/g, '');
};
```

In the example above `hyphenCase` would be called when user tried to save (or type) a className and would change their crazy value of "'#*&n7_7-7*&%#'" to "n7_7-7" which- while still not pretty, is perfectly valid.

On the backend the server would process the xml anyways and if its for an existing form there is data to compared it to. Once parsed it should be a matter not allowing the name attribute to be overwritten.

**Comment by surajprajapati** [comment]
Hi kevinchappell,
How can i used  the full flow, functionality of all features added at the time of creating form field dynamically, that are full fill at the time of client sit(at the time submitting the form)
Actually i want to know how can i handle all the features like Required field, max length to validate,
I thanks in advance please let me know.

**Comment by salvagit** [comment]
Hi Kevin.
how i can hook to add field action ?
thanks! great lib!

**Comment by mudassarhanifchohan** [comment]
Hi Kevin,

I want to add Dynamic values in autocomplete Text field but unable to write any function or other mechanism will you please guide me to customize it.

**Comment by bhavna11patidar** [comment]
Hi Kevin,
I want to remove autocomplete and hidden input... How can I do so???

**Comment by kevinchappell** [comment]
@bhavna11patidar https://formbuilder.readthedocs.io/en/latest/formBuilder/options/disableFields/

@mudassarhanifchohan please create a new issue

@salvagit `typeUserEvents` https://formbuilder.readthedocs.io/en/latest/formBuilder/options/typeUserEvents/

**Comment by bhavna11patidar** [comment]
Thank you so Much

**Comment by bhavna11patidar** [comment]
Hello kelvin,
How Can I add More Input fields For drag and drop option like Name, Mobile No....

**Comment by bhavna11patidar** [comment]
Hello kelvin, 
I just want to call a function after field removal ....
how can i do that..........

**Comment by rahulmahadik** [comment]
@bhavna11patidar 

Go to **form-builder.min.js** 

Search for `A.prototype.removeField = function (A) {`

in your `form-builder.min.js` file 

You can call your function from this function, Where this function calls on field removal event

Hope this will help you. :)

**Comment by bhavna11patidar** [comment]
Hello Thanks For Answer I m not getting where to call Function
Exactly.......
I jst Want To call below Function:-
$('body').on('click','.delete-confirm',function(){
  alert("dasd");
  $('.current_lobook_columns').html("");
      fdata=formBuilder.formData;
      var d=JSON.parse(fdata);
     // formBuilder.actions.removeField();
      console.log(d);
});

**Comment by bhavna11patidar** [comment]
@rahulmahadik 
Hello Thanks For Answer I m not getting where to call Function
Exactly.......
I jst Want To call below Function:-
$('body').on('click','.delete-confirm',function(){
  alert("dasd");
  $('.current_lobook_columns').html("");
      fdata=formBuilder.formData;
      var d=JSON.parse(fdata);
     // formBuilder.actions.removeField();
      console.log(d);
});

**Comment by bhavna11patidar** [comment]
@rahulmahadik  
I jst want To call below function after removal of field from from....

document.addEventListener('fieldRemoved', function(){
       	alert(4567);
});

**Comment by bhavna11patidar** [comment]
hello Kevin,
How can I add required on label field

**Comment by abhilashlegend** [comment]
Hi kelvin,
I just want to call a function after field removal 
how can i do that ?

**Comment by mrityunjay38** [comment]
Hi

I am trying to disable editing on some render formData.

formBuilder = fbEditor.formBuilder(options);

options = {
defaultFields : [//data]
}

Now, the issue that I am facing is that currently, there's no feature available to disable editing.
So, I tried this --

`<li id="frmb-1573821267932-fld-1"/>`
`console.log($('li[id^="frmb"][id$="fld-1"]').length);`

I am trying to select those <li> tags by their id pattern but for some unknown reason I am not able to select them.

But I tried to replicate this by creating elements locally under document.ready and it is able to find them by starting and ending pattern.

Please suggest a way to disable editing of particular rendered formData.
