### ISSUE TITLE
[Question] How can I seperate the controls into different groups

### ISSUE THREAD

**Issue by peteryangthinkgeo** [kevinchappell/formBuilder#830]
Hi Teams,

I am a fresh man on fromBuilder. In my application, there will be a little more controls, if there is a way to separate the controls into the different groups like below shows:
<img width="265" alt="groups" src="https://user-images.githubusercontent.com/16588029/46568340-addb7f00-c975-11e8-962e-3fa369d544bf.PNG">

The "Common Fields" includes the controls like "Button", "Date", etc. And there are some other groups like "Layout" and "HTML Elements".

Looking for your forward!

Thanks,
Peter

**Comment by peteryangthinkgeo** [comment]
- [ ]

**Comment by kevinchappell** [comment]
There is no built-in way of doing this with formBuilder however certain it could be done with some extra code. Leaving this open in case someone wants to contribute that code.

**Comment by peteryangthinkgeo** [comment]
Thanks for the reply. I will close this thread.
