### ISSUE TITLE
Error while lauching gulp task

### ISSUE THREAD

**Issue by Skeldrarg** [kevinchappell/formBuilder#831]
### Description:
Hello, I started recently to use formBuilder and when I try to launch the gulp task "default", it makes the error in screenshot.
It seems coming from the "import '../sass/form-builder.scss' " in form-builder.js, but I don't know how to correct this error. 

### Environment Details:

 - formBuilder Version: 2.9.8
 - Node.js : 8.12.0
 - Browser: no browser used yet
 - OS: windows 10

### Screenshot - *(optional)*
![image](https://user-images.githubusercontent.com/22833622/46667286-7c5af180-cbc9-11e8-9765-a9ec8a024b24.png)

**Comment by el-Knix** [comment]
Been getting the same error, tried everything but i cannot get the gulp task to work

**Comment by kevinchappell** [comment]
This is resolved in 2.10.0
