### ISSUE TITLE
In the latest update youhave just ru-Ru.lang that get updated only no english noelse 

### ISSUE THREAD

**Issue by mrhili** [kevinchappell/formBuilder#833]

**Comment by kevinchappell** [comment]
@mrhili Can you explain more? Do you mean the current master branch, current npm release or @next release?

**Comment by mrhili** [comment]
That link is the probleme

https://formbuilder.online/assets/lang/en_US.lang

Change the language to  ru_Ru  and everything will work fine

**Comment by kevinchappell** [comment]
The link to the files should be: https://formbuilder.online/assets/lang/ru-RU.lang
