### ISSUE TITLE
On click save button doesnt do nothing

### ISSUE THREAD

**Issue by ArditKurti** [kevinchappell/formBuilder#834]
### Description:

Hi everyone. When i click on save it doesn't do anything.

Here is the code.

var options = {
         editOnAdd: true,
         defaultFields: [{
             className: "form-control",
             label: "Titolo del Campionamento",
             placeholder: "Titolo del Campionamento",
             name: "title",
             required: true,
             type: "text"
         }],
         controlOrder: [
             'text',
             'textarea'
         ],
        actionButtons: [{
            id: 'smile',
            className: 'btn btn-success form-builder-save',
            label: 'Save',
            type: 'button'
        }]
     };
    var formBuilder =  $("#formBuilder").formBuilder(options);

$("#formBuilder").find('.save-template').on('click' ,function() {
        var json = formBuilder.actions.getData('json', true);
        console.log(json);
        $.ajax({
            type: 'POST',
            url: '/admin/save',
            data: {json: json},
            success: function () {
                alert('success')
            },
            error: function () {
                alert('fail');
            }
        });
    });

### Environment Details:

 - formBuilder Version: Latest
 - Browser: Chrome

**Comment by ArditKurti** [comment]
@kevinchappell

**Comment by kevinchappell** [comment]
AFAIK there is no `.save-template`. Can you use the `onSave` option instead?

**Comment by ArditKurti** [comment]
.save-template was the save button class. 
Anyway onSave is not on the documentation or i cant find it.
Can u help me with an example .
Thanks @kevinchappell

**Comment by kevinchappell** [comment]
I see you're right. Current version does not have onSave in the docs. I'll send example when I get to a computer.

**Comment by ArditKurti** [comment]
ok thanks

**Comment by ArditKurti** [comment]
@kevinchappell pls provide the onSave option. Thanks in advance

**Comment by kevinchappell** [comment]
`onSave` is now in the docs https://formbuilder.readthedocs.io/en/latest/formBuilder/options/onSave/
