### ISSUE TITLE
button group 

### ISSUE THREAD

**Issue by alpastar** [kevinchappell/formBuilder#837]
- Browser:  chrome-65
 - OS:  windows-7
jquery3, bootstrap4 

i am newbie to formBuilder . but 
i  want to  make a  (horizontal) button-group , 
( or want to  layout button horizontally) 
what  should be done ?

define button-group in fields  make a element in  formbuilder canvas .
but in rendering , error occurs 
.
just to make a  custom-control  is  somewhat cumbersome,
is there any  other good  way ?

 [code-sample] 
 var a_field_custom = [{               //  define new  control
      label: 'button-group' ,
      attrs: {
        type: 'buttonGroup'
      },
      icon: ''
   }];

  var o_template = {
     buttonGroup : function(to_fld_data) {
      return {
        field: `<div class="btn-group" role="group" aria-label="Basic example" id="${to_fld_data}"> 
                 <button type="button" class="btn btn-secondary" id="btn_yes">YES</button>
                 <button type="button" class="btn btn-secondary" id="btn_no">NO</button>
                 </div>`         ,  
        onRender: function() {
           $(document.getElementById(to_fld_data.name)).html() ;
        }
      };
   }
 };

[error-msg] 
form-render.min.js:6 Uncaught Error: Invalid control type. 
(Type: buttonGroup, Subtype: undefined). 
Please ensure you have registered it, and imported it correctly.

**Comment by simon-hevs** [comment]
Just check the inline checkbox in the editor

**Comment by kevinchappell** [comment]
@alpastar formBuilder doesn;t have a built-in butto group but you can make one using custom control or as @simon-hevs pointed out inline checkbox and modify on render.
