### ISSUE TITLE
Save to a mysql database

### ISSUE THREAD

**Issue by 11JoseMarcos11** [kevinchappell/formBuilder#838]
### Description:

Hello everyone.

I would like to know if it is possible to save the dragged fields in a MYSQL database.
Sorry for my English. I'm from Brazil and I'm using Google Translate.

Thank you

### Environment Details:
Save to a mysql database
 - formBuilder Version: 
 - Browser: Chrome
 - OS:  Linux

### Expected Behavior
Functional
### Actual Behavior
Perfect
### Steps to Reproduce
Save to a mysql database

**Comment by kevinchappell** [comment]
olá @11JoseMarcos11 , o formBuilder é apenas uma ferramento do frontend que exporta dados em XML ou JSON. A maneira vai guardar os seus dados mesmo depende do stack e framework do seu projeto.

https://scotch.io/tutorials/working-with-json-in-mysql

english:
formBuilder is a frontend tool only, saving to mysql is considered backend work and therfore outside the scope of formBuilder. How you save your data depends on your stack and backend framework (if you have one). The above link may help with better understanding working with JSON and MySQL
