### ISSUE TITLE
How do I extend the components of tables like this? 

### ISSUE THREAD

**Issue by MissNanLan** [kevinchappell/formBuilder#839]
### Environment Details:

 - formBuilder Version: 
 - Browser: 
 - OS: 

### Screenshot - *(optional)*
![image](https://user-images.githubusercontent.com/22790863/47285741-9e6b5f80-d61e-11e8-864a-a55eb316151f.png)

**Comment by kevinchappell** [comment]
I think this is a little outside the scope of formBuilder but if you wanted to use formBuilder for this you could do it by creating a custom control. https://formbuilder.readthedocs.io/en/latest/formBuilder/controls/
