### ISSUE TITLE
Where are the 2.10 dist files?

### ISSUE THREAD

**Issue by eradin** [kevinchappell/formBuilder#847]
Previously there were min files for the js.  I don't see that.

Thank you.

**Comment by eradin** [comment]
Didn't know that.  I grabbed them from npm and I see the min files.  Previous versions also had a control_plugin folder. I am not using those but if anybody is, they are missing in the dist folder.

**Comment by kevinchappell** [comment]
Oh thanks, those should be included. Will release 2.10.1 that includes them

**Comment by kevinchappell** [comment]
ah youre right. I need to add it to `npm.files` for for control_plugins to be published. reopening until resolved

**Comment by kevinchappell** [comment]
This is fixed in 2.10.4 
![image](https://user-images.githubusercontent.com/1457540/48085674-c676c900-e1af-11e8-80d7-2c11943efc45.png)
