### ISSUE TITLE
How to create field option with typeUserAttrs

### ISSUE THREAD

**Issue by Skeldrarg** [kevinchappell/formBuilder#848]
### Description:
I try to create a field option for a custom control, but it doesn't work.
### Environment Details:

 - formBuilder Version: 2.10.0
 - Browser: Chrome
 - OS:  windows 10

### Expected Behavior
A field like the field in screenshot.

### Actual Behavior
The attribut isn't displayed

### Screenshot - *(optional)*
![optionsfield](https://user-images.githubusercontent.com/22833622/47863459-9a49f980-ddf7-11e8-932e-4d6f3d1fd279.png)

**Comment by kevinchappell** [comment]
Can you share your code for the custom control? Options cannot be created with `typeUserAttrs` but can be created using a custom control class.

**Comment by Fenix-ops** [comment]
> Can you share your code for the custom control? Options cannot be created with `typeUserAttrs` but can be created using a custom control class.
my class is below what do i do here to add options in it
if (!window.fbControls) window.fbControls = [];
window.fbControls.push(function (controlClass) {

    /**
     * Text input class
     * Output a <input type="text" ... /> form element
     */
    class controlSubCategorySelect extends controlClass {
        /**
         * definition
         * @return {Object} select control definition
         */
        static get definition() {
            return {

                icon: '<i class="fa fa-list" aria-hidden="true"></i>',
                i18n: {
                    default: 'SubCategory'
                }
            }
        };


        /**
         * build a select DOM element, supporting other jquery text form-control's
         * @return {Object} DOM Element to be injected into the form.
         */
        build() {
            return this.markup('span', null, { id: this.config.name });
        }




        /**
         * onRender callback
         */
        onRender() {
            // Set userData if available
            console.log($('#' + this.config.name));
            $('#' + this.config.name).html('<h1>Subcateogry</h1>');
        }
    }
    // register this control for the following types & text subtypes
    controlClass.register('SubCategory', controlSubCategorySelect);
    return controlSubCategorySelect;
});

**Comment by kashif-ali-khan** [comment]
> > Can you share your code for the custom control? Options cannot be created with `typeUserAttrs` but can be created using a custom control class.
> > @kevinchappell
> > my class is below what do i do here to add options in it
> > if (!window.fbControls) window.fbControls = [];
> > window.fbControls.push(function (controlClass) {
> 
> ```
> /**
>  * Text input class
>  * Output a <input type="text" ... /> form element
>  */
> class controlSubCategorySelect extends controlClass {
>     /**
>      * definition
>      * @return {Object} select control definition
>      */
>     static get definition() {
>         return {
> 
>             icon: '<i class="fa fa-list" aria-hidden="true"></i>',
>             i18n: {
>                 default: 'SubCategory'
>             }
>         }
>     };
> 
> 
>     /**
>      * build a select DOM element, supporting other jquery text form-control's
>      * @return {Object} DOM Element to be injected into the form.
>      */
>     build() {
>         return this.markup('span', null, { id: this.config.name });
>     }
> 
> 
> 
> 
>     /**
>      * onRender callback
>      */
>     onRender() {
>         // Set userData if available
>         console.log($('#' + this.config.name));
>         $('#' + this.config.name).html('<h1>Subcateogry</h1>');
>     }
> }
> // register this control for the following types & text subtypes
> controlClass.register('SubCategory', controlSubCategorySelect);
> return controlSubCategorySelect;
> ```
> 
> });

I also want to achieve, something like this,
please let me know if you found solution for same
Thanks

**Comment by kashif-ali-khan** [comment]
> Can you share your code for the custom control? Options cannot be created with `typeUserAttrs` but can be created using a custom control class.

Can i have a example of, how can i Options in cutom control, using custom control class

**Comment by NoobLTv** [comment]
Any update?
