### ISSUE TITLE
remove Injected Style

### ISSUE THREAD

**Issue by faiyip** [kevinchappell/formBuilder#862]
hi,
   Is there a way to remove the injected style from the formRender ?
  I tried the option { disableInjectedStyle: 1 }, but that didn't remove the injected style, rendered-form.  I am using the version 2.10.9
  Or using a custom css file would be great too.

Thanks in advance.
Fai

**Comment by simon-hevs** [comment]
I think this may only work on the form builder side. However you can remove it from render with a single line of jQuery if you really want to:

    $('.formBuilder-injected-style').remove();

**Comment by Jojoshua** [comment]
Try
disableInjectedStyle: true
