### ISSUE TITLE
TypeError: Invalid attempt to destructure non-iterable instance form-render.min.js

### ISSUE THREAD

**Issue by greatsaltlake** [kevinchappell/formBuilder#867]
This error appears in the browser console, the form still renders. Example here
https://codepen.io/kevinchappell/pen/vGBWxO

**Comment by kevinchappell** [comment]
@e12e youre right. I had considered deploying tagged versions to S3 or similar but worried that in the long run it might get costly for me as I don't know what data charges would be involved. Better I think would be to have it hosted on [cdnjs](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md) but I havent gone through the steps yet.
