### ISSUE TITLE
Builder Request: show custom attribute (along with Label) in the field header

### ISSUE THREAD

**Issue by nwoolls** [kevinchappell/formBuilder#868]
### Description:

We are looking for a supported way to have a custom header value shown for fields in the builder. Specifically we'd like to show the value of another attribute (not Label) along with the Label value, and have that update as the field is edited.

### Environment Details:

 - formBuilder Version: Any
 - Browser: Chrome
 - OS: macOS

### Expected Behavior

We are looking for a supported way to have a custom header value shown for fields in the builder. I am referring to the area where the Label is shown, followed by an asterisk if the field requires a value. Specifically, we would like to show both the value for Label as well as the value for another attribute in the header - and have that header update properly when either the Label attribute or the other attribute is modified in the field editor.

Using older formBuilder versions we did this via CSS selectors and DOM manipulation but this has proven fragile from release-to-release of formBuilder and made it difficult to move to newer versions. We'd like to get on a supported path for this.

If this is not supported is it a desired feature if we were to create a PR? e.g. being able to specify a template for the header value along with the formBuilder options.

### Actual Behavior

No supported way (?) to have custom data from a field attribute (along with / aside from Label) in the field header.

### Steps to Reproduce

Try to have a field's attribute shown in the header (along with the Label attribute value).

**Comment by Jojoshua** [comment]
What is the use case for this?

**Comment by lucasnetau** [comment]
This can be achieved with a Custom control plugin (define additional attributes in defaultAttrs and then construct your label as required. You could also possibly do it with a label template
