### ISSUE TITLE
Uncaught TypeError: a.cloneNode is not a function

### ISSUE THREAD

**Issue by misterharshith** [kevinchappell/formBuilder#877]
### Description: 
Hi, Im getting fallowing error **"Uncaught TypeError: a.cloneNode is not a function"** while clicking on add new page in Tabbed/Multi-Page Forms. As i'm struck in between the project can you please help me with resolving cloneNode Error.

Codepen Link: https://codepen.io/kevinchappell/pen/BKYPRp

### Environment Details:

 - formBuilder Version: **v3.1.2**
 - Browser: Chrome v70.0.3538.110
 - OS: Mac High Sierra v10.13.3

### Screenshot - *(optional)*
![clonenode error](https://user-images.githubusercontent.com/16413182/49211316-4fff6c80-f3e5-11e8-92eb-59b9209a25a0.png)

**Comment by mpereira13** [comment]
pls, check if it's work for you.

jQuery($ => {
        var $tabUL = $('#tabs'),
            $formPages = $('#form-builder-pages'),
            $newPage = $('#new-page'),
            $newPageLink = $('#add-page-tab'),
            countFB = 1,
            fbEditor = [$('#page-1').formBuilder()];

        $newPageLink.click(function () {
            countFB++;
            $newPageLink.before(`<li><a href="#page-${countFB}">Page ${countFB}</a></li>`);
            $newPage.before(`<div id="page-${countFB}" class="fb-editor"></div>`)
            $formPages.tabs('refresh');
            var x = countFB - 1;
            $formPages.tabs('option', 'active', x);
            fbEditor.push($(`#page-${countFB}`).formBuilder());
        });

        $formPages.tabs({
            beforeActivate: function (event, ui) {
                if (ui.newPanel.selector === "#new-page") {
                    return false;
                }
            }
        });
    });

**Comment by lucasnetau** [comment]
Jumping on an old ticket but the codePen uses arrow functions which don't have a binding to "this", yet in the code it does a $(this).clone() which for Chrome returns Window which you cannot clone.

So if you change 

`() => {`

to 

`function(event) {`

it will work.

**Comment by Jojoshua** [comment]
Feel free to reopen if this is still an issue.
