### ISSUE TITLE
typeUserAttrs: some Values got broken since an earlier Version

### ISSUE THREAD

**Issue by ThomasWiens** [kevinchappell/formBuilder#878]
### Description:

i was using an earlier version of formBuilder from around the end of 2017/ start of 2018. In there i used the an object to inject values via typeUserAttrs. This worked well for me. Now, with the current version (3.1.2) this got broken :(

(btw. from the documentation doesn't give information about which options i can change. It would be nice of you, if you could enhance the documentation in this regard.)

### Environment Details:

 - formBuilder Version: 3.1.2
 - Browser: chrome
 - OS: Win10

### Expected Behavior
the header component accepts additional attributes: id and name

### Actual Behavior
it doesn't

### Steps to Reproduce
```
var options = {
    typeUserAttrs: {
        header: {
    	    id: {
    	        label: 'id'
    	    },
    	    name: {
                label: 'name'
    	    }
        }
    }
}
var fbEditor = document.getElementById(divName);	
$(fbEditor).formBuilder(options);
```
this is just an excerpt. if more informations are needed i will gladly provide them. Also i do this for several more components such as paragraph.

**Comment by ThomasWiens** [comment]
Probably a better way to reproduce:
Go into your documentation and open the article for editing typeUserAttrs and scroll to _Usage_. [https://formbuilder.online/docs/formBuilder/options/typeUserAttrs/](url)

There you configured a date component to have extra attributes such as a min and a max value.
When adding 2 date controls the first one doesn't have those attributes, the second control does have them.

**Comment by Tabssummulani** [comment]
i m also facing same issue

**Comment by Tabssummulani** [comment]
hello this issue is resolved at my side please add 'value' property in typeUserAttrs pls find below code

typeUserAttrs: {
        date: {
          min: {
            label: 'Date min.',
            value: ''     //<---- add value attribute
          },
          max: {
            label: 'Date max.',
            maxlength: '10',
            onclick: 'alert("wooohoooo")',
            placeholder: 'yeah "sure" whateverman',
            value: ''      //<---- add value attribute
          },
          value: {
            label: 'default value',
            type: 'date',
            value: ''        //<---- add value attribute
          }
        }
}

**Comment by Jojoshua** [comment]
I assume this got done, closing.
