### ISSUE TITLE
How to enable bootstrap grid?

### ISSUE THREAD

**Issue by johndavemanuel** [kevinchappell/formBuilder#882]
I have read in the changelog that you have enabled the column and row, but I cannot see it on the live demo and I cannot see it on the documentation

Any help will be appreciated.

**Comment by daebak74** [comment]
Edit the field and in the class section add bootstrap class for example col-md-6

**Comment by johndavemanuel** [comment]
I see know, it seems hard for "normal" users to do that. I thought it has drag and drop row or column

**Comment by Jojoshua** [comment]
This aims to help https://github.com/kevinchappell/formBuilder/pull/1243
