### ISSUE TITLE
Date format bug

### ISSUE THREAD

**Issue by mourareaupro** [kevinchappell/formBuilder#883]
I have a problem with the date format, 

I can do that : 12/02/200000 in the input date field. how could i stop to 2000 ? i can reproduce this error on the online formBuilder
![capture](https://user-images.githubusercontent.com/25173073/49950878-f5900100-fef8-11e8-9f54-1e96ad175174.PNG)
.

**Comment by simon-hevs** [comment]
This is using the built in date control for the browser, looks like you are using chrome, and this is the correct behaviour. You could however create attributes on the control to specify min and max date formats that would limit the year.

**Comment by Jojoshua** [comment]
Feel free to reopen if this is still an issue.
