### ISSUE TITLE
Error when adding/entering form controls on the stage

### ISSUE THREAD

**Issue by mapsedge** [kevinchappell/formBuilder#886]
### Environment Details: Window Server 2012, IIS; Windows 10 desktop, Chrome 71 64bit.

 - formBuilder Version: current, whatever's hotlinked.
 - Browser: Chrome 71 64bit; Opera 56.0.3051.116
 - OS: Windows 10

### Steps to Reproduce  Cannot reproduce at will; refreshing the page seems to help, but the error might occur after adding one control, or ten. 

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="https://formbuilder.online/assets/js/form-builder.min.js"></script>
<script src="https://formbuilder.online/assets/js/form-render.min.js"></script>

Everything appears to build okay, but after dragging a control onto the stage, when I tab between field properties, from Label to Help Text for instance, I get the following errors:

Uncaught TypeError: Cannot read property 'replace' of null
at r.camelCase (form-builder.min.js:6)
at form-builder.min.js:19
at r.forEach (form-builder.min.js:6)
at t.getAttrVals (form-builder.min.js:19)
at form-builder.min.js:19
at r.forEach (form-builder.min.js:6)
at t.prepData (form-builder.min.js:19)
at Object.json (form-builder.min.js:19)
at t.save (form-builder.min.js:19)
at HTMLInputElement.C.on.leading (form-builder.min.js:19)

**Comment by MobileTallent** [comment]
same issue

**Comment by mapsedge** [comment]
After a long time of no response, I just rolled my own and moved on.

**Comment by MobileTallent** [comment]
The issue was because of confliction with bootstrap-select module. I removed it.

**Comment by lucasnetau** [comment]
This would require the field attributes inputs to have no name attribute set, if this was occurring the whole formBuilder stage is corrupted.

If a reproducible test case can be provided please reopen this issue or create a new one with the reproduction
