### ISSUE TITLE
v3.1.3 doesn't work in IE11

### ISSUE THREAD

**Issue by slawn** [kevinchappell/formBuilder#887]
I'm not sure about previous versions from 3.x.x (I'm upgrading directly from v2.9.8) - but when trying latest v3.1.3 in IE11 it throws errors and doesn't work at all. 

How to reproduce - just visit https://formbuilder.online/ in IE11 - the form builder doesn't display at all. Those are the errors:

SCRIPT438: Object doesn't support property or method 'entries'
form-builder.min.js (12,7736)

SCRIPT438: Object doesn't support property or method 'entries'
form-render.min.js (12,7736)

SCRIPT438: Object doesn't support property or method 'formBuilder'
vendor.min.js (1,30843)

Here is screen shot of the problem:

![image](https://user-images.githubusercontent.com/17828022/50099792-d6ee7a80-0216-11e9-8163-2ccb54b3b573.png)

**Comment by pasmik** [comment]
Hi, you have to user polyfill... I fixed it on my environment.

**Comment by sxndy1** [comment]
@pasmik How exactely did you solve that with polyfill?

**Comment by pasmik** [comment]
@sxndy1 which polyfill you need?

**Comment by sxndy1** [comment]
![image](https://user-images.githubusercontent.com/47420177/52414474-c0f98980-2ae4-11e9-848e-fd49e5288741.png)

Object doesn't support property or method 'assign'
form-builder.min.js

I don't know which polyfill I need. Sorry, till now I've never heard about.

**Comment by pasmik** [comment]
just create js file and include it before you call the formBuilder. Its compiled from TS, I hope it will work for you.

**Comment by sxndy1** [comment]
Unfortunately not, but thank you anyway! I will inform my self about.

**Comment by p333ter** [comment]
OK, then you can generate polyfill which you want on this site:
https://polyfill.io/v3/url-builder

This have to help you :)

**Comment by slawn** [comment]
> 
> 
> Unfortunately not, but thank you anyway! I will inform my self about.

Any luck?? I've tried all the polyfill options from polyfill.io but still no luck ...

I'm still getting

**SCRIPT438: Object doesn't support property or method 'assign'
form-builder.min.js (12,7433)**

`<script crossorigin="anonymous" src="https://polyfill.io/v3/polyfill.min.js?features=default%2CArray.from%2CArray.isArray%2CArray.of%2CArray.prototype.%40%40iterator%2CArray.prototype.copyWithin%2CArray.prototype.entries%2CArray.prototype.every%2CArray.prototype.fill%2CArray.prototype.filter%2CArray.prototype.find%2CArray.prototype.findIndex%2CArray.prototype.forEach%2CArray.prototype.includes%2CArray.prototype.indexOf%2CArray.prototype.keys%2CArray.prototype.lastIndexOf%2CArray.prototype.map%2CArray.prototype.reduce%2CArray.prototype.some%2CArray.prototype.reduceRight%2CArray.prototype.values%2CAudioContext%2CBlob%2CCustomEvent%2CDOMTokenList%2CDOMTokenList.prototype.%40%40iterator%2CDate.now%2CDate.prototype.toISOString%2CDocumentFragment%2CDocumentFragment.prototype.append%2CDocumentFragment.prototype.prepend%2CElement%2CElement.prototype.after%2CElement.prototype.before%2CElement.prototype.append%2CElement.prototype.classList%2CElement.prototype.cloneNode%2CElement.prototype.closest%2CElement.prototype.dataset%2CElement.prototype.matches%2CElement.prototype.placeholder%2CElement.prototype.prepend%2CElement.prototype.remove%2CElement.prototype.replaceWith%2CEvent%2CEvent.focusin%2CEvent.hashchange%2CEventSource%2CFunction.prototype.bind%2CFunction.prototype.name%2CHTMLCanvasElement.prototype.toBlob%2CHTMLDocument%2CHTMLPictureElement%2CIntersectionObserver%2CIntersectionObserverEntry%2CIntl%2CJSON%2CMath.acosh%2CMap%2CMath.asinh%2CMath.atanh%2CMath.cbrt%2CMath.clz32%2CMath.cosh%2CMath.expm1%2CMath.fround%2CMath.hypot%2CMath.imul%2CMath.log10%2CMath.log1p%2CMath.log2%2CMath.sign%2CMath.tanh%2CMath.trunc%2CMath.sinh%2CMutationObserver%2CNode.prototype.contains%2CNodeList.prototype.%40%40iterator%2CNodeList.prototype.forEach%2CNumber.Epsilon%2CNumber.MAX_SAFE_INTEGER%2CNumber.MIN_SAFE_INTEGER%2CNumber.isFinite%2CNumber.isInteger%2CNumber.isNaN%2CNumber.isSafeInteger%2CNumber.parseFloat%2CNumber.parseInt%2CObject.assign%2CObject.create%2CObject.defineProperties%2CObject.defineProperty%2CObject.entries%2CObject.freeze%2CObject.getOwnPropertyDescriptor%2CObject.getOwnPropertyNames%2CObject.is%2CObject.getPrototypeOf%2CObject.keys%2CObject.values%2CObject.setPrototypeOf%2CPromise%2CPromise.prototype.finally%2CString.prototype.%40%40iterator%2CString.fromCodePoint%2CSet%2CRegExp.prototype.flags%2CString.prototype.codePointAt%2CString.prototype.endsWith%2CString.prototype.includes%2CString.prototype.padEnd%2CString.prototype.padStart%2CString.prototype.repeat%2CString.prototype.startsWith%2CString.prototype.trim%2CSymbol.hasInstance%2CSymbol%2CSymbol.isConcatSpreadable%2CSymbol.iterator%2CSymbol.match%2CSymbol.replace%2CSymbol.search%2CSymbol.species%2CSymbol.split%2CSymbol.toPrimitive%2CSymbol.toStringTag%2CSymbol.unscopables%2CURL%2CUserTiming%2CWeakMap%2CWeakSet%2CWebAnimations%2CWindow%2CXMLHttpRequest%2Catob%2Cconsole%2Cconsole.assert%2Cconsole.clear%2Cconsole.count%2Cconsole.debug%2Cconsole.dir%2Cconsole.dirxml%2Cconsole.error%2Cconsole.exception%2Cconsole.group%2Cconsole.groupCollapsed%2Cconsole.groupEnd%2Cconsole.info%2Cconsole.log%2Cconsole.markTimeline%2Cconsole.profile%2Cconsole.profileEnd%2Cconsole.profiles%2Cconsole.table%2Cconsole.time%2Cconsole.timeStamp%2Cconsole.timeEnd%2Cconsole.timeline%2Cconsole.timelineEnd%2Cconsole.trace%2Cconsole.warn%2CdevicePixelRatio%2Cdocument%2Cdocument.currentScript%2Cdocument.getElementsByClassName%2Cdocument.head%2Cdocument.querySelector%2Cdocument.visibilityState%2Cfetch%2CgetComputedStyle%2ClocalStorage%2Clocation.origin%2CmatchMedia%2Cnavigator.geolocation%2Cnavigator.sendBeacon%2Cperformance.now%2CrequestAnimationFrame%2Cscreen.orientation%2CsetImmediate%2C%7Ehtml5-elements%2C%7Eviewport"></script>`

**Comment by fillae** [comment]
I solved using the babel core polyfill.  Follow the "Usage in Browser" here:

https://babeljs.io/docs/en/babel-polyfill

There is also an issue with arrays using nodelist now, so I had to also include the following polyfill:
`if (window.NodeList && !NodeList.prototype.forEach) {
    NodeList.prototype.forEach = function (callback, thisArg) {
        thisArg = thisArg || window;
        for (var i = 0; i < this.length; i++) {
            callback.call(thisArg, this[i], i, this);
        }
    };
}`

**Comment by slawn** [comment]
> 
> 
> I solved using the babel core polyfill. Follow the "Usage in Browser" here:
> 
> https://babeljs.io/docs/en/babel-polyfill
> 
> There is also an issue with arrays using nodelist now, so I had to also include the following polyfill:
> `if (window.NodeList && !NodeList.prototype.forEach) { NodeList.prototype.forEach = function (callback, thisArg) { thisArg = thisArg || window; for (var i = 0; i < this.length; i++) { callback.call(thisArg, this[i], i, this); } }; }`

That did the trick. thanks

**Comment by ThuThuong234** [comment]
lam vay ne ma'
https://polyfill.io/v3/polyfill.min.js?features=Object.assign%2CObject.entries%2CArray.prototype.entries%2CPromise%2CArray.prototype.find%2CArray.prototype.findIndex%2CObject.values%2CArray.prototype.values
