### ISSUE TITLE
After upgrade project from angular 4 to 7 I am facing issue in jquery form builder

### ISSUE THREAD

**Issue by krunal81093** [kevinchappell/formBuilder#888]
It's showing the value of undefined in the console but before that it's working fine. The error is in the formbuilder.ts file

export class FormBuilderCreateor {    
  getFormBuilder(opts: any, element: any) {
    return FormBuilder(opts,element);
  }
}

const FormBuilder =  (opts, element) => {
  console.log(this); //got the undefined
}

**Comment by Jojoshua** [comment]
Please reopen if you still have issues
