### ISSUE TITLE
Not able to set json data for multi-page/ Tabbed form on edit on formBuilder

### ISSUE THREAD

**Issue by misterharshith** [kevinchappell/formBuilder#890]
### Description: 
Hi @kevinchappell, I am not able to set the saved multi page form json data on edit function, as setData works well with single page formBuilder but not on multi tabbed formBuilder

**Example:**
SetData works well with single page builder onclick of Set data button in below example
https://codepen.io/kevinchappell/pen/ozagKr

But in Multi Tabbed formBuilder not able to set multipage form data on single click and create respective pages based on json value
https://codepen.io/kevinchappell/pen/BKYPRp

### Environment Details: 

 - formBuilder Version: v3.1.2
 - Browser: Chrome v70.0.3538.110
 - OS: Mac High Sierra v10.13.3

### Expected Behavior: 
Onclick button Set multipage form json data and create pages accordingly

### Actual Behavior
Not able to set multipage form json data onlcik

**Comment by omvirala** [comment]
@misterharshith how can you resolve this?

**Comment by Selvi-winvest** [comment]
Anybody resolved this issue ?

**Comment by Jojoshua** [comment]
Each formbuilder object you create needs to be saved and then you can call the set data.
