### ISSUE TITLE
Display the control icon in the form builder area

### ISSUE THREAD

**Issue by simoncas** [kevinchappell/formBuilder#892]
### Description:

Hello,

Is it possible to setup the form builder to display both the control **icon** and its **label** in the form builder area ?

In case of huge form, it's sometimes hard to remember the type of each control and displaying the control icon in conjunction with the label may help.

What I expect is the same as the first screenshot, the dragged **autocomplete** title is composed of the control icon and it's label. 

The second screenshot is the actual behaviour. The title of the dragged autocomplete control displays only its label. The control icon is not shown. 

Can I quickly customise the library to display the controller icon in dragged area using the built-in features or do I have to implement this feature ?

Thanks in advance for the advices.

### Screenshot - *(optional)*

<img width="1090" alt="screenshot 2019-01-07 at 08 16 51_edited" src="https://user-images.githubusercontent.com/11412464/50755137-67d5d600-1258-11e9-91ca-fbfe4712f513.png">

<img width="1090" alt="screenshot 2019-01-07 at 08 16 51" src="https://user-images.githubusercontent.com/11412464/50754521-4bd13500-1256-11e9-9544-a549f067a50a.png">

**Comment by jogireddygowthami** [comment]
Hi, 

whether it is possible to pass the multiple options to formbuilder for example: $(fbEditor).formBuilder(options, fields); but this is not working. Could please suggest me how to pass the field & options and it should apply both options & fields.  iam trying to add other button to form builder i.e. email with icon. Please help out with this
