### ISSUE TITLE
Other Value bug

### ISSUE THREAD

**Issue by mourareaupro** [kevinchappell/formBuilder#893]
I have a problem with the "Other" field from the radio button group or checkbox group when i write something in the other option field my JSON don't save this value. i also checked in the demoOnline and it's the same. 

Could you help me ? 

![capture](https://user-images.githubusercontent.com/25173073/50898094-5fbf9700-140e-11e9-80e2-4364337f7543.PNG)

`[
  {
    "type": "radio-group",
    "label": "Radio Group",
    "name": "radio-group-1547034400996",
    "other": true,
    "values": [
      {
        "label": "Option 1",
        "value": "option-1"
      },
      {
        "label": "Option 2",
        "value": "option-2"
      },
      {
        "label": "Option 3",
        "value": "option-3",
        "selected": true
      }
    ]
  },
  {
    "type": "checkbox-group",
    "label": "Checkbox Group",
    "name": "checkbox-group-1547035016551",
    "other": true,
    "values": [
      {
        "label": "Option 1",
        "value": "option-1",
        "selected": true
      }
    ]
  }
]`

**Comment by khakman** [comment]
We are experiencing the same issue.  Looking forward to a fixed or understanding ways in which we could contribute to the acceleration of a fix for this issue.

**Comment by mourareaupro** [comment]
Any update  @kevinchappell @khakman  ? thanks in advance

**Comment by lucasnetau** [comment]
I cannot replicate this locally or on the demo site with the current release. Do you still encounter this issue?

**Comment by lucasnetau** [comment]
The other options are designed to be a end user entered other value not part of a configured set. Can you please describe the requirement for formBuilder to handle the other case on the builder side. If it's a possible option what is preventing it being added to the list of options?
