### ISSUE TITLE
Control Plugin Subtypes

### ISSUE THREAD

**Issue by fillae** [kevinchappell/formBuilder#894]
### Description:
I am trying to add subtypes to a control plugin, but the "Type" selection is not being displayed.  I am basically creating custom input fields for items that will be auto populated when the form is loaded.  I am using the subtype to determine what data goes where.  I can get the subtypes to display if I add them to the "text" control, but not to my custom plugin.

Here is how I am trying to register them:
![register1](https://user-images.githubusercontent.com/19737928/50996885-69b1ca80-14e0-11e9-9d8b-d334d93d077e.PNG)

And here is what the control looks like in the builder:
![display1](https://user-images.githubusercontent.com/19737928/50996906-7afad700-14e0-11e9-95f4-69bdd8880976.PNG)

The Type field is not being displayed.  Alternatively, this is what it looks like registering as subtypes to the "text" control:
![register2](https://user-images.githubusercontent.com/19737928/50996980-a54c9480-14e0-11e9-9c49-b4a22031c6ef.PNG)

![display2](https://user-images.githubusercontent.com/19737928/50996985-a8e01b80-14e0-11e9-8f69-98d7a094a1dc.PNG)

I am coming to the conclusion that subtypes cannot be added to plugins.  Am I missing something else that is required?

Thanks.

### Environment Details:

 - formBuilder Version: 3.1.3
 - Browser: Chrome
 - OS: Win 10

**Comment by chakrabar** [comment]
I ran into the same issue. After searching through the code, I found that `subtype` attribute has to be added to the list of default attributes for your control. For that, update code in `form-builder.js`

```js
const typeAttrsMap = {
  //current code
  yourControl: defaultAttrs.concat(['subtype'])
}
```

**Comment by psmarsch** [comment]
@kevinchappell Is there absolutely no way to define the options in the control class itself? I am about to create several custom controls which are loaded dynamically and would much prefer no to touch form-builder.js for all of them.

**Comment by chandler3224** [comment]
@kevinchappell This feature is now live, I'd like to request that this issue is closed.

**Comment by kevinchappell** [comment]
@chandler3224 thanks for following up! closing
