### ISSUE TITLE
disabledSubtypes

### ISSUE THREAD

**Issue by Muhammad-Taimoor** [kevinchappell/formBuilder#895]
Hi, I am trying to disableHTMLLabel and disable subTypes but it isn't working, The code as following:
<code> that.formBuilder = $('.modal-prompt', elFormBuilder).formBuilder({
						 "formData" : elFormDesign.val()
						,"editOnAdd": true
						// ,"i18n": {"locale": "ru-RU"}
						,"disableFields": [
							//"autocomplete"
							//,"button"
							"file"
							// ,"header"
							//,"hidden"
							//,"paragraph"
							//,"date"
							//,"checkbox-group"
							//,"number"
							//,"radio-group"
						]
						// typeUserDisabledAttrs: {
						// 'checkbox-group': [
						// 'name',
						// 'description',
						// 'required',
						// 'inline',
						// 'toggle'
						// ]
						// }
						,"disabledAttrs": [
							 "access"
							// ,"className" //not disabled, but hidden using css
							,"description"
							,"inline"
							// ,"label"
							// ,"max"
							// ,"maxlength"
							// ,"min"
							// ,"multiple"
							// ,"name"
							// ,"options"
							,"other"
							,"placeholder"
							// ,"required"
							// ,"rows"
							// ,"step"
							,"style"
							//,"subtype"
							,"toggle"
							// ,"value" //not disabled, but hidden using css
						]
						,"disableHTMLLabels": true
						,"disabledSubtypes": {
							"text": ['password'],
						}
						,"disabledActionButtons": ["data", "clear", "save"]
					});</code>

**Comment by Jojoshua** [comment]
Please reopen with a fiddle to reproduce
