### ISSUE TITLE
Other field traduction on the renderForm

### ISSUE THREAD

**Issue by mourareaupro** [kevinchappell/formBuilder#896]
There is a way to translate "Other" label field from the renderView? 
![capture](https://user-images.githubusercontent.com/25173073/51610275-a4722480-1f1c-11e9-9123-d7f654bcd0ae.PNG)

Thanks in advance

**Comment by wandumi** [comment]
I would like to know how did you render the json from the database

**Comment by mourareaupro** [comment]
Hello, i render it like this : 


`<div id="<?php echo $page->getIdPage(); ?>" class="render-wrap"></div>
                        <script>
                            jQuery(function($) {
                                var data = <?php echo json_encode($candidature_page->getValeur()); ?>;
                                var text = data.replace(/&quot;/g, '"');
                                text = text.replace('"\\"[', '[');
                                text = text.replace(']\\""', ']');

                                var frm = $('.render-wrap');
                                var JsonData = JSON.parse(text);
                                var $ctrl;
                                var $labelFr;
                                var $labelEn;
                                var $culture = "<?php echo sfContext::getInstance()->getUser()->getCulture(); ?>";

                                $.each(JsonData, function (key, value) {
                                    $ctrl = $('[name=' + key + ']', frm);

                                    $labelFr = value["label"];
                                    $labelEn = value["labelEn"];
                                    var default_label = value["label"];
                                    var default_help = value["description"];

                                    if($culture == 'en_US' && value["labelEn"] != null) {

                                        $(this).attr('label' , value["labelEn"]);

                                    }else{

                                        $(this).attr('label' , default_label);

                                    }

                                    if($culture == 'en_US' && value["description"] != null && value["helpEn"] != null){

                                        $(this).attr('description' , value["helpEn"]);

                                    }else{

                                        $(this).attr('description' , default_help);

                                    }

                                    if($(this).attr('values')){

                                        for(i in $(this).attr('values')){

                                            if($culture == 'en_US' && $(this).attr('values')[i]['label_en']){
                                                $(this).attr('values')[i]['label'] = $(this).attr('values')[i]['label_en'];
                                            }else{
                                                $(this).attr('values')[i]['label'] = $(this).attr('values')[i]['label'];
                                            }

                                            console.log($(this).attr('values')[i]['label_en']);
                                        }
                                    }
                                });

                                $('.render-wrap').formRender({
                                    formData: JsonData,
                                    dataType: 'json'
                                });
                            });
                        </script>
                </div>`

**Comment by mourareaupro** [comment]
Any ideas ?

**Comment by buttle** [comment]
We are looking for a solution to this too.

Thank you.

**Comment by Porrumentzio** [comment]
Any news on this?

**Comment by lucasnetau** [comment]
This has been resolved in PR #1385
