### ISSUE TITLE
Is it possible to maintain a fixed width for the form fields (i.e. so that it doesn't collapse to icon if the window is resized less than 482px)?

### ISSUE THREAD

**Issue by mhagerty** [kevinchappell/formBuilder#898]
### Description:
I'd like to be able to maintain the Label Name and Icon for the form fields, even if the screen is resized to less than 482px.  I've messed with the classes, but I'm not versed enough in mixins and scss to make this a reality.  Is there an option that I'm missing?  Aside from that, thank you for such an amazingly straight-forward and well-documented tool!

### Environment Details:

 - formBuilder Version: latest
 - Browser: Chrome
 - OS: Mac

**Comment by Jojoshua** [comment]
You would wrap this in your own container and control its width
