### ISSUE TITLE
TypeError: t.trim is not a function

### ISSUE THREAD

**Issue by watercayman** [kevinchappell/formBuilder#899]
### Description:
TypeError: t.trim is not a function when adding a user-created control with a value to be set within fields 

When I add a user-created control to the form **a second time**, it breaks with the above error.  First time is fine.  If I remove the programatic setting of the value, it works fine.  This is on a radio-group.  There are no other issues on this instance.

### Environment Details:

 - formBuilder Version: latest
 - Browser: FF
 - OS: 

### Steps to Reproduce
Add the code below to the config:
 ```
fields : [ 
       {
          label: "Main YES NO",
          type: "radio-group",
          mainYesNo: {
              value: true
          }
       }
    ]
```
Drag this "Main YES NO" control on to the form (or any other control).  Then, drag this control a second time and the js errors out.  If I remove the `mainYesNo: {   value: true   }` code, it will not error.

### Screenshot - *(optional)*
![image](https://user-images.githubusercontent.com/13262406/51789745-5185b080-215a-11e9-9f7a-ff9a9ce7e910.png)

**Comment by watercayman** [comment]
Not a form-builder issue, this is not a bug.  Apologies, this works perfectly if I change the code slightly.
`mainYesNo: true` works fine.  

I'll leave this here in case someone screws up syntax in similar way in future.

Thank you for this outstanding library.

**Comment by inquisitive-stha** [comment]
I am getting the same issue, however, its when you add a className, if you leave className blank, it works fine.
