### ISSUE TITLE
Save/Retrieve Form Field Data

### ISSUE THREAD

**Issue by dannycamps** [kevinchappell/formBuilder#9]
Hello,

First - thanks for your work on this utility.

Next set of questions for this:

1. I noted in a previous question asked that you are writing the generated XML to a hidden textarea on screen (cool).  My question is if I want to re-load a previously saved form (e.g. to allow a user to edit a previously created form), do I just set the value of the hidden textarea to the previously saved XML on page load?

2. If I want to add/remove a field type or if I want to add an attribute to a field type, how can I go about doing that?  An example - is for each field, I want the user to be able to select from a dropdown a DB field to map the data to.

Thank you.
Daniel

**Comment by kevinchappell** [comment]
Hi Daniel,
> do I just set the value of the hidden textarea to the previously saved XML on page load?

That should do it :)

> If I want to add/remove a field type or if I want to add an attribute to a field type, how can I go about doing that? An example - is for each field, I want the user to be able to select from a dropdown a DB field to map the data to.

Unfortunately this is not possible with the current version but the good news is formBuilder is currently undergoing a major rewrite with the next release slated to be a full 2.0. The feature you described along with many others will be included in the 2.0 release towards the end of the month.

**Comment by dannycamps** [comment]
Hey Kevin,

I have been able to get the form builder to create a form and write the fields to a DB table.  I am also storing the complete XML data string so I can re-populate the form builder to allow field editing.

I am now trying to set the formBuilder with the XML data string being retrieved from my DB table.  I have the following logic coded in my app:

jQuery(document).ready(function ($) {
                  'use strict';
                  $('#formBuilder').val("<%=cf.xml_data.Replace("\"","\\\"").Replace("\r","").Replace("\n","").Replace("\t","")%>");
                  $(document.getElementById("formBuilder")).formBuilder();

              });

The page loads but the form builder is empty.  When I click the 'View XML' link, I am seeing the XML data there but it is not reflecting in the UI.  If I try to add/change a control to the form, it replaces my existing XML data with new content.

Looking at the JS error console in Firefox, it is pointing to an error in form-builder.js
TypeError: $field.data(...) is undefined1 form-builder.js:559:19

The line in the source code is:
var fType = $field.data('attrs').type,

Any thoughts or best approaches for re-populating the form builder to allow edits to previously created forms?

Thanks,
-Daniel

**Comment by kevinchappell** [comment]
There was an issue with how the data was loaded by the plugin. It should be resolved now with PR #18 Still, I would avoid manually setting the textarea value with JavaScript if possible but if you must maybe you could use `.html(val).text()`.

For example:
```
var xmlVal = $('<div/>').html('<%=cf.xml_data%>').text();
var $fbTextarea = $(document.getElementById('formBuilder'));
$fbTextarea.val(xmlVal);
$fbTextarea.formBuilder();
```

The above is untested but something similar should work.

**Comment by dannycamps** [comment]
Hi Kevin,

Thank you for this fix.  It is almost perfect.  I am now able to repopulate the form.  The only issue is the option values are not being retained for dropdowns, radios, etc...

On the form itself, for each multi-select item, I am seeing only 'Option 1', 'Option 2' - despite having those values set in the XML I am passing to the form builder.

Thanks,
-Daniel

**Comment by arbabi2010** [comment]
Hi Kevin,
thanks for your great work.
when i click on save button nothing happens .

**Comment by kevinchappell** [comment]
Other than jquery ui and jquery, no. 

The save button is mainly a ui element for you to hook your own save function to. This is intentionally left to the developer since accounting for all use cases would be impossible every app will have its own way of saving data. 

In the docs you'll find an example that reads and writes data to `window.sessionStorage` using the save button that you can follow to save data to your backend.
