### ISSUE TITLE
FineUploader class not appear

### ISSUE THREAD

**Issue by SamuelPelletier** [kevinchappell/formBuilder#902]
### Description:
Hi ! It's a great project but I have a problem when I would like set a class with FormBuilder for FineUploader. I set my class in the file field form (like image after) but this class nerver appear in HTML.
For information : when I save my form with a new class, this class is save correctly.
### Environment Details:
 - formBuilder Version: 3.1.3 VF
 - Browser: Google Chrome & Firefox
 - OS: Windows 7

### Expected Behavior
I would like my new class appear somewhere in HTML FineUploader tag
### Actual Behavior
My new class not appear in HTML
### Steps to Reproduce
1. Add a file uploader component
2. Change file field type to Fine Uploader
3. Change or add class in the class field
4. Check in HTML if the class added appear
### Screenshot - *(optional)*
![image](https://user-images.githubusercontent.com/17120376/52117028-fb5db500-2612-11e9-9165-c6b72e7c8a19.png)

**Comment by lucasnetau** [comment]
@kevinchappell FineUploader is now EOL and the FormBuilder plugin has been inoperable for a while since the CDN hosted version no longer exists.

https://github.com/FineUploader/fine-uploader/issues/2073

Should we:
1) Remove file.fineuploader since it has been broken for years
2) Fix up the CDN link to the last version 5.16.2 and add a warning if the plugin is loaded?

**Comment by kevinchappell** [comment]
> @kevinchappell FineUploader is now EOL and the FormBuilder plugin has been inoperable for a while since the CDN hosted version no longer exists.
> 
> https://github.com/FineUploader/fine-uploader/issues/2073
> 
> Should we:
> 1) Remove file.fineuploader since it has been broken for years
> 2) Fix up the CDN link to the last version 5.16.2 and add a warning if the plugin is loaded?

let's remove it. We have all kinds of hooks and stuff developers can use to implement their own file uploader. If there is a demand we can do a basic version using fetch
