### ISSUE TITLE
formBuilder() is not a function

### ISSUE THREAD

**Issue by Ner0ls** [kevinchappell/formBuilder#903]
### Environment Details:

 - formBuilder Version: 3.1.3
 - Browser: Chromium 71.0.3578.98
 - OS: Manjaro Linux

### Expected Behavior
formBuilder initializing correctly

### Actual Behavior
"formBuilder() is not a function".

### Steps to Reproduce
Install from npm:

```
npm i formBuilder
npm run dev
```
Note: I updated my app.js before doing `npm run dev`, I tried with:

- `require('formBuilder')`
- `formBuilder = require('formBuilder')`
- `window.formBuilder = require('formBuilder')`

None of them worked.

### Screenshot - *(optional)*
This is my HTML code:
![2019-02-03-230517_850x289_scrot](https://user-images.githubusercontent.com/38695851/52186775-615f5d80-2808-11e9-9e3e-737396321bef.png)

This is my package.json
![2019-02-03-230549_936x442_scrot](https://user-images.githubusercontent.com/38695851/52186893-f6faed00-2808-11e9-8512-9cc96fabeaa9.png)

And this is currently my app.js
![2019-02-03-230624_754x429_scrot](https://user-images.githubusercontent.com/38695851/52186904-02e6af00-2809-11e9-9427-cf1920f2e3c3.png)

Any help will be appreciated :c

**Comment by SamuelPelletier** [comment]
Hi,

Can you try just this : 
`<script src="https://formbuilder.online/assets/js/form-builder.min.js"></script>`
`<script src="https://formbuilder.online/assets/js/form-render.min.js"></script>`

`<script>
jQuery(function($) {
    $(document.getElementById('formbuilder')).formBuilder();
  });
</script>`

I hope it's help you :smiley:

**Comment by LunaticShock** [comment]
> Hi,
> 
> Can you try just this :
> `<script src="https://formbuilder.online/assets/js/form-builder.min.js"></script>`
> `<script src="https://formbuilder.online/assets/js/form-render.min.js"></script>`
> 
> `<script> jQuery(function($) { $(document.getElementById('formbuilder')).formBuilder(); }); </script>`
> 
> I hope it's help you

I get it to work through CDN, but I forgot to specify that I need to compile it, because I want to add custom elements to it :disappointed:

**Comment by sheaw** [comment]
I had the same issue -- something about jqeury permissions, I believe.

In any event, I got it to work by:

1.  remove: 

`<script src="https://formbuilder.online/assets/js/form-render.min.js"></script>`

2.  copy/paste the entire "form-render.min.js" library source DIRECTLY into your jquery function:

```
<script> jQuery(function($) {

[[[[paste of entire form-render.min.js SOURCE CODE here]]]]

$(document.getElementById('formbuilder')).formBuilder(); }); 

</script>

```
Hope it works for you too.

Cheers.
