### ISSUE TITLE
Is it possible to disable jqueryform builder save and clear button and use our own custom button to do same functionality

### ISSUE THREAD

**Issue by ss14620** [kevinchappell/formBuilder#904]
### Environment Details:

 - formBuilder Version: 
 - Browser: 
 - OS:

**Comment by RaphGC** [comment]
Yes you can disable buttons : https://formbuilder.online/docs/formBuilder/options/disabledActionButtons/
And make your own : https://formbuilder.online/docs/formBuilder/options/actionButtons/

**Comment by ss14620** [comment]
Thank you so much for the guidance.
