### ISSUE TITLE
How to inject the compressed file which downloaded from the web

### ISSUE THREAD

**Issue by dreldrel** [kevinchappell/formBuilder#906]
### Description:
Hi guys, I want to inject the library to the HTML file which the library is download from the web. But the web console always says "jQuery.Deferred exception: $(...).formBuilder is not a function TypeError: $(...).formBuilder is not a function". Could anyone help me to solve the problem? The code is as follow.

Right now I inject three js file including form-builder.js, index.js and control.js.
### Environment Details:

 - formBuilder Version: 3.1.3
 - Browser: Google, IE
 - OS: Windows 8.1

### Screenshot - *(optional)*
![1](https://user-images.githubusercontent.com/45089360/52468422-a6e2a880-2bc3-11e9-95a8-70ce8407c4ca.png)
![2](https://user-images.githubusercontent.com/45089360/52468650-4acc5400-2bc4-11e9-88f6-be7c911bdfe2.png)

**Comment by lucasnetau** [comment]
You are injecting the source form-builder.js which isn't a completely built module. You need to run `npm run build` and then copy form-builder.min.js from the dist/ directory to get the built library
