### ISSUE TITLE
form builder includes in any project

### ISSUE THREAD

**Issue by ajkosh** [kevinchappell/formBuilder#911]
### Description:
cloned from url and build with npm then run demo folder,How i should includes all js so it will work in any project.
### Environment Details:

 - formBuilder Version: latest
 - Browser: mozila
 - OS: ubuntu 16.4

### Expected Behavior
demo should run but when include all js file in any project it should reflect form builder on any framework or page
### Actual Behavior
broken ui page screenshot attached
### Steps to Reproduce
just inlucde all js in one folder and call demo
![build](https://user-images.githubusercontent.com/8582472/52831995-bcdcf580-30fc-11e9-9d6b-04581572dac3.png)

**Comment by Jojoshua** [comment]
Please retry on the latest version
