### ISSUE TITLE
Not able to get file details from file upload control in file rendered

### ISSUE THREAD

**Issue by manojrock** [kevinchappell/formBuilder#912]
### Description:
Not able to Find  file upload details in file rendered page . after upload file in rendered page . I am getting file JSON DATA like  
{  
      "type":"file",
      "label":"Pan upload",
      "className":"form-control",
      "name":"file-1550658410235",
      "subtype":"file"
   }
In above JSON when i uploaded file in rendered page then getting above json data having know file name or url any kind of details. 
### Environment Details:
  Environment in chrome browser .
 - formBuilder Version: 
 - Browser:   chrome
 - OS:

**Comment by satishag** [comment]
Any update on this? We are facing similar issue. Maybe there is a work around or different implementation, but could someone please give some pointers?

**Comment by Licarte97** [comment]
You can do this by using document.getElementById(jsondata.name)

**Comment by Jojoshua** [comment]
Yes you will have to get the file data with JavaScript.
