### ISSUE TITLE
onAddField 

### ISSUE THREAD

**Issue by Mordef** [kevinchappell/formBuilder#916]
### Description:

onAddField not fired

### Environment Details:

 - formBuilder Version: 3.1.3 
 - Browser: Firefox 65.0.2
 - OS: Win10

Taken example from https://formbuilder.online/docs/formBuilder/options/onAddField/

**Comment by Mordef** [comment]
Just a mistake in the docs:
Headline: onAddField <-- works
Example: onFieldAdd <-- wrong

**Comment by kevinchappell** [comment]
resolved in #936

**Comment by asangster** [comment]
@kevinchappell Please update code sample in docs: https://formbuilder.readthedocs.io/en/latest/formBuilder/options/onAddField/
