### ISSUE TITLE
Cannot read property 'getData' of undefined

### ISSUE THREAD

**Issue by DubStepMad** [kevinchappell/formBuilder#917]
### Description: 

I am trying to save the form fields, to an json format to store into a database to be used down the line and updated when needed.

I have read the document and only found some useful points but some of it seems to be outdated compared to the README file included with the .zip file.

### Environment Details:

 - formBuilder Version: No sure since I am using the following: `<script src="https://formbuilder.online/assets/js/form-builder.min.js"></script>`
 - Browser: Chrome
 - OS: Windows 10 Enterprise

### Expected Behavior
To display an alert (for testing) of the form in json format. 
### Actual Behavior
Cannot read property 'getData' of undefined
### Steps to Reproduce
```javascript
jQuery($ => {
  var fbTemplate = document.getElementById('fb-editor');
  var options = {
      dataType: 'json',
      onSave: function(formBuilder) {
          save(formBuilder);
      },

  };
  var formBuilder = $(fbTemplate).formBuilder(options);

  function save(formBuilder) {

      alert(formBuilder.actions.getData('json'));

      $.ajax({
          type: 'POST',
          url: '{https://test.com}',
          data: "form_field = "+data,
          success: function () {
              alert('success')
          },
          error: function () {
              alert('fail');
          }
      });
  }
});
```

**Comment by kevinchappell** [comment]
@DubStepMad You are passing the `onSave` event as formBuilder variable. Removing that solves it:

https://codepen.io/kevinchappell/pen/mgPpGB?editors=0010
