### ISSUE TITLE
Can't set defaultFields dynamically.

### ISSUE THREAD

**Issue by jringeisen** [kevinchappell/formBuilder#920]
### Description:
I am trying to create an edit option so that someone can edit their form instead of recreating a new form and I am trying to set the defaultFields dynamically and I keep getting this error `t.defaultFields.forEach is not a function`

If I `console.log(JSON.parse(vm.formData.form))` and copy and paste the result from the console log to the defaultFields it works.

Any help would be awesome!

### Environment Details:

 - formBuilder Version: latest
 - Browser: Chrome
 - OS: Mac

### Expected Behavior
I'm storing the following object in the database:
`[{"type":"text","label":"Referred By","className":"form-control","name":"referred_by","subtype":"text"}]` and when I retrieve that object and set it to the defaultFields in options I get the above error. I'm setting it like this 
`defaultFields: JSON.parse(vm.formData.form)`

### Actual Behavior
`defaultFields: JSON.parse(vm.formData.form)` is returning `t.defaultFields.forEach is not a function`

**Comment by jringeisen** [comment]
I figured it out with the following piece of code:

    $('#fb-editor' + vm.formData.id).formBuilder(options).promise.then(formBuilder => { 
        formBuilder.actions.setData(JSON.parse(vm.formData.form))
        vm.formBuilder.builder = formBuilder
    })

**Comment by kevinchappell** [comment]
Glad you got it working. I was going to suggest `setData` but in your example you are still creating a new instance.

I've [updated the demo](https://formbuilder.online/docs/formBuilder/actions/setData/) for `setData` to better reflect your use case.
