### ISSUE TITLE
FormBuilder Button CSS

### ISSUE THREAD

**Issue by jsmithdeal** [kevinchappell/formBuilder#923]
### Description: 
classNames aren’t set for buttons

### Environment Details:

 - formBuilder Version: 3.1.3
 - Browser: Chrome
 - OS: Windows 7

### Expected Behavior
btn, btn-default, and any selected style class should append to the className json attribute automatically

### Actual Behavior
No classes are appended to className attribute without typing them in the class box

### Steps to Reproduce
Create a form containing a button, select a style for the button, render the form, and see that the button doesn’t contain any classes

**Comment by kevinchappell** [comment]
resolved in #924 

![fix-btn-style](https://user-images.githubusercontent.com/1457540/55269135-7b884b80-524d-11e9-8e2a-15cc5e7b3e70.gif)

**Comment by Reyemneirda** [comment]
> resolved in #924
> 
> ![fix-btn-style](https://user-images.githubusercontent.com/1457540/55269135-7b884b80-524d-11e9-8e2a-15cc5e7b3e70.gif)

Is it possible to set our own classes ?
