### ISSUE TITLE
How can I get form json in FormBuilder.component.ts file 

### ISSUE THREAD

**Issue by ronak8532** [kevinchappell/formBuilder#929]
Hi !
I am new to this dynamic form builder and i have checked in code so i noticed that on save button click there are we have json of complete form which is we drag and drop in screen .
So now i added one button and in this button click i want that json data.

`export class FormBuilderComponent implements OnInit {
  data: any;
  public myService: any;
  constructor(private dataService: DataService) { }
   
  formBuilder: any;
  formData: any;
    ngOnInit(): void {
      initJq();
      var actionButtons = [
        {
          id: "smile",
          className: "btn btn-success",
          label: "😁",
          type: "button",
          events: {
            click: () => {
              this.dataService.addFormTemplate(); 
            }
          }
        }
      ];
      this.formBuilder = (<any>jQuery('.build-wrap')).formBuilder({ actionButtons: actionButtons });
      console.log(this.formBuilder);
    }
}
`
I want pass json data in click event of button

**Comment by kevinchappell** [comment]
`this.formBuilder` will already be defined when the button is clicked so you can access the data using either `this.formBuilder.actions.getData` or `this.formBuilder.formData`

**Comment by ronak8532** [comment]
I am getting error like instance.actions.getData is not function when i am passing this.formBuilder.formData to my service and i don't know how exactly i have use this.formBuilder.actions.getData so please if it is possible then guide me i have gone through documentation but i didn't got it.
Thanks you.

**Comment by kevinchappell** [comment]
Can you create a demo that reproduces this problem? https://codesandbox.io/s/oxooqxo20z

It will be easier to to understand the problem if I can see the code.

**Comment by ronak8532** [comment]
https://codesandbox.io/embed/nk71kkjzm0 I have added one smilly button and in click of that button i want json of drag control. Thank you for response.

**Comment by ecmciasabellano** [comment]
Any update on this? Having the same problem. No other way to pass formBuilder data/options through custom actionButtons.
