### ISSUE TITLE
disabledSubtypes

### ISSUE THREAD

**Issue by mourareaupro** [kevinchappell/formBuilder#931]
disabledSubtypes don't work for me i tried with a fresh download demo.

disabledSubtypes: {
        text: ['password']
    },

by the way this works : 

disabledFieldButtons: {
        textarea: ['copy']
    },

let me know, thanks in advance

**Comment by blockbaster** [comment]
If you want to deactivate the "copy"-function, you have to set this in the buttons:

const disabledFieldButtons = {
  'textarea': ['copy']
}
