### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by tcarroll2** [kevinchappell/formBuilder#932]
### Description:
The links are broken for Custom Controls at [https://formbuilder.online/docs/development/#custom-controls](https://formbuilder.online/docs/development/#custom-controls)

### Environment Details:

 - formBuilder Version: 
 - Browser: 
 - OS: 

### Steps to Reproduce
Click a link at the above address and you will get a 404 error.

**Comment by kevinchappell** [comment]
@tcarroll2 Thanks for opening this, the links should be fixed now: https://formbuilder.online/docs/development/

it may require a hard refresh to clear cache before seeing the changes.
