### ISSUE TITLE
jQuery is not defined

### ISSUE THREAD

**Issue by ajsb85** [kevinchappell/formBuilder#946]
Hi, @kevinchappell 

I just did 3 steps:

- git clone ...
- yarn
- yarn start

![image](https://user-images.githubusercontent.com/663460/57612100-7882b980-7574-11e9-94cf-cf87aea7b611.png)

```console
Failed to load resource: the server responded with a status of 404 (Not Found)
form-builder.min.js:16341 Uncaught ReferenceError: jQuery is not defined
    at form-builder.min.js:16341
form-render.min.js:13346 Uncaught ReferenceError: jQuery is not defined
    at form-render.min.js:13346
demo.min.js:11173 Uncaught ReferenceError: jQuery is not defined
    at demo.min.js:11173
jquery.rateyo.js:1133 Uncaught TypeError: Cannot read property 'fn' of undefined
    at jquery.rateyo.js:1133
    at jquery.rateyo.js:1133
:8080/favicon.ico:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by ajsb85** [comment]
I just added this line, to execute the function.

https://github.com/kevinchappell/formBuilder/blob/a5028073576002af518aabab93ca48efd5ed8514/tools/build-vendor.js#L16

```diff
-
+ concatVendorFiles()
```

**Comment by kevinchappell** [comment]
Thanks for finding this. This function should be run after install node modules. Will open pr to fix today.
