### ISSUE TITLE
typeUserAttrs renders a text field for a checkbox input for field types "text" and "textarea"

### ISSUE THREAD

**Issue by sivashree** [kevinchappell/formBuilder#951]
### Description: when I try to add a new typeUserAttr of type checkbox to the field types  "text" and "textarea", it is rendering a text field instead of checkbox. For the other field types, it is rendering a checkbox.

 - Browser: Chrome
 - OS: MacOS mojave

### Steps to Reproduce:
Add the following JSON to options. 
typeUserAttrs: {
        "text": {
          dependency: {
            label: "Dependency",
            value: false
          }
        }
}

### Screenshot - 
![Screen Shot 2019-05-22 at 2 25 27 PM](https://user-images.githubusercontent.com/50871691/58161312-a915d200-7c9d-11e9-998d-a26e4f1285e2.png)

**Comment by sivashree** [comment]
Hi @kevinchappell , this is really strange. the same JSON object works well for other field types. Is there anyway where we can provide the type of field for custom user attribute as shown below?

typeUserAttrs: {
        "text": {
          dependency: {
            label: "Dependency exists",
            type: checkbox-group,
            value: false
          }
        }

**Comment by kevinchappell** [comment]
I agree this is strange. Will look into it today

**Comment by kevinchappell** [comment]
I'm unable to reproduce. The following definitions both work for generating a checkbox. Can you [create a codepen](https://codepen.io/kevinchappell/pen/vLjOLL?editors=1010) that demonstrates the problem?

```javascript
dependency: {
    label: 'Dependency',
    type: 'checkbox-group',
    value: false,
  }
```

and 
```javascript
dependency: {
    label: 'Dependency',
    value: false,
  }
```

**Comment by sivashree** [comment]
Hi @kevinchappell , here is the codesandbox https://codesandbox.io/s/formbuilder-angular-901lm .
This is reproducible when I add few default fields and disable few field buttons for those default fields.

These are the default fields I have in my form.
`defaultFields: [
        {
          className: "form-control",
          label: "Field1",
          name: "field1",
          required: true,
          type: "text",
          disabledFieldButtons: ["remove", "edit", "copy"]
        },
        {
          className: "form-control",
          label: "Field2",
          name: "field2",
          required: true,
          type: "text",
          disabledFieldButtons: ["remove", "edit", "copy"]
        },
        {
          className: "form-control",
          label: "Field3",
          name: "field3",
          required: true,
          type: "textarea",
          disabledFieldButtons: ["remove", "edit", "copy"]
        },
        {
          className: "form-control",
          label: "Field4",
          name: "field4",
          type: "text",
          disabledFieldButtons: ["remove", "edit", "copy"]
        }
      ],`

**Observations:** 
- When I add this "**disableFieldButtons**" to any field, it is hiding those field buttons for that field. However, when I double-click on that field, I am able to edit it.

- Only when I add "**disableFieldButtons**" to default fields, this issue is reproducible. 

Note: As per the documentation provided, I can use "disableFieldButtons" only to all the fields in general. But I tried adding it to default fields in my form and it worked. But, just now I realized that it was just hiding the fields.

**Comment by sivashree** [comment]
Hi @kevinchappell , adding codepen https://codepen.io/anon/pen/JqZJGJ.
Please add a new text field and notice the custom attribute (typeUserAttrs) I have added.
You can see a text field instead of a checkbox.

**Comment by sivashree** [comment]
Hi @kevinchappell , is this reproducible now?

**Comment by MarcusDelvecchio** [comment]
Ever figure this out? I am having the same problem where the checkbox is rendering a text field. I also noticed that the first time I drop my control in however, the checkbox is rendering, likely because of the bug outlines here  [https://github.com/kevinchappell/formBuilder/issues/915](url)
