### ISSUE TITLE
Uncaught TypeError: Cannot read property 'fields' of undefined

### ISSUE THREAD

**Issue by AndriyYushko** [kevinchappell/formBuilder#952]
### Environment Details:

 - formBuilder Version: 3.2.3
 - Browser: Chrome 74.0.3729.108
 - OS: Ubuntu 16.04

Get that error after update from 2.9.8 to 3.2.3 when try to set option inputSets
Code:
`inputSets: [
                    {
                        label: __('user_info'),
                        name: 'userInfo',
                        icon: '<i class="fa fa-user" aria-hidden="true"></i>',
                        showHeader: true,
                        fields: [
                            {
                                type: 'text',
                                label: __('full_name')
                            },
                            {
                                type: 'controlEmail',
                                label: 'E-mail'
                            },
                            {
                                type: 'phoneNumber',
                                label: __('phone_number')
                            }
                        ]
                    }
                ]`
In 2.9.8 all work correct
Since v2.10.0 not work.
I think it happened after fix bug in that release http://joxi.ru/4AknD1jioVDeN2

**Comment by AndriyYushko** [comment]
Problem was in name. After rename userInfo to user-details all work correct

**Comment by kevinchappell** [comment]
That's interesting. I'd like to investigate further. For now would you say this is resolved?

**Comment by AndriyYushko** [comment]
Yes after rename name property all work correctly

**Comment by kevinchappell** [comment]
OK, closing for now but will see why that made a difference. AFAIK you should be able to name input sets anything you want
