### ISSUE TITLE
npm install does not work correctly

### ISSUE THREAD

**Issue by tsdevelopment** [kevinchappell/formBuilder#954]
### Description:
Whenever I run `npm install` to install the package, I get not the original code. So I can not include the package in my custom javascript.

### Environment Details:

 - formBuilder Version: 3.2.3
 - Browser: -
 - OS: Windows 10
- node: v11.10.0
- npm: 6.7.0

### Expected Behavior
Source Code directory should look like the git repository

### Actual Behavior
Source Code directory looks strange, src folder is completely missing. Only a directory `dist` is available. And several other files.

### Steps to Reproduce
Create a new project and run `npm run install --save-dev`

### Screenshot - *(optional)*
![form-builder](https://user-images.githubusercontent.com/4952908/58367191-88878b00-7edc-11e9-9d27-316992c16614.PNG)

**Comment by kevinchappell** [comment]
I thought this was standard behavior for a lot of modules- to only include transpiled bundles. Do you get an error when including the transpiled files? 

All files except dist are excluded to keep the install as light as possible. Using files directly from `src/` will require compatible babel settings in your project, I don't think this is a good approach

To address your problem though I created a branch that will include the `src/` files on install. You can now add formBuilder with `src/` files by running `npm i --save kevinchappell/formBuilder#fix/missing-src`
