### ISSUE TITLE
Convert content into the json to be stored in a MySQL database

### ISSUE THREAD

**Issue by pixsolution** [kevinchappell/formBuilder#958]
### Description:
Hello everyone! I'm working with laravel, so the frontend is with blade and I'm having problems transforming the content of html to json see capture here: 
![image (26)](https://user-images.githubusercontent.com/47191848/58484743-f644e880-8162-11e9-9766-1c14c064694a.png)

 How can I convert that content (html) into the json to be stored in a MySQL database?

### Environment Details:

 - formBuilder Version: formBuilder v3.2.4
 - Browser: chrome
 - OS: windows

**Comment by nhhao1996** [comment]
Can you show me your blade view?

**Comment by pixsolution** [comment]
Hi @nhhao1996 

thanks for your reply

Yes, it is here: 
![image (27)](https://user-images.githubusercontent.com/47191848/58556822-31a3ed80-821d-11e9-8ce4-69fa6afcd41c.png)

where the json is seen and then by js I transform that code json to html to show it. But after filling the information on the form I need to transform it into json to be stored in the database. How can I do it?

With this function I transformed the json into html
![image (28)](https://user-images.githubusercontent.com/47191848/58556909-63b54f80-821d-11e9-804d-1c4b68504fb7.png)
![image (29)](https://user-images.githubusercontent.com/47191848/58556918-6a43c700-821d-11e9-9782-19efda8e0881.png)

I hope you can help me
Thanks
Regards

**Comment by nhhao1996** [comment]
Have you read this? https://formbuilder.readthedocs.io/en/latest/formRender/options/render/

**Comment by pixsolution** [comment]
Hi @nhhao1996 

Thanks for your reply

I was taking a look at this link and it generates the code in Json: https://formbuilder.readthedocs.io/en/latest/formRender/actions/userData/
However, it is generating the code in json of a form that is not the one I need. It always generates the code for the last form (form 2): https://codepen.io/chaw3x/pen/OYBdrb
For example, I asked for form 1, and it generates json code for form 2.

How can I generate the code in json for the form I require?
I appreciate the help on this matter

Regards

**Comment by selcank** [comment]
I'm having a similar problem.Button click get end form userdata but first page data does not get. Please check my demo. Where is wrong?

[](https://codepen.io/test212/pen/zVYywB)

Thanks.

**Comment by selcank** [comment]
https://codepen.io/test212/pen/zVYywB

**Comment by suryacaprice** [comment]
So how to save the data in mysql and retrive the values for the display

**Comment by suryacaprice** [comment]
is it the best idea to store the result in the nosql or just save it in the MySQL which will be best for long term approach

**Comment by Jojoshua** [comment]
Can also store as json or xml.
