### ISSUE TITLE
simple-line-icons are not working

### ISSUE THREAD

**Issue by AndTessitore** [kevinchappell/formBuilder#960]
Since I use simple line icons, formbuilder overrides the same class used by simple-line and breaks it! 
There should be an option to set custom class name for formbuilder elements so it can be customized and fix such problems

**Comment by burgoyne** [comment]
I believe I'm having a similar issue with font awesome. My page has a bunch of icons in the menu, but with form builder 3.2.5, the icons do not render properly.

**Comment by johndeen** [comment]
@burgoyne , @AndTessitore 
Please check issue: [https://github.com/kevinchappell/formBuilder/issues/918](https://github.com/kevinchappell/formBuilder/issues/918). If you can understand the fix then please help me out too.

**Comment by burgoyne** [comment]
@johndeen See my reply to you there. I solved it.

**Comment by lucasnetau** [comment]
Conflict was resolved in 3.5.2 (August 24th 2020) https://github.com/kevinchappell/formBuilder/releases/tag/v3.5.2

Fixed by https://github.com/kevinchappell/formBuilder/commit/1231aae178edad3dad8cdffb753020db3bc6a24c
