### ISSUE TITLE
getData from multiple Instances not possible (since 2.10)

### ISSUE THREAD

**Issue by marcus-at-localhost** [kevinchappell/formBuilder#965]
### Description:

With version 2.9.x I was able to do something like this:

```js
jQuery(function($) {
  var fbInstances = {
    	'buildWrap': $('#build-wrap').formBuilder(),
		'header': $('#header').formBuilder(),
		'content': $('#content').formBuilder(),
		'footer': $('#footer').formBuilder(),
	};


  document.getElementById('getJSON').addEventListener('click', function() {
    Object.keys(fbInstances).forEach(function(key){
      console.log(key, fbInstances[key].actions.getData())
    });
  });
});
```
Multiple instances of formBuilder and one button to collect all the data.

Starting with 2.10 I can't loop through the instances anymore and even `fbInstances[key].promise(f => {f.actions.getData()});` results in nothing.

Here is a minimal testcase: https://codepen.io/localhorst/pen/dBorvL

For a single instance it seems to work, and the demo with multiple forms works as well (I updated it with the latest versions https://codepen.io/localhorst/pen/OeVGaZ) 

But I can't make it work in my case. Any help is appreciated!

### Environment Details:

 - formBuilder Version: 3.x (since 2.10)
 - Browser: all
 - OS: all

### Expected Behavior

Get data from multiple instances via `fbInstances[key].actions.getData()`

### Actual Behavior

`actions.*`is not available 

### Steps to Reproduce

https://codepen.io/localhorst/pen/dBorvL

**Comment by RezaT1994** [comment]
Same problem

**Comment by gustavo43t** [comment]
Same problem, only the last instance work.

**Comment by Nshan0102** [comment]
Is there a solution for this issue?

**Comment by marcus-at-localhorst** [comment]
The solution is somewhere to find in how to handle promises. (https://formbuilder.online/docs/formBuilder/promise/)

I changed the fiddle a bit: https://codepen.io/localhorst/pen/JjPJLgZ

![image](https://user-images.githubusercontent.com/1337223/63946447-7128e280-ca75-11e9-9bf9-00ba7ac2eb4d.png)

Looping through the fbInstances returns promises and only the last key hold the `formData`.

with 

```js
fbInstances[key].promise.then(function(res){
  console.log(res.formData);
}) 
```
it's possible to access the formData but only for one field.
I have no idea what's going on and how to handle this. Hopefully @kevinchappell can shine some light on it.

**Comment by wendellrocha** [comment]
Same problem with formRender. Multiples instances of formRender and one button to collect all userData.

**Comment by chiahungwang** [comment]
You can try it like this, Init by Recursive Function.
[https://codepen.io/chiahungwang/pen/PoYrMEZ?editors=1010](url)

**Comment by Jojoshua** [comment]
Solution here also https://github.com/kevinchappell/formBuilder/issues/1088#issuecomment-646232029
