### ISSUE TITLE
I want to call a function when a field is removed

### ISSUE THREAD

**Issue by abhilashlegend** [kevinchappell/formBuilder#966]
### Description:
I want to call a event or function when a field is removed. How can I do that? 
### Environment Details:

 - Lastest formBuilder Version: 
 - Any Browser: 
 - Windows OS:

**Comment by nutzaalex** [comment]
I have a similar problem in React, I need to know when the builder is empty upon removing all fields, but I wasn't able to find any sort of mechanism to do that, why is there onAddField but not onRemoveField or something similar?

**Comment by dpbeaumont** [comment]
Have you tried using
`   document.addEventListener('fieldRemoved', () => {
                });`

**Comment by Jojoshua** [comment]
There is an undocumented onremove event that you can use similarly from here
https://formbuilder.online/docs/formBuilder/options/typeUserEvents/
