### ISSUE TITLE
How to use formBuilder with downloaded source

### ISSUE THREAD

**Issue by jag227** [kevinchappell/formBuilder#967]
### Description:
Sorry for a simple question I think but I'm quite new to Javascript.
I often use this library by add these line in my html file: 
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
  <script src="https://formbuilder.online/assets/js/form-builder.min.js"></script>
Now, I downloaded source from git and want to use it local. I tried to link form-builder.js file in this source to my html file but it's have nothing. 
How I can do this?
Thank you!

### Environment Details:

 - formBuilder Version: latest
 - Browser: Chrome
 - OS: Windows 10

**Comment by marcus-at-localhorst** [comment]
You have to build (compile) the script yourself. It's all described here: https://formbuilder.online/docs/contributing/ (You have to setup node.js and npm)
