### ISSUE TITLE
Form Render with starRating gives an error

### ISSUE THREAD

**Issue by hassan1593** [kevinchappell/formBuilder#970]
### i have created a form using form builder on my webpage it works fine in all area but at the time of rendering using starRating also it gives me an error that star rating is not a valid type can someone help??
this is my code of saved form:
[{"type":"header","subtype":"h4","label":"Fill up the survey please<br>"},{"type":"text","label":"Full Name","className":"form-control","name":"text-1560334577994","subtype":"text"},{"type":"text","label":"Contact","className":"form-control","name":"text-1560334597880","subtype":"text"},{"type":"textarea","label":"Survery","className":"form-control","name":"textarea-1560334610786","subtype":"textarea"},{"type":"starRating","label":"Rate us ?<br>","name":"starRating-1561099401463"},{"type":"radio-group","label":"Satisfactory Level<br>","inline":true,"name":"radio-group-1560334621918","other":true,"values":[{"label":"Excellent","value":"option-1"},{"label":"Average","value":"option-2"},{"label":"Poor","value":"option-3"}]},{"type":"text","label":"One word for us ?<br>","className":"form-control","name":"text-1560341608583","subtype":"text"}]

### Environment Details:

 - formBuilder Version: 
 - Browser: chrome moxilla firefox
 - OS: 

### it shows only the error:
Error: Invalid control type. (Type: starRating, Subtype: undefined). Please ensure you have registered it, and imported it correctly.

**Comment by brunoeris** [comment]
I receive the same error message here when I try to render a starRating

**Comment by brunoeris** [comment]
@hassan1593 I solve this error importing starRating to my script.
`import starRating from formBuilder/dist/control_plugins/starRating.min.js`

**Comment by lucasnetau** [comment]
The plugin is built as a seperate Js file.  You need to copy dist/control_plugins/starRating.min.js and load it into your page after formBuilder.min.js is added
