### ISSUE TITLE
Not working in IE 11

### ISSUE THREAD

**Issue by birdy247** [kevinchappell/formBuilder#973]
### Description:

Using form builder with Internet Explorer 11 and it does not load

### Environment Details:

 - formBuilder Version:  3.2.4
 - Browser: 11.829.17134.0
 - OS: Windows 10

### Expected Behavior

The form builder loads

### Actual Behavior

The form builder does not load properly

**Comment by mac89** [comment]
The `Object.entries` function is required, which doesn't exist in IE 11. But it can be added using a polyfill, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries.

**Comment by brasofilo** [comment]
Had the same issue on iOS 9, polyfill solved it. Thanks!
