### ISSUE TITLE
Table creation in FormBuilder

### ISSUE THREAD

**Issue by burgerboy85** [kevinchappell/formBuilder#974]
Hi Kevin,

Really like what you have done here with FormBuilder i do have a question in regards to this:

Is there any way we can add a table within a form whereas a user could add a new row to populate a new line of data?

An idea here would be to add a row of data relating to Qualifications or Work History where a new line can be added for each new item.

Is that something that is achievable through FormBuilder?

**Comment by dpow40** [comment]
I believe this is achievable but should be done through a custom plugin like specified in the documentation. Do let me know if I'm wrong @kevinchappell

**Comment by kashif-ali-khan** [comment]
> Hi Kevin,
> 
> Really like what you have done here with FormBuilder i do have a question in regards to this:
> 
> Is there any way we can add a table within a form whereas a user could add a new row to populate a new line of data?
> 
> An idea here would be to add a row of data relating to Qualifications or Work History where a new line can be added for each new item.
> 
> Is that something that is achievable through FormBuilder?

Did you get something on this ?
i also want to achieve something like this.

it will be helpful , if you have already gone through it

**Comment by Jojoshua** [comment]
You can easily add whatever table control you like using custom plugin https://formbuilder.online/docs/formBuilder/control-plugins/

**Comment by GiorgioRindonone** [comment]
> 

Can you please show me how to implement a custom table generator? I will pay you!
Contact me here on g.rindonone@contech.xyz, we can discuss everything you need of course.
Thanks.

**Comment by ShijinUIS** [comment]
hi @GiorgioRindonone  did you find any solution for the table generator ?

**Comment by marcoheine** [comment]
Hi @GiorgioRindonone @ShijinUIS,
 did you find any solution for the table generator ?
