### ISSUE TITLE
Fields get's removed on adding

### ISSUE THREAD

**Issue by rudevdr** [kevinchappell/formBuilder#977]
### Environment Details:

 - formBuilder Version: 3.5.2
 - Browser: Linux
 - OS: Chrome

### Expected Behavior

Removing fields should not remove field from container
https://i.imgur.com/hwen3SZ.gifv
### Actual Behavior

1. Fields gets removed. 
2. Fields don't get placed properly

### Framework

I am using React.

### Screenshot - *(optional)*
[FormBuilder](https://i.imgur.com/hwen3SZ.gifv)

### My `webpack.config.js`

	var webpack = require('webpack');
	const pkg = require('./package.json')
	const {
		resolve,
		join
	} = require('path')
	const HtmlWebpackPlugin = require('html-webpack-plugin')

	const webpackConfig = {
		entry: {
			'dist/babel-polyfill': 'babel-polyfill',
			"dist/index": './src/index.js',
			'dist/form-builder': resolve(__dirname, pkg.config.files.formBuilder.js),
			'dist/form-render': resolve(__dirname, pkg.config.files.formRender.js)
		},
		output: {
			path: resolve(__dirname, './dist'),
			filename: '[name].min.js',
		},
		module: {
			rules: [{
					enforce: 'pre',
					test: /\.js$/,
					exclude: /node_modules/,
					loader: 'eslint-loader',
				},
				{
					test: /\.(js|jsx)$/,
					exclude: /node_modules/,
					loader: 'babel-loader',
				},
				{
					test: /\.lang$/,
					loader: 'file-loader?name=[path][name].[ext]&context=./src',
				},
				{
					test: /\.(png|svg|jpg|gif)$/,
					use: [
						'file-loader'
					]
				},
				{
					test: /\.html$/,
					use: [{
						loader: "html-loader"
					}]
				},
				{
					test: /\.scss$/,
					use: ['style-loader',
						'css-loader',
						'postcss-loader',
						'sass-loader',
					],
				},
			],
		},
		plugins: [
			new HtmlWebpackPlugin({
				template: './public/index.html',
				filename: './index.html',
				favicon: './public/favicon.ico',
			})
		],
		resolve: {
			modules: [resolve(__dirname, 'src'), 'node_modules'],
			extensions: ['.js', '.scss'],
		},
		devServer: {
			inline: true,
			contentBase: './dist',
			noInfo: true,
			port: 3000
		}
	}

	module.exports = webpackConfig

### My `FormBuilder.js`

		import $ from 'jquery';
	import React from 'react';
	import ReactDOM from 'react-dom';
	import 'jquery-ui-sortable';
	import './FormBuilder.scss';

	window.jQuery = $;
	window.$ = $;
	var jQuery = $;

	$(document).ready(function($) {
		var fbEditor = document.getElementById('build-wrap');
		var formData = '[{"type":"text","label":"Full Name","subtype":"text","className":"form-control","name":"text-1476748004559"},{"type":"select","label":"Occupation","className":"form-control","name":"select-1476748006618","values":[{"label":"Street Sweeper","value":"option-1","selected":true},{"label":"Moth Man","value":"option-2"},{"label":"Chemist","value":"option-3"}]},{"type":"textarea","label":"Short Bio","rows":"5","className":"form-control","name":"textarea-1476748007461"}]';
		$('#fb-editor').formBuilder().promise.then(formBuilder => {console.log(formBuilder.actions.setData(formData0))});
		$(fbEditor).formBuilder().promise.then(formBuilder => formBuilder.actions.setData(formData));
	});

	//const formBuilder = $('#fb-editor').formBuilder({formData});

	class FormBuilder extends React.Component {

		render() {
			return <div id="build-wrap" ref="fb" />;
		}
	}

	export default FormBuilder

**Comment by kevinchappell** [comment]
this looks like it could be an issue with implementation. Unfortunately I am not able to re-produce the issue. Can you make a codesandbox that replicates the issue youre having?
