### ISSUE TITLE
Content Size Modifying Events

### ISSUE THREAD

**Issue by DubStepMad** [kevinchappell/formBuilder#982]
### Description:
I'm currently using NiceScroll which needs an event to be triggered to update the body height to allow the content to be displayed correctly without being behind the footer.

The event that needs firing is `$("body").getNiceScroll().resize()`

 - formBuilder Version: 2.9.8
 - Browser: Chrome
 - OS: Windows 10

I currently have this working for the following events:
`fieldAdded`
`fieldRemoved`

Example:
`document.addEventListener('fieldAdded', function(e) {
        $("body").getNiceScroll().resize();
    });`

Any help would be deeply appreciated.

**Comment by lucasnetau** [comment]
The best way to do this is to add a MutationObserver (https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) to your code to call the resize if the stage has changed in height
