### ISSUE TITLE
Multiple white spaces in label (at attribute)

### ISSUE THREAD

**Issue by bloommetha** [kevinchappell/formBuilder#983]
### **Description:**
I try to use jQuery formBuilder for my project and then I see this problem.

In normal case, when I choose some attributes then I press button to send the form data in JSON via Ajax to PHP and I alert the result, it's going to be like this picture.
![image](https://user-images.githubusercontent.com/18434378/62689153-75bd2680-b9f4-11e9-81bd-a1046f2202f7.png)

But when I try to edit label name with 2 white spaces like this picture.
![image](https://user-images.githubusercontent.com/18434378/62689173-840b4280-b9f4-11e9-9417-89cc603cebfc.png)

Then I press button to send form data, it's going to be like this picture.
![image](https://user-images.githubusercontent.com/18434378/62689180-879ec980-b9f4-11e9-9d8a-3ed1b57f1bcc.png)

I don't really know how can happen or how to fix it. Could you please tell me how can I fix this problem? It would be grateful. Thank you very much.

### **Environment Details:**
 - formBuilder Version: v3.2.4
 - Browser: Chrome, FireFox
 - OS: Windows

**Comment by lucasnetau** [comment]
When adding multiple spaces into a contenteditable the browsers will inject non-breakable spaces `&nbsp;`, there is likely an issue with the alert() call with unescaped html entities. Since this is a user function called by onSave it is not an issue in the library
