### ISSUE TITLE
Create a new input field within an added field

### ISSUE THREAD

**Issue by duhanbulak** [kevinchappell/formBuilder#985]
### Description: 
Hello I want the user to enter another label next to the label entered but I couldn't find out how to do it. I'd appreciate it if you helped.

### Screenshot - *(optional)*
![Screenshot_1](https://user-images.githubusercontent.com/50981181/63211353-983ef600-c0fe-11e9-8cf3-87877762b2df.png)

**Comment by matthew798** [comment]
This isn't exactly what you are looking for, but i needed the same thing and wasn't ready to put it the time to reverse engineer this library. I came up with a super simple system. Form creators just insert a | (pipe) between each language and when the page is loaded, I have a "form data localizer" that splits the string by pipes and keeps only the one at the correct index. It's a bit ugly but it works well.

**Comment by duhanbulak** [comment]
> This isn't exactly what you are looking for, but i needed the same thing and wasn't ready to put it the time to reverse engineer this library. I came up with a super simple system. Form creators just insert a | (pipe) between each language and when the page is loaded, I have a "form data localizer" that splits the string by pipes and keeps only the one at the correct index. It's a bit ugly but it works well.

I'm very sorry, but my English isn't very good, and I'd appreciate it if you could write it a little more clearly.

**Comment by kevinchappell** [comment]
@duhanbulak You can use `typeUserAttrs` option to add additional attribute fields.
