### ISSUE TITLE
How to typeUserAttrs on checkbox-group options

### ISSUE THREAD

**Issue by sxndy1** [kevinchappell/formBuilder#986]
### Description: Default by adding a checkbox-group is one option with the label "Option 1" and the value "option-1". 
I want to have a custom option like "Hello" and "World". How to setup the typeUserAttrs?

I tried something like that, but I think the syntax is wrong because I don't see an options-attribute anymore with that:
```
           typeUserAttrs: {
                "checkbox-group": {
                    options: {
                        values: [{ label: "Hello", value: "World" }]
                    }
                }
            }
```

### Environment Details:

 - formBuilder Version: 3.2.3
 - Browser: all
 - OS: Win10

### Screenshot - *(optional)*
![image](https://user-images.githubusercontent.com/47420177/63332262-85fbcc80-c337-11e9-860d-226ccca3c741.png)

**Comment by MarcusDelvecchio** [comment]
@sxndy1 Ever figure it out?

**Comment by sxndy1** [comment]
Nope, I've never got an answer and couldn't solve it. Sorry guys!

**Comment by kashif-ali-khan** [comment]
@kevinchappell ,
Any update on this ?
or Any workaround, how can we achieve this ?

**Comment by kevinchappell** [comment]
its possible to do this now with `onAddOption` callback. return the attributes you want to appear on the option.  https://formbuilder.online/docs/formBuilder/options/onAddOption/
