### ISSUE TITLE
TypeUserAttrs Boolean Value Sometimes Showing Textbox

### ISSUE THREAD

**Issue by davidarivera** [kevinchappell/formBuilder#987]
### Description:
I have the following typeUserAttrs defined

    typeUserAttrs: {
        text: {
            readonly: {
                label: 'readonly',
                value: false,
            }
        }
    }

Sometimes when I edit I get a check box which is expected. Other times I get a text box. It appears this happens with any element except the first element which is added.
### Environment Details:

 - formBuilder Version: 
 - Browser: 
 - OS: 

### Expected Behavior
If the type of 'value' is Boolean, you should always get a checkbox.

### Actual Behavior
If the type of 'value' is Boolean, you sometimes get a checkbox and other times get a text box.

**Comment by brunopastor** [comment]
This is also happening to me.

I hope this has a workaround somehow.

**Comment by W1-PopelierE** [comment]
@brunopastor @davidarivera 
`typeUserAttrs: {
        text: {
            readonly: {
                label: 'readonly',
                value: false,
                type: 'checkbox'
            }
        }
      }`

With the above typeUserAttrs this seems to be fixed.

**Comment by brunopastor** [comment]
@W1-PopelierE You are right!

Thanks for pointing it out.

**Comment by kevinchappell** [comment]
yes, as @W1-PopelierE pointed out, `type: 'checkbox'` will workaround but the original issue is also fixed.
