### ISSUE TITLE
How to use AWS app sync for backend

### ISSUE THREAD

**Issue by suryacaprice** [kevinchappell/formBuilder#989]
https://aws.amazon.com/appsync/ is an interesting feature and i want the data from the form builder to be stored in the DynamoDB via AppSync . Is there a sample available for  it ?

**Comment by kevinchappell** [comment]
currently there are no backend examples. formBuilder is a frontend tool that shouldnt have any trouble creating data to send to the backend of your choice, including AppSync.

That said, creating an AppSync example is outside the scope of this project but would be welcome contribution.
