### ISSUE TITLE
jQuery.Deferred exception: $(...).formRender is not a function 

### ISSUE THREAD

**Issue by sayedbs** [kevinchappell/formBuilder#990]
### Environment Details:

in React showing this issue when Save form and 
onSave: function(evt, formData) {
    $('#render-wrap').formRender({formData});
  }

**Comment by Obaidraj** [comment]
![issue1234](https://user-images.githubusercontent.com/38789569/151947282-342cfc47-0f12-4c1c-b764-39eb958a54c4.PNG)

**Comment by Jojoshua** [comment]
You'll need to reopen with a fiddle if still an issue
