### ISSUE TITLE
Bug: impossible to enter text into other-value in checkbox-group (safari)

### ISSUE THREAD

**Issue by Mauerbluemchen** [kevinchappell/formBuilder#991]
### Description:
Bug: impossible to enter text into other-value in checkbox-group (safari)
clicking into the other text field closes the field and unchecks the other option

### Environment Details:

 - formBuilder Version: 3.2.5
 - Browser: Safari
 - OS: MacOS (also on iOS)

### Expected Behavior
beeing able to write text into the other field on a checkbox-group

### Actual Behavior
clicking into the other text field closes the field and unchecks the other option

### Steps to Reproduce
add checkbox-group to form, check option to let users enter an unlisted option
bug happens in both form-builder and form-renderer
just check the other option in the form and focus the text field

### Screenshot - *(optional)*
![safari](https://user-images.githubusercontent.com/33925782/65327395-1f770200-dbb4-11e9-8bcf-ddfc5741178c.png)

**Comment by Mauerbluemchen** [comment]
I fixed that one in my local checkout in the select.js like this:

![image](https://user-images.githubusercontent.com/33925782/67014832-d0aa8280-f0f5-11e9-85a2-28cc928c6104.png)

**Comment by lucasnetau** [comment]
Cannot replicate with current Safari and current release version. This has likely been fixed since reported. Please reopen if the issue still remains
