### ISSUE TITLE
FormBuilder not working on IE 11

### ISSUE THREAD

**Issue by hankun411** [kevinchappell/formBuilder#992]
### Environment Details:

 - formBuilder Version: 3.2.5
 - Browser: IE 11
 - OS: windows 10

### Steps to Reproduce: Use IE 11 and go on https://formbuilder.online/
There were many properties used that isn't supported by IE 11.
I added polyfill from Babel and it got it up and running but any drop downs or radios in edit mode will crash the browser.

If you know of a version that works well IE 11, please let me know thanks.

**Comment by matthew798** [comment]
We are currently using formbuilder in IE11.0.9600.19431 and it works well except for the date field. I am currently investigating. We use:
`https://polyfill.io/v3/polyfill.min.js?features=Object.assign%2CObject.entries%2CPromise%2CArray.prototype.includes%2CArray.prototype.find%2CString.prototype.startsWith%2CObject.values%2CString.prototype.includes`
As our polyfill.

It seems that formbuilder.online doesn't include the polyfills. A bit ridiculous considering that it also says IE11 is supported.

**Comment by hankun411** [comment]
Thanks! That has helped me fix the issue. It works relatively better now.
