### ISSUE TITLE
How can I disabled values for a custom field?

### ISSUE THREAD

**Issue by dmcmahon85** [kevinchappell/formBuilder#993]
### Description:
I created some custom selects that are being built off SQL data.  I would like to lock those values down so our users can add the select but not manipulate the options for the select.  Is there a way to do this currently?

I tried disabledAttrs: ["options"] but this removes all of the values I set as well as removing the values section when editing the select. Anyone have any ideas on this one?

### Environment Details:

 - formBuilder Version: 3.2.5
 - Browser: Any
 - OS: Linux (CentOS 7)

**Comment by Fenix-ops** [comment]
hi i am trying to do the same thing. to create custom select and bind SQL data but i am struggling can you please share code it will be help full.I also want that user can manipulate the values to if you find solution of that please share that to
thanks

**Comment by Jojoshua** [comment]
If you really don't want user data getting into the database then you should handle this serverside and ensure userData is cleared when saving.
