### ISSUE TITLE
Add Differnet Icon for custom Field in form builder.

### ISSUE THREAD

**Issue by bhp2810** [kevinchappell/formBuilder#997]
### Description:
Need to add Custom filed. With different Icon. Where can I found list of icons and how can I get it for my custom field. Mainly I need select icon.
![Screenshot_5](https://user-images.githubusercontent.com/46674257/66652442-5be9cb00-ec53-11e9-9e41-92929103c8e9.png)

### Environment Details:

 - formBuilder Version: 
 - Browser: 
 - OS:

**Comment by abhijeetSingh-uta** [comment]
https://formbuilder.online/docs/formBuilder/options/replaceFields/
https://codepen.io/kevinchappell/pen/YEOmea

**Comment by kevinchappell** [comment]
https://codepen.io/kevinchappell/pen/YEOmea

**Comment by abhijeetSingh-uta** [comment]
You can use font awesome icons using code below. If you don't use "icon" field it will use the default icon for that type.

fields : [
    {
        label: "Email",
        type: "text",
        subtype: "email",
        icon: "<i class='fa fa-envelope'></i>"
    },
    {
        label: "First Name",
        type: "text",
        subtype: "text",
        icon: "<i class='fa fa-user'></i>"
    }
];

Also check this: https://codepen.io/kevinchappell/pen/bWErNB
