### ISSUE TITLE
Error on start, not rendering

### ISSUE THREAD

**Issue by MBoberski** [kevinchappell/formBuilder#998]
### Description:
After adding to my page I get:

> jQuery.Deferred exception: $(...).formBuilder is not a function TypeError: $(...).formBuilder is not a function

### Environment Details:

 - formBuilder Version: formBuilder-5289429
 - Browser: Chrome
 - OS: Win10

### Expected Behavior
Shows form
### Actual Behavior
Not working
### Steps to Reproduce
Use this confs:
![image](https://user-images.githubusercontent.com/2800036/66708606-46f46100-ed53-11e9-9ed9-7b5e3e85b871.png)
![image](https://user-images.githubusercontent.com/2800036/66708609-5673aa00-ed53-11e9-9eb3-3e7449d09210.png)

**Comment by kevinchappell** [comment]
i was unable to repro. is this still an issue?
