### ISSUE TITLE
FormBuilder: Max, min and step in formData does not work for number fields

### ISSUE THREAD

**Issue by nahojd** [kevinchappell/formBuilder#999]
When setting formData in formbuilder options, min, max and step for number fields does not work. They are not set in the UI for designing the form, and they are not present when the formdata is generated after save. What's more, if I set the value for a number field, it sets max, min and step as well.

Example options that does not work: 

```javascript
options = {
  formData: 
    '[{"type":"number", "label":"Max and min does not work for number", "max":100, "min":10,"step":2},' +
    '{"type":"number", "label":"Value overwrites max min and step", "max":100, "min":10,"step":2,"value":"50"},' +
    '{"type":"text", "label":"Maxlength works for text", "maxlength":5}]'
    };
```

Example in codepen: https://codepen.io/nahojd/pen/YzzGXJV

### Environment Details:

 - formBuilder Version: 3.2.5
 - Browser: Firefox
 - OS: Windows

**Comment by buttle** [comment]
Hi,
I was just about to open an issue for the same thing. :)

My observations.
Max, min, and step are in fact saved correctly (I can see that in the database). But.. when the form is edited again; max, min, and step are lost.
I'm pretty sure this is because their values are not rendered as input values (inputs are blank). That means that every time you edit a form, you have to remember to set those number-field attributes again before saving.

Do you find that too @nahojd ?

**Comment by nahojd** [comment]
@buttle Yes, that's my experience as well. When the max, min or step attributes are set, they are saved correctly. But when you load the saved data again, they are not set anymore.

**Comment by stefansn** [comment]
@nahojd have you found a solution for this problem?

**Comment by nahojd** [comment]
@stefansn Well, I have found the bug in the formbuilder, but it needs to be fixed in the code.

In `form-builder.js`, in the `numberAttribute` function starting on line 706, it actually removes the min, max and step attributes and passes them on as attributes instead of values, which sounds good, but is wrong. The result is that instead of the configuration input fields for min, max and step having the value of min, max and step respectively, instead they get the _actual min, max and step attributes_.

So the solution is to change this:

```javascript
 const numberAttribute = (attribute, values) => {
    const { class: classname, className, min = 0, max, step, value, ...attrs } = values
    const attrVal = attrs[attribute] || value
    const attrLabel = mi18n.get(attribute) || attribute
    const placeholder = mi18n.get(`placeholder.${attribute}`)

    const inputConfig = {
      type: 'number',
      value: attrVal,
      name: attribute,
      min,
      max,
      step,
      placeholder,
      className: `fld-${attribute} form-control ${classname || className || ''}`.trim(),
      id: `${attribute}-${data.lastID}`,
    }
    //The rest of the method is omitted
}
```

to this

```javascript
 const numberAttribute = (attribute, values) => {
    const { class: classname, className, value, ...attrs } = values
    const attrVal = attrs[attribute] || value
    const attrLabel = mi18n.get(attribute) || attribute
    const placeholder = mi18n.get(`placeholder.${attribute}`)

    const inputConfig = {
      type: 'number',
      value: attrVal,
      name: attribute,
      placeholder,
      className: `fld-${attribute} form-control ${classname || className || ''}`.trim(),
      id: `${attribute}-${data.lastID}`,
    }
    //The rest of the method is omitted
}
```

That seems to fix the problem completely. I have fixed in a fork of this repository: https://github.com/nahojd/formBuilder/commit/1d4220205c5567f456bf895b2fbfa65b0ae62c25

@kevinchappell have I understood this correctly, and in that case, would you like a pull request or just fix it yourself, it's a very minor fix as you can see.

**Comment by criticalfault** [comment]
This is pretty hacky, but while i am waiting for the new JS files to drop, this is what i came up with. I'm also having a heck of a time getting my webpack to work with this, but i am extremely new to webpack. Just in case this helps someone else who needed it to be set when the form loads from another source. 

 $("input[id^='step-frmb-'").each(function(item) { $(this).val($(this).attr('step')); });
 $("input[id^='min-frmb-'").each(function(item) { $(this).val($(this).attr('min')); });
 $("input[id^='max-frmb-'").each(function(item) { $(this).val($(this).attr('max')); });

**Comment by nahojd** [comment]
I created a pull request for my fix: https://github.com/kevinchappell/formBuilder/pull/1018

**Comment by Stapelpanda** [comment]
The PR is merged, but the problem still remains: https://codepen.io/stapelpanda/pen/yLYQbmO
Somehow the value of the "value" attribute is taken as the value for "step","min" and "max" attributes.

**Comment by Stapelpanda** [comment]
Added a quick fix, the `numberAttribute` function uses `value` if no value is set for the Min, Max and step parameters. "https://github.com/kevinchappell/formBuilder/compare/master...Stapelpanda:dev-remove-default?expand=1"
